### ISSUE TITLE
currentUser is null but I'm logged in in the CP

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#2860] opened 2018-05-09 11:00 UTC
I've a login form in the frontend. When I send it it logs me in in the CP but not in the Frontend.
```
{{ d(currentUser) }} => null
```

Don't understand whats wrong here. Bug?

### Additional info

- Craft version: 3.0.6
- PHP version: 7.0

**Comment by Coysh** [comment] 2018-05-09 14:54
I'm also having this, was working before 3.0.6

Craft version: 3.0.6
PHP version: 7.2

**Comment by davidhellmann** [comment] 2018-05-09 19:43
@brandonkelly how can I downgrade to 3.0.5 or is that not possible?  : )

**Comment by brandonkelly** [comment] 2018-05-09 23:45
🤔 Not sure why this would be happening all of a sudden for you – nothing related to that changed in 3.0.6, and `currentUser` is still working on my end.

No new database migrations were added in 3.0.6 so you can safely go back to 3.0.5. Just `cd` to your Craft project in your terminal, and run this:

```
composer require craftcms/cms:3.0.5
```

Let me know if reverting to 3.0.5 does in fact fix this for you.

**Comment by Coysh** [comment] 2018-05-10 09:19
Interesting -  downgrading to 3.0.5 and `currentUser` was working.
Tried updating to 3.0.6 and `currentUser` was null again.
Repeated the process and same results

**Comment by angrybrad** [comment] 2018-05-10 13:47
Any chance someone is able to reproduce this on a public box we could get some CP and (s)FTP/SSH access to?  If so, could you send some credentials over to support@craftcms.com?

**Comment by brandonkelly** [comment] 2018-05-10 18:02
Turns out this was a symptom of the same bug that caused #2866, so both are fixed now for the next release.

**Closed** 2018-05-10 18:01 UTC

**Comment by brandonkelly** [comment] 2018-05-10 18:29
We just released Craft 3.0.7 with the fix.

**Comment by Coysh** [comment] 2018-05-10 21:34
@brandonkelly P&T are the quickest bug fixers in the galaxy! Thanks 👍

**Comment by samhibberd** [comment] 2019-12-12 10:52
@brandonkelly we are running into this on 3.3.18.1, have tried disabling custom modules + plugins but still running into it. Also tested it on 3.4 beta 3. User identity returning `null` when its set in Extensions.php:

https://github.com/craftcms/cms/blob/9ce695ec114eb6f7c660e891d3b6479fa0235f43/src/web/twig/Extension.php#L1135

Any thoughts?

**Comment by brandonkelly** [comment] 2019-12-12 20:03
@samhibberd Add this line right before that `$globals['currentUser']` line and reload your browser – what does it output?

```php
Craft::dd((new \Exception)->getTraceAsString());
```

**Comment by samhibberd** [comment] 2019-12-12 20:20
```
'#0 /Users/samhibberd/Sites/beta.findarace.com/vendor/twig/twig/src/ExtensionSet.php(329): craft\\web\\twig\\Extension->getGlobals()
#1 /Users/samhibberd/Sites/beta.findarace.com/vendor/twig/twig/src/Environment.php(928): Twig\\ExtensionSet->getGlobals()
#2 /Users/samhibberd/Sites/beta.findarace.com/vendor/twig/twig/src/Environment.php(948): Twig\\Environment->getGlobals()
#3 /Users/samhibberd/Sites/beta.findarace.com/vendor/twig/twig/src/Template.php(380): Twig\\Environment->mergeGlobals(Array)
#4 /Users/samhibberd/Sites/beta.findarace.com/vendor/twig/twig/src/Template.php(392): Twig\\Template->display(Array)
#5 /Users/samhibberd/Sites/beta.findarace.com/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\\Template->render(Array, Array)
#6 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/web/View.php(466): Twig\\TemplateWrapper->render(Array)
#7 /Users/samhibberd/Sites/beta.findarace.com/modules/findarace/src/fields/DynamicFieldTrait.php(104): craft\\web\\View->renderString(\'{{ findarace.ap...\')
#8 /Users/samhibberd/Sites/beta.findarace.com/modules/findarace/src/fields/DynamicFieldTrait.php(36): modules\\findarace\\fields\\DynamicDropdown->getDynamicOptions()
#9 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/base/BaseObject.php(109): modules\\findarace\\fields\\DynamicDropdown->init()
#10 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/helpers/Component.php(113): yii\\base\\BaseObject->__construct(Array)
#11 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/services/Fields.php(562): craft\\helpers\\Component::createComponent(Array, \'craft\\\\base\\\\Fiel...\')
#12 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/services/Fields.php(587): craft\\services\\Fields->createField(Array)
#13 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1966): craft\\services\\Fields->getAllFields()
#14 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1364): craft\\elements\\db\\ElementQuery->customFields()
#15 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\\elements\\db\\ElementQuery->prepare(Object(craft\\db\\mysql\\QueryBuilder))
#16 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/db/Query.php(146): yii\\db\\QueryBuilder->build(Object(craft\\elements\\db\\UserQuery))
#17 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/db/Query.php(274): yii\\db\\Query->createCommand(Object(craft\\db\\Connection))
#18 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/db/Query.php(177): yii\\db\\Query->one(NULL)
#19 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1513): craft\\db\\Query->one(NULL)
#20 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/elements/User.php(399): craft\\elements\\db\\ElementQuery->one()
#21 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/web/User.php(690): craft\\elements\\User::findIdentity(\'2\')
#22 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/web/User.php(491): yii\\web\\User->renewAuthStatus()
#23 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/web/User.php(192): craft\\web\\User->renewAuthStatus()
#24 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/web/User.php(231): yii\\web\\User->getIdentity()
#25 /Users/samhibberd/Sites/beta.findarace.com/vendor/selvinortiz/patrol/src/services/PatrolService.php(278): craft\\web\\User->getIsAdmin()
#26 /Users/samhibberd/Sites/beta.findarace.com/vendor/selvinortiz/patrol/src/services/PatrolService.php(229): selvinortiz\\patrol\\services\\PatrolService->doesCurrentUserHaveAccess()
#27 /Users/samhibberd/Sites/beta.findarace.com/vendor/selvinortiz/patrol/src/services/PatrolService.php(66): selvinortiz\\patrol\\services\\PatrolService->handleMaintenanceMode()
#28 /Users/samhibberd/Sites/beta.findarace.com/vendor/selvinortiz/patrol/src/Patrol.php(47): selvinortiz\\patrol\\services\\PatrolService->watch()
#29 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/base/BaseObject.php(109): selvinortiz\\patrol\\Patrol->init()
#30 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/base/Module.php(158): yii\\base\\BaseObject->__construct(Array)
#31 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/base/Plugin.php(130): yii\\base\\Module->__construct(\'patrol\', Object(craft\\web\\Application), Array)
#32 [internal function]: craft\\base\\Plugin->__construct(\'patrol\', Object(craft\\web\\Application), Array)
#33 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#34 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/di/Container.php(159): yii\\di\\Container->build(\'selvinortiz\\\\pat...\', Array, Array)
#35 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/BaseYii.php(351): yii\\di\\Container->get(\'selvinortiz\\\\pat...\', Array, Array)
#36 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/services/Plugins.php(897): yii\\BaseYii::createObject(Array, Array)
#37 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/services/Plugins.php(230): craft\\services\\Plugins->createPlugin(\'patrol\', Array)
#38 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/base/ApplicationTrait.php(1375): craft\\services\\Plugins->loadPlugins()
#39 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/web/Application.php(112): craft\\web\\Application->_postInit()
#40 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\\web\\Application->init()
#41 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/base/Application.php(206): yii\\base\\BaseObject->__construct(Array)
#42 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/src/web/Application.php(100): yii\\base\\Application->__construct(Array)
#43 [internal function]: craft\\web\\Application->__construct(Array)
#44 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#45 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/di/Container.php(159): yii\\di\\Container->build(\'craft\\\\web\\\\Appli...\', Array, Array)
#46 /Users/samhibberd/Sites/beta.findarace.com/vendor/yiisoft/yii2/BaseYii.php(351): yii\\di\\Container->get(\'craft\\\\web\\\\Appli...\', Array, Array)
#47 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/bootstrap/bootstrap.php(244): yii\\BaseYii::createObject(Array)
#48 /Users/samhibberd/Sites/beta.findarace.com/vendor/craftcms/cms/bootstrap/web.php(51): require(\'/Users/samhibbe...\')
#49 /Users/samhibberd/Sites/beta.findarace.com/web/index.php(20): require(\'/Users/samhibbe...\')
#50 /Users/samhibberd/.composer/vendor/weprovide/valet-plus/server.php(131): require(\'/Users/samhibbe...\')
#51 {main}'
```

**Comment by samhibberd** [comment] 2019-12-12 20:27
@brandonkelly investigating further - after completely removing our module and rebuilding the autoload files, it does point to something in our code, looks like one of our field types.

**Comment by brandonkelly** [comment] 2019-12-13 18:16
@samhibberd In both cases it’s because Patrol is triggering an element query before Craft & plugins have been fully initialized. Posted https://github.com/selvinortiz/craft-plugin-patrol/issues/20 explaining the issue and how to fix.
