### ISSUE TITLE
Internal Server Error - Entry is missing its section ID when Save as a draft

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#2556] opened 2018-03-09 16:48 UTC
### Description

When I save a new entry with _Save as a draft_ button, I get this error:

```
Internal Server Error
Entry is missing its section ID
```

When I save a new entry using _Save_, or _Save and continue editing_, or _Save and add another_: everything is working fine.

### Steps to reproduce

1. Save a new entry with _Save a draft_ button

### Additional info

- Craft version: 3.0.0-RC14
- PHP version: 7.1.8
- Database driver & version: MySQL 5.6.35

**Comment by brandonkelly** [comment] 2018-03-09 17:53
Duplicate of #2544, and fixed for the next release.

You can get the fix early by changing your `craftcms/cms` version requirement to `"dev-develop as 3.0.0-RC99"` in composer.json, and then run `composer update`.

**Closed by brandonkelly** 2018-03-09 17:53 UTC
