### ISSUE TITLE
GraphQL: @formatDateTime directive not outputting dates (Craft 3.4.2)

### ISSUE THREAD

**Issue by jeromecoupe** [craftcms/cms#5576] opened 2020-02-04 08:40 UTC
### Description

The `@formatDateTime` GraphQL directive does not work for me in Craft 3.4.2

* `postDate` outputs a date
* `postDate @formatDateTime(format: "Y-m-d")` outputs `"Y-m-d"`

Downgrading to Craft 3.4.0 seems to fix it

### Steps to reproduce

1. Install Craft 3.4.2
2. Use the `@formatDateTime` GraphQL directive in a query

### Additional info

- Craft: 3.4.2
- PHP version 7.3.8
- Database driver & version: MySQL 5.7.26
- Plugins & versions: none

**Comment by andris-sevcenko** [comment] 2020-02-04 08:45
Duplicate of #5569

**Closed by andris-sevcenko** 2020-02-04 08:45 UTC
