### ISSUE TITLE
In Craft 3.6+, GraphQL queries with siteId: "*" return no entries

### ISSUE THREAD

**Issue by humandevs** [craftcms/cms#9098] opened 2021-06-29 16:05 UTC
### Description
After upgrading from Craft 3.5.19 to 3.6.17, GraphQL queries with siteId: "*" return an empty set. 

In 3.5, the query would correctly return results for all siteIds when siteId: "*" is chosen.

Here's an example of a query that returns only the default siteId's entries (because siteId is not included in the query):
![image](https://user-images.githubusercontent.com/57273245/123829198-1782e080-d8b7-11eb-8d02-4a2fecd682df.png)

And here's a query that returns an empty set, but which should return entries from every site:
![image](https://user-images.githubusercontent.com/57273245/123829064-fa4e1200-d8b6-11eb-9f87-174a768b6422.png)

This may be related to the change in field type for siteId, as it was a "String" type in 3.5 and is now a "QueryArgument" type in 3.6.17.

As a note, this change in field type causes existing GraphQL queries that use variables with specified field types to fail with a `Variable "$siteId" of type "String" used in position expecting type "[Craft_QueryArgument]` error. Thus, this schema change should probably be noted in the "Upgrading to 3.6" release notes somewhere, or even better it could accept this field as either a "String" or a "QueryArgument" type, for backwards compatibility.

As a note, "*" is actually the default value for 'siteId' if you select 'siteId' as one of the dimensions of the query.

### Steps to reproduce

1. Create an Entries GraphQL query with 'siteId' as one of the fields to filter by, and choose "*" as the value (in order to select all siteIds, as per the Element API documentation https://craftcms.com/docs/3.x/entries.html#site).
2. Your results seem to be an empty set of Entries, instead of entries from all siteIds.

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4
- Database driver & version: 5.7.19-log
- Plugins & versions: Super Table 2.6.8

**Comment by humandevs** [comment] 2021-06-29 16:08
As a workaround, for anyone else that runs into this, the same functionality of "*" can be obtained by passing an 'insane' value to the 'not' keyword, like so:
`siteId: ["not","-1"]`

As per the Element API docs: https://craftcms.com/docs/3.x/entries.html#site

E.G.
![image](https://user-images.githubusercontent.com/57273245/123831616-5dd93f00-d8b9-11eb-9010-9e936e8b287e.png)

**Comment by andris-sevcenko** [comment] 2021-07-05 10:27
I'm unable to reproduce this locally. See the attached screenshot.

Can you send over your `composer.json`, `composer.lock` files as well as a database dump to support@craftcms.com, so we can try recreating the issue then>

![Screen Shot 2021-07-05 at 13 26 08](https://user-images.githubusercontent.com/1891118/124457534-920a9f00-dd94-11eb-8d61-bb071cb94792.png)

**Comment by humandevs** [comment] 2021-07-07 03:07
Ah, there's an easy explanation for that one. `site` works with "*", but `siteId` returns an empty set.

**Comment by andris-sevcenko** [comment] 2021-07-07 11:01
> Ah, there's an easy explanation for that one. site works with "*", but siteId returns an empty set.

Pardon me, I missed that. I'll add support for `*` in `siteId` as well.

**Comment by andris-sevcenko** [comment] 2021-07-07 11:58
Thank you for your patience! Just pushed a fix to this for the next release.

**Closed** 2021-07-07 11:58 UTC
Labels: bug
