### ISSUE TITLE
[4.x]: Password request on running php craft db/backup

### ISSUE THREAD

**Issue by umkasanki** [craftcms/cms#14945] opened 2024-05-06 16:57 UTC
### Description
After updating Craft to 4.9.1, the `php craft db/backup` command started asking for a password.
The error was noticed only on the site with PostgreSQL only. 
On the site with MySQL command works as expected.

### Steps to reproduce

1. Update Craft to 4.9.1
2. run `php craft db/backup` command

### Expected behavior
Make a backup without asking for a password

PostgreSQL 
![изображение](https://github.com/craftcms/cms/assets/496132/9432cca7-72f5-400e-8385-b82df768a26f)

MySQL 
![изображение](https://github.com/craftcms/cms/assets/496132/10823929-43ff-4eb5-b570-d2635021ea03)

### Craft CMS version

4.9.1

### PHP version

8.1.25, 8.2.18

### Operating system and version

Linux 5.15.0-79-generic,  Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

PostgreSQL 14.10

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-13)

### Installed plugins and versions

Amazon S3 	2.2.1
Blitz 	4.17.0
CP Field Inspect 	1.4.4
Dumper 	5.0.1
Formie 	2.1.13
ImageOptimize 	4.0.7
Logs 	4.0.0
MatrixMate 	2.1.4
Navigation 	2.0.27
Preparse Field 	2.0.2
Redactor 	3.0.4
Retour 	4.1.16
SendGrid 	2.0.1
Sentry Logger 	4.1.6
SEOmatic 	4.0.48
Super Table 	3.0.14
Typed link field 	2.1.5
Vite 	4.0.9

**Comment by timkelty** [comment] 2024-05-06 17:17
@umkasanki do you have anything configured for `backupCommand` or `backupCommandFormat`?

I can't reproduce this, at least through DDEV, or docker-compose directly.

**Comment by umkasanki** [comment] 2024-05-07 07:31
> @umkasanki do you have anything configured for `backupCommand` or `backupCommandFormat`?

No. I don't have `backupCommand` or `backupCommandFormat` params in my general.php

**Comment by timkelty** [comment] 2024-05-07 08:43
@umkasanki this is fixed by https://github.com/craftcms/cms/pull/14948

You can try it by requiring `craftcms/cms:dev-bugfix/missing-pg-password`. We should have a release with the fix out shortly.

**Comment by umkasanki** [comment] 2024-05-07 12:15
Fixed. Tnx

**Comment by brandonkelly** [comment] 2024-05-07 18:43
@umkasanki Thanks for testing! Craft 4.9.2 and 5.1.2 are out with that fix now.

**Closed as completed by brandonkelly** 2024-05-07 18:43 UTC
Labels: bug, craft4
