### ISSUE TITLE
PHP Notice – yii\base\ErrorException Undefined offset: 1

### ISSUE THREAD

**Issue by BramBeekman** [craftcms/cms#5525] opened 2020-01-29 09:54 UTC
After update i get this error

**Comment by andris-sevcenko** [comment] 2020-01-29 11:08
Do you have a stack trace in your log files?

**Comment by BramBeekman** [comment] 2020-01-29 11:53
> Do you have a stack trace in your log files?

Yes.


Stack trace:
#0 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\craftcms\cms\src\helpers\ProjectConfig.php(275): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', 'C:\\Users\\bramb\\...', 275, Array)
#1 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\craftcms\cms\src\helpers\ProjectConfig.php(284): craft\helpers\ProjectConfig::unpackAssociativeArray(Array, true)
#2 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\craftcms\cms\src\helpers\ProjectConfig.php(254): craft\helpers\ProjectConfig::unpackAssociativeArray(Array)
#3 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\craftcms\cms\src\services\Plugins.php(1372): craft\helpers\ProjectConfig::unpackAssociativeArrays(Array)
#4 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\craftcms\cms\src\services\Plugins.php(206): craft\services\Plugins->_getPluginConfigData('feed-me')
#5 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\craftcms\cms\src\base\ApplicationTrait.php(1351): craft\services\Plugins->loadPlugins()
#6 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\craftcms\cms\src\console\Application.php(59): craft\console\Application->_postInit()
#7 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\yiisoft\yii2\base\BaseObject.php(109): craft\console\Application->init()
#8 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\yiisoft\yii2\base\Application.php(206): yii\base\BaseObject->__construct(Array)
#9 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\yiisoft\yii2\console\Application.php(89): yii\base\Application->__construct(Array)
#10 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\craftcms\cms\src\console\Application.php(48): yii\console\Application->__construct(Array)
#11 [internal function]: craft\console\Application->__construct(Array)
#12 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\yiisoft\yii2\di\Container.php(400): ReflectionClass->newInstanceArgs(Array)
#13 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\yiisoft\yii2\di\Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array)
#14 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\yiisoft\yii2\BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#15 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\craftcms\cms\bootstrap\bootstrap.php(245): yii\BaseYii::createObject(Array)
#16 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\vendor\craftcms\cms\bootstrap\console.php(43): require('C:\\Users\\bramb\\...')
#17 C:\Users\bramb\Documents\Websites\leendersbiketotaal.nl\craft(21): require('C:\\Users\\bramb\\...')
#18 {main}
2020-01-29 11:07:15 [-][-][-][info][application] $_GET = []

**Comment by andris-sevcenko** [comment] 2020-01-29 12:13
Ah okay, that was fixed today. To fix this,change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#67d2a4aa7724189682897035c1b90baeb358ebf7 as 3.4.0.2",
  "...": "..."
}
```

Then run `composer update`.

And then perform the update again? I'm afraid there was a small oversight in how Project Config changes were migrated which borked plugin settings that used associative arrays.

Sorry about that!

**Comment by BramBeekman** [comment] 2020-01-29 12:17
> ```json
> "craftcms/cms": "dev-develop#67d2a4aa7724189682897035c1b90baeb358ebf7 as 3.4.0.2",
> ```

Still not working.

**Comment by andris-sevcenko** [comment] 2020-01-29 12:20
Did you perform the update on a pre-3.4 update database?

**Comment by BramBeekman** [comment] 2020-01-29 12:22
> Did you perform the update on a pre-3.4 update database?

Yes i think so..

**Comment by andris-sevcenko** [comment] 2020-01-29 12:24
@BramBeekman in that case, can you send over the pre-update database, your composer.json, and composer.lock files to support@craftcms.com and reference this issue, please?

**Comment by BramBeekman** [comment] 2020-01-29 12:25
> @BramBeekman in that case, can you send over the pre-update database, your composer.json, and composer.lock files to [support@craftcms.com](mailto:support@craftcms.com) and reference this issue, please?

I'm not sure if i did, can you explain what it means?

**Comment by andris-sevcenko** [comment] 2020-01-29 12:28
I mean can you zip up your pre-update database (from the installation that was before you updated to 3.4.x) and send it over email to support@craftcms.com. Also, please attach the composer.json and composer.lock files, so I can install the site locally and see what problem you're having. Make sure to mention this Github issue in the subject, so we know what that is all about :)

**Comment by BramBeekman** [comment] 2020-01-29 12:31
> I mean can you zip up your pre-update database (from the installation that was before you updated to 3.4.x) and send it over email to [support@craftcms.com](mailto:support@craftcms.com). Also, please attach the composer.json and composer.lock files, so I can install the site locally and see what problem you're having. Make sure to mention this Github issue in the subject, so we know what that is all about :)

Done

**Comment by brandonkelly** [comment] 2020-01-29 18:34
Closing this; we’ll get this resolved offline.

**Comment by Tam** [comment] 2020-02-10 15:09
I'm getting this error as well (Craft 3.4.5). Looks like something went wrong when project config tried to store an associative array from a config file where the value was a function.

```php
return [
    'geoLocationAutoRedirect' => true,
    'geoLocationRedirectMap' => [
        'example' => [ 'isEU' => function ($isEu) { return $isEu; } ],
        //                       ^ looks like this is causing the error
        'default' => '*',
    ],
];
```

```
2020-02-10 06:56:48 [-][-][44dee9d50e61b8684ab6d44a80fd7482][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined offset: 1 in /var/www/html/vendor/craftcms/cms/src/helpers/ProjectConfig.php:275
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/html/v...', 275)
#1 /var/www/html/vendor/craftcms/cms/src/helpers/ProjectConfig.php(275): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/html/v...', 275, Array)
#2 /var/www/html/vendor/craftcms/cms/src/helpers/ProjectConfig.php(284): craft\helpers\ProjectConfig::unpackAssociativeArray(Array, true)
#3 /var/www/html/vendor/craftcms/cms/src/helpers/ProjectConfig.php(254): craft\helpers\ProjectConfig::unpackAssociativeArray(Array)
#4 /var/www/html/vendor/craftcms/cms/src/services/Plugins.php(1372): craft\helpers\ProjectConfig::unpackAssociativeArrays(Array)
#5 /var/www/html/vendor/craftcms/cms/src/services/Plugins.php(206): craft\services\Plugins->_getPluginConfigData('simplemap')
#6 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1351): craft\services\Plugins->loadPlugins()
#7 /var/www/html/vendor/craftcms/cms/src/web/Application.php(103): craft\web\Application->_postInit()
#8 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#9 /var/www/html/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#10 /var/www/html/vendor/craftcms/cms/src/web/Application.php(91): yii\base\Application->__construct(Array)
#11 [internal function]: craft\web\Application->__construct(Array)
#12 /var/www/html/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#13 /var/www/html/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#14 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#15 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array)
#16 /var/www/html/vendor/craftcms/cms/bootstrap/web.php(51): require('/var/www/html/v...')
#17 /var/www/html/web/index.php(20): require('/var/www/html/v...')
#18 {main}
```

**Comment by brandonkelly** [comment] 2020-02-11 17:08
@Tam Hm yeah… that shouldn’t have been saved to begin with. Can you send your `composer.json` and `composer.lock` files, along with a database backup, over to support@craftcms.com?

**Comment by Tam** [comment] 2020-02-12 10:32
@brandonkelly That's sent, let me know if you need anything else!

**Comment by mizziness** [comment] 2020-04-28 14:28
This just happened to me in my local environment after I had removed a language-based site from the system, running Craft CMS version 3.4.15. The issue seems to have been caused by the associated row in the `sites` table remaining after the site delete.  

Here's the table contents *after* the site had been deleted already:

![image](https://user-images.githubusercontent.com/4164335/80498906-49f31f80-893a-11ea-92fb-59a26d969092.png)

As a result, code where the site IDs were being iterated over would throw this error. I was able to fix it by manually removing the dead site row from the `sites` table. 

Hope this helps someone!

**Comment by brandonkelly** [comment] 2020-04-28 22:45
@mizziness Sites only get soft-deleted initially. Shouldn’t result in any errors though. Do you still have a database backup from before you went in and deleted that row? If so can you please send into support@craftcms.com?

**Comment by mizziness** [comment] 2020-06-08 16:34
> @mizziness Sites only get soft-deleted initially. Shouldn’t result in any errors though. Do you still have a database backup from before you went in and deleted that row? If so can you please send into [support@craftcms.com](mailto:support@craftcms.com)?

Apologies for the slow reply!  

I do believe I may have the database backups from around then - I will go spelunking and see if a) I do and b) if I can recreate the issue - if so, I'll send it all over to you :) Thanks!

**Comment by brandonkelly** [comment] 2020-06-12 12:10
What exactly is Scout doing with the project config that is messing things up?

**Comment by timkelty** [comment] 2020-06-13 04:52
@brandonkelly Scout isn't doing anything explicit with project config.

The setting that is causing the error is `indices`, which is only settable via `config/scout.php`: https://github.com/riasvdv/craft-scout/blob/master/src/models/Settings.php#L28, and is an array of objects (instances of https://github.com/riasvdv/craft-scout/blob/master/src/ScoutIndex.php).

When the settings are saved in the CP, the instances are converted to yaml, and then we get the `unpackAssociativeArray` error.

**Comment by brandonkelly** [comment] 2020-06-15 22:04
Ahh, gotcha.

**Comment by brandonkelly** [comment] 2020-06-15 22:23
The way Scout 2 is storing nested objects in its field settings would have been problematic even before project config.

I’ve just submitted riasvdv/craft-scout#162 which should fix this error going forward.

**Closed by brandonkelly** 2020-06-15 22:23 UTC

**Comment by timkelty** [comment] 2020-06-15 22:32
Thanks @brandonkelly.

Is/should there be something in the docs stating plugin settings shouldn't contain values like this, or should explicitly exclude them as you PR'd?

**Comment by brandonkelly** [comment] 2020-06-15 22:33
Probably! cc @mattstein

**Comment by mattstein** [comment] 2020-06-16 14:52
Added a note to [the Plugin Settings page](https://docs.craftcms.com/v3/extend/plugin-settings.html#settings-model), @timkelty.

**Comment by williamhibberd** [comment] 2021-05-27 11:30
I'm getting the same error related to the TotalRevenue commerce widget. 
Any advice on how to fix it and get back into the cp?

```
yii\base\ErrorException: Undefined offset: 1 in /home/forge/***.com/vendor/craftcms/commerce/src/widgets/TotalRevenue.php:140
Stack trace:
#0 /home/forge/myurl.com/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/home/forge/pip...', 140)
#1 /home/forge/myurl.com/vendor/craftcms/commerce/src/widgets/TotalRevenue.php(140): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/home/forge/pip...', 140, Array)
#2 [internal function]: craft\commerce\widgets\TotalRevenue::craft\commerce\widgets\{closure}(NULL)
#3 /home/forge/myurl.com/vendor/craftcms/commerce/src/widgets/TotalRevenue.php(139): array_map(Object(Closure), Array)
#4 /home/forge/myurl.com/vendor/craftcms/cms/src/controllers/DashboardController.php(508): craft\commerce\widgets\TotalRevenue->getBodyHtml()
#5 /home/forge/myurl.com/vendor/craftcms/cms/src/controllers/DashboardController.php(107): craft\controllers\DashboardController->_getWidgetInfo(Object(craft\commerce\widgets\TotalRevenue))
#6 [internal function]: craft\controllers\DashboardController->actionIndex()
#7 /home/forge/myurl.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /home/forge/myurl.com/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#9 /home/forge/myurl.com/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('index', Array)
#10 /home/forge/myurl.com/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('index', Array)
#11 /home/forge/myurl.com/vendor/craftcms/cms/src/web/Application.php(278): yii\base\Module->runAction('dashboard/index', Array)
#12 /home/forge/myurl.com/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('dashboard/index', Array)
#13 /home/forge/myurl.com/vendor/craftcms/cms/src/web/Application.php(263): yii\web\Application->handleRequest(Object(craft\web\Request))
#14 /home/forge/myurl.com/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /home/forge/myurl.com/web/index.php(22): yii\base\Application->run()
#16 {main}
```

**Comment by brandonkelly** [comment] 2021-05-28 04:12
@williamhibberd See craftcms/commerce#2117
