### ISSUE TITLE
Save action on My Account generates 403 error when in devMode

### ISSUE THREAD

**Issue by johnfmorton** [craftcms/cms#1875] opened 2017-07-26 20:46 UTC
### Description

With **devMode** set to true, when trying to update my own user details, hitting save generates the error "HTTP 403 – Forbidden – yii\web\ForbiddenHttpException".

### Steps to reproduce

1. Go to https://mysite.com/admin/myaccount
2. Change something, like your first name or user photo.
3. Hit SAVE
4. The info will have been saved, but you are presented with a 403 Forbidden error.

### Additional info

- Craft version: 3.0.0-beta.22
- PHP version: 7.1.5-1+deb.sury.org~xenial+2
- Database driver & version: MySQL 5.7.19-0ubuntu0.16.04.1
- Plugins & versions: Doxter

**Comment by brandonkelly** [comment] 2017-07-26 22:27
What is the URL at the time you get the 403 error? I’m not able to reproduce, and nothing in the code for the actual `users/save-user` action would cause a 403 error _after_ the user has been saved.

**Comment by brandonkelly** [comment] 2017-07-27 20:58
After looking into this on John's box, I'm pretty sure this is a duplicate of the underlying bug in #1849 (albeit different symptoms).

@johnfmorton Can you try running `composer require craftcms/cms:dev-develop` and see if the issue still occurs?

**Closed by brandonkelly** 2017-07-27 20:58 UTC
Labels: need more info

**Comment by johnfmorton** [comment] 2017-07-28 22:01
Yes, that's fixed now. Thank you.

**Comment by brandonkelly** [comment] 2017-07-28 22:49
Great :) And the fix has been officially released as part of Beta 23 now.
