### ISSUE TITLE
TypeError: Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given

### ISSUE THREAD

**Issue by jules1091** [craftcms/cms#5530] opened 2020-01-29 14:30 UTC
We got this bug today with Craft 3.3 after adding fields to field group.

```
PHP version	7.2.24
OS version	Linux 4.15.0-64-generic
Database driver & version	MySQL 8.0.19
Image driver & version	GD 7.2.24
Craft edition & version	Craft Pro 3.3.18.1
Yii version	2.0.30
Twig version	2.12.2
Guzzle version	6.5.0
Imagine version	1.2.3-dev
```

```
2020-01-29 14:56:22 [-][476][f0ibss123mmstuma8rcpfi7h7g][error][TypeError] TypeError: Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given, called in /path/to/craft/vendor/craftcms/cms/src/base/Field.php on line 478 and defined in /path/to/craft/vendor/craftcms/cms/src/services/Fields.php:240
Stack trace:
#0 /path/to/craft/vendor/craftcms/cms/src/base/Field.php(478): craft\services\Fields->getGroupById(NULL)
#1 /path/to/craft/vendor/yiisoft/yii2/base/Component.php(139): craft\base\Field->getGroup()
#2 /path/to/craft/vendor/craftcms/cms/src/helpers/Template.php(89): yii\base\Component->__get('group')
#3 /path/to/craft/storage/runtime/compiled_templates/af/aff6cc283acac8d3c425f91f1644b8704d4652db44a301e81c384bd3b4b850d9.php(307): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\fields\Matrix), 'group', Array)
#4 /path/to/craft/vendor/twig/twig/src/Template.php(184): __TwigTemplate_ebf1bd4b29a86d5921abf2af52af7a00b0486718e909f60aaf99a2a14da6cfdb->block_content(Array, Array)
#5 /path/to/craft/storage/runtime/compiled_templates/72/7204753040a30a720f46661b66773d3b4af6ae6f2f5f50ba5347d4186ad14a1e.php(727): Twig\Template->displayBlock('content', Array, Array)
#6 /path/to/craft/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c1e0f919a5413be13dfcd65bfa15f8fb959e8341940b07bb5a5b3d7e8d79f844->block_main(Array, Array)
#7 /path/to/craft/storage/runtime/compiled_templates/72/7204753040a30a720f46661b66773d3b4af6ae6f2f5f50ba5347d4186ad14a1e.php(576): Twig\Template->displayBlock('main', Array, Array)
#8 /path/to/craft/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c1e0f919a5413be13dfcd65bfa15f8fb959e8341940b07bb5a5b3d7e8d79f844->block_body(Array, Array)
#9 /path/to/craft/storage/runtime/compiled_templates/de/de4c8362bc1e31725a77b1bb7f4aee8b9afa9a729b3a3357a6668aa1db2c8b6f.php(75): Twig\Template->displayBlock('body', Array, Array)
#10 /path/to/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_e411ffc4c4db07fe06e7b63c37effec6ad60ca39fe14382c49db3b423473f6b4->doDisplay(Array, Array)
#11 /path/to/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /path/to/craft/storage/runtime/compiled_templates/9e/9eab13eb6339ba3f4c8d8c3fe88aa91adea73ec46d5c0586fd907af631d4f38e.php(56): Twig\Template->display(Array, Array)
#13 /path/to/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_9845b3ccabfc2040f32e7e5953bb48cab2b790e791ec0b6c8adec2f62fb26f98->doDisplay(Array, Array)
#14 /path/to/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /path/to/craft/storage/runtime/compiled_templates/72/7204753040a30a720f46661b66773d3b4af6ae6f2f5f50ba5347d4186ad14a1e.php(118): Twig\Template->display(Array, Array)
#16 /path/to/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_c1e0f919a5413be13dfcd65bfa15f8fb959e8341940b07bb5a5b3d7e8d79f844->doDisplay(Array, Array)
#17 /path/to/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /path/to/craft/storage/runtime/compiled_templates/af/aff6cc283acac8d3c425f91f1644b8704d4652db44a301e81c384bd3b4b850d9.php(82): Twig\Template->display(Array, Array)
#19 /path/to/craft/vendor/twig/twig/src/Template.php(407): __TwigTemplate_ebf1bd4b29a86d5921abf2af52af7a00b0486718e909f60aaf99a2a14da6cfdb->doDisplay(Array, Array)
#20 /path/to/craft/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /path/to/craft/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#22 /path/to/craft/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#23 /path/to/craft/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#24 /path/to/craft/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('settings/fields', Array)
#25 /path/to/craft/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('settings/fields', Array)
#26 /path/to/craft/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('settings/fields', Array)
#27 /path/to/craft/vendor/craftcms/cms/src/controllers/TemplatesController.php(101): craft\web\Controller->renderTemplate('settings/fields', Array)
#28 [internal function]: craft\controllers\TemplatesController->actionRender('settings/fields', Array)
#29 /path/to/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /path/to/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#31 /path/to/craft/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('render', Array)
#32 /path/to/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#33 /path/to/craft/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('templates/rende...', Array)
#34 /path/to/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#35 /path/to/craft/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#36 /path/to/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#37 /path/to/craft/web/index.php(42): yii\base\Application->run()
#38 {main}
```

**Comment by brandonkelly** [comment] 2020-01-29 18:56
It’s hard to tell from your stack trace what’s going on, but you could try running `./craft project-config/rebuild` and see if that helps. Otherwise, please send your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com with steps to reproduce the error, and we can try to look into it from there?

**Comment by enobis-dev** [comment] 2020-07-10 16:50
Having the same issue on a large site just occur when we tried to add a new field, did running `./craft project-config/rebuild` resolve the issue?

**Comment by mofman** [comment] 2020-08-06 10:56
On Craft 3.5.1

Getting this same error when got to settings>fields since trying to add a field - i got an error there too.

Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given, called in /Users/andrew/Sites/knockbracken-fuels/vendor/craftcms/cms/src/base/Field.php on line 554

**Comment by brandonkelly** [comment] 2020-08-06 21:19
@mofman Please email your Composer files and a database backup to support@craftcms.com as well, so we can look into it.

**Comment by mofman** [comment] 2020-08-06 21:24
Thanks Brandon - sent.

**Comment by paulmendrik** [comment] 2020-08-12 11:03
Same problem here after installing Craft 3.5.1 cannot creat new field or edit entries in Commerce. At first I completely lost the site after trying to update through the Dashboard , which seemed to work for the CMS but when I then tried to update Commerce in the same way, I lost the site completely and although I tried everything in the book, using composer etc. , in the end I decided to nuke the site and install Craft again, I did have a database backup and when completed the fresh install and Craft was back , I imported the old database files and had the site back again of sorts., until I tried to edit or add new data and the errors started to appear, it's been an absolute nightmare, especially as this is a site which is normally up to now at least, successfully managed by my client, through the dashboard as they have no terminal or composer knowledge. This is one of the reasons I have been recommending Craft to most of my clients, the fact that they could install the updates themselves without the assistance of a developer, which is a plus point for most. To get this site back even as an experienced developer took a couple of days and still there are issues, this is a real headache, which is not something I want to go through again every time there is a major update. It's a shame as up to now, I couldn't praise Craft enough as a cms, but now I 'm seriously looking at headless solutions and full stack development. FYI this is the latest error TypeError

Argument 1 passed to craft\web\View::renderObjectTemplate() must be of the type string, null given

**Comment by brandonkelly** [comment] 2020-08-12 19:56
@paulmendrik Sorry to hear that. If you write into support@craftcms.com with your Composer files and a database backup, we can look into it from there. If we are able to identify a bug we will get it fixed.

**Comment by paulmendrik** [comment] 2020-08-13 08:39
Hi Brandon, thanks for the reply, it's a real headache to say the least but will do what you suggested.Some additional information , whenever I try to changer something in the cms, this is the sql error I get "The SQL being executed was: UPDATE `sites` SET `groupId`=NULL, `baseUrl`='https://stationfurniture.store', `dateUpdated`='2020-08-13 08:33:25' WHERE `id`=1". Thanks for looking at this much appreciated !

**Comment by paulmendrik** [comment] 2020-08-13 08:53
Please find attached db backup file and composer files of the installation which is creating this problem, I’ve put this installation on a test server @https://imwd.design/  to access admin , username:admin password: station  
Hope you can locate the problem and a fix  !

Best wishes

Paul

    WEBDESIGN    
Paul Mendrik
t. +33 (0)6 06 43 23 56
w. www.imwd.fr
    
Ce message, ainsi que les pièces jointes, sont établis, sous la seule responsabilité de l’expéditeur, à l’intention exclusive de ses destinataires ; ils peuvent contenir des informations confidentielles. Toute publication, utilisation ou diffusion doit être autorisée préalablement. Ce message a fait l’objet d’un traitement anti-virus. Il est rappelé que tout message électronique est susceptible d’altération au cours de son acheminement sur Internet.


 


On 12 August 2020 at 21:56:17, Brandon Kelly (notifications@github.com) wrote:

@paulmendrik Sorry to hear that. If you write into support@craftcms.com with your Composer files and a database backup, we can look into it from there. If we are able to identify a bug we will get it fixed.

**Comment by brandonkelly** [comment] 2020-08-13 20:07
Hey Paul,

Please send those into support@craftcms.com – not GitHub.

**Comment by paulmendrik** [comment] 2020-08-20 12:08
Hi Brandon, Although the CMS appears  to working alright Commerce is still a major problem even after recent updates, whenever I try to edit or add a product say, I get this error "Argument 1 passed to craft\web\View::renderObjectTemplate() must be of the type string, null given, called in /home/kat/sites/design/vendor/craftcms/commerce/src/elements/Product.php on line 798" I heard back from Oli after sending the database and composer files with regard  to the CMS problem and have advised him of the ongoing Commerce problem  but haven't heard back again . BTW running ./craft project-config/rebuild does not fix the issue either.

**Comment by paulmendrik** [comment] 2020-08-20 12:32
Hi Brandon, another update after running ./craft project-config/rebuild again I get this:  "Rebuilding the project config from the current state ... error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Public Schema' for key 'gqlschemas_name_unq_idx'
The SQL being executed was: INSERT INTO `gqlschemas` (`uid`, `name`, `isPublic`, `scope`, `dateCreated`, `dateUpdated`) VALUES ('7488677a-fcb5-49a0-8352-99e9cbb1137e', 'Public Schema', 1, '[]', '2020-08-20 12:13:21', '2020-08-20 12:13:21')".  Does this help ?

**Comment by sclander** [comment] 2020-08-24 19:15
Pieter-Jan (and anyone else who may be experiencing this issue).

I was able to solve this through a little DB surgery. If you have access to the database through an external tool do this: 

1. search the fields table for any entries where context="global" and groupId="null" and delete them
2. search the projectconfig table for any entries where path looks like "fields.<uuid>.fieldGroup and value="null" and delete those
3. delete your config/project/ folder and navigate to the admin panel so it get regenerated

I'm not 100% sure 2 and 3 are necessary, but just wanted to include everything I did in case those parts are key.

**Comment by jornwildenbeest** [comment] 2020-08-25 07:54
@sclander Thanks for your tip! It worked for me. 

I used the following queries for anyone else who may be experiencing this issue.

1. `select * from craft_fields where context = "global" and groupId is NULL`
2. `select * from craft_projectconfig where path like 'fields%' and path like '%fieldGroup' and value = "null"`
3. delete your config/project/ folder and navigate to the admin panel so it gets regenerated

Just like @sclander said.

**Comment by brandonkelly** [comment] 2020-08-25 23:51
We are usually able to track this back to project config YAML changes getting applied before the [environments were properly set up for it](https://craftcms.com/docs/3.x/project-config.html#environment-setup). So we’ve made that much less likely to happen in Craft 3.5.6 and onward, due to the changes in e3557477ded88223933039031be5de8a79dac2c7:

- Craft will no longer block you from accessing the control panel when it detects that there are pending project config YAML changes while in Dev Mode, and forcing you to choose between either applying or ignoring the changes. Instead, it will start displaying a banner across the top of the control panel, pointing out that there are pending changes, with a “Review” link.

  ![A control panel alert that says there are pending project config YAML changes](https://user-images.githubusercontent.com/47792/91238809-c03e3d80-e6f2-11ea-8a71-38d86f93c1eb.png)


- Clicking “Review” will take you to the Project Config utility, which now clearly displays exactly which YAML changes are pending. If your project isn’t actually properly set up for project config yet, you will see a large volume of changes here that should alert you to the fact that maybe applying them isn’t a smart idea. Additionally, there is a warning that links to the Environment Setup instructions right above the Apply buttons. There’s also a new “Discard changes” button, which will regenerate your project config YAML files based on the currently-loaded project config, discarding any pending changes.

  ![The Project Config utility, showing a comparison view of the pending project config YAML changes](https://user-images.githubusercontent.com/47792/91238876-e532b080-e6f2-11ea-9e7b-e8866c9945a5.png)

- The same comparison view is also available from a new `project-config/diff` command:

  ![Example project-config/diff command output](https://user-images.githubusercontent.com/47792/91238955-0a272380-e6f3-11ea-864f-2206be39fc25.png)

**Comment by paulmendrik** [comment] 2020-09-01 09:23
Hi Brandon, Great that seems to have resolved all those issues, thanks again !

I do have another issue which happened at the same time as the others and hasn't been resolved with this latest update. It concerns the Craft Commerce Stripe plugin for the stripe gateway I use on this site. It was working fine before all this happened but now I'm getting a HTTP 400 Bad Request  , Request contains invalid body param. I'm using the following to create the payment form:

<form method="POST">
<input type="hidden" name="action" value="commerce/payments/pay"/>
<input type="hidden" name="redirect" value="/commerce/customer/order?number={number}"/>
<input type="hidden" name="cancelUrl" value="{{ '/shop/checkout/payment'|hash }}"/>
{{ csrfInput() }}

{{ cart.gateway.getPaymentFormHtml({})|raw }}

<div class="uk-form-controls uk-margin-large-top">
<button type="submit" class="uk-button uk-button-secondary">Pay {{ cart.totalPrice|commerceCurrency(cart.paymentCurrency,convert=true) }}</button>
</div>

</form>

Finally checking the logs in stripe it gives a 200 O.K. without finalising the payment. 

Any ideas ?

**Comment by brandonkelly** [comment] 2020-09-01 20:10
@paulmendrik Glad to hear that. Can you please post the Stripe issue over at https://github.com/craftcms/commerce-stripe/issues ?

**Closed by brandonkelly** 2020-09-01 20:10 UTC

**Comment by paulmendrik** [comment] 2020-09-02 06:01
@brandonkelly no worries, will do !

**Comment by eteos** [comment] 2020-11-04 11:19
Just want to add that instead of deleting the fields that don't have a group, you can also just add them to a random group in the DB to make it work again. IMO thats more convenient since then you don't have to recreate the fields. 

Don't forget to run a project-config/rebuild afterwards to apply these DB changes to the yaml.

**Comment by robinsm** [comment] 2021-08-19 13:17
None of the above worked for us with exactly the same issue.
In Craft admin, Utilities -> Project Config -> Reapply everything also failed with an error.

Eventually applied project-config in the terminal (with --force) and it solved the issue.

`./craft project-config/apply --force `

Hope that helps somebody.
