### ISSUE TITLE
[4.5]: Deprecation notices because of dynamic properties

### ISSUE THREAD

**Issue by alexgit2k** [craftcms/cms#14009] opened 2023-12-08 13:49 UTC
### Description

Craft CMS still uses dynamic properties which are deprecated since PHP 8.2, see https://php.watch/versions/8.2/dynamic-properties-deprecated

In PHP 9.0, dynamic properties will result in a fatal error!

### Steps to reproduce

1. composer require phpstan/phpstan
2. vendor/bin/phpstan analyse

### Expected behavior

No deprecation notices

### Actual behavior

Deprecation notices like:
```
Access to an undefined property craft\base\ElementInterface::$applicationDeadline. 
Access to an undefined property craft\base\ElementInterface::$badgeIcon. 
Access to an undefined property craft\base\ElementInterface::$benefitRelations. 
Access to an undefined property craft\base\ElementInterface::$cardColor. 
Access to an undefined property craft\base\ElementInterface::$cardImage. 
Access to an undefined property craft\base\ElementInterface::$cardLink. 
Access to an undefined property craft\base\ElementInterface::$cardLogo. 
Access to an undefined property craft\base\ElementInterface::$customEventDate. 
Access to an undefined property craft\base\ElementInterface::$disableCardImage. 
Access to an undefined property craft\base\ElementInterface::$duplicateOf. 
Access to an undefined property craft\base\ElementInterface::$eventEnd. 
Access to an undefined property craft\base\ElementInterface::$eventStart. 
Access to an undefined property craft\base\ElementInterface::$eventTargetGroup. 
Access to an undefined property craft\base\ElementInterface::$hardDelete. 
Access to an undefined property craft\base\ElementInterface::$id. 
Access to an undefined property craft\base\ElementInterface::$image. 
Access to an undefined property craft\base\ElementInterface::$kicker. 
Access to an undefined property craft\base\ElementInterface::$logo. 
Access to an undefined property craft\base\ElementInterface::$metaDescription. 
Access to an undefined property craft\base\ElementInterface::$moreInformation. 
Access to an undefined property craft\base\ElementInterface::$noindex. 
Access to an undefined property craft\base\ElementInterface::$ogDescription. 
Access to an undefined property craft\base\ElementInterface::$ogImage. 
Access to an undefined property craft\base\ElementInterface::$partnerCompany. 
Access to an undefined property craft\base\ElementInterface::$place. 
Access to an undefined property craft\base\ElementInterface::$productDates. 
Access to an undefined property craft\base\ElementInterface::$productTargetGroup. 
Access to an undefined property craft\base\ElementInterface::$scholarshipDescription. 
Access to an undefined property craft\base\ElementInterface::$showApplicationDeadline. 
Access to an undefined property craft\base\ElementInterface::$siteId. 
Access to an undefined property craft\base\ElementInterface::$title. 
Access to an undefined property craft\base\ElementInterface::$updatingFromDerivative. 
Access to an undefined property craft\base\ElementInterface::$uri. 
Access to an undefined property craft\base\ElementInterface::$useCustomEventDate. 
Access to an undefined property craft\base\FieldInterface::$handle. 
Access to an undefined property craft\base\FieldInterface::$id. 
```

### Solution

Declare the properties or mark classes to allow dynamic properties, see https://www.php.net/manual/en/class.allowdynamicproperties.php

### Craft CMS version

4.5

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment] 2023-12-09 15:12
Craft doesn’t ever use dynamic properties – any class that extends `yii\base\BaseObject` will throw an exception if you try.

The issue is that PHPStan doesn’t recognize our `@mixin ElementTrait` here:

https://github.com/craftcms/cms/blob/ddb107ae0170cd1993b5e97b7af37bf7f6cddd32/src/base/ElementInterface.php#L26

That works for PhpStorm, but PHPStan is more strict about it.

For now, you can just have PHPStan ignore those issues, as we’ve done for Craft 5 here:

https://github.com/craftcms/cms/blob/94c91e9aeaea7d7aac6e8d442ef1213fc0f58b2c/phpstan.neon#L56-L57

In the future, we are expecting this will be fixed via a new `@phpstan-require-use` tag we can add (https://github.com/phpstan/phpstan/issues/9899).

**Closed by brandonkelly** 2023-12-09 15:12 UTC
Labels: bug, craft4
