### ISSUE TITLE
Custom plugins that share names with ones in the Plugin Store have name/update collisions

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#3751] opened 2019-01-30 03:00 UTC
### Description
There are times we build a custom plugin for a client and don't intend to publish this to the Plugin Store. For instance, I may create a simple "Twitter" or "Weather" plugin. However, if there's already a "[Twitter](http://plugins.craftcms.com/twitter)" or "Weather" plugin in the Plugin Store then I see the updates for that plugin in the "Updates" section of the control panel. 

The same goes for the "Plugin" page. If I click the icon for the custom "Twitter" plugin it takes me to [the Twitter plugin that currently exists in the Plugin Store](http://plugins.craftcms.com/twitter).

### Steps to reproduce

1. Create a "Twitter" plugin using the Plugin Factory generator and ensure you set the version to `1.0.0`
2. Add it into a `plugins` directory in your Craft project
3. Add the following to your composer.json:

```
"repositories": [
    {
      "type": "path",
      "url": "path/to/plugins/*"
    }
  ]
```

4. Run `composer require authorName/twitter`
5. Go to Utilities > Updates within the control panel
6. You'll see the changelog for the actual "Twitter" plugin in the Plugin Store

### Additional info

- Craft version: 3.1.6.1
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25

**Comment by brandonkelly** [comment] 2019-01-30 22:47
Duplicate of #3054 - see the discussion there.

**Closed by brandonkelly** 2019-01-30 22:47 UTC

**Comment by aaronbushnell** [comment] 2019-01-31 02:05
Ah, sounds like I oughta be utilizing Modules in place of Plugins to avoid this. Thanks, @brandonkelly!
