### ISSUE TITLE
Custom Fields fail to display error messages

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#2608] opened 2018-03-20 19:35 UTC
### Description

Custom Fields do not show error messages:
http://share.barrelstrength.co/2g253d003J0W

Craft fails validation and displays 'Unable to save entry' but doesn't display any error messages.

Not sure if this relates, but we recently started experiencing a related issues in our Sprout Forms plugin. Currently, in our case, Sprout Forms does not only fail to show error messages, all of the validators fail to even run. Submitting an entry on the front-end or backend just submits every time. We haven't got to the bottom of it yet, but we're hoping to see if this issue gets resolved in Craft.

### Steps to reproduce

1. Add a field to a channel
2. Make it required
3. Try to save without adding a value

### Additional info

- Craft version: RC15
- PHP version: 7.1
- Database driver & version: Mysql
- Plugins & versions: Lots under development, but have tested and seen similar results in multiple environments.

**Comment by brandonkelly** [comment] 2018-03-21 18:55
Duplicate of #2572

**Closed by brandonkelly** 2018-03-21 18:55 UTC
