### ISSUE TITLE
[3.2] upload assets to asset field with data saved not working

### ISSUE THREAD

**Issue by zizther** [craftcms/cms#4532] opened 2019-07-11 16:52 UTC
### Description

When trying to add assets to a field with assets already saved, the Assets modal shows but does not complete loading fully, show any assets, or give the ability to upload

There are no 404 or console log errors.

This issue happens if the field is in a Global, in a Section, or in a matrix field.

It is the same with fields created before the C3.2 update and new fields created in 3.2

### Steps to reproduce

1. Create an assets field assign it to a section or global
2. Upload file and save
3. Try to add another asset

### Additional info

- Craft version: 3.2.0
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.23
- Plugins & versions: 
       Neo 2.3.5
       S3 1.2.3
       Redactor 2.3.3.2
       SEOmatic 3.2.13
       Imager 2.1.10

**Comment by brandonkelly** [comment] 2019-07-11 17:43
This is a duplicate of #4522.

**Closed by brandonkelly** 2019-07-11 17:43 UTC
