### ISSUE TITLE
camelCase in DB_TABLE_PREFIX will be ignored in search index and creates error

### ISSUE THREAD

**Issue by elfacht** [craftcms/cms#5102] opened 2019-10-15 12:00 UTC
### Description

When a `DB_TABLE_PREFIX` with a camelCase will be used, the CMS will ignore it when it creates the `searchindex` table.

![Screenshot 2019-10-15 um 13 56 01](https://user-images.githubusercontent.com/529443/66829434-ae78ff00-ef53-11e9-874c-4d480667437d.jpg)

This will be a problem if a local DB will be transferred to i.e. staging. It will produce an error:

```
2019-10-15 13:50:04 [-][1][-][error][craft\queue\QueueLogBehavior::afterError]  [2] Updating search indexes (attempt: 1) - Error (time: 0.007s): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'paracuda_sunday.sunDa_searchindex' doesn't exist
```

### Steps to reproduce

1. Set `DB_TABLE_PREFIX='sunDa'`
2. Transfer local DB to staging server.
3. Receive errors when searching for entries in CP

### Additional info

- Craft version: 3.3.9

**Comment by brandonkelly** [comment] 2019-10-15 13:09
I’m not able to reproduce this; I just installed Craft with both MySQL and PostgreSQL with a camelCased table prefix, and the `searchindex` table got the same prefix casing as all the other tables.

If it’s working locally for you, and the issue only arises when transferring to a staging server, then it’s something to do with that deployment process, not Craft.

**Closed by brandonkelly** 2019-10-15 13:09 UTC

**Comment by elfacht** [comment] 2019-10-15 13:17
@brandonkelly Thanks for having a look at this. The DB table is already in lowercase on the local environment (screenshot). I don't know how and where my deployment process should alter the table name locally, especially when all other tables are fine and in camel case. I'm doing the transfer to staging by hand, but as said, it happened already on local. Any idea what may caused this?

**Comment by brandonkelly** [comment] 2019-10-15 16:44
Are you able to reproduce with a fresh install?

We’ve never had a need to rename the `searchindex` table in the code.
