### ISSUE TITLE
Add an expand all/collapse all button for categories (and structures) in the admin panel

### ISSUE THREAD

**Issue by cp-gregj** [craftcms/cms#7097] opened 2020-11-06 00:25 UTC
One of our clients currently uses a category set to organise part of their website, but they now have quite a lot of categories (thousands total, but only 4 top level) and they're finding managing this a bit frustrating as they have to close a lot of categories to get to the one that the ones that they actually want open. Having the ability to expand all and collapse all categories would make editing this much easier when there are a lot of categories.

Could be good for multi-level structures too.

**Comment by hiasl** [comment] 2020-11-11 15:16
Just wanted to request this for **multi-level structures** and found this request. 
+1 from our company / clients

**Comment by brandonkelly** [comment] 2021-02-12 00:54
This is a duplicate of #7097.

**Comment by hiasl** [comment] 2021-02-12 10:40
Please reopen one of the tickets, currently both are closed. Thanks!

**Comment by brandonkelly** [comment] 2021-02-12 18:23
Doh, sorry!

**Closed** 2021-06-22 06:29 UTC
Labels: enhancement, ui :eyes:
