### ISSUE TITLE
[Feature Request] Sortable global sets

### ISSUE THREAD

**Issue by McCrisp** [craftcms/cms#3230] opened 2018-08-23 11:48 UTC
It is not a huge issue, and I dont know if it is an easy solution to this, but being able to manually sort the order that global sets appear in would be quite nice in some cases.

![screen shot 2018-08-23 at 13 43 43](https://user-images.githubusercontent.com/13944443/44523663-f4815c80-a6da-11e8-92b7-00550cc74ffe.png)

**Comment by Anubarak** [comment] 2018-08-25 22:12
It is possible to change order. You can use `GlobalSetQuery::EVENT_AFTER_PREPARE` to change the query and include the order you like

**Comment by brandonkelly** [comment] 2018-08-27 10:28
Duplicate of #916

**Closed by brandonkelly** 2018-08-27 10:28 UTC
