### ISSUE TITLE
TypeError on admin settings/fields/ page

### ISSUE THREAD

**Issue by mizziness** [craftcms/cms#6856] opened 2020-09-17 16:57 UTC
### Description
Suddenly, if we try and view the settings page for fields in production, we get the following 500 error and the page does not load:

`2020-09-17 10:26:24 [-][127040][9a482a2810f748122845222bfe33acc8][error][TypeError] TypeError: Argument 1 passed to craft\services\Fields::getGroupById() must be of the type integer, null given, called in /storage/av05293/www/public_html/vendor/craftcms/cms/src/base/Field.php on line 556 and defined in /storage/av05293/www/public_html/vendor/craftcms/cms/src/services/Fields.php:245
`

No changes had been made to the database in 48 hours, other than a single blog entry being added by a non-admin. Nothing was changed related to fields.

(Stack trace pasted below)

### Steps to reproduce

1. Visit the build-in fields settings page at `/batman/settings/fields/`
2. 500 error

However, loading the url with a known field groupId works:

1. Go to `/batman/settings/fields/40`
2. Field data page loads.

### Error Info

The error pops here on line 91:

https://github.com/craftcms/cms/blob/b7c13482041d31eed7dd67a2ca511a44eaa542b0/src/templates/settings/fields/index.html#L90-L92

As a workaround, if I comment out `{% set group = field.group.name|t('site')|e %}` or change it to something like `{% set group = groups.one() %}` then the page loads again.

`Stack trace:
#0 /storage/av05293/www/public_html/vendor/craftcms/cms/src/base/Field.php(556): craft\services\Fields->getGroupById(NULL)
#1 /storage/av05293/www/public_html/vendor/yiisoft/yii2/base/Component.php(139): craft\base\Field->getGroup()
#2 /storage/av05293/www/public_html/vendor/craftcms/cms/src/helpers/Template.php(76): yii\base\Component->__get('group')
#3 /storage/av05293/www/public_html/storage/runtime/compiled_templates/d1/d1c93dafebdafab4ff98959a1927aadae7f5fb4ee2bfc298c77d68b4ca3a30fa.php(91): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\fields\Matrix), 'group', Array)
#4 /storage/av05293/www/public_html/vendor/twig/twig/src/Template.php(407): __TwigTemplate_d490584e11575497e1f29d9c1d363c4fd662e91138e06b04a42c66a4ae626f82->doDisplay(Array, Array)
#5 /storage/av05293/www/public_html/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /storage/av05293/www/public_html/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#7 /storage/av05293/www/public_html/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#8 /storage/av05293/www/public_html/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#9 /storage/av05293/www/public_html/vendor/craftcms/cms/src/web/View.php(392): Twig\Environment->render('settings/fields', Array)
#10 /storage/av05293/www/public_html/vendor/craftcms/cms/src/web/View.php(453): craft\web\View->renderTemplate('settings/fields', Array)
#11 /storage/av05293/www/public_html/vendor/craftcms/cms/src/web/Controller.php(251): craft\web\View->renderPageTemplate('settings/fields', Array, 'cp')
#12 /storage/av05293/www/public_html/vendor/craftcms/cms/src/controllers/TemplatesController.php(100): craft\web\Controller->renderTemplate('settings/fields', Array)
#13 [internal function]: craft\controllers\TemplatesController->actionRender('settings/fields', Array)
#14 /storage/av05293/www/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /storage/av05293/www/public_html/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#16 /storage/av05293/www/public_html/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('render', Array)
#17 /storage/av05293/www/public_html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#18 /storage/av05293/www/public_html/vendor/craftcms/cms/src/web/Application.php(280): yii\base\Module->runAction('templates/rende...', Array)
#19 /storage/av05293/www/public_html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#20 /storage/av05293/www/public_html/vendor/craftcms/cms/src/web/Application.php(265): yii\web\Application->handleRequest(Object(craft\web\Request))
#21 /storage/av05293/www/public_html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /storage/av05293/www/public_html/web/index.php(21): yii\base\Application->run()
#23 {main}
2020-09-17 10:26:21 [-][127040][9a482a2810f748122845222bfe33acc8][info][application] $_GET = [
    'p' => 'batman/settings/fields'
]`

### Additional info

PHP version 7.0.33
MySQL 5.7.31
Craft Pro 3.5.10.1

**Comment by ilicmarko** [comment] 2020-12-02 15:17
Possible duplicate of #5530

**Comment by brandonkelly** [comment] 2020-12-02 17:56
Whoops looks like this slipped through the cracks. Yeah looks the same to me.

**Closed by brandonkelly** 2020-12-02 17:56 UTC
Labels: bug
