### ISSUE TITLE
[5.x]: Plugin icons on the main settings page are styled over by Craft styling

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#14191] opened 2024-01-24 12:45 UTC
### Description
![image](https://github.com/craftcms/cms/assets/22771556/f4412e87-5400-4c04-8f1d-d367f12356c9)
All the plugin icons are getting a blue fill color on the `/admin/settings` page, unless they have inline fill styling

### Craft CMS version

5.0.0-alpha.8

### PHP version

8.3.2

### Operating system and version

Ubuntu 22.04

### Database type and version

mysql 8.0.32

**Comment by i-just** [comment] 2024-01-24 12:51
Hi, thanks for reporting! It looks like a duplicate of #14186, already fixed for the next release.

**Closed by i-just** 2024-01-24 12:51 UTC
Labels: bug
