### ISSUE TITLE
GraphQL: Empty result for asset query in matrix block within neo field

### ISSUE THREAD

**Issue by NickLanger1990** [craftcms/cms#5743] opened 2020-03-01 13:21 UTC
### Description
When an asset/image field is queried within a matrix block in a neo field the result is empty and an empty array is returned.

Entry -> Entries field -> Entry -> Neo Field -> Matrix Block -> Asset

### Steps to reproduce

1. Create a section with a Neo Field which contains an Matrix Field with an asset.

```
query {
  entries {
    ... on testContent_testContent_Entry {
      contentBuilder {
        ... on contentBuilder_imageNeoBlock_BlockType {
          imageMatrixField {
            ... on imageMatrixField_imageAsset_BlockType {
              imageAsset {
                img
                url
              }
            }
          }
        }
      }
    }
  }
}
```

### Additional info

- Craft version: 3.4.9
- PHP version: 7.3.14
- Database driver & version: MySQL 5.7.29
- Plugins & versions: 
Asset Usage 2.0.1
Dumper 2.0.0
ImageOptimize: 1.6.11
Navigation: 1.3.6
Neo: 2.6.2
Redactor: 2.6.0.1
Retour: 3.1.33
Sentry: 1.5.1
Seomatic: 3.2.45
Snitch: 3.0.1
Super Tablle 2.4.4

**Comment by andris-sevcenko** [comment] 2020-03-02 10:50
I'm unable to reproduce this. Does the schema you're using have any knowledge of the Volume that the Asset is from?

**Comment by NickLanger1990** [comment] 2020-03-02 11:45
yes. if i query instead of entries assets i get all my assets.

**Comment by andris-sevcenko** [comment] 2020-03-02 12:51
That's odd. Is it possible to get access to the site where you're experiencing this? If so, can you mail the CP access over to support@craftcms.com and reference this issue so we can look into this further?

**Comment by xconstruct** [comment] 2020-03-06 19:09
We'll probably prepare a minimal site for you to reproduce the problem, but in the meantime I've stepped through the code to try finding the cause.

I'm guessing the problem lies somewhere in preloading the asset field in the matrix block. If we override the `extractEagerLoadCondition` method of the resolver with a stub, it works as expected.

Also I've noticed that the eagerLoadConditions for the matrix block return only `['imageAsset']` with no block type prefix. If I'm understanding the code correctly, we'd rather expect something like `['blockType:imageAsset']`?

**Comment by andris-sevcenko** [comment] 2020-03-11 06:41
@NickLanger1990  Alright, so there's something wonky with eager-loading rule creation when traversing nested Matrix inside a Neo field. This is because Neo re-uses other fields as opposed to defining its own fields (like Matrix and SuperTable) does. This means that when analyzing the query and traversing into a Neo field, it causes all sorts of confusion for Craft when it comes to field contexts. This will be resolved in Craft 3.5

**Comment by andris-sevcenko** [comment] 2020-03-11 06:42
@xconstruct not sure if that's the same as the original issue. If that _also_ involves a Neo field, it might be the same issue. If not, please open a new GitHub issue. (If that's the case, though, please note that I'm unable to reproduce the wrong eager-load paths on Craft 3.4.9)

**Comment by andris-sevcenko** [comment] 2020-03-11 11:28
@NickLanger1990 Actually, this is a Neo issue. One that is easy to fix. You can follow it here: https://github.com/spicywebau/craft-neo/issues/306

**Closed by andris-sevcenko** 2020-03-11 11:28 UTC
