### ISSUE TITLE
Trapped by allowAdminChanges failing migration/s

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#5595] opened 2020-02-05 21:16 UTC
### Description
This occurs on a different path than you were likely thinking of in providing allowAdminChanges config originally, but probably a common enough one, where I found encirclement, and had to reload the database from backup to get out.

- Rather than upgrade in place, I pushed a dev site on latest Craft 3.4.3 to staging, which had been on 3.4.alpha1 I believe
- Naturally database wanted to update, pushed the button
- A migration failed, offer to restore database accepted
- Site 500s because a database column  is missing
- evidently database was not actually restored
- I realized allowAdminChanges was false through site having been .env'd to staging; reverted that
- loaded an outside-backed-up database
- now accepting database update ran all migrations
- back on the air, now 3.4.3 latest

Underlying this is another issue. I actually did the site push because 'mysteriously' I couldn't see Settings menu choice as an Admin, got 500 if I pathed url to it. All this was because  of allowAdminChanges false. 

Thus I would respectfully suggest there be a notification on and at the bottom of the lefthand menu panel of the cp, whenever all operations are not available because of allowAdminChanges false. Would save headscratching and false moves often enough, would suspect....thank you.

### Additional info

- Craft version: was 3.4.alpha1 believe. or beta1

**Comment by brandonkelly** [comment] 2020-02-05 21:24
Not sure I’m following. Did you get an error about `allowAdminChanges` in your original update attempt? If so, this is likely a duplicate of #5588.

**Comment by narration-sd** [comment] 2020-02-05 21:58
Good point. Sort of. I did get the "Changes to the project config are not possible while in read-only mode." message, forgot in the list of steps above.  

This  however says nothing about what 'read-only mode' is caused by...reflectively realized as allowAdminChanges false. Not obvious, and after-the-fact, thus my suggested second item to be very indicative of when this is so. Also so missing CP commands aren't a puzzle in the first place.

The primary item for this issue is to prevent the lockout loop in the first place. If 'read-only mode', then the database upgrade should not be attempted, don't you think? Instead, here again, a direct message that allowAdminChanges is false (rather than 'read-only mode????' and that you will need to change this to proceed with updating the database for the new Craft version code which has been uploaded. On a server push....

I'm probably stringing ideas again, so hope these two items are clear...

**Comment by brandonkelly** [comment] 2020-02-05 22:55
> Good point. Sort of. I did get the "Changes to the project config are not possible while in read-only mode." message, forgot in the list of steps above.

Alright, in that case it’s the same issue as #5588, so will close this as a duplicate.

> If 'read-only mode', then the database upgrade should not be attempted, don't you think?

If you are saying it shouldn’t be possible to update Craft on environments with `allowAdminChanges = false`, then I disagree :)

**Closed by brandonkelly** 2020-02-05 22:55 UTC

**Comment by narration-sd** [comment] 2020-02-05 23:05
Well...
> Alright, in that case it’s the same issue as #5588, so will close this as a duplicate.

As long as you fix that the message is inexplicable when stated as [only] 'read-only mode' vs. saying allowAdminChanges is false...

>  If you are saying it shouldn’t be possible to update Craft on environments with allowAdminChanges = false, then I disagree :)

I am saying it shouldn't be possible to enter the 'need update to database' stage, if the update to Craft php  files was from an external (sftp etc.) push. And that it should tell why not explicitly, as above,

I can see  you want to allow it if a person 'updates Craft' -- using the CP  Update button, yes.

I think you can tell the difference as one or the other happens...

**Comment by narration-sd** [comment] 2020-02-05 23:07
quick necessary edit just above....

**Comment by brandonkelly** [comment] 2020-02-05 23:18
> I am saying it shouldn't be possible to enter the 'need update to database' stage, if the update to Craft php files was from an external (sftp etc.) push, plus of course that allowAdminChanges is false

_Database_ changes **must** be run on **all** environments. The only thing we have to be cautious about is making _project config_ changes from migrations on environments where `allowAdminChanges = false`. Generally this is avoided by having the migration check the incoming Craft schema version in `project.yaml` – if it’s `>=` the schema version the migration was written for, that’s a good sign that the migration has already made whatever project config changes it needed to make on another environment, so no need to re-do the same changes on this one (they will get synced in soon enough once the migrations are finished executing).

The issue here is that there is likely some place in a 3.4 migration where we are not following that migration strategy perfectly.

**Comment by narration-sd** [comment] 2020-02-05 23:26
So you're saying the 'read-only' state fail message here was because  project config was engaged?

Possible that it had been, am uncertain, and (yet) reloading my off-site recent db backup allowed to proceed.

I accept the migration-watch strategy might have been borked since the prior db was alpha or beta especially.

You're telling me straight that 'read-only' means project config is read-only? Because it's reloading th prior db _plus_ allowAdminChanges true is what let me break out of the problem and proceed....

**Comment by brandonkelly** [comment] 2020-02-05 23:33
> So you're saying the 'read-only' state fail message here was because project config was engaged?

Correct, unrelated to database changes.

**Comment by brandonkelly** [comment] 2020-02-05 23:33
The exact error is `Changes to the project config are not possible while in read-only mode.` so that should be clear.

**Comment by brandonkelly** [comment] 2020-02-05 23:33
The exact error is `Changes to the project config are not possible while in read-only mode.` so that should be clear.

**Comment by narration-sd** [comment] 2020-02-05 23:36
'read-only mode' is the unclear phrase: that this is set by allowAdminChanges is the needed point....

And that I couldn't get back into CP at all because now the database was borked is still a fault to fix, yes? Which is why I am so interested in heading off this scenario before it happens

**Comment by narration-sd** [comment] 2020-02-05 23:38
And yes, just greped logs, and re: project config is what the error said; that's ok to that extent,  yes. But why, not yet...and prevention, once again...

**Comment by narration-sd** [comment] 2020-02-06 00:32
You noted I'm still on this, https://github.com/craftcms/cms/issues/5595#issuecomment-582664846, right? 

But out for a while, so no hurry - I believe this takes a little quiet thought anyway

**Comment by brandonkelly** [comment] 2020-02-06 00:40
To clarify, when `allowAdminChanges = false`, one _effect_ of that setting is that it puts the Project Config in **read-only mode**. You can technically toggle Project Config read-only mode independently of that config setting via the [craft\services\ProjectConfig::$readOnly](https://docs.craftcms.com/api/v3/craft-services-projectconfig.html#readonly) property.  You can see here how that gets set based on the `allowAdminChanges` value by default, but it’s overridable:

https://github.com/craftcms/cms/blob/9cf6b233afb68fb4988f21f8a55d4420b3dbb16b/src/helpers/App.php#L556

**Comment by narration-sd** [comment] 2020-02-06 00:44
Fair enough, but then even more needed to let a person know _how_ 'read-only mode' might have been set?

And again, the prevention of the lockout case I got inot seems a pretty good priority?

Because again, I couldn't even see the CP (or the site also borked) to recover.

Sorry to press, Brandon, but you see why, I think

**Comment by brandonkelly** [comment] 2020-02-06 18:39
Generally speaking people shouldn’t be able to get into a situation where they see that error to begin with. As will be the case here as of the next 3.4 release – see https://github.com/craftcms/cms/issues/5588#issuecomment-583048669.

**Comment by narration-sd** [comment] 2020-02-06 18:42
Yeah, I was watching that -- and had scanned the log to see how related I thought it was to case here.

Glad you're thinking about it, @brandonkelly,  and anyway, leaving you to do that as I know you prefer. May have had some added insight for your way arrive overnight but will probably spare you the email that might have resulted :)

**Comment by narration-sd** [comment] 2020-02-06 21:01
Just, I intend anyway, one more or so simple-side point on this. Became two.

1) I've just been looking at Project Config and related doc vs. my config on this site, and note `'useProjectConfigFile' => false`.  

I can of course think of this both ways, but if PC isn't enabled, is there a good reason that the db update required from the site php-source pushed update should have run into the `allowAdminChanges => false` block?

2) Underlying, the reason this mixup got my attention in the first place is that the push-button restore-prior-database _failed_.  Thus the site was 500 off the air, no t a good thing if it had been real instead of staging, as well as the CP being unreachable. 

I can't think of any reason except maybe another unintended effect of allowAdminChanges why the backup db wasn't...taken? ...or... was unable to be restored? I can't quite figure out from timestamps if it was taken,, but I think so.

**Comment by brandonkelly** [comment] 2020-02-06 21:43
> 1. I've just been looking at Project Config and related doc vs. my config on this site, and note `'useProjectConfigFile' => false`.
> 
> I can of course think of this both ways, but if PC isn't enabled, is there a good reason that the db update required from the site php-source pushed update should have run into the `allowAdminChanges => false` block?

Project config isn’t an optional feature that can be enabled/disabled. The only optional part of it is whether it gets written out to (and synced with) a `project.yaml` file. It still makes sense that the Project Config be put in a read-only mode when `allowAdminChanges = false`.

> 2. Underlying, the reason this mixup got my attention in the first place is that the push-button restore-prior-database _failed_.  Thus the site was 500 off the air, not a good thing if it had been real instead of staging, as well as the CP being unreachable.
> 
> I can't think of any reason except maybe another unintended consequence of allowAdminChanges false why the backup db wasn't...taken? ...or... was unable to be restored? I can't quite figure out from timestamps if it was taken, but I think so.

The logs will probably help reveal what the real issue was, but probably unrelated to `allowAdminChanges`. You could try running the `./craft restore` command with an existing DB backup and see if that works. It runs the same underlying code that the updater will run if it encounters an error.

**Comment by narration-sd** [comment] 2020-02-06 22:17
Ok, I tried that restore, after precautions. It worked whether `allowAdminChanges` was true or false, as you suspect.

However, it was turning `allowAdminChanges` back on, then pre-restoring my prior database that allowed successful recovery where the database got properly upgraded for 3.4.4

The site had useProjectConfigFile false, but in the altercation, the db upgrade after pushed site source broke on this denial of being able to build, maybe not store, Project Config.

Remember that after this occurred, the site was in 500 state due to improper db contents, as of the halted db upgrade. If I'd realized, I might have been able to get the old one back right away via the recover command you just noted, yes, but still we'd like this not to happen I suspect. Making Matt's new job of communicating to persons what's needed to do more feasible?

Here's the full log with the read-only error recorded, as I don't know how much context you'd need to realize what went wrong. 

[web-rdon.zip](https://github.com/craftcms/cms/files/4167970/web-rdon.zip)
