### ISSUE TITLE
Entry edit screen not scaled to browser window... 

### ISSUE THREAD

**Issue by spotd** [craftcms/cms#2192] opened 2017-12-10 20:59 UTC
### Description

I think it may be as a result of using many matrix buttons at the bottom. As these are setting the width, when they should be dropping down a line? I have to scale browser window to be huge and then drag browser left off screen to reach the right hand bar (slug etc)

### Steps to reproduce

1. Create a matrix field with LOADS of block types
2. start an entry with this matrix field used

### Additional info

- Craft version: 3.0.0-RC1 (Pro)
- PHP version: 7.1.12
- Database driver & version: MySQL 5.5.58-0+deb7u1
- Plugins & versions: 
    - Element API 2.5.1
    - Amazon S3 1.0.7
    - CKEditor 1.0.0-beta.1
    - Redactor 1.0.0
    - Beam 2.0.0
    - Craft Redactor Script Buttons 1.1.0

**Comment by iliaivanov** [comment] 2017-12-11 12:26
Same here +1.

**Comment by brandonkelly** [comment] 2017-12-11 20:38
Duplicate of #2169, fixed in 8cb8dce

**Closed by brandonkelly** 2017-12-11 20:38 UTC
