### ISSUE TITLE
Seeing Twig code for pagination on backend entries page

### ISSUE THREAD

**Issue by icreatestuff** [craftcms/cms#5158] opened 2019-10-23 11:20 UTC
### Description

![entries-pagination-twig-issue](https://user-images.githubusercontent.com/1300714/67387736-68ddb700-f58f-11e9-8f89-689e263135ae.jpg)

Loading up `/entries` page within the control panel I can see the twig code instead of the pagination info/links. This seems to always show no matter which section I choose from the sidebar too.

### Additional info

- Craft version: 3.3.8
- PHP version: 7.2.23
- Database driver & version: MySQL 5.6.46

**Comment by brandonkelly** [comment] 2019-10-23 18:49
This is a duplicate of #4995 - fixed for the next release!

**Closed by brandonkelly** 2019-10-23 18:49 UTC
