### ISSUE TITLE
[3.2] Endless loop of drafts when trying to view or delete a draft

### ISSUE THREAD

**Issue by zizther** [craftcms/cms#4545] opened 2019-07-12 12:37 UTC
### Description

An entry which has one or more drafts already causes an endless loop of draft creation when trying to either view or delete a draft.

This causes a lot of drafts to build up, on top of a number of drafts being created from the way it works at the moment.

### Steps to reproduce

1. Create an entry
2. Save the entry
3. Make an edit and wait for a draft to be saved
4. Refresh the page (so you can see the current entry)
5. Click the Revision/Draft dropdown
6. A new draft is created at this point
7. Click a draft, then try to delete it
8. Another draft has been created

### Additional info

- Craft version: 3.2.0
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.23
- Plugins & versions:

**Comment by hiasl** [comment] 2019-07-14 20:57
@zizther Question: are you using Supercool's Table Maker plugin in this page? Because I have similar behaviors with Craft 3.2.1 but as far as I know by now it only happens when the page contains a Table Maker  field... (in a matrix in my case). At least I can not reproduce the problem you describe unless Table Maker is in the page.

**Comment by zizther** [comment] 2019-07-15 13:16
@hiasl I have Neo installed, I know there maybe a possible issue there.
But I get this issue on sections which have a matrix field.

I have tested (Craft 3.2.2) on sections without matrix and they are fine, the draft behaviour works as expected.

**Comment by hiasl** [comment] 2019-07-15 15:13
@zizther we also have Neo here...

**Comment by zizther** [comment] 2019-07-15 16:52
@hiasl Interesting.
I have tried creating new entries and the same thing happens after I have the `First Draft`.

If I save an entry and then go back to it, a Draft will start, it will save if I go to edit something.
When I go to select a Draft, it then resaves another Draft, then when I load that draft and go to delete it, it will resave another draft.

I don't know if this is an issue to do with Matrix, or having Neo installed with Matrix fields?

Seems like the draft saving action is also tied to the Revisions/Draft dropdown, which then causes this issue.

**Comment by ccsantos23** [comment] 2019-07-15 19:21
When I open a page for authoring, it starts on a tab that has simple fields.  Everything is fine at this point.  When I switch to the tab that has a matrix field, it generates a draft even before any changes.  And I also get the endless loop of draft creation when I try to delete drafts.  
No Neo field.  This is on Craft 3.2.2.  I don't remember seeing this behavior in 3.2.0.

**Comment by ccsantos23** [comment] 2019-07-15 19:31
It shouldn't create a new draft for the same user if there's already an existing draft.

**Comment by brandonkelly** [comment] 2019-07-15 21:59
I’m able to reproduce this in some cases when using Redactor, though updating the entry from the auto-created draft will fix it for me.

**Comment by brandonkelly** [comment] 2019-07-15 22:00
In any case, we may be moving away from automatic draft creation (see #4535 & #4549), which would solve this.

**Comment by brandonkelly** [comment] 2019-07-16 00:07
Closing this now as we’ve made that change for the upcoming 3.2.3 release. See https://github.com/craftcms/cms/issues/4535#issuecomment-511613774

**Closed by brandonkelly** 2019-07-16 00:07 UTC
