### ISSUE TITLE
UI Bug: Category Selector appears to allow selections beyond the limit

### ISSUE THREAD

**Issue by michaelcolletto** [craftcms/cms#4691] opened 2019-08-01 04:08 UTC
### Description
In Craft 3, when a Category is selected and the selection limit has been reached, the "+ Add a category" button should disappear or be disabled.

The behavior I'm suggesting is already the default interaction when selecting Entries with the "+ Add an entry" button, and used to be the default interaction when selecting Categories in Craft 2.

The current interaction in Craft 3 is confusing. The button remains present and clickable even after the selection limit has been reached. Clicking the "+ Add a category" button to add a Category after the limit has already been reached simply replaces (one of) the current selection(s), which can lead to errors. A user should have to first remove a selection to re-enable the button, then add a new selection.

### Steps to reproduce

1. Add a Category selector to an Entry and set a limit on the number of Categories you can select
2. Select Categories up to the limit
3. Attempt to select another Category because _it doesn't look like there's a limit that's been met_ and see what happens

### Additional info

- Craft version: 3
- Screenshots below are from the same Entry type, but the first is in Craft 2 and the second is after updating to Craft 3. "Brand" (select 1) and "Product Category" (select 1-2) are both Categories.

**Craft 2 category selector UI**
![](https://user-images.githubusercontent.com/43583917/61889623-c18bae00-aed3-11e9-91e2-9775adc5a6e1.png)
**Craft 3 category selector UI**
![](https://user-images.githubusercontent.com/43583917/61889624-c18bae00-aed3-11e9-890d-42da131ed7e3.png)

**Comment by brandonkelly** [comment] 2019-08-01 14:40
This is a duplicate of #1847

**Closed by brandonkelly** 2019-08-01 14:40 UTC
