### ISSUE TITLE
Field Type Select Alphabetical

### ISSUE THREAD

**Issue by bymayo** [craftcms/cms#3072] opened 2018-07-05 13:40 UTC
### Description

It would be good if the field list when creating a new field was A>Z. It does this when you edit a field, but not when you first create a new field.

<img width="441" alt="screen shot 2018-07-05 at 14 39 03" src="https://user-images.githubusercontent.com/522877/42326543-5ad50d06-8061-11e8-9be7-0aa58e1a80ac.png">

### Steps to reproduce

1. Creating any field and viewing the list under 'Field Type'.

### Additional info

- Craft version: 3.0.14
- PHP version: 7.1
- Database driver & version:  MySQL
- Plugins & versions: Many!

**Comment by brandonkelly** [comment] 2018-07-05 16:03
I’m not able to reproduce this (even with LinkIt installed).

Can you try disabling all of your plugins besides LinkIt and see if the issue persists?

**Comment by bymayo** [comment] 2018-07-06 10:03
@brandonkelly I disabled Linkit and still the issue.

I actually give the wrong description on how to replicate this issue! 

The field list only does this issue when choosing a field type inside a Matrix block, not when choosing the field type initially.

**Comment by brandonkelly** [comment] 2018-07-08 03:54
Ahh, thanks, fixed now for the next release.

**Closed by brandonkelly** 2018-07-08 03:54 UTC
