### ISSUE TITLE
[4.x]: Addresses have no UK County (administrativeArea) option

### ISSUE THREAD

**Issue by bymayo** [craftcms/cms#13345] opened 2023-06-21 15:31 UTC
### Description

Since using the new address options in Craft 4, we've noticed that when you select United Kingdom as a country, that County field just vanishes, and theres no `administrativeArea` for UK.

This is strange as we definitely have Counties 😂 Lancashire, Manchester, Yorkshire, London etc. 

It's particularly problematic when using addreses with Commerce, as we've had to add our own County field, but then this causes confusion with people processing orders as theres sometimes 2 county fields in the address, one mainly being blank unless it's a UK address.

### Steps to reproduce

1. Go to Addresses
2. Add/edit address
3. Change address country to United Kingdom

### Expected behavior

County / administrativeArea field should appear

### Actual behavior

County / administrativeArea field doesn't appear

### Craft CMS version

4.4.11

### PHP version

8.1

### Installed plugins and versions

- Craft Commerce 4.2.11

**Comment by i-just** [comment] 2023-06-22 07:36
Hi, thanks for reaching out. It sounds like a duplicate of: #13101. There's more info there which should help clarify things!

**Closed by i-just** 2023-06-22 07:36 UTC
Labels: bug, craft4

**Comment by brandonkelly** [comment] 2023-08-22 17:25
Craft 4.5.0 is out with a new event that makes it possible to customize address subdivisions (#13361).
