### ISSUE TITLE
After adding a new dropdown field with a default value to a section, saving those entries without changing that default value does not save the default value

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#6362] opened 2020-07-12 13:44 UTC
A client ran into this problem and asked me for help, and it stumped me for a while too until I started outputting values step-by-step.

### Description

To a section that already has entries, I added a new Dropdown field. That field has one of the options set to be the default value.

1. Problem 1) After doing so, one might expect all the entries in the section to have that dropdown field's value be the default value. This is not the case, and although I think I understand why, it might be unexpected. However...
2. Problem 2) Editing one of the entries now shows the new dropdown field, default value shown to be selected. However, saving this entry without touching that field does not save that default value to the entry! Presumably, this is because that field hasn't been marked as "dirty" since it hasn't been changed, and therefore it's value doesn't need to be saved to the DB. 

### Steps to reproduce

1. Create a new dropdown field, with a couple of options to choose from, and mark one of the options as default.
2. Add that field to a section with existing entries.
3. Edit one of those entries.
4. Visually confirm that the dropdown is showing the default option as selected, without touching the field.
5. Save the entry.
6. Output the value of that entry's dropdown field in a template. It should be null/blank instead of the default value.

### Additional info

- Craft version: Craft Pro 3.4.5
- PHP version: 7.2.1
- Database driver & version: 	MySQL 5.5.5
- Plugins & versions:
  - Architect	2.3.2
  - Asset Rev	6.0.2
  - Button Box	2.0.4
  - Colorit	1.0.8
  - Colour Swatches	1.2.3
  - Cookie Consent Banner	1.2.5
  - Entry Instructions	1.0.7
  - Feed Me	4.2.0.1
  - Field Manager	2.1.6
  - Freeform	3.6.2
  - Icon Picker	1.1.8
  - Imager	v2.4.0
  - Image Resizer	2.0.6
  - Linkit	1.1.11
  - LJ Range Slider	1.0.0
  - Maps	3.7.7
  - Mix	1.5.2
  - Neo	2.6.1
  - Postmark	2.0.2
  - Redactor	2.5.0
  - Redactor Custom Styles	3.0.2
  - SEO	3.6.3
  - Sherlock	2.2.0
  - Simple Text	2.0.2
  - Super Table	2.4.4
  - Table Maker	2.0.1

**Comment by brandonkelly** [comment] 2020-07-13 13:08
> Problem 1) After doing so, one might expect all the entries in the section to have that dropdown field's value be the default value. This is not the case, and although I think I understand why, it might be unexpected.

Correct, that is currently expected (see #2446).

> Problem 2) Editing one of the entries now shows the new dropdown field, default value shown to be selected.

Well, the _first_ option should be selected, whatever that is. I guess in your case that also happens to be the default value.

However, saving this entry without touching that field does not save that default value to the entry! Presumably, this is because that field hasn't been marked as "dirty" since it hasn't been changed, and therefore it's value doesn't need to be saved to the DB.

That’s a duplicate of #5632, which was fixed in Craft 3.4.6.

**Closed by brandonkelly** 2020-07-13 13:08 UTC
Labels: duplicate
