### ISSUE TITLE
[5.x]: Defaults on multi-select fields not functional in Matrix nested entries

### ISSUE THREAD

**Issue by gateszies** [craftcms/cms#15756] opened 2024-09-18 21:16 UTC
### Description
When dealing with nested entries in a Matrix, defaults on multi-select fields are not being correctly saved or stored when saving their parent entry. This leads to large errors on the authoring end and disables the ability to use defaults.

### Steps to reproduce

1. Create a Matrix field with nested entry types
<img width="450" alt="Screenshot 2024-09-18 at 4 04 06 PM" src="https://github.com/user-attachments/assets/da2555c8-3d11-4d62-8830-ff264da00ebb">

2. Add a multi-select field to the entry type, ie Radio, Dropdown and select a default value
<img width="450" alt="Screenshot 2024-09-18 at 4 03 04 PM" src="https://github.com/user-attachments/assets/a2077758-77b0-47ec-a176-32c7547d32c7">

3. In a page that contains that Matrix field, add entry type from dropdown. You can see that the defaults are correctly selected here. Don't interact with any of the fields and hit `Create entry`.
<img width="450" alt="Screenshot 2024-09-18 at 4 07 01 PM" src="https://github.com/user-attachments/assets/52e3618f-8f46-47e5-bd63-d0fd3fe96d83">

4. Hit `Save` on the parent entry and get error messages about validation error in nested entry. These fields have defaults set and previously showed those defaults selected, but after saving the parent entry you can see the defaults have been cleared and nothing is selected.
<img width="450" alt="Screenshot 2024-09-18 at 4 09 25 PM" src="https://github.com/user-attachments/assets/7bd43e01-0337-4130-8e2f-8937764d7370">

### Expected behavior
The defaults of multi-select fields in nested entries should remain selected after creating a nested entry and saving the parent entry without having to define them manually.

### Actual behavior
The defaults of multi-select fields in nested entries are cleared after saving parent entries. This throws an error and disables the actual usage of defaults for the author.

### Craft CMS version

5.4.0.1

### PHP version

8.2.23

### Installed plugins and versions

<img width="400" alt="Screenshot 2024-09-18 at 4 15 34 PM" src="https://github.com/user-attachments/assets/c502de8e-5da4-4f13-b1db-870e6c8c45b5">

**Comment by gateszies** [comment] 2024-09-18 21:16
Similar issue was reported over [here](https://github.com/craftcms/cms/issues/14731#issuecomment-2341093858) 👀

**Comment by i-just** [comment] 2024-09-19 13:16
Hi, thanks for getting in touch! It sounds like a duplicate of https://github.com/craftcms/cms/issues/15706. If you update to 5.4.4, it should be fixed.

**Closed as completed by i-just** 2024-09-19 13:16 UTC
Labels: bug
