### ISSUE TITLE
FR: Add "width" option to field layout.

### ISSUE THREAD

**Issue by chanwhab** [craftcms/cms#4024] opened 2019-03-21 04:23 UTC
### Description
A section with lots of fields is hard to edit. 
You will have to scroll a long way.
Meanwhile the way to customize widget layout is so cool and easy to use.
Can we put that feature on the field layout too?

Also, adding a toggle for switching breakpoint is cool too. So we dont need to change browser size to adjust responsive layout.

![layout-for-field](https://user-images.githubusercontent.com/7658690/54733255-af230000-4bd3-11e9-85e2-3f4ff5f5c5bf.PNG)

For example, what kirby done:
![kirby-layout](https://user-images.githubusercontent.com/7658690/54733387-63248b00-4bd4-11e9-88bf-947c7e8ae3f9.PNG)

**Comment by brandonkelly** [comment] 2019-03-21 05:17
Duplicate of #2644

**Closed by brandonkelly** 2019-03-21 05:17 UTC

**Comment by chanwhab** [comment] 2019-03-21 05:48
oh, this is really my mistake. thanks anyway.
