### ISSUE TITLE
[3.7.0-beta.4] Server error on Entries view

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#9093] opened 2021-06-28 02:09 UTC
Updated devMode.fm to `3.7.0-beta.4` and the ElementIndexesController throws the following error when viewing the Episodes channel:

```
2021-06-27 21:45:12 [-][1][-][error][yii\db\Exception] PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "0" does not exist
LINE 12: ORDER BY "0"
                  ^ in /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute()
#2 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal()
#3 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all()
#5 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1588): craft\db\Query->all()
#6 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/craftcms/cms/src/base/Element.php(785): craft\elements\db\ElementQuery->all()
#7 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(520): craft\base\Element::indexHtml()
#8 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(135): craft\controllers\ElementIndexesController->elementResponseData()
#9 [internal function]: craft\controllers\ElementIndexesController->actionGetElements()
#10 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#11 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#12 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#13 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#14 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/craftcms/cms/src/web/Application.php(271): yii\base\Module->runAction()
#15 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/craftcms/cms/src/web/Application.php(574): craft\web\Application->runAction()
#16 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/craftcms/cms/src/web/Application.php(250): craft\web\Application->_processActionRequest()
#17 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#18 /home/forge/devmode.fm/releases/20ad5325998ae72dec79a7ce9c785f1ea0674a4b/web/index.php(24): yii\base\Application->run()
#19 {main}
```

Seems like it's trying to order the elements in the ElementIndex by `null`, which is getting coerced to `0`

Interestingly, I can access the entries themselves (which seem to be fine) if I put something in the Search field. See attached movie.

Full server logs attached; the database is Postgres, if it matters.

https://user-images.githubusercontent.com/7570798/123569404-3f2d5800-d794-11eb-885c-7ec6c86314dd.mov

[craft3.7.0-beta.4-web.log](https://github.com/craftcms/cms/files/6722855/craft3.7.0-beta.4-web.log)

**Comment by khalwat** [comment] 2021-06-28 12:00
If it helps, this must be something stored/saved in Local Storage on my browser, because the site works perfectly on my desktop machine. The above errors happen only on my laptop, both running Chrome.

**Comment by khalwat** [comment] 2021-06-28 18:33
Local storage on the machine where it does not work:

<img width="1083" alt="Screen Shot 2021-06-28 at 2 32 02 PM" src="https://user-images.githubusercontent.com/7570798/123686489-dab6db00-d81d-11eb-9424-3d2465242ddb.png">

**Comment by khalwat** [comment] 2021-06-28 18:38
Local storage on the machine where it _does_ work:
<img width="1252" alt="Screen Shot 2021-06-28 at 2 37 40 PM" src="https://user-images.githubusercontent.com/7570798/123687058-76484b80-d81e-11eb-9f45-8157c84f02be.png">

**Comment by brandonkelly** [comment] 2021-06-28 22:24
Thanks for reporting! It was caused by [this change](https://github.com/craftcms/cms/commit/f86ac030c5526f65b503c76bafb2e161f90fb216#diff-7f5515881ed38a21d7f62769829d834174a01f871c5314a4996ab0444fb9e9b5L498-R508). Fixed now for the next release.

**Closed by brandonkelly** 2021-06-28 22:24 UTC
Labels: bug

**Comment by brandonkelly** [comment] 2021-06-29 17:13
3.7.0-beta.5 is out now with the fix.
