### ISSUE TITLE
[Enhancement] Total number of entries

### ISSUE THREAD

**Issue by nexflo** [craftcms/cms#2516] opened 2018-03-01 13:13 UTC
There is no native way to see the total amount of entries in channel.

In a Content Management System one should natively see how many entries are in a section I believe - this shouldn't be left to a plugin, but feels like the most "core" of features?

**Comment by ryanmasuga** [comment] 2018-03-21 20:17
I agree that this feels like a core feature. It would help offset frustration with infinite scroll and lack of pagination in the CP.

**Comment by brandonkelly** [comment] 2019-01-11 12:45
This is a duplicate of #1023

**Closed by brandonkelly** 2019-01-11 12:45 UTC
Labels: enhancement, feature: ax :writing_hand:
