### ISSUE TITLE
Publish draft results in "Exception: Could not acquire a lock to save a revision for element"

### ISSUE THREAD

**Issue by craftedsystems** [craftcms/cms#7661] opened 2021-03-08 22:31 UTC
### Description

I can not publish drafts.

### Steps to reproduce

1. Select a draft from the drop down
2. Click "Publish draft" button

```
2021-03-08 23:27:04 [-][1][97acg1al2in48t6gkpkuconl55][error][yii\db\Exception] yii\db\Exception: Could not acquire a lock to save a revision for element 288 in /home/vindobona.wien/httpdocs/vendor/craftcms/cms/src/services/Revisions.php:78
Stack trace:
#0 /home/vindobona.wien/httpdocs/vendor/craftcms/cms/src/elements/Entry.php(1584): craft\services\Revisions->createRevision(Object(craft\elements\Entry), NULL, 'Applied \xE2\x80\x9CEntw...')
#1 /home/vindobona.wien/httpdocs/vendor/craftcms/cms/src/services/Elements.php(1141): craft\elements\Entry->afterPropagate(false)
#2 /home/vindobona.wien/httpdocs/vendor/craftcms/cms/src/services/Drafts.php(442): craft\services\Elements->duplicateElement(Object(craft\elements\Entry), Array)
#3 /home/vindobona.wien/httpdocs/vendor/craftcms/cms/src/controllers/EntryRevisionsController.php(441): craft\services\Drafts->publishDraft(Object(craft\elements\Entry))
#4 [internal function]: craft\controllers\EntryRevisionsController->actionPublishDraft()
#5 /home/vindobona.wien/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /home/vindobona.wien/httpdocs/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#7 /home/vindobona.wien/httpdocs/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('publish-draft', Array)
#8 /home/vindobona.wien/httpdocs/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('publish-draft', Array)
#9 /home/vindobona.wien/httpdocs/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('entry-revisions...', Array)
#10 /home/vindobona.wien/httpdocs/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('entry-revisions...', Array)
#11 /home/vindobona.wien/httpdocs/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#12 /home/vindobona.wien/httpdocs/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /home/vindobona.wien/httpdocs/web/index.php(22): yii\base\Application->run()
#14 {main}
```

### Additional info

- Craft version: 3.6.9
- PHP version: 7.3.27
- Database driver & version: MySQL 5.5.68
- Plugins & versions:
Agent 1.1.8
Asset Rev 6.0.2
Asset Usage 2.2.1
Content Stats 2.1.2
Control Panel CSS 2.3.0
CP Field Inspect 1.2.4
Default Dashboard 1.0.8
Dumper 2.0.0
Element Link 1.0.2
Entry Count 2.0.3
Expanded Singles 1.1.3
Logs 3.0.3
Minify 1.2.10
Overflow 2.0.0
Password Policy 1.0.6
Reasons 2.2.4
Redactor 2.8.5
Relations 1.2.1
Restrict Asset Delete 1.1.1
Snitch 3.0.4.1
Store Hours 2.1.1.1
Super Table 2.6.7
Typogrify 1.1.18

**Comment by craftedsystems** [comment] 2021-03-08 23:13
Same exception with this setup:
• PHP version: 7.3.27
• Database driver & version: MySQL 5.6.51

**Comment by brandonkelly** [comment] 2021-03-09 01:25
Not able to reproduce this on my end. Can you please send a database backup and your Composer files into support@craftcms.com, and point out which entry/draft you’re seeing this with?

**Comment by ManiakMill** [comment] 2021-03-14 13:38
Hello. Have a same problem. 
Config: 

- PHP version | 7.3.27
- Database driver & version | MySQL 5.6.51
- Craft edition & version | Craft Pro 3.6.10

**Comment by craftedsystems** [comment] 2021-03-14 20:34
I did some tests with removing various plugins and found that since I removed the plugin [Relations](https://github.com/Nav33d/craft-relations) the exceptions are gone. I will keep an eye on the logs, but I hope that we can close this issue soon. 🤞

**Comment by brandonkelly** [comment] 2021-03-15 22:17
That repo has been archived on GitHub so I wouldn’t hold my breath that the bug will be fixed. I just marked it as abandoned in the plugin store. Perhaps [Reverse Relations](https://plugins.craftcms.com/reverserelations) will work better for you.

**Closed by brandonkelly** 2021-03-15 22:17 UTC
Labels: bug
