### ISSUE TITLE
[4.x]: Sticky asset filesystem panel when creating new asset volume

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#13735] opened 2023-09-22 10:08 UTC
### Description

When creating a new Asset Volume, if I click "Create a new filesystem" under "Asset Filesystem", the slide out becomes a little too persistent if I decide to cancel.

### Steps to reproduce

https://github.com/craftcms/cms/assets/2373940/9a1ed121-ac34-4f89-862f-5471a75f91c6

### Craft CMS version

4.5.5

### PHP version

8.1

### Installed plugins and versions

-

**Comment by i-just** [comment] 2023-09-22 10:20
Hi, thanks for reporting. This is a duplicate of https://github.com/craftcms/cms/issues/13707, so I’m going to close this one, but feel free to follow along there.

**Closed by i-just** 2023-09-22 10:20 UTC
Labels: bug, duplicate, craft4
