### ISSUE TITLE
[4.x]: Smart apostrophe is removed in PlainText

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/cms#12906] opened 2023-03-15 20:53 UTC
### Description

When we use this apostrophe `’` in a PlanText field, the apostrophe is removed after the page is saved, the straight apostrophe `'` work

### Craft CMS version

4.4.2

### PHP version

8.1.13

### Installed plugins and versions

-

**Comment by i-just** [comment] 2023-03-16 13:21
Thanks for reporting. It's the same root cause as with #12905, so I'm going to close this one as a duplicate, but you can follow along on #12905.

**Closed** 2023-03-16 13:33 UTC
Labels: bug, duplicate, craft4

**Comment by brandonkelly** [comment] 2023-03-16 18:31
For posterity, this has been fixed in 4.4.3.
