### ISSUE TITLE
3.4-RC1.1 Error when deleting a section

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#5438] opened 2020-01-14 23:36 UTC
### Description

When deleting a section, an error is reported in the console and the section remains. Deleting it a second time works.

### Steps to reproduce

1. Go to Settings > Sections
2. Delete a section by clicking on the "X"
3. View the error in the console:
```
axios.min.js?v=1579038413:8 POST http://laloupe.test/index.php/admin/actions/sections/delete-section 500 (Internal Server Error)
axios.min.js?v=1579038413:8 Uncaught (in promise) Error: Request failed with status code 500
```
4. View the error in the network tab:
```
{"error":"No entry types exist for section 20"}
```
5. Delete the section again
6. It is successfully deleted

### Additional info

- Craft version: 3.4-RC1.1

**Comment by andris-sevcenko** [comment] 2020-01-15 11:42
I'm not able to reproduce this. Was this on an install that was migrated from Craft 3.x to 3.4? Was this section created manually in the CP?

**Comment by bencroker** [comment] 2020-01-15 20:09
Added a step 0, which may be important :)

0. Create a `Single` section
1. Go to Settings > Sections
2. Delete the section by clicking on the "X"
3. View the error in the console

**Comment by brandonkelly** [comment] 2020-01-17 18:38
We just released Craft 3.4 RC2 with a fix for this.

**Closed by brandonkelly** 2020-01-17 18:38 UTC

**Comment by matfish2** [comment] 2021-11-15 16:12
Getting the same error on Craft 3.7.20. 
Section was programmatically created.
Error is thrown on Sections.php:1136:

```
    $section = $this->getSectionByUid($data['section']);
```
 Trying to access array offset on value of type null 
I suppose `$data` is null

**Comment by matfish2** [comment] 2021-11-19 11:08
I am getting the same issue when creating sections from API: 
Issue is on `Sections.php:1136`:
```
 $section = $this->getSectionByUid($data['section']);
```

`$data` is set on line 1130:
```
  $data = $event->newValue;
```
I dumped `$event` and `newValue` is `null`

**Comment by bencroker** [comment] 2021-11-19 11:15
@matfish2 this most likely has a different cause, I'd suggest opening a new issue.
