### ISSUE TITLE
Index view for section only shows first added tag

### ISSUE THREAD

**Issue by StijnCoolen** [craftcms/cms#3132] opened 2018-07-23 14:41 UTC
### Description
When adding tags to an entry only the first one added is shown in the tag's column on the index for the entry's section. In my opinion having multiple tags is quite common and it would be nice if the index showed more than one.

### Steps to reproduce

1. Create a tag group
2. Add tags from this group to an entry
3. Go to this entry's section and make sure you set the tag column to visible
4. You should see the first tag you added listed

### Additional info

- Craft version: 3.0.16.1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.7.21
- Plugins & versions: clubstudioltd/craft-asset-rev (6.0.1) and craftcms/ckeditor (1.0.0-beta.2)

**Comment by brandonkelly** [comment] 2018-07-24 00:37
Duplicate of #1083

**Closed by brandonkelly** 2018-07-24 00:37 UTC
