### ISSUE TITLE
Cannot add a custom locale via `config/locales` if PHP intl extension is installed.

### ISSUE THREAD

**Issue by thisisjamessmith** [craftcms/cms#6892] opened 2020-09-23 11:02 UTC
### Description

I want to add some custom locales that are not included in PHP's list geerated by the intl extension. These reflect the languages available under Settings > Sites > [choose site] > Language. When the intl extension is not installed, you can add custom locales in `config/locales` and they successfully appear, but when it is installed, you cannot add to the ones generated by the extension.

### Steps to reproduce

1. Have an installation with PHP's intl extension installed
2. Add a custom locale file `config/locales` that doesn't exist in PHP's intl list such as `en-ID.php` (English Indonesia)
3. Add this into general.php:

```
'extraAppLocales' => [
    'English (Indonesia)' => 'en-ID',
],
```

4. Get an error when loading the CP:
```Invalid language: en-id in craftcms/cms/src/helpers/Localization.php:44```

### Additional info

- Craft version: 3.4.28.1
- PHP version: 7.1

**Comment by brandonkelly** [comment] 2020-09-23 20:30
Marked this as an enhancement request as this currently works by design. The Intl extension is supposed to provide an exhaustive list of recognized locales

**Closed** 2021-06-22 06:28 UTC
Labels: enhancement, internationalization :globe_with_meridians:
