### ISSUE TITLE
[Feature Request] Get Asset URL on Asset Index

### ISSUE THREAD

**Issue by mzlock** [craftcms/cms#3868] opened 2019-02-19 21:28 UTC
This was a feature in Craft 2, but appears to have disappeared in Craft 3. On the Assets Index page, I want to be able to get an Asset's original file URL.

Use case: I upload a PDF to my site to share with someone -- and I need the URL of that PDF to send/share it. But there is no option to copy, view, or find that URL. Asset options include renaming, replacing, editing, but there's no way to get its URL.

- Craft version: 3.1.12
- Checked on Happy Lager test site

**Comment by brandonkelly** [comment] 2019-02-19 22:09
Duplicate of #3859

**Closed by brandonkelly** 2019-02-19 22:09 UTC
