### ISSUE TITLE
[4.x]: UI Error when value in selectizeField is "new"

### ISSUE THREAD

**Issue by CMeldgaard** [craftcms/cms#11992] opened 2022-09-22 08:26 UTC
### Description
When creating a selectizeField with an option where its value is `new`, will break the UI. This field is created on a custom gateway.

### Steps to reproduce
Create a selectizeField with a option with value `new`

### Expected behavior
List with option values
![image (3)](https://user-images.githubusercontent.com/14794642/191696569-b551b456-8c77-45a8-8b9f-630dfeecdd2d.png)

### Actual behavior
A "+" and "..." icon is added because the `data-value="new"` will trigger CSS class
![image (2)](https://user-images.githubusercontent.com/14794642/191696189-4919c2c7-e342-4abb-b7ca-6c47e4c96e94.png)

### Craft CMS version

4.2.4

### PHP version

8.0

### Installed plugins and versions

-

**Comment by brianjhanson** [comment] 2022-09-22 14:03
This looks to be a duplicate of #11946 which has been fixed for Craft 5, but in the mean time you'll need to [avoid using `new` as an option value](https://github.com/craftcms/cms/issues/11946#issuecomment-1248373017).

**Closed by brianjhanson** 2022-09-22 14:03 UTC
Labels: bug, craft4
