### ISSUE TITLE
"author" not flagged as a reserved word

### ISSUE THREAD

**Issue by joffyb** [craftcms/cms#6716] opened 2020-08-25 14:18 UTC
### Description
It is possible to create a field with the handle "author", but when an entry is created with said field the recent entries widget throw the error `Calling unknown method: craft\elements\db\EntryQuery::username()`

The offending line is on line 10:

`{%- if CraftEdition == CraftPro and entry.author %}, {{ entry.author.username }}{% endif -%}`

### Steps to reproduce

1. Create a field with the handle of author
2. Create an entry using the field
3. Attempt to go to /admin/dashboard

### Additional info

- Craft version: 3.5.5
- PHP version: 7.1.22
- Database driver & version: MySQL 5.7.23
- Plugins & versions: N/A

**Comment by brandonkelly** [comment] 2020-08-25 15:01
This is a duplicate of #2797.

**Closed by brandonkelly** 2020-08-25 15:01 UTC
Labels: bug

**Comment by brandonkelly** [comment] 2021-06-10 23:39
For posterity, this is [resolved for Craft 3.7](https://github.com/craftcms/cms/issues/2797#issuecomment-859155102).
