### ISSUE TITLE
It had a REST API, so that other webapps could communicate with it

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1126] opened 2017-01-31 03:51 UTC
> Created by: Magne (magnemg@gmail.com) on 2015/04/22 10:44:50 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

**Comment by brandonkelly** [comment] 2017-03-13 22:58
duplicate of #815

**Closed** 2017-03-13 22:58 UTC
Labels: feature request
