### ISSUE TITLE
Transforms in GraphQL have unexpected folder names

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/cms#4940] opened 2019-09-14 07:11 UTC
I don't know where you are on this (and  our off-line conversation about it), Andris @andris-sevcenko, but I noticed something extra while testing this correction of most recent merge to keep this pull request current with ongoing Craft cms/develop.

It's that when using the directive form of transform, you get a different target folder for the eventual transformed image - snake-cased, rather than camel from the actual tranform name. .That will cause a mismatch I think between what Craft GraphQL returns, and what a plain Twig script (or CraftQL for anyone wanting to transition) returns.

_Originally posted by @narration-sd in https://github.com/craftcms/cms/pull/4879#issuecomment-531405463_

**Comment by andris-sevcenko** [comment] 2019-09-14 07:19
> It's that when using the directive form of transform, you get a different target folder for the eventual transformed image - snake-cased, rather than camel from the actual tranform name.

Can you post the transform directive you're using? I was unable to reproduce it locally and, also, the code runs through the same exact steps as when called from Twig, so I'm not sure how it could differ.

**Comment by narration-sd** [comment] 2019-09-14 18:22
It's true  that  something  else is going on here...I haven't time to play with this, this morning, but I ran up what's essentially a dual  query out of another test script, and see I was apparently fooled by the long paths.

What's going on here actually is that in the directive form (second record), the transform isn't being enacted at all. Hence  the last thing before the image filename is just the base for the asset -- same as base on the transformed by my evented argument (first record).

I don't seem to think I broke the directive by my PR code, but again, can't look just now.

![andris-transform-no-transform](https://user-images.githubusercontent.com/247945/64912284-d15c8d00-d6e1-11e9-8188-0ada9ce1eb69.png)

**Comment by narration-sd** [comment] 2019-09-14 21:29
Ok, I found enough time later in the day to look again. I checked another load, where transform worked, then backed this particular one down so my event and its use were again gone.

Result; on identical query, @transform, your style, is working again. So I guess this issue report is my breakage, and I'll close it.

Intuition doesn't suggest a reason why, and I'm not probably inclined to track it down if you're just going to throw away this PR as seems. A first, I must say, but this has been too much effort of several kinds, as you might figure it yourself.

On the replacement, good it's in play. I hope you remember it needs to handle _any_ field argument, not just  `transform` as you've mentioned. - that's just been one of particular focus of course at first.

**Comment by narration-sd** [comment] 2019-09-14 21:30
Well, I can't close it, as you re-orged, so you'll have to, but I now think the issue is moot, as said.

**Comment by narration-sd** [comment] 2019-09-15 10:54
Ah. Far too late to do more than say the intuition which finally showed itself, but I'd be near to certain what's caused this problem.

It's not in the PR's event arrangements, but in the simple replacement resolver example I wrote to try it out on images.

This works fine to gain transform via field argument -- but its default case with no argument doesn't engage any check/act for a possible directive.

This could get fixed no doubt, and a similar ability to call (back?) on that when external resolvers are present will be need to be in the considerations for your own proposal, seems likely @andris-sevcenko .

**Closed** 2019-09-15 17:54 UTC
Labels: :mag: graphql
