### ISSUE TITLE
[3.x]: Exception thrown when applying draft

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#11083] opened 2022-05-04 14:55 UTC
### Description

Happened in two different sites, in different enviroments, so seems not unique to my case.

When a draft gets applied (provisional or normal draft) an exception is thrown with a stack trace like this:

``` 
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tasmar`.`changedfields`, CONSTRAINT `changedfields_elementId_fk` FOREIGN KEY (`elementId`) REFERENCES `elements` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) in D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\yiisoft\yii2\db\Command.php:1302
Stack trace:
#0 D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\yiisoft\yii2\db\Command.php(1302): PDOStatement->execute()
#1 D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\yiisoft\yii2\db\Command.php(1102): yii\db\Command->internalExecute('INSERT INTO `ch...')
#2 D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\craftcms\cms\src\helpers\Db.php(860): yii\db\Command->execute()
#3 D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\craftcms\cms\src\services\Elements.php(2819): craft\helpers\Db::upsert('{{%changedfield...', Array, Array, Array, false)
#4 [internal function]: craft\services\Elements->craft\services\{closure}(Object(yii\base\Event))
#5 D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\yiisoft\yii2\base\Component.php(633): call_user_func(Object(Closure), Object(yii\base\Event))
#6 D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\yiisoft\yii2\base\Application.php(387): yii\base\Component->trigger('afterRequest')
#7 D:\Work\Clients\Tasmar\_repos\tasmar_root\web\index.php(22): yii\base\Application->run()
#8 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tasmar`.`changedfields`, CONSTRAINT `changedfields_elementId_fk` FOREIGN KEY (`elementId`) REFERENCES `elements` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
The SQL being executed was: INSERT INTO `changedfields` (`dateUpdated`, `propagated`, `userId`, `elementId`, `siteId`, `fieldId`) VALUES ('2022-05-04 14:48:39', 0, 1, 641, 1, 11) ON DUPLICATE KEY UPDATE `dateUpdated`='2022-05-04 14:48:39', `propagated`=0, `userId`=1 in D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\yiisoft\yii2\db\Schema.php:676
Stack trace:
#0 D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\yiisoft\yii2\db\Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `ch...')
#1 D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\yiisoft\yii2\db\Command.php(1102): yii\db\Command->internalExecute('INSERT INTO `ch...')
#2 D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\craftcms\cms\src\helpers\Db.php(860): yii\db\Command->execute()
#3 D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\craftcms\cms\src\services\Elements.php(2819): craft\helpers\Db::upsert('{{%changedfield...', Array, Array, Array, false)
#4 [internal function]: craft\services\Elements->craft\services\{closure}(Object(yii\base\Event))
#5 D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\yiisoft\yii2\base\Component.php(633): call_user_func(Object(Closure), Object(yii\base\Event))
#6 D:\Work\Clients\Tasmar\_repos\tasmar_root\vendor\yiisoft\yii2\base\Application.php(387): yii\base\Component->trigger('afterRequest')
#7 D:\Work\Clients\Tasmar\_repos\tasmar_root\web\index.php(22): yii\base\Application->run()
#8 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1452
    [2] => Cannot add or update a child row: a foreign key constraint fails (`tasmar`.`changedfields`, CONSTRAINT `changedfields_elementId_fk` FOREIGN KEY (`elementId`) REFERENCES `elements` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
)
```

### Steps to reproduce

1. Update to 3.7.40
2. Edit an entry and apply the draft.

### Expected behavior

The draft gets applied, life goes on

### Actual behavior

The above exception is thrown. The draft DOES get applied though.

Maybe related to the fix for #10662 

### Craft CMS version

3.7.40

### PHP version

8.1.5

### Database type and version

MySQL 8.0.29

### Installed plugins and versions

-

**Comment by mmikkel** [comment] 2022-05-04 21:18
I just had the same exception when applying a draft on Craft 4.0.0.1, but not able to reproduce so far.

Also seen it happen on Craft 3.7.40, but not able to reproduce there either.

In both cases the draft applied was created before upgrading Craft (from 4.0.0-RC3 and 3.7.39, respectively), perhaps that could be relevant.

**Comment by brandonkelly** [comment] 2022-05-04 23:20
Thanks for reporting that! Fixed for the next release.

**Comment by mmikkel** [comment] 2022-05-05 08:30
I could be wrong, but https://github.com/craftcms/cms/commit/d726d265e6cb96bad811688d12441097f2378066 appears to be a fix for #11084, not this issue?

**Comment by jerome2710** [comment] 2022-05-05 11:05
@brandonkelly We are now also experiencing this issue for multiple client sites after updating. Could you confirm this issue is fixed and scheduled for the next release, despite @mmikkel observation?

**Comment by DowleyDeveloped** [comment] 2022-05-05 12:56
@brandonkelly Also now experiencing this on 3.7.40.1

**Comment by davidsprinz** [comment] 2022-05-05 14:10
Unfortunately, it’s the same for me after updating to 3.7.40.1.

**Comment by juban** [comment] 2022-05-05 16:40
I can confirm. Looks like the #10662 optimization had some side effect. Starting with Craft 3.7.40, I'm having major issue when modifying and saving an existing entry resulting in `Integrity constraint violation` SQL Errors during inserts in the `changedfields` table. Reverting to Craft 3.7.39 resolve the issue. I'll try to investigate further in order to identify the root issue (this is perhaps a plugin misbehaving, SuperTable presumably, or a module) and open a ticket for that with more informations.

**Comment by brandonkelly** [comment] 2022-05-06 05:56
Whoops, closed the wrong issue.

**Comment by brandonkelly** [comment] 2022-05-06 06:10
Able to reproduce when applying a draft, if the save is made before the latest changes have had a chance to autosave. Rolled back the change that caused this, for the next release. Will get that tagged asap…

**Comment by juban** [comment] 2022-05-06 06:30
> 

@brandonkelly Will you release a fix for Craft 3 also?

**Comment by brandonkelly** [comment] 2022-05-06 07:05
@juban yes – fixed on v3 initially, and have also merged into v4.

**Closed** 2022-05-06 07:44 UTC
Labels: bug, craft3

**Comment by brandonkelly** [comment] 2022-05-06 08:16
Craft 3.7.41 and 4.0.1 are out now with that fix.
