### ISSUE TITLE
Update Failure CraftCMS 3.0.0-beta.23

### ISSUE THREAD

**Issue by vaughn-taylor** [craftcms/cms#1890] opened 2017-07-31 20:49 UTC
### Description

When I clicked the update button in the CP, I got the following message:

_Error: The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly_

I clicked the update button a second time and I got the following message in CP:

**Service Unavailable**
It looks like someone is currently performing a system update.

And this message on my front-end

**Service Unavailable**
Our site is temporarily unavailable. Please try again later.

At this point, I could not get to my CP or front end, so I reinstalled CraftCMS Beta 3 using the instructions here: https://github.com/craftcms/docs/blob/master/en/installation.md

I did not try to recreate my DB after reinstall, I just used the creds from my .env on the new install. But I'm getting the same errors as listed above. I'm not sure where to go from here? Should I just start completely from scratch with a new DB and all?

### Steps to reproduce

1. Clicked the auto update button in Control Panel
2.

### Additional info

- Craft version: CraftCMS 3.0.0-beta.23
- PHP version: 7.1.1
- Database driver & version: MySQL 5.6.35
- Plugins & versions:

**Comment by vaughn-taylor** [comment] 2017-07-31 20:57
I figured out how to resolve this issue by looking at this entry: https://github.com/craftcms/cms/issues/1883

I edited the "info" table > "maintenance" field changing the value from 1 to 0.

Then I visited my CP, and I got a message that some things needed to be cleaned up. For some reason, the DB could not be backed up, so I just continued (is this a permissions issue?). Anyway, everything is up and running again.

**Comment by hiasl** [comment] 2017-07-31 21:14
had the same problem, same solution

**Comment by MDXDave** [comment] 2017-07-31 21:50
Duplicate of #1885 and #1883

**Comment by brandonkelly** [comment] 2017-07-31 23:00
@vaughn-taylor Did you end up setting the `COMPOSER_HOME` constant in index.php? Or was that not needed in the end?

**Comment by vaughn-taylor** [comment] 2017-08-02 15:53
@brandonkelly, I only saw that message one time -- immediately after I updated in the CP. On the second update attempt, I got the "Service Unavailable" message. So, I guess it was not needed in the end?

**Comment by brandonkelly** [comment] 2017-08-02 19:19
Sorry, misread the error; this is actually a new issue.

What OS/version are you running?

**Comment by brandonkelly** [comment] 2017-08-02 22:05
After looking into the error you’re getting, there’s no way around it, but now Craft checks to ensure `COMPOSER_HOME` or `HOME` is set before putting itself into Maintenance Mode, which will fix the subsequent error you originally saw (“It looks like someone is currently performing a system update.”).

**Closed by brandonkelly** 2017-08-02 22:05 UTC
