### ISSUE TITLE
cannot make case changes to local asset file names via admin

### ISSUE THREAD

**Issue by olets** [craftcms/cms#3130] opened 2018-07-22 21:01 UTC
### Description

Attempts to rename a local asset with no changes expect case changes error, with 

```
A file with the name “<new file name>” already exists.
```

e.g. renaming `My-file.jpg` to `my-file.jpg` will error with `A file with the name "my-file.jpg" already exists.`

### Steps to reproduce

1. Add a local asset
2. In the admin, double click the asset to edit it. Make a case change in the file name. Save.

### Additional info

- Craft version: 3.0.16.1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.31

**Comment by andris-sevcenko** [comment] 2018-07-23 07:29
Duplicate of #2641 

Also, there's no feasible solution to this as of now.

**Closed by andris-sevcenko** 2018-07-23 07:29 UTC
