### ISSUE TITLE
Preview and/or View button of NOT Enabled and Status as Disabled entries are returning a 404

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#10121] opened 2021-11-19 09:44 UTC
### Description

After an update from Craft Pro `3.7.19.1` to `3.7.21`, the Preview and/or View button of **NOT** _Enabled_ and Status as _Disabled_ entries are returning a 404 instead of the preview.

### Steps to reproduce

1. Create a new entry
2. Setup entry as **NOT** _Enabled_ and Status as _Disabled_
3. Use the _Preview_ and/or _View_ button
4. Get the 404 error

### Additional info

- Craft version: Craft Pro 3.7.21
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7.23

**Comment by brandonkelly** [comment] 2021-11-19 18:28
I’m not able to reproduce this. Is your template throwing a 404 error somewhere perhaps?

**Comment by caalholm** [comment] 2021-11-22 11:03
I can confirm that this is still an issue as I'm able to reproduce it in a clean install as described above. But it only affects e**ntries within a Structure**, not Channel or a Single. If you create a Structure and set the template, it will not find the template when the entry is not enabled. It seems that the variable $template, passed to TemplateController's actionRender-method, **contains the slug instead of the template-path** when the entry is not enabled. I see the same behaviour for both Preview and View.

**Comment by romainpoirier** [comment] 2021-11-22 14:40
> Is your template throwing a 404 error somewhere perhaps?

@brandonkelly, I have a 404.twig error page, and the template the Entry is trying to reach is at the correct path.
I can also confirm that I'm trying to preview from a Structure.

**Comment by jimmylorunning** [comment] 2021-11-22 14:46
I'm also experiencing this bug. When I enable the page, it works fine, but as soon as I disable it, it shows me the 404 page in preview.

**Comment by mmikkel** [comment] 2021-11-22 22:33
Happening on my end, too. Can confirm that the issue only affects disabled structure entries, and only current revisions (i.e. it does not happen for disabled _drafts_).

**Comment by brandonkelly** [comment] 2021-11-23 13:45
Doh, I should have tested a Structure section entry. This was a silly mistake caused by 751e0186ebc072379572e7659c91d6e6f3063c15. Fixed now for today’s release.

**Closed** 2021-11-23 13:44 UTC
Labels: bug

**Comment by brandonkelly** [comment] 2021-11-23 19:48
Craft 3.7.22 is out now with that fix. Thanks all!
