### ISSUE TITLE
FR: Multi-site System/Site Status Toggle

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4050] opened 2019-03-26 02:21 UTC
### Description
For multi-site setups it would be great to have a “site status” toggle synonymous with the current “system status” toggle so it would be possible to turn an individual site “on” or “off”.

While individual sites can be set to “on” or “off” by adding the site specific config for “system status” in general.php it would be very convienient to have this togglable via the control panel.

**Comment by brandonkelly** [comment] 2019-03-26 22:18
Duplicate of #3005

**Closed by brandonkelly** 2019-03-26 22:18 UTC
