### ISSUE TITLE
Drafts not showing up in 'all' entry list

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#7937] opened 2021-05-14 08:06 UTC
### Description

After saving a draft it's not listed in the entry list which is causing confusion and feels like something went wrong. It is listed though when filtering on 'Draft', but I think we/customers might expect the draft to also show up when having the list unfiltered, because the filter says it's showing 'All'.
This was working before, so something has changed in (one of the) latest sub version(s) causing this as it seems.

![image](https://user-images.githubusercontent.com/69322733/118241346-5215f280-b49c-11eb-9ece-e2173ce78fc3.png)

BTW as a side note (as I can't find the other thread where someone else mentioned this:) I hope you guys could change the icon for the draft as this icon gives the strong feeling something is technically wrong. It's like one of those icons you see when an image could not be found on a web page (broken link). Maybe an icon that looks like a draft/sketch, like a paper with a pencil on it, would be less triggering the 'something went wrong' scary reaction and would be more descriptive.
Something like this perhaps:
![draft](https://user-images.githubusercontent.com/69322733/118242608-cef59c00-b49d-11eb-875c-039be139437b.jpg)

### Steps to reproduce

1. Create a draft
2. Look for the draft in the list; it's not there

### Additional info

- Craft version: 3.6.13
- PHP version: 7.4.16
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment] 2021-05-14 12:19
I’m not able to reproduce this; Unpublished drafts are still showing up in the Entries index for me.

Are you applying any custom filtering to the index from a module via the `EVENT_REGISTER_SOURCES` event or something like that?

**Comment by bencresty** [comment] 2021-05-14 13:15
> Are you applying any custom filtering to the index from a module via the `EVENT_REGISTER_SOURCES` event or something like that?

Thansks for your response. No, I'm not using custom filtering. I've scrolled through the list and tried different things several times, also refreshed the page etc., but it's not in the list and there's no pagination needed, so it's not on some other page either. 

I would be surprised if there's a link with the installed plugins (also because most of them haven't changed in quite some time and it was working before), but just in case, installed are:
- CodeMirror 1.0.2
- Contact Form 2.2.7
- Contact Form Extensions 1.2.4
- Environment Label 3.2.0
- Matrix Colors 2.0.1
- MatrixMate 1.2.7
- Matrix Toolbar 1.0.6
- Minify 1.2.10
- Plausible 1.0.4
- Redactor 2.8.7
- Redactor Anchors 1.1.0
- Retour 3.1.53
- Similar 1.1.4
- Smith

(For the rest there are two active custom build plugins, but these do nothing CMS related and haven't changed in months either)

Hope this helps

**Comment by brandonkelly** [comment] 2021-05-14 21:17
Are you able to reproduce on a fresh Craft install?

**Comment by brandonkelly** [comment] 2021-05-14 21:18
Note that entries will only show up once you’ve made some sort of edit to them. If you simply click the **New entry** button and then return to the Entries index without making any changes, it won’t show up in the list.

**Comment by bencresty** [comment] 2021-05-15 12:48
> Are you able to reproduce on a fresh Craft install?

I'm sorry, I don't have the time to do a fresh Craft install and don't want to do that and don't think it helps to debug either to be honest. Also, what would the difference be between me doing a fresh Craft install and you doing a fresh Craft install?

> Note that entries will only show up once you’ve made some sort of edit to them. If you simply click the **New entry** button and then return to the Entries index without making any changes, it won’t show up in the list.

I made several edits. And as I wrote before; this was working in previous versions. I didn't change anything in the CMS nor code except for running the updates.

**Comment by brandonkelly** [comment] 2021-05-15 19:06
> I'm sorry, I don't have the time to do a fresh Craft install and don't want to do that and don't think it helps to debug either to be honest. Also, what would the difference be between me doing a fresh Craft install and you doing a fresh Craft install?

As I said it’s working on my end, so I’m trying to determine whether this is environmental or an issue with one of those plugins. If you are able to reproduce on a fresh install, then it’s environmental. If it works as expected for you on a fresh install, then it’s a plugin issue.

**Comment by brandonkelly** [comment] 2021-05-15 19:14
Another thing you could try is temporarily setting the [disabledPlugins](https://craftcms.com/docs/3.x/config/config-settings.html#disabledplugins) config setting to `'*'` from `config/general.php`:

```php
'disabledPlugins' => '*',
```

**Comment by bencresty** [comment] 2021-05-16 10:42
> Another thing you could try is temporarily setting the [disabledPlugins](https://craftcms.com/docs/3.x/config/config-settings.html#disabledplugins) config setting to `'*'` from `config/general.php`:
> 
> ```
> 'disabledPlugins' => '*',
> ```

This is a great setting to know. Just did a quick test here with the existing installation, this is what I did:

** [ Starting with Craft 3.6.13 (solo) ] **
* click new entry
* set a title for this new entry
* click 'Save Draft' (CP switches to the 'all' entries list)
* Draft is not in the list (only visible when switching filter manually to 'Drafts'. When switching back to 'All' it's not in the list)

* re-opening the just created draft
* change the title of the draft
* click 'Save Draft'
* Draft not in the 'all' list, same as before (only when switching filter to 'Drafts')

* re-opening draft
* editing draft title
* Now not clicking safe draft, but only let it auto save
* Draft is still not in the list (only when switching filter to 'Drafts')

* Disabling all plugins via general.php and reloading CP
* Check to see if plugins are really all disabled in the CP --> check

* Showing the 'All' entries list in the CP
* Still the draft isn't shown there (but still is when switching to Drafts)

* re-opening draft
* editing draft title
* click 'Save Draft'
* Still not in the list (only when switching filter to 'Drafts')

** Using Craft 3.6.14 **
* Enable plugins again
* Upgrade Craft to 3.6.14 with terminal
* Reload CP
* Still draft isn't visible

* re-opening draft
* editing draft title
* click 'Save Draft'
* Still not in the list (only when switching filter to 'Drafts')

* Clear all cache (from terminal)
* Run garbage collect (from terminal)
* Clear browser cache
* Reload CP
* Still not in the list (only when switching filter to 'Drafts')

* Disabling all plugins again via general.php (and checked in CP; yes, they're all disabled)
* Reload CP
* Still draft isn't visible in All entries


So it's clear it's not related to the plugins. And that the latest 3.6-version doesn't fix this. Also it's clearly not a caching issue.

** Question / Draft workflow **

side note:
Even to me as a developer I see myself struggling to really gasp the right Drafts-workflow in Craft. Of course I understand drafts and I've worked with several CMSses for years, some of them pretty advanced and complex. But there are some things I am still struggling with; like; why is there a Save Draft-button when drafts are automatically saved after each edit? Is there a difference between the two?

Also I found myself editing an entry which I had edited before but the changes weren't there anymore, which I found out too late. That was completely my fault as they were still there, but the latest draft wasn't loaded when entering the entry. I would instinctively have expected the latest draft to be loaded per default when editing a draft. And I wonder why that's not the case as this feels prone to errors to me, because when we forget to switch to the latest draft (like I did, because I didn't know it was needed), we loose all our previous edits (without even knowing it sometimes).

I wonder if customers without a technical background would instinctively understand the right workflow. But this is just a side note and I've understood that things are going to change in 3.7 for the better. So I'm looking forward to that!

Question for now though:
** Why is there a Save Draft-button when drafts are automatically saved after each edit? Is there a difference between the two? **

Thanks for your responses, even during a weekend!

**Comment by brandonkelly** [comment] 2021-05-16 12:39
> So it's clear it's not related to the plugins.

OK. Can you please send your Composer files, any additional autoloaded files (e.g. your `modules/` folder), and a database backup into support@craftcms.com? We can try to reproduce with your installation.

Regarding your other feedback, you’re not the only one who’s confused. We’ve made some big improvements to the publishing workflow for 3.7 – see #7899.

> Why is there a Save Draft-button when drafts are automatically saved after each edit? Is there a difference between the two?

They do the same thing. The button is there for peace of mind.

**Comment by JoshCoady** [comment] 2021-05-17 02:39
> > Why is there a Save Draft-button when drafts are automatically saved after each edit? Is there a difference between the two?
> 
> They do the same thing. The button is there for peace of mind.

If the internet connection drops during an autosave, it will get stuck at the spinner state and no further autosaves will work even once the internet connection is restored. The keyboard shortcut Cmd/Ctrl + S also no longer works, so the only way to save work done after this happens is clicking on that Save Draft button.

**Comment by brandonkelly** [comment] 2021-05-17 10:25
@JoshCoady I hadn’t heard that before, but clearly that’s a bug. I just updated the draft-saving code to use our more modern Axios-based Ajax method (24512cd29c6a68ce2ee1417c38b0ee1d34de6442), which should be more resilient.

**Comment by brandonkelly** [comment] 2021-05-20 18:47
Going to close this for the time being. @bencresty If you can send those files our way, we can look into it further from there.

**Closed by brandonkelly** 2021-05-20 18:47 UTC
Labels: bug

**Comment by bencresty** [comment] 2021-05-25 07:24
> OK. Can you please send your Composer files, any additional autoloaded files (e.g. your `modules/` folder), and a database backup into [support@craftcms.com](mailto:support@craftcms.com)? We can try to reproduce with your installation.

Sorry, policy here is to never send databases/code/logs. Can tell you there are no modules inside the modules folder and the composer json is like:

``` json
{
    "name": "bencresty/project",
    "description": "project",
    "minimum-stability": "stable",
    "repositories": [
        {
            "type": "path",
            "url": "./plugins/bencresty/user-fb/public"
        },
        {
            "type": "path",
            "url": "./plugins/bencresty/twig-filters/public"
        },
        {
            "type": "path",
            "url": "./plugins/bencresty/sitemap-ping/public"
        }
    ],
    "require": {
        "born05/craft-assetusage": "2.2.1",
        "craftcms/cms": "3.6.14",
        "craftcms/contact-form": "^2.2",
        "craftcms/redactor": "2.8.7",
        "doublesecretagency/craft-inventory": "2.1.1",
        "doublesecretagency/craft-matrixcolors": "^2.0",
        "hybridinteractive/craft-contact-form-extensions": "1.2.4",
        "luwes/craft3-codemirror": "^1.0",
        "monachilada/craft-matrixtoolbar": "^1.0",
        "nystudio107/craft-minify": "^1.2",
        "nystudio107/craft-retour": "3.1.53",
        "nystudio107/craft-similar": "1.1.4",
        "shornuk/craft-plausible": "^1.0",
        "topshelfcraft/environment-label": "^3.2",
        "utakka/redactor-anchors": "^1.1",
        "vaersaagod/matrixmate": "1.2.7",
        "verbb/smith": "1.1.13",
        "vlucas/phpdotenv": "^3.4.0",
        "bencresty/sitemap-ping": "^0.0.1",
        "bencresty/twig-filters": "^0.0.1",
        "bencresty/user-fb": "^0.0.5"
    },
    "require-dev": {
        "yiisoft/yii2-shell": "^2.0.3"
    },
    "autoload": {
        "psr-4": {
            "modules\\": "modules/"
        }
    },
    "config": {
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "php": "7.4.9"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ]
    }
}
```
 
> Regarding your other feedback, you’re not the only one who’s confused. We’ve made some big improvements to the publishing workflow for 3.7 – see #7899.

Thanks!


> Going to close this for the time being. @bencresty If you can send those files our way, we can look into it further from there.

Not shure why closing though, as the issue is still there

**Comment by brandonkelly** [comment] 2021-05-25 09:29
@bencresty Can you at least send in your Composer files (including `.lock`) and your project config files (`config/project/`) then?
