### ISSUE TITLE
[3.2] Draft query strings cause back navigation to show "Page Not Found"

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#4574] opened 2019-07-15 23:31 UTC
### Description
The new draft feature introduces a bug where browser navigation can take the user to a broken page.

### Steps to reproduce

1. Open an existing entry
2. Make a change (draft appends something like `?draftId=25` to the current url)
3. Save the entry
4. Try to navigate back

It's worth noting that any browser navigation will take the user to a draft view, so if a user was to make an edit to a post, change their mind and navigate back, then navigate forward, they'd be back in the same draft they just left. Not sure if this would be confusing to the user or not.

Is it intended for draft views to persist in navigation?

### Additional info

- Craft version: 3.2.2

**Comment by brandonkelly** [comment] 2019-07-16 00:11
This should be resolved by a658ad42b76c2a367e962b8d2fdac5f886d591f4 (see https://github.com/craftcms/cms/issues/4535#issuecomment-511613774 for more info).

**Comment by jsunsawyer** [comment] 2019-07-17 23:52
@brandonkelly A user is still able to navigate to these types of pages by doing the following.

1. View an entry
2. Click "Preview"
3. Click "Close Preview"
4. Delete the draft that opening preview created.
5. Navigate back via browser navigation

**Comment by brandonkelly** [comment] 2019-07-18 00:03
Yeah we’re back to this being a semi-problem in Craft 3.2.4. We update the URL once the draft is created, because if we didn’t, there would be similar issues:

1. View entry
2. Click “Preview” or “Save as a draft” (now you are viewing the draft; the location HREF updates)
3. Reload the page

If we didn’t update the URL, the Current revision would load, rather than the draft you were editing.

Or let’s say you don’t reload, but you copy the URL so you can send it to a colleague. You’d expect them to see your draft; instead they’d see the Current revision.

I can think of a couple ways we could help here though:

- Use `history.pushState()` instead of `history.replaceState()` when changing the URL, which would add the draft URL as a _new_ item in your browser history, rather than replacing the current one. Then in your example, you’d still get the 404 in step 5, but you could click “Back” once more and still get back to the Current revision.

- When accessing an invalid draft ID, Craft could automatically redirect the browser to the main entry URL (dropping the `draftId` param from the query string).

Thinking the latter is a better option.

**Comment by brandonkelly** [comment] 2019-07-18 00:14
And done for the next release.

**Closed** 2019-07-18 00:14 UTC

**Comment by jsunsawyer** [comment] 2020-02-05 22:17
@brandonkelly We're back to seeing this issue in Craft 3.4.3.

This happens for both draft query strings as well as deleted entry urls.

**Comment by brandonkelly** [comment] 2020-02-05 22:58
@jsunsawyer Can you post a new GH issue with updated steps to reproduce?

**Comment by jsunsawyer** [comment] 2020-02-05 22:59
@brandonkelly Sure!
