### ISSUE TITLE
FR: Native support for additional columns in tables

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#4344] opened 2019-05-31 16:03 UTC
### Description
Currently, in order to create a table with a flexible number of rows and columns, you have to use a plugin (https://github.com/supercool/tablemaker); however, this plugin is quite neglected at this point and it feels like something that ought to be a setting on the table field to begin with. I'm imagining with this setting, most of the field settings would become the field input and the field settings would simply be:
- Min rows
- Max rows
- Min columns (new)
- Max columns (new)
- Add row label
- Add column label (new)

The mode (fixed or custom columns) would be controlled by a lightswitch on the field settings that would toggle the available settings.

### Additional info

- Craft version: 3.x

**Comment by brandonkelly** [comment] 2019-05-31 16:26
This is a duplicate of #4300

**Closed by brandonkelly** 2019-05-31 16:26 UTC
