### ISSUE TITLE
Show a list of singles the same way channels and structures are shown in the Entries tab.

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1018] opened 2017-01-31 03:47 UTC
> Created by: Hasco Ulijn (hascoulijn@gmail.com) on 2015/08/24 10:48:17 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

At the moment single pages are hidden under Singles in the side menu. What if you could reach a single like the homepage directly under a submenu beneath Singles like Channels and Structures.

**Comment by brandonkelly** [comment] 2017-04-24 16:33
duplicate of #831

**Closed by brandonkelly** 2017-04-24 16:33 UTC
Labels: feature request
