### ISSUE TITLE
[FR] Possibility to disable matrix blocks on a per section level

### ISSUE THREAD

**Issue by michtio** [craftcms/cms#6448] opened 2020-07-24 10:20 UTC
### Description

It would be a nice addition if you could create a matrix fields that contains x-blocks, but from those blocks, once we add it to a section ( let's say a blog entry ) and that matrix field contains blocks that we only want to use on a structure ( to create a full page ), it would make a great use case to be able to say:

Hey for this section, I don't want the user to be able to use block x and block y. It would give a nicer dev experience, rather than to create 2 different matrix fields, where you'll need to duplicate 70% of the blocks specifically for that blog content entry, while you actually have those blocks already set up.

**Comment by brandonkelly** [comment] 2020-07-24 14:20
Seems like this is a duplicate of #3462.

**Closed by brandonkelly** 2020-07-24 14:20 UTC
Labels: enhancement

**Comment by daltonrooney** [comment] 2020-07-24 21:17
@michtio If you’re open to a plugin, MatrixMate can handle this.
