### ISSUE TITLE
Features that help manage the editorial/content flow better

### ISSUE THREAD

**Issue by craftster** [craftcms/cms#2085] opened 2017-11-03 12:29 UTC
Recently switched from Wordpress to Craft. Still learning. We have a full-fledged editorial team with copy editors and editors. Managing the editorial flow inside Craft seems to be bit of an issue. Here's how we used to do in Wordpress:

1. Writer would write the article and then submit to copy editor for review. 
2. Copy editor would then fix the copy and submit to editor for a final check and scheduling. 
3. Also, Wordpress showed it on the post screen if a post is being currently edited, which made it easy for everyone else. 

Point 3 is the biggest issue we are facing in Craft. There is a plugin available that I have found but it only shows a 'currently editing' warning when one goes **inside** an entry. 

Ideally it should be right on the entries screen, below the post title preferably. And if there's a warning pop-up like Wordpress, it would help. 

Point 1 and 2 are bit of an issue too because there's no way to submit an entry for review. Right now, the writers need to inform the editors personally each time a post is complete. This defeats the purpose of using a CMS. One shouldn't need to communicate about all these things outside the CMS. The CMS should manage this. 

Ideally different editors should have different entry queues to take care of, as and when they are submitted an entry to edit. 

Maybe there's a way to do the above and I don't know about it. Please let me know if there is.

**Comment by brandonkelly** [comment] 2017-11-03 15:38
Agree that these should be core responsibilities of a CMS, and we do plan on taking Craft in this direction down the road. Improving author experience, especially for larger editorial teams, will be our main focus for [Craft 4.0](https://github.com/craftcms/cms/projects/4).

In the meantime, check out [this plugin](https://github.com/verbb/workflow), which adds an editorial workflow to Craft.

// duplicate of #824 and #829

**Closed by brandonkelly** 2017-11-03 15:38 UTC
Labels: duplicate
