### ISSUE TITLE
[4.x]: renderTemplate doesn't find module paths when using Command+S

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#10777] opened 2022-03-18 04:30 UTC
### What happened?

I have a custom Element that renders a template (along with several other layout elements) in the `Element::getFieldLayout()` method:

```
...
new Html($this->getDataSource()->getSettingsHtml()),
...
```

The Element layout uses Craft's new unified Element editor for rendering the Element form. The Element form renders fine and saves correctly when I manually hit the save button.

However, when I hit Command+S or select the 'Save and continue editing' save action, the Element saves but throws an error when loading the Element page after the save is complete.

```
Twig Template Loading Error – craft\web\twig\TemplateLoaderException
Unable to find the template “sprout-module-reports/_components/datasources/CustomQuery/settings” in "__string_template__7f41cbc86fee6bf3ccf0fa1f26b09169e24506eef3022bfc64967735b27ca318" at line 1.
```

It seems in this second case Craft can no longer find the custom module path for my templates. I've dumped `Craft::$app->getView()->getTemplatesPath()` and it is the same path for both scenarios.

The code being rendered in the line that throws the error:

```
return Craft::$app->getView()->renderTemplate('sprout-module-reports/_components/datasources/CustomQuery/settings', [
            'settings' => count($settings) ? $settings : $this->report->getSettings(),
        ]);
```

Any ideas why the module template path `sprout-module-reports` is not found in the quick save scenario?

### Craft CMS version

4.0.0-beta.2

### PHP version

8

### Operating system and version

MacOS

### Database type and version

MySQL

### Installed plugins and versions

- Sprout plugins, Commerce

**Comment by BenParizek** [comment] 2022-03-20 01:28
I've updated how I'm handling Field Layouts in my element and no longer relying on building a Field Layout Element in the `Element::getFieldLayout()` method so this issue is no longer an issue for me, but may still happen if someone else tries something similar.

I'm still feeling fairly new to a lot of the new unified element editor stuff so this may just be caused by a poor implementation decision on my end as I get up to speed and more familiar with the new features.

**Comment by brandonkelly** [comment] 2022-04-05 18:29
Where/how are you registering the `sprout-module-reports` template root?

**Comment by BenParizek** [comment] 2022-04-06 18:25
I no longer have the code above in place to test changes, but the template root is registered in a Yii module that is loaded by the reports plugin. 

### Init method of plugin

```
ReportsModule::isEnabled() && ReportsModule::getInstance();
```

### Init method of module

```
Event::on(
            View::class,
            View::EVENT_REGISTER_CP_TEMPLATE_ROOTS,
            function(RegisterTemplateRootsEvent $e): void {
                $e->roots['sprout-module-reports'] = $this->getBasePath().DIRECTORY_SEPARATOR.'templates';
            });
```

**Comment by brandonkelly** [comment] 2022-04-06 20:55
Does `isEnabled()` instantiate the module? `getInstance()` won’t – it just returns `null` if the module hasn’t been instantiated yet. So maybe that’s the bug – your template root isn’t getting registered because nothing is instantiating it before the template is requested.

**Comment by BenParizek** [comment] 2022-04-18 13:58
Those methods do a handful of configuration things for me including instantiating the module. So in my case the template root was registered and working in some places, but seemed to be behaving differently in that `Element::getFieldLayout()` method.

**Comment by brandonkelly** [comment] 2022-04-18 22:39
How exactly is the module getting instantiated though?

**Comment by BenParizek** [comment] 2022-04-18 23:01
ReportsModule::getInstance() calls to the module class:

```
public static function getInstance(): ReportsModule
    {
        /** @var ReportsModule $module */
        $module = Sprout::getSproutModule(static::class, 'sprout-module-reports');

        return $module;
    }
```

Which calls to a core helper method:

```
public static function getSproutModule(string $class, string $id): Module
    {
        if ($module = Craft::$app->getModule($id)) {
            return $module;
        }

        $module = new $class($id);
        static::setInstance($module);
        Craft::$app->setModule($id, $module);

        return $module::getInstance();
    }
```

**Comment by brandonkelly** [comment] 2022-04-19 22:41
Closing for now until there’s a reproducible use case.

**Closed by brandonkelly** 2022-04-19 22:41 UTC
Labels: bug, craft4
