### ISSUE TITLE
[4.x]: Search index jobs fail randomly

### ISSUE THREAD

**Issue by timoschwarzer** [craftcms/cms#12047] opened 2022-10-04 06:04 UTC
### Description

Since Craft 4.0, search index jobs fail randomly for us with the error/stacktrace below. Most jobs run through without errors but after 1 day of day-to-day activity in the CMS I have about 30-50 failed jobs in the queue.

### Setup

- Craft CMS 4.2.5.2
- PostgreSQL 12.12
- 5 Workers run by supervisord
  ```ini
  [program:worker]
  process_name=%(program_name)s_%(process_num)02d
  command=/app/craft queue/listen -v
  catch_workers_output = Yes
  stdout_events_enabled=true
  stderr_events_enabled=true
  stdout_logfile_maxbytes=0
  stderr_logfile_maxbytes=0
  stdout_logfile=/dev/stdout
  stderr_logfile=/dev/stderr
  user=www-data
  numprocs=5
  ```

### Actual behavior

```
db-1             | 2022-10-04 05:34:55.326 UTC [628] ERROR:  duplicate key value violates unique constraint "pk_bzsntbgdnrckjctukjognriuerikddfycwed"
db-1             | 2022-10-04 05:34:55.326 UTC [628] DETAIL:  Key ("elementId", attribute, "fieldId", "siteId")=(5, slug, 0, 4) already exists.
db-1             | 2022-10-04 05:34:55.326 UTC [628] STATEMENT:  INSERT INTO "searchindex" ("elementId", "attribute", "fieldId", "siteId", "keywords", "keywords_vector") VALUES ($1, $2, $3, $4, $5, $6)
craft-1          | 2022-10-04 07:34:55 [245] t9n:["app","Updating search indexes"] (attempt: 1, pid: 450) - Error (0.083 s)
craft-1          | > yii\db\IntegrityException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "pk_bzsntbgdnrckjctukjognriuerikddfycwed"
craft-1          | Stack trace:
craft-1          | #0 /app/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO "se...')
craft-1          | #1 /app/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('INSERT INTO "se...')
craft-1          | #2 /app/vendor/craftcms/cms/src/helpers/Db.php(945): yii\db\Command->execute()
craft-1          | #3 /app/vendor/craftcms/cms/src/services/Search.php(382): craft\helpers\Db::insert('{{%searchindex}...', Array)
craft-1          | #4 /app/vendor/craftcms/cms/src/services/Search.php(172): craft\services\Search->_indexKeywords(Object(craft\elements\Entry), ' startseite ', 'slug')
craft-1          | #5 /app/vendor/craftcms/cms/src/queue/jobs/UpdateSearchIndex.php(65): craft\services\Search->indexElementAttributes(Object(craft\elements\Entry), Array)
craft-1          | #6 /app/vendor/yiisoft/yii2-queue/src/Queue.php(246): craft\queue\jobs\UpdateSearchIndex->execute(Object(craft\queue\Queue))
craft-1          | #7 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('245', 'O:34:"craft\\que...', '300', '1')
craft-1          | #8 /app/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute('245', 'O:34:"craft\\que...', '300', '1', '450')
craft-1          | #9 [internal function]: yii\queue\cli\Command->actionExec('245', '300', '1', '450')
craft-1          | #10 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
craft-1          | #11 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
craft-1          | #12 /app/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('exec', Array)
craft-1          | #13 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('exec', Array)
craft-1          | #14 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array)
craft-1          | #15 /app/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('queue/exec', Array)
craft-1          | #16 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('queue/exec', Array)
craft-1          | #17 /app/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
craft-1          | #18 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
craft-1          | #19 /app/craft(13): yii\base\Application->run()
craft-1          | #20 {main}
```

### Craft CMS version

4.2.5.2

### PHP version

8.1.11

### Operating system and version

Debian 11

### Database type and version

PostgreSQL 12.12

### Installed plugins and versions

Calendarize	dev-craft-4
Expanded Singles	dev-craft-4
Extended Search	3.0.1
Formie	2.0.12
Isolate	dev-craft-4
MatrixMate	2.1.0
Redactor	3.0.2
Redactor Anchors	1.4.0
Smith	2.0.0
Template Comments	4.0.0
Twigpack	4.0.0-beta.4

**Comment by angrybrad** [comment] 2022-10-05 01:50
> 5 Workers run by supervisord

It's almost certainly a race condition caused by this, which is why we recommend running only one queue runner for 99.9% of sites.

Drop that down to one worker and see if you can reproduce the issue.

**Comment by timoschwarzer** [comment] 2022-10-05 11:08
Thanks for the answer, I'll try that!

> which is why we recommend running only one queue runner for 99.9% of sites

The docs [here](https://craftcms.com/docs/4.x/config/general.html#runqueueautomatically) link to [these Yii2 docs](https://github.com/yiisoft/yii2-queue/blob/master/docs/guide/worker.md) that use 4 workers in the example so I didn't expect it to break with Craft. Note that running multiple workers worked fine with Craft 3, so this is some regression. I understand though that this is not a high-priority bug. Maybe just adding a hint to the docs for the time being?

**Comment by angrybrad** [comment] 2022-10-05 18:39
Yup - we've got an article on configuring queues for Craft _in the queue_, if you will.

Going to go ahead and close this, but if you still hit the error after dropping down to 1 worker, comment back, and will investigate more!

**Closed by angrybrad** 2022-10-05 18:39 UTC
Labels: bug, craft4

**Comment by angrybrad** [comment] 2023-04-24 17:08
@aaronbushnell There’s an open WIP PR for it here courtesy of @AugustMiller https://github.com/craftcms/docs/pull/493/files

**Comment by AugustMiller** [comment] 2023-04-25 23:16
@aaronbushnell This has been published!

https://craftcms.com/docs/4.x/queue.html

**Comment by aaronbushnell** [comment] 2023-04-27 19:12
You all are so quick! Thanks, @AugustMiller @angrybrad!

**Comment by bossanova808** [comment] 2023-12-05 00:06
@AugustMiller @angrybrad Currently ooking at some queue issues myself at the moment - the now live article seems to imply that 4 workers is normal/ok (in contradiction to the discussion here) - and there's no reference in this to limiting queue workers to just  a single worker.

Did the advice on this change, or is the documentation missing this advice-that-is-still-current?

**Comment by AugustMiller** [comment] 2023-12-05 21:28
Craft definitely supports multiple workers! The article assumes that the reader is interested in configuring _more than zero_ non-HTTP queue runners. 😉

Brad's comment in this thread is strictly a debugging tip—if we can isolate variables and determine that the issue only presents when using multiple workers (or conversely, that it presents _irrespective_ of the number of workers), it would be easier to tell whether the problem is within Craft, or something specific to the project state, database, etc.

**Comment by bossanova808** [comment] 2023-12-06 00:51
Ok, no worries - I read Brad's comment above as being a bit more of a general recommendation than that, but good to know (as I use two workers by default currently)

(I use locks in all my queue jobs to avoid any concurrency issues)
