### ISSUE TITLE
Reverting to an older entries version / publishing draft overrides secondary locale content

### ISSUE THREAD

**Issue by JordanMed** [craftcms/cms#5249] opened 2019-11-19 18:09 UTC
### Description
Reverting to an older version of an entry or publishing a draft of an entry will erase existing content on other locales. For example I have an english and french locale for my site. If i set up a draft for each local (using english on english and french on french) when I post my drafts, which ever I post second will override the first. I.E. I post french after posting english, my english page will now contain all of my french content. 

### Steps to reproduce

Here's how I did it:
-Create English page
-Populate with english content
-Save as draft
-Create French page
-Populate with french content
-Save as draft
-Publish English page from draft
-Publish French page from draft
-French content has ended up on English page

This also happens when reverting to older versions. 
-Revert english to older version. 
-French page's content is now the same as the english version. 

### Additional info

- Craft version: 2.7.10
- PHP version: 7.2
- Database driver & version: Maria DB 
- Plugins & versions: n/a

**Comment by brandonkelly** [comment] 2019-11-21 01:18
This is a duplicate of #4642. We are working to fix it in Craft 3.4.

**Closed by brandonkelly** 2019-11-21 01:18 UTC
