### ISSUE TITLE
Debug toolbar Craft icon CSS conflict

### ISSUE THREAD

**Issue by simonkuran** [craftcms/cms#6737] opened 2020-08-27 13:09 UTC
### Description
When a site has global CSS like this:
`img {
	width: 100%;
	height: auto;
}`

The Craft icon in the debug toolbar is the wrong size. I believe the icon should either have a native size of 30 x 30px or explicitly have its size set via CSS instead of just HTML attributes.

### Additional info

- Craft version: 3.5.6
<img width="1660" alt="Screen Shot 2020-08-27 at 4 44 00 PM" src="https://user-images.githubusercontent.com/41410727/91445984-e77a4380-e887-11ea-8d3b-3afddd5c8e62.png">
<img width="1664" alt="Screen Shot 2020-08-27 at 4 44 55 PM" src="https://user-images.githubusercontent.com/41410727/91445995-eba66100-e887-11ea-9630-98d184eeb6cf.png">

**Comment by mmikkel** [comment] 2020-08-27 13:40
I use the below CSS to "fix" this, but I agree that it'd be a good idea to set an explicit width/height for the logo in core. FWIW, this didn't happen before the logo was redesigned.

```css
[class$="debug-toolbar__title"] {
    max-width: 30px;
}
```

**Comment by brandonkelly** [comment] 2020-08-27 13:47
This is a duplicate of #6447. I PR’d a fix (yiisoft/yii2-debug#435) which has been merged for the next release (2.1.14), but not sure when that will go out.

**Closed by brandonkelly** 2020-08-27 13:47 UTC
Labels: bug

**Comment by simonkuran** [comment] 2020-08-27 14:02
Great, thanks. Sorry I didn't find the duplicate.

**Comment by brandonkelly** [comment] 2020-11-10 23:52
yii2-debug 2.1.14 is out now with that fix. Run `composer update` to get it.
