### ISSUE TITLE
HTTP 400 – Bad Request – yii\web\BadRequestHttpException Invalid token on page Preview / View

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#10325] opened 2022-01-06 13:43 UTC
### Description
I have a page Preview / View issue when clicking on one of this two buttons within the CP:
`HTTP 400 – Bad Request – yii\web\BadRequestHttpException Invalid token`

This kind of URL is generated:
`https://my-website.dev/my-section?token=ns5RRa1tOkxTod_UZyN-f-rz4UVKru1A/my-slug`

While Entry URI format is set like this:
`{parent.uri}/{slug}`

For no reason, the Entry slug is appended after the token query, which probably results in this HTTP 400 error.

I don't have any special rule in my htaccess file and no `{% redirect %}` in my Twig template file.

### Additional info

- Craft version: 3.7.27.1
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.34

**Comment by brandonkelly** [comment] 2022-01-07 00:58
Is this for Craft Solo or Pro?

If Pro, go to **Settings** → **Sections** → [your section name]. What is the preview target’s **URL Format** set to?

**Comment by romainpoirier** [comment] 2022-01-07 08:13
It's for Craft Pro.

Preview Targets is set to:

- **Label:** Primary entry page
- **URL Format:** {url}
- **Auto-refresh:** checked

I haven't edited this setting from default value.

**Comment by brandonkelly** [comment] 2022-01-07 20:14
Not really sure how the slug could be getting added to the end there, and not able to reproduce locally. Can you send over your Composer files, any custom plugins/modules, and a database backup, to support@craftcms.com so we can look into it from there?

**Comment by olivierbon** [comment] 2022-01-10 14:50
Redirection in a template was the problem - resolved in support.

**Closed by olivierbon** 2022-01-10 14:50 UTC
Labels: bug
