### ISSUE TITLE
Feature Request: Instructions for global sets

### ISSUE THREAD

**Issue by matt-adigital** [craftcms/cms#1923] opened 2017-08-16 09:01 UTC
### Description

Instructions for the heading and body fields for a 404 page would differ from the instructions for a sidebar section using the same fields. If we could add an instruction to the global sets, similar in the way you can to a matrix field, then it would make life much easier for cms users.

Can this be made available for Craft v2? Thank you.

**Comment by brandonkelly** [comment] 2017-08-16 13:52
If we made this possible, it would go hand-in-hand with being able to customize field names as well. So I’m going to mark this as a duplicate of #806.

**Closed by brandonkelly** 2017-08-16 13:52 UTC

**Comment by matt-adigital** [comment] 2017-08-16 14:00
Ok thanks Brandon, marking as duplicate has lead us to find https://github.com/benjamminf/craft-relabel in #806 which will do what we need for now, thanks for the help
