### ISSUE TITLE
[UX/UI] Field Layout Designer

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#6906] opened 2020-09-27 22:01 UTC
It would be nice when I add a new Tab in the Field Layout Designer to have Instant the possibility to give the Tab a name.
The default is something like: `Tab 3` but in 99% I have to rename this Tab. This reduce the clicks and sometime I've create a lot of tabs : )

![image](https://user-images.githubusercontent.com/764292/94376863-8d3a0000-011d-11eb-865b-16f16bbcca40.png)

**Comment by brandonkelly** [comment] 2020-09-29 10:07
This is a duplicate of #1956. I just went ahead and made the change for the next release :)

**Closed by brandonkelly** 2020-09-29 10:07 UTC
Labels: enhancement

**Comment by brandonkelly** [comment] 2020-10-01 19:19
Craft 3.5.12 is out now with that change ✨

**Comment by davidhellmann** [comment] 2020-10-01 20:36
Thanks! :)
