### ISSUE TITLE
[4.x]: Integrity constraint violation when saving an entry with an empty slug

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#11115] opened 2022-05-06 01:32 UTC
### What happened?

I discovered this after duplicating some entries. I cleared out the slug, wanting it to auto-create it from the title.

### Steps to reproduce

1. Load an entry publish screen in the CP
2. Delete the slug
3. Wait for it to autosave
4. Save entry

https://cln.sh/QkpI37

```
2022-05-06 01:28:15 [web.ERROR] [yii\db\IntegrityException] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`spokeandchain`.`changedattributes`, CONSTRAINT `changedattributes_elementId_fk` FOREIGN KEY (`elementId`) REFERENCES `elements` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) in /app/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /app/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /app/vendor/craftcms/cms/src/helpers/Db.php(1010): yii\db\Command->execute()
#3 /app/vendor/craftcms/cms/src/services/Elements.php(2813): craft\helpers\Db::upsert()
#4 [internal function]: craft\services\Elements->craft\services\{closure}()
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func()
#6 /app/vendor/yiisoft/yii2/base/Application.php(387): yii\base\Component->trigger()
#7 /app/web/index.php(23): yii\base\Application->run()
#8 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`spokeandchain`.`changedattributes`, CONSTRAINT `changedattributes_elementId_fk` FOREIGN KEY (`elementId`) REFERENCES `elements` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
The SQL being executed was: INSERT INTO `changedattributes` (`elementId`, `siteId`, `attribute`, `dateUpdated`, `propagated`, `userId`) VALUES (15256, 1, 'slug', '2022-05-06 01:28:15', 0, 1) ON DUPLICATE KEY UPDATE `elementId`=15256, `siteId`=1, `attribute`='slug', `dateUpdated`='2022-05-06 01:28:15', `propagated`=0, `userId`=1 in /app/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException()
#1 /app/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /app/vendor/craftcms/cms/src/helpers/Db.php(1010): yii\db\Command->execute()
#3 /app/vendor/craftcms/cms/src/services/Elements.php(2813): craft\helpers\Db::upsert()
#4 [internal function]: craft\services\Elements->craft\services\{closure}()
#5 /app/vendor/yiisoft/yii2/base/Component.php(633): call_user_func()
#6 /app/vendor/yiisoft/yii2/base/Application.php(387): yii\base\Component->trigger()
#7 /app/web/index.php(23): yii\base\Application->run()
#8 {main}
```

### Craft CMS version

4.0.0.1

### PHP version

8.0.18

### Database type and version

Tested on Postgres (Europa) and MariaDB (Spoke)

### Installed plugins and versions

-

**Comment by thupsi** [comment] 2022-05-06 05:40
Definatelly happens in other cases too (not only when the slug is empty). And applies to 3.x and 4.x versions. See #11083

**Comment by brandonkelly** [comment] 2022-05-06 06:48
Yep, duplicate of #11083.

**Closed by brandonkelly** 2022-05-06 06:48 UTC
Labels: bug, craft4
