### ISSUE TITLE
Uncaught (in promise) TypeError: i.includes is not a function when adding a block

### ISSUE THREAD

**Issue by angelokeirsebilck** [craftcms/cms#16055] opened 2024-11-08 13:00 UTC
### Description

I am using a CK Editor field with Entry type blocks.

On 1 page, the single section for the homepage i'm getting a JS error when adding blocks to my CK Editor field. I have 3 languages: NL,FR and EN. I only get this error on EN and FR.

When adding the block I get an JS error in the console: 

`Uncaught (in promise) TypeError: i.includes is not a function
    at ElementEditor.js:1147:18`

On other pages using the same setup/CK Editor field I don't get this error.

### Expected behavior

On other pages when adding the block I can see the block added in the CK Editor field.

### Actual behavior

No block is added, console gives me JS error.

### Additional info

- Craft version: Craft Pro 5.4.10.1
- PHP version: 8.3.13
- Database driver & version: MySQL 18
- Plugins & versions:

Amazon S3	2.2.1
Button Box	5.0.0
CKEditor	       4.3.1
Control Panel CSS	3.0.0
Elements Panel	3.0.0
Embedded Assets	5.3.0
Formie	3.0.9
Hyper	dev-craft-5
Image Resizer	4.0.1
Knock Knock	3.0.1
Minify	5.0.0
SEOmatic	5.1.5
Social Share	2.0.2
Sprig	3.5.1
Vite	5.0.1

I'm happy to give more details/db if needed.

**Comment by brandonkelly** [comment] 2024-11-08 14:58
Thanks for reporting that. Looks like it might be more of a Craft CMS issue despite happening in CKEditor so I transferred to the `cms` repo.

I can’t reproduce though, and looking at the code, I don’t understand how the error could occur. If you could send your database and Composer files into support@craftcms.com, we can look further into it from there.

**Comment by angelokeirsebilck** [comment] 2024-11-12 07:30
> Thanks for reporting that. Looks like it might be more of a Craft CMS issue despite happening in CKEditor so I transferred to the `cms` repo.
> 
> I can’t reproduce though, and looking at the code, I don’t understand how the error could occur. If you could send your database and Composer files into [support@craftcms.com](mailto:support@craftcms.com), we can look further into it from there.

I've sent the composer files and DB to [support@craftcms.com](mailto:support@craftcms.com). Let me know if you need anything else.

**Comment by brandonkelly** [comment] 2024-11-12 16:13
Thanks, received! Which entry are you getting the error on?

**Comment by angelokeirsebilck** [comment] 2024-11-12 19:28
> Thanks, received! Which entry are you getting the error on?

On the Home Single Section. For example in the CK Editor field (Column 2) on the first Block - Default when adding a Links block below the text.

**Comment by brandonkelly** [comment] 2024-11-16 02:38
Thanks! I was able to reproduce with your site, and got it fixed for the next release.

You can get the fix early by changing your `craftcms/cms` requirement in `composer.json` to:

```json
"craftcms/cms": "5.x-dev as 5.5.0.1",
```

**Closed as completed by brandonkelly** 2024-11-16 02:38 UTC
Labels: bug

**Comment by brandonkelly** [comment] 2024-11-19 00:36
Craft 4.13.3 and 5.5.1 are out with that fix. Thanks again!
