### ISSUE TITLE
[4.x]: craft up command not picking up CKEditor config change

### ISSUE THREAD

**Issue by RandomJo** [craftcms/cms#15322] opened 2024-07-09 16:22 UTC
### Description

We noticed that when we added the media embed button to CKEditor, that project config change was accidentally being reverted by other developers because `craft up` was not applying the CKEditor config change.

### Steps to reproduce

1. Take a database snapshot.
2. Add a button to the CKEditor config and commit project config changes.
3. Revert to your database snapshot that does not include the project config change for CKEditor.
4. Run `craft up` (see screenshot for my result; you can see it didn't pick up the config change)
![Screenshot 2024-07-09 at 11 09 32 AM](https://github.com/craftcms/cms/assets/230458/a181251c-9ccb-4683-9de6-f7ce4d5ba3a6)
5. Run `craft project-config/apply` (see screenshot for my result; you can see this did pick up the config change)
![Screenshot 2024-07-09 at 11 10 02 AM](https://github.com/craftcms/cms/assets/230458/9bb0258e-24c2-4ea3-85b4-c4cd6d4dc9ab)

### Expected behavior

I expect `craft up` to pick up all config changes per the description of the CLI command.

### Actual behavior

`craft up` is not picking up our CKEditor change. Not sure if this could be a downstream issue with the plugin or something with Craft more globally.

### Craft CMS version

4.9.7

### PHP version

8.2.20

### Operating system and version

Linux 6.9.6-orbstack-00147-gb0567c7c0069

### Database type and version

MySQL 8.0.36

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

CKEditor: 3.8.3

**Comment by brandonkelly** [comment] 2024-07-09 20:32
Just tested this locally and wasn’t able to reproduce. `up` found all of the pending project config changes and pulled them in:

```sh
> ddev craft up
Checking for pending Craft and plugin migrations ...
No new migrations found. Your system is up to date.

Applying changes from your project config files ...
- updating fields.7ca32393-f78c-4de0-9f8f-52b64e09584f.settings ...
  - adding meta.__names__.7ca32393-f78c-4de0-9f8f-52b64e09584f ... done
  - updating fields.7ca32393-f78c-4de0-9f8f-52b64e09584f ... done
  done
- updating fields.08f8ec90-f7ad-4d40-9880-3c96304f1e4e.settings ...
  - updating fields.08f8ec90-f7ad-4d40-9880-3c96304f1e4e ... done
  done
- updating fields.67ff16f0-04e2-492b-b999-a7d364331d80.settings ...
  - updating fields.67ff16f0-04e2-492b-b999-a7d364331d80 ... done
  done
- updating fields.aef80333-1412-4130-bb84-ac3bdbbcbbe2.settings ...
  - updating fields.aef80333-1412-4130-bb84-ac3bdbbcbbe2 ... done
  done
- updating fields.c9ccf068-4ace-4b21-9356-68f3faa96cf3.settings ...
  - adding meta.__names__.c9ccf068-4ace-4b21-9356-68f3faa96cf3 ... done
  - updating fields.c9ccf068-4ace-4b21-9356-68f3faa96cf3 ... done
  done
- updating fields.e03a8ea1-0b9b-4e8c-bbf5-f7197caad45c.settings ...
  - adding meta.__names__.e03a8ea1-0b9b-4e8c-bbf5-f7197caad45c ... done
  - updating fields.e03a8ea1-0b9b-4e8c-bbf5-f7197caad45c ... done
  done
- updating dateModified ... done
- adding ckeditor.configs.e3309014-5d90-4240-8fc5-44d09f616aef.options.code ... done
- adding ckeditor.configs.82c4200d-9db1-49d5-b5ea-2163d3c44148.options.code ... done
- adding ckeditor.configs.57e301f3-28a2-4375-a2eb-bb3239f61c48.options.code ... done
- adding ckeditor.configs.e3309014-5d90-4240-8fc5-44d09f616aef.headingLevels ... done
- adding ckeditor.configs.e3309014-5d90-4240-8fc5-44d09f616aef.toolbar ... done
- adding ckeditor.configs.82c4200d-9db1-49d5-b5ea-2163d3c44148.headingLevels ... done
- adding ckeditor.configs.82c4200d-9db1-49d5-b5ea-2163d3c44148.toolbar ... done
- adding ckeditor.configs.57e301f3-28a2-4375-a2eb-bb3239f61c48.headingLevels ... done
- adding ckeditor.configs.57e301f3-28a2-4375-a2eb-bb3239f61c48.toolbar ... done
- adding meta.__names__.e3309014-5d90-4240-8fc5-44d09f616aef ... done
- updating ckeditor.configs.e3309014-5d90-4240-8fc5-44d09f616aef ... done
- adding meta.__names__.82c4200d-9db1-49d5-b5ea-2163d3c44148 ... done
- updating ckeditor.configs.82c4200d-9db1-49d5-b5ea-2163d3c44148 ... done
- adding meta.__names__.57e301f3-28a2-4375-a2eb-bb3239f61c48 ... done
- updating ckeditor.configs.57e301f3-28a2-4375-a2eb-bb3239f61c48 ... done
- updating meta.__names__ ... done
Finished applying changes

Checking for pending content migrations ...
No new migrations found. Your system is up-to-date.
```

And `project-config/apply` found no new pending changes:

```sh
> ddev craft project-config/apply
Applying changes from your project config files ...
Finished applying changes
```

If `up` isn’t picking up changes but `project-config/apply` does, that usually indicates that the `dateModified` value in `config/project/project.yaml` is the same as the internally-cached value. (`up` only looks at `dateModified` to determine if something has changed; `project-config/apply` does a deep comparison.)

If you’re ever merging your work with other developers’ project config YAML changes, you should be getting a conflict on that `dateModified` value. When that happens, make sure you resolve by running `craft project-config/touch` rather than resolving manually. `project-config/touch` will resolve the conflict for you, with a new timestamp that is different from both current values, so `up` should work as expected on all environments.

**Closed as completed by brandonkelly** 2024-07-09 20:32 UTC
Labels: bug, craft4

**Comment by brandonkelly** [comment] 2024-07-17 20:55
This came up again (#15357) and I decided to change the `up` command to stop caring about `dateModified` and run `project-config/apply` as a sub command, no matter what.

That change has been made for the upcoming 4.11 and 5.3 releases.

**Comment by brandonkelly** [comment] 2024-07-18 23:51
Sorry, had to revert that change as it was causing other issues.

**Comment by MangoMarcus** [comment] 2024-11-26 16:40
@brandonkelly Could you clarify why this fix was reverted?

I'm encountering a similar problem in v5, where I import an older DB from another environment and run `craft up` but the project config isn't applied because the files haven't actually been updated - they are however still out of sync with the DB

For a workaround we're probably going to run `craft clear-cahes/data` before `craft up`

Thanks!

**Comment by brandonkelly** [comment] 2024-11-27 23:42
@MangoMarcus I can’t remember exactly.

Can you post a new issue with steps to reproduce the caching issue?
