### ISSUE TITLE
[3.2] Getting stuck in a state where it's not possible to save new entries when dragging files onto an asset field

### ISSUE THREAD

**Issue by aelvan** [craftcms/cms#4534] opened 2019-07-11 19:15 UTC
### Steps to reproduce

1. Create a section that has an entry type with an asset field.
2. Create a new entry.
3. Add a title, and _drag a file onto the asset field_.
4. Click "Save entry". The browser (Chrome in my case) pops up a message saying "Leave site? Changes you made may not be saved.". That doesn't sound right, so click "Cancel".

The "Save entry" button is now disabled, and changing the content does not enable it. I've not found a way to save the entry successfully after this happens.

### Additional info

- Craft version: 3.2.0
- PHP version: 7.2.14
- Database driver & version: 5.7.25

**Comment by brandonkelly** [comment] 2019-07-11 21:19
Can you test this in 3.2.1? A possibly-related bug was fixed in that.

**Comment by aelvan** [comment] 2019-07-11 21:33
Just tested on 3.2.1 and the issue is still there.

**Comment by brandonkelly** [comment] 2019-07-11 21:46
Thanks! I’m not able to reproduce this though. What are your Assets field settings? Are you getting any JavaScript errors on the page?

**Comment by mmikkel** [comment] 2019-07-12 08:16
@brandonkelly I'm able to reproduce this (also using Chrome on Mac). There are no JS errors in the console, and it only happens if you drag a file to the Assets field, not if you actually click "Add an Asset".

I made a quick screencast to demo the issue: https://recordit.co/YFEj4QyRYq

**Comment by aelvan** [comment] 2019-07-12 08:17
I tried changing the Asset field settings around, but that doesn't make any difference. I'm able to reproduce with no restrictions to folder, all sources enabled, no restrictions to file types, limit of 1, and no validation of related assets. No errors in the console. 

Here's a recording that shows what I'm doing:  https://recordit.co/3iyrYB2UXm

**Closed** 2019-07-12 23:26 UTC

**Comment by brandonkelly** [comment] 2019-07-12 23:30
Thanks for the videos! I noticed that there was no spinner in the header, after the upload had completed, which means that Craft didn’t realize that the form had changed. Fixed that for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#a303b5c3043d6c77f09c01230aa88135c603694d as 3.2.1",
  "...": "..."
}
```

Then run `composer update`.
