### ISSUE TITLE
`':notempty:'` not working for email fields

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#9641] opened 2021-07-26 14:13 UTC
### Description

In an element query I’ve set a custom field parameter for a email field to `':notempty:'`. It is not working, the result contains entries where the `customerEmail` field returns an empty string. When I set it to `':empty:'` no entries are returned at all.

```php
Entry::find()->customerEmail(':notempty:');
```

I am able to get the wanted result by using the `where()` method.

```php
Entry::find()->where(['not', ['field_customerEmail' => '']]);
```

_(Issue title and description updated after I noticed that it’s in fact a field of type email and not a normal plain text field.)_

### Additional info

- Craft version: 3.6.12.1
- PHP version: 7.3.7
- Database driver & version: PostgreSQL 11.11
- Plugins & versions: n/a

**Comment by carlcs** [comment] 2021-07-26 16:09
I’ve tested this on a clean install where I created a plain text and an email field, and it looks like empty values are stored differently.

- `customerEmail` is a plain text field
- `customerEmailNew` is an email field, which I created after entries with UID 10cdf6 and a87ac0 where created

<img width="479" alt="Bildschirmfoto 2021-07-26 um 17 57 10" src="https://user-images.githubusercontent.com/7516543/127020625-f04c032b-1260-474a-b96e-e9565e223cc7.png">

**Comment by brandonkelly** [comment] 2021-07-27 14:57
I’m not able to reproduce this – both `:empty:` and `:notempty:` are working as expected for Email fields on my end. 

> I am able to get the wanted result by using the `where()` method.
> 
> ```php
> Entry::find()->where(['not', ['field_customerEmail' => '']]);
> ```

That’s basically what `:notempty:` is supposed to be doing, except it wall also account for `NULL` values, so more like:

```php
Entry::find()->where(['not', [
    'or',
    ['field_customerEmail' => null],
    ['field_customerEmail' => ''],
]]);
```

Can you replace your `all()` method with `getRawSql()`, dump it out paste the SQL statement here?



> I’ve tested this on a clean install where I created a plain text and an email field, and it looks like empty values are stored differently.

That did help identify a bug where blank email values weren’t always getting stored as `NULL`. Just released Craft 3.7.6 with a fix (a3970f41ab79c1888a3da06d5311092d55fc72a6). Note that fix is actually going to break your custom `where()` code though, since you’re not currently checking for `NULL`.

> * `customerEmail` is a plain text field (stores VARCHAR)
> 
> * `customerEmailNew` is an email field (stores TEXT), which I created after entries with UID 10cdf6 and a87ac0 were created

Plain Text fields will use VARCHAR or TEXT depending on their Column Type setting (or if left to Automatic, then depending on their Max Length setting). However Email fields will **always** use a VARCHAR column:

https://github.com/craftcms/cms/blob/adb3eb97347d8628dbec88a327334b60b223ac5e/src/fields/Email.php#L50-L53

So I’m not sure how you could have ended up with an Email field that is set to a TEXT column. If you go in and resave your Email field, does it switch to VARCHAR?

**Comment by carlcs** [comment] 2021-07-27 18:16
The SQL query when using `':notempty:'` with the field parameter doesn’t include a condition for an empty string in the `WHERE` clause.

```SQL
WHERE (NOT ("content"."field_customerEmail" IS NULL))
```
 When you tried to reproduce, did you have an installation with a Postgres database? I didn’t have a chance to debug using xdebug, but I would guess something is off with this condition here.

https://github.com/craftcms/cms/blob/0440d4ec4a8304f7480fd03fcaebb720e0d7d673/src/helpers/Db.php#L511-L512

And sorry about the confusion with the column types. I’ve mixed these up in my message. My email field uses VARCHAR and my text field uses a TEXT column.

**Comment by carlcs** [comment] 2021-07-27 18:29
I’ve just updated to 3.7.6 and it fixed the problem for me. I had to resave entries in question because there no migration included.

**Comment by brandonkelly** [comment] 2021-07-28 15:57
Doh, I missed that this is for Postgres. That explains it, and was able to reproduce there. Fixed now for the next release.

**Closed** 2021-07-28 15:57 UTC
Labels: bug

**Comment by brandonkelly** [comment] 2021-07-30 00:50
Craft 3.7.7 is out now with a fix for existing values that may still be set to empty strings (or any other field types still allowing empty strings to be saved).

**Comment by carlcs** [comment] 2021-07-30 07:58
Thanks Brandon!
