### ISSUE TITLE
Yo! When adding a new field, can the default group be Default instead of the alphabetically first group?Cheers :)

### ISSUE THREAD

**Issue by mijewe** [craftcms/cms#1936] opened 2017-08-22 10:33 UTC
### Steps to reproduce

1.
2.

### Additional info

- Craft version: 2.6.2989 (Pro)
- PHP version: 7.0.19
- Database driver & version: MySQL 5.5.5-10.2.6-MariaDB
- Plugins & versions: 
    - Cachey 1.0
    - Image Resize 0.1
    - Reasons 0.2.1
    - Redirect Manager 1.9.1
    - Sitemap 1.1.3
    - Sprout Fields 1.0.0
    - Sprout Link Field 0.8.0

**Comment by brandonkelly** [comment] 2017-08-22 14:51
Duplicate of #1785 - see the discussion there.

**Closed by brandonkelly** 2017-08-22 14:51 UTC
