### ISSUE TITLE
Reference tags don't get updated after resave

### ISSUE THREAD

**Issue by steveooo9** [craftcms/cms#2338] opened 2018-01-23 15:34 UTC
### Description

It seems that a reference tag doesn't get updated or wrongly saved. See https://github.com/nystudio107/richvariables/issues/5

@khalwat says that this issue was fixed in Craft 3, so a backport of this bugfix would be great!

### Steps to reproduce

1. Insert a variable tag
2. Save
3. Save again
4. Changing the variable doesn't update the tag (in the preview or on the site)

### Additional info

- Craft version: 2.6.2983

**Comment by khalwat** [comment] 2018-01-23 15:44
I don't remember the exact commit, but somewhere along the way Brandon applied to fix that took care of this for Craft 3.x.

**Comment by brandonkelly** [comment] 2018-01-23 20:49
Yep - duplicate of #1643.

**Closed by brandonkelly** 2018-01-23 20:49 UTC

**Comment by khalwat** [comment] 2018-01-23 20:51
...but I'm not sure this was ever back-ported to be fixed in Craft 2.x, which is I think what he's hoping for?

**Comment by steveooo9** [comment] 2018-01-23 21:37
@brandonkelly I can say that it isn't fixed in v2 and should be. It's some real bug that should be there :)

**Comment by brandonkelly** [comment] 2018-01-24 18:27
It’s still a duplicate :) Re-opened the original. We’ll see if we can get it fixed for v2.
