### ISSUE TITLE
handle "author" is a system-handle, should be excluded from field-setup

### ISSUE THREAD

**Issue by igorA53** [craftcms/cms#3120] opened 2018-07-20 06:58 UTC
### Description

the field handle "author" can be used in the field-setup, but returns the internal entries-author instead of your own field-contents. It's only a minor issue though.

### Steps to reproduce

1. make field with field handle "author"
2. "entry.author" returns the entry author/user in the template 

### Additional info

- Craft version: 3.0.16
- PHP version: 7.1.12
- Database driver & version: mysql 5.0.12
- Plugins & versions:

**Comment by brandonkelly** [comment] 2018-07-20 15:02
Duplicate of #2797

**Closed by brandonkelly** 2018-07-20 15:02 UTC

**Comment by brandonkelly** [comment] 2021-06-10 23:39
For posterity, this is [resolved for Craft 3.7](https://github.com/craftcms/cms/issues/2797#issuecomment-859155102).
