### ISSUE TITLE
Project config sync fails when renaming two fields using same handle

### ISSUE THREAD

**Issue by nettum** [craftcms/cms#6050] opened 2020-05-12 06:33 UTC
### Description
Rename a fields handle used in globals, e.g. `field_a` to `field_something` and another field `field_b` to `field_a` in one project config sync will fail.

### Steps to reproduce

1. Setup a new craft project and enable project config.
2. Create two field, `field_a` and `field_b`.
3. Create a global set and add `field_a` to it.
4. Commit changes.
5. Checkout the project in a second folder and with another database (this would normally be other devs/stage/prod env).
6. Sync project config changes in second folder.
7. Go back to the original project and rename  `field_a` to `field_something`. Rename `field_b` to `field_a`. 
8. Commit changes.
9. Run git pull on second folder and try to sync project config.

This will result in the same error as #5946

Atttched change in project config that will fail: https://github.com/nettum/Craft-200512/commit/ec42f83c59c3fd02a3125283b33d8cccd3f251d5
![image](https://user-images.githubusercontent.com/798156/81645791-79218a80-942a-11ea-9452-d1ab5bbb92cb.png)

### Additional info

- Craft version: 3.4.18
- PHP version: 7.2.30
- Database driver & version: MySQL 5.7.30
- Plugins & versions: N/A

**Comment by andris-sevcenko** [comment] 2020-05-12 07:17
Yeah, this is a duplicate of #4369 and is sort-of related to the original issue.

Currently not entirely sure how to fix this automatically, since Project Config is about bringing a site from config A to config B, but this issue is about doing that in a specific order. However, that's simply not possible for Project Config in its current form, because that would require the target site to be in a state that the source site has existed in at some point, but that is not always going to be the case.

The first step (and an intermediate, sort of workable solution) is to, as pointed out in https://github.com/craftcms/cms/issues/5946#issuecomment-618441069 by @brandonkelly, run validation before applying any changes and, if any validation errors are found, simply not apply the config and list the validation errors, giving you a chance to figure out how to approach this edge case.

**Comment by brandonkelly** [comment] 2020-05-12 18:06
Sorry @nettum , I had forgotten it was already reported in #4369. Will close.

**Closed by brandonkelly** 2020-05-12 18:06 UTC
Labels: bug, severity:normal
