### ISSUE TITLE
Changing from Plaintext to Date/Time should delete db column contents prior to conversion (PDO Exception)

### ISSUE THREAD

**Issue by cherrykoda** [craftcms/cms#6862] opened 2020-09-18 17:43 UTC
### Description

When updating a field from plaintext to date/time, and there is already text in the field on some entries, an error occurs. This likely should erase the content instead.

### Steps to reproduce

1. Create a plaintext field (mine was inside a supertable field)
2. Add field to an entry
3. Populate the entry with text
4. Edit the field to be a Date/Time field

### Additional info

- Craft version: 3.5.10.1
- PHP version: 7.3.19
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Supertable 2.6.2

### Error Screenshot

![image](https://user-images.githubusercontent.com/3789834/93628317-5d1f8e00-f9b4-11ea-8c71-316749ea80a2.png)

**Comment by brandonkelly** [comment] 2020-09-18 18:13
This is a duplicate of #3605. We plan to fix it in Craft 4.

**Closed by brandonkelly** 2020-09-18 18:13 UTC
Labels: bug
