### ISSUE TITLE
Rendering issue with Large Thumbnail view mode in quick editor (2.6)

### ISSUE THREAD

**Issue by domstubbs** [craftcms/cms#2126] opened 2017-11-23 11:32 UTC
### Description

When Assets fields have the Large Thumbnails view mode enabled they overflow their row height in the quick editor. Tested in Safari & Chrome.

Thumbnail view mode:
<img width="409" alt="large-thumbnail" src="https://user-images.githubusercontent.com/717265/33170795-845a8bcc-d041-11e7-8c21-1ebb426d0ee3.png">

List view mode:
<img width="400" alt="list" src="https://user-images.githubusercontent.com/717265/33170796-8477f662-d041-11e7-9fd5-57e79b5dfbc5.png">

### Steps to reproduce

1. Configure an Assets field with the Large Thumbnails view mode
2. Attach a file to that field in any entry
3. Double-click on the entry in a list view to open the quick editor

### Additional info

- Craft version: 2.6.2997
- PHP version: N/A
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by brandonkelly** [comment] 2017-11-27 21:42
Duplicate of #1802 (fixed for the next release via 69b12e46f9371398da9433bd275e2415ad83b893).

**Closed by brandonkelly** 2017-11-27 21:42 UTC

**Comment by domstubbs** [comment] 2017-11-28 10:44
Thanks - sorry for the duplicate.
