### ISSUE TITLE
[4.x]: Entry condition not showing all options

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#13881] opened 2023-10-27 09:37 UTC
### Description
I have 2 fields with the same Title but a different handle
1. header options: `header_options`: dropdown field with 3 options.
2. header options: `header_options_page` dropdown field with 2 options.

Issue number 1: When doing the entry conditions there is no way for me to know when I have to select a field to add a rule on what handle I'm making the rule for (since only the title is shown).

Issue number 2: Adding `only header_options_page` to the Field layout, I can't select any rules for that field. I only see 1 option in the Entry conditions wit the title `header options`. (which is the wrong one). 

### Expected behavior
1. Having also the handle exposed when selecting entry conditions would make it a lot easier to know what field you're dealing with
1. I would expect only to be able to set Entry condition options for fields within the field layout.

### Craft CMS version

4.5.9

### Installed plugins and versions

-

**Comment by i-just** [comment] 2023-10-27 12:42
Hi, thanks for reaching out! 

It sounds like a duplicate of https://github.com/craftcms/cms/issues/13296, and a PR has been raised. I’ll re-request a review on it now. 

I’m going to close this one, but you can follow along on #13296.

**Closed by i-just** 2023-10-27 12:42 UTC
Labels: bug, craft4

**Comment by brandonkelly** [comment] 2024-01-09 19:14
This is resolved in Craft 4.6.0 – see https://github.com/craftcms/cms/issues/13296#issuecomment-1883633589.
