### ISSUE TITLE
CLI: PHP Deprecated Warning on update

### ISSUE THREAD

**Issue by Jan10** [craftcms/cms#7250] opened 2020-12-11 08:02 UTC
### Description

When I try to update Craft CMS via CLI:

```
./craft update all
PHP Deprecated Warning 'yii\base\ErrorException' with message 'Method ReflectionParameter::isArray() is deprecated'

in /Users/jan/Sites/xxxxxx/vendor/yiisoft/yii2/console/Controller.php:214

Stack trace:
#0 /Users/jan/Sites/xxxxxx/vendor/yiisoft/yii2/console/Controller.php(214): yii\base\ErrorHandler->handleError(8192, 'Method Reflecti...', '/Users/jan/Site...', 214)
#1 /Users/jan/Sites/xxxxxx/vendor/yiisoft/yii2/base/InlineAction.php(51): yii\console\Controller->bindActionParams(Object(yii\base\InlineAction), Array)
#2 /Users/jan/Sites/xxxxxx/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#3 /Users/jan/Sites/xxxxxx/vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction('', Array)
#4 /Users/jan/Sites/xxxxxx/vendor/craftcms/cms/src/console/Controller.php(188): yii\console\Controller->runAction('', Array)
#5 /Users/jan/Sites/xxxxxx/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
#6 /Users/jan/Sites/xxxxxx/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('update', Array)
#7 /Users/jan/Sites/xxxxxx/vendor/craftcms/cms/src/console/Application.php(88): yii\console\Application->runAction('update', Array)
#8 /Users/jan/Sites/xxxxxx/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('update', Array)
#9 /Users/jan/Sites/xxxxxx/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /Users/jan/Sites/xxxxxx/craft(23): yii\base\Application->run()
#11 {main}

nitro version
nitro 1.1.1

You are on the latest version of Nitro!

nitro info
Nitro installed, ready for something incredible at 192.168.64.2.

Add a project with "nitro add <directory>".

Server Information
-------------------------
IP address: 192.168.64.2
PHP version: 7.4
```

### Steps to reproduce

1. Open CLI and fire `./craft update all`

### Additional info

- Craft version: 3.5.16
- PHP version: 7.4

**Comment by brandonkelly** [comment] 2020-12-12 23:50
This is a duplicate of https://github.com/yiisoft/yii2/issues/18297, which was fixed in Yii 2.0.39. It’s a PHP 8 deprecation error. I know you said you’re on PHP 7.4 but perhaps the CLI is running PHP 8 if that’s what you started the machine with, or something. Try running `php -V` and see what that spits out.

Craft will be pulling in Yii 2.0.39 / 40 in 3.6.

**Closed by brandonkelly** 2020-12-12 23:50 UTC
Labels: bug
