### ISSUE TITLE
[3.4] Preview on assets opens two different types of preview

### ISSUE THREAD

**Issue by aelvan** [craftcms/cms#5517] opened 2020-01-28 19:47 UTC
### Description

When clicking preview from the edit asset page, two types of previews are opened on top of each other; one old-school image-only preview, and one full live preview.

![image](https://user-images.githubusercontent.com/2675644/73299277-2d4a2d00-420f-11ea-86b0-396dec6c29a2.png)

Also, there're some random glitches where the image is offset inside the old-school preview as shown above, but I'm guessing this is the one that's redundant now, so..

### Steps to reproduce

1. Edit an image asset.
2. Click preview from the action button bar.
3. Two previews open on top of each other, randomly overlaying each other. Both has to be closed to exit.

### Additional info

- Craft version: Craft 3.4
- PHP version: PHP 7.3.8
- Database driver & version: Mysql 5.7.6

**Comment by andris-sevcenko** [comment] 2020-01-28 20:05
What browser are you using and do you have any plugins installed? I'm unable to reproduce this.

**Comment by aelvan** [comment] 2020-01-28 20:14
That was Chrome 79 on OSX. No plugins installed. Also tested on Firefox 71 and Safari 13.0.4 now, same behaviour.

**Comment by Mosnar** [comment] 2020-01-28 20:26
@aelvan Safe to assume you've cleared all your CMS caches? Particularly cpresources

**Comment by aelvan** [comment] 2020-01-28 21:01
@Mosnar Tried again now after clearing all caches. Still the same behaviour. This is on a fresh install of 3.4, I've only installed it, set up a couple of sections, fields, an asset source, and uploaded some images.

**Comment by aelvan** [comment] 2020-01-28 21:04
Also, the "Preview" button on the preview image to the right in the edit page, doesn't do anything when I click it. Maybe related?

![image](https://user-images.githubusercontent.com/2675644/73305285-15c47180-421a-11ea-998a-ee41a5350adc.png)

**Comment by mmikkel** [comment] 2020-01-28 21:21
I'm seeing exactly the same behaviour as @aelvan on a fresh 3.4.0.1 install, with no plugins installed. The Preview button at the top opens up both the new Live Preview and the legacy preview (although it varies which of them is on top); the Preview button over the image thumbnail does nothing when clicked.

Tested in Google 79 and Firefox 72 on Mac (OSX Mojave).

**Comment by andris-sevcenko** [comment] 2020-01-29 08:55
Any chance either of you could share access to a site where it's reproducible? If so, can you please shoot an email to support@craftcms.com and reference this issue?

**Comment by wsydney76** [comment] 2020-01-29 09:12
Can confirm this behavior for SOLO edition, when upgraded to PRO, everything works fine.

/Mel

**Comment by andris-sevcenko** [comment] 2020-01-29 09:15
@wsydney76 Whoa. That changes everything. Thank you, able to reproduce!

**Comment by andris-sevcenko** [comment] 2020-01-30 12:22
Welp, that was amusing. Thanks for the help, everyone! Just pushed a fix for the next 3.4 release!

**Closed** 2020-01-30 12:22 UTC
Labels: bug, severity:minor

**Comment by brandonkelly** [comment] 2020-01-31 23:48
Craft 3.4.2 is out now with this fix.
