### ISSUE TITLE
Post Date day and month swap on save

### ISSUE THREAD

**Issue by mrjohnsly** [craftcms/cms#1495] opened 2017-03-11 20:13 UTC
### Description

When creating an entry or editing the post date of an entry, the day and month swap around on save. For example if I set the post date to 01/02/17 on save this swaps to 02/01/17.

This only happens on my local install and not on the server.

### Steps to reproduce

1. Create an entry
2. Set the date
3. Save the entry

### Additional info

**Local Setup**
- Craft version: Craft Personal 3.0.0-beta.7
- PHP version: 7.1.1
- Database driver & version: MySQL 5.7.17
- Plugins & versions: No plugins

**Server Setup**
- Craft version: Craft Personal 3.0.0-beta.7
- PHP version: 7.1.0
- Database driver & version: MySQL 5.7.16
- Plugins & versions: No plugins

**Comment by takobell** [comment] 2017-03-12 04:56
What's the locale/language you're using for the logged in account when you see this?

**Comment by mrjohnsly** [comment] 2017-03-13 07:17
Apologies. While checking what the locale was set to I noticed Intl extension wasn't installed.

Fixing that has fixed the bug.

**Comment by takobell** [comment] 2017-03-13 17:14
Still sounds like a bug with the fallback data we're using if intl isn't installed. What locale did you see it in?

**Comment by gui-gui** [comment] 2017-04-17 23:34
I have experienced the same error ( Language/locale : pt ). 

On top of the error reported above, I have also noticed that if i resave the entry, the entry publish date is being set to 2018.

**Steps to reproduce**

Create and Save Entry (in my test: april 17th 2017)
Open it again and hit Save again
Entry publish date is set to future (in my test: may 4th 2018)

**Comment by takobell** [comment] 2017-04-18 22:02
@gui-gui Having a hard time reproducing this. You using the latest Craft 3 beta release (12)? Does it happen across different browsers? What about the MySQL version?

**Comment by gui-gui** [comment] 2017-04-18 22:21
Hey @takobell, it happens, at least, with chrome and firefox, did not test in any other browser.

**Application Info**

PHP version	7.0.9
Database driver & version	MySQL 5.5.5-10.1.16-MariaDB
Image driver & version	GD 7.0.9
Craft edition & version	Craft Personal 3.0.0-beta.12
Yii version	2.0.11.2

it seems that i do not have Intl extension installed. Since it is marked as "passed with warning".

**Comment by takobell** [comment] 2017-04-19 00:16
@gui-gui super weird.  I tried disabling the intl extension on the latest Chrome and FF using same PHP version and MySQL and can't reproduce using `pt`. Tried setting Craft timezone to Brazilian in case that affected anything.  Shooting in the dark, but maybe it has something to do with the language the browser is set to?

**Closed** 2017-05-08 13:21 UTC
Labels: bug, severity: minor
