### ISSUE TITLE
Entries page ordering and columns should be configured using project.yaml

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#4980] opened 2019-09-24 09:07 UTC
### Description
When viewing the Entries section of Craft, you have control over the ordering and grouping of your sections, as well as the field columns for each section.

It would be really helpful if this information was written to `project.yaml`

**Comment by brandonkelly** [comment] 2019-09-25 11:18
Duplicate of #3658.

**Closed by brandonkelly** 2019-09-25 11:18 UTC
