### ISSUE TITLE
[5.x]: Query Aborted Exception in query with relatedTo({sourceElement...})

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14552] opened 2024-03-08 08:20 UTC
### Description

Queries like this worked fine in Craft 4:

```twig
{% set query = craft.entries
    .section('person')
    .relatedTo({sourceElement: 45721, field: 'cast'})
    .orderBy('lastName, firstName') %}

{% for entry in query.all %}
    {{ entry.link }}<br>
{% endfor %}
```

or 

```twig
{% set query = craft.assets
    .volume('fotograf')
    .relatedTo({sourceElement: 57579, field: 'photoImages.images' })
%}

{{ query.count() }}
```

In Craft 5 they return 0 results.

If `{{ dump(query.rawSql) }}` is called, there is this error:

![image](https://github.com/craftcms/cms/assets/60010597/4fcdf881-31e7-4603-ad2a-9adc225efe00)

### Steps to reproduce

Create a content model like this:

Section 'film'
-> Matrix field 'cast'
    -> Entry Type 'role'
        -> Entries field 'person' pointing to section 'person'

Query for all 'person' entries related to 'film' like above
### Craft CMS version

5.0.x-dev as Craft Solo 5.0.0-beta.6

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.33

### Installed plugins and versions

-

**Comment by i-just** [comment] 2024-03-11 14:48
Hi, thanks for reporting! I raised a PR for this.

**Comment by brandonkelly** [comment] 2024-03-14 13:37
That’s now fixed for the next release. Thanks again!

You can update early by changing your `craftcms/cms` requirement in composer.json to `5.0.x-dev as 5.0.0-beta.7` and running `composer update`.

**Closed by brandonkelly** 2024-03-14 13:37 UTC
Labels: bug

**Comment by brandonkelly** [comment] 2024-03-15 21:53
Craft 5.0.0-beta.8 is out now with that fix.

**Comment by dgsiegel** [comment] 2024-03-19 09:55
@brandonkelly @i-just this seems to apply to Craft 4.8.3 as well, at least I am getting the same error when a search doesn't return any results. 4.8.1 works fine, so I am suspecting https://github.com/craftcms/cms/commit/01a1638395f5e2518c854f973d9bc4adb560afa2 to be the culprit.

**Comment by brandonkelly** [comment] 2024-03-19 15:57
@dgsiegel Follewed up at #14623. Not going to be related to this bug, which was caused by a Craft 5-specific change.
