### ISSUE TITLE
Issue saving Phone Number field in 3.6.10

### ISSUE THREAD

**Issue by rynpsc** [craftcms/cms#7671] opened 2021-03-11 08:39 UTC
Something has changed in Craft 3.6.10 that is resulting in my plugin not saving the field when creating a new entry and then publishing the draft. On publishing the field value is cleared, however if you "Save Draft" instead of publishing everything works or edit an existing entry and save.

I can't see anything in the changelog that would explain it.

### Steps to reproduce

1. Create and add the Phone Number field to a section
2. Create a new entry, entering a valid phone number and then "Publish Draft". Page will reload but the field value has disappeared.
3. Create another entry but this time save the draft, this time the value is saved.

### Additional info

- Craft version: 3.6.10
- PHP version: 7.4
- Database driver & version: MySQL 5.7.32
- Plugins & versions: Phone Number 1.4.2

See here for original issue https://github.com/rynpsc/craft-phone-number/issues/12

**Comment by brandonkelly** [comment] 2021-03-12 00:38
Sorry about that, @rynpsc. This was caused by a831e6b4cca35da652f195f33e46c32799a194ab, which fixed a bug where field values that were normalized to objects weren’t getting cloned when elements were duplicated via `craft\services\Elements::duplicateElement()`. That exposed the bug in your plugin because your field type’s `normalizeValue()` method isn’t checking to see if the incoming value is already a `PhoneNumberModel` object. I’ve PR’d a fix at https://github.com/rynpsc/craft-phone-number/pull/13.

(This is definitely a bug in your own plugin, though, not Craft, as this isn’t the first instance where a pre-normalized value is passed into `normalizeValue()`. Another scenario where this same bug would occur is when propagating an element value over to a new site, on multi-site installs, if the Phone Number field wasn’t marked as translatable.)

**Closed by brandonkelly** 2021-03-12 00:38 UTC
Labels: bug

**Comment by rynpsc** [comment] 2021-03-12 08:15
Oops. Thanks for the clarification Brandon.
