### ISSUE TITLE
Quick Field Add-on

### ISSUE THREAD

**Issue by nexflo** [craftcms/cms#6734] opened 2020-08-27 07:37 UTC
In Craft there used to be a "Quick Field" plugin which allowed one, to create new fields directly inside the Section Panels. (it basically just opened the create new field panel in a modal)

With the new Section Updates, this seems like it should really come back...so one doesnt have to jump back all the time..into the fields section. Little update -> huge impact.

**Comment by brandonkelly** [comment] 2020-08-27 21:07
This is a duplicate of #2685 – which you also submitted :)

It’s on deck for Craft 4 (currently in development).

**Closed by brandonkelly** 2020-08-27 21:07 UTC
Labels: enhancement
