### ISSUE TITLE
Mismatched element index fields

### ISSUE THREAD

**Issue by KatieMFritz** [craftcms/cms#4514] opened 2019-07-10 14:48 UTC
### Description

In the element index display, I'm seeing mismatched fields in the display and sort options. I see fields that don't apply to the selected section, and I don't see all the fields that ARE included in the selected section.

I noticed this in 3.1.33 and 3.1.34 and I just updated to 3.2.0 and it's still happening.

Possibly related to #4314.

### Additional info

- Craft version: Craft Pro 3.2.0
- PHP version: 7.3.3
- Database driver & version: PostgreSQL 10.9
- Plugins & versions: too many plugins... 🙀 This might be part of my problem.

![Screen Shot 2019-07-10 at 10 46 44 AM](https://user-images.githubusercontent.com/7085184/60979095-21912a80-a300-11e9-9938-79d065ac81a8.png)
![Screen Shot 2019-07-10 at 10 46 52 AM](https://user-images.githubusercontent.com/7085184/60979102-23f38480-a300-11e9-989d-9d95a0fd215b.png)

**Comment by brandonkelly** [comment] 2019-07-11 18:52
So yeah this is basically a duplicate of #4314. Issue is that currently table attributes and sort attributes are defined globally for the element type, and so all fields that are currently associated with the element type are going to be included (if they have opted into being previewable/sortable).

We will be revisiting how all this works in Craft 4.

**Closed by brandonkelly** 2019-07-11 18:52 UTC

**Comment by brandonkelly** [comment] 2019-07-11 18:54
Just noticed this is exactly 200 issues later than the other one, kinda cool!

**Comment by KatieMFritz** [comment] 2019-07-12 14:40
By element type, you mean like channel or structure or single? 

If that's the case, I get why irrelevant fields are showing up. But then why don't I have access to all fields?

Any tips for managing this in the meantime?

**Comment by brandonkelly** [comment] 2019-07-14 16:51
By element type I mean entires, categories, assets, etc.

Only field types that implement `PreviewableFieldInterface` will be shown as table column options, and only field types that implement `SortableFieldInterface` will be shown as sort options. So it’s expected that some fields will be missing in each of those contexts.

**Comment by khalwat** [comment] 2019-07-31 13:10
This could probably be fixed one of two ways:

1. Have a separate generated behavior for each Section rather than just one `ContentBehavior.php` file
2. Filter what is displayed in the sort options to fields that are associated with the section only, rather than all fields available on the element

**Comment by brandonkelly** [comment] 2020-05-20 23:42
For posterity, this has been fixed for Craft 3.5. See https://github.com/craftcms/cms/issues/4314#issuecomment-631793986 for details.
