### ISSUE TITLE
Fields en layout presets

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#954] opened 2017-01-31 03:45 UTC
> Created by: Johannes Lamers (johanneslamers@gmail.com) on 2015/03/10 17:03:25 +0000
> Votes at time of UserVoice import: 8

-----------------------------------

Don't know if this is best for a core feature or a plugin:

If I start with a project I always have some basic fields and field layouts setup. SEO fields, basic image fields (alt text, copyright etc), some standard matrix blocks etc. Would it be nice to save and download the fields + layouts as a preset to use it on your next project? Just import the preset file and you're done!

**Comment by brandonkelly** [comment] 2018-02-25 22:36
duplicate of #1429

**Closed by brandonkelly** 2018-02-25 22:36 UTC
Labels: feature
