### ISSUE TITLE
Craft Update error

### ISSUE THREAD

**Issue by mccombs** [craftcms/cms#1885] opened 2017-07-29 20:09 UTC
### Description

Similar to issue #1883 - Craft says there is an update available (22 - 23). When I click the **update** button, it gives me an error saying

> It looks like someone is currently performing a system update.

The url is set to `/admin/update?install=craft:3.0.0-beta.23`

I can still use the admin panel and everything works as normal, I just can't update to the most current version.

### Steps to reproduce

1. Update from Craft CMS 3.0.0-beta.22 to 3.0.0-beta.23

### Additional info

- Craft version: Craft CMS 3.0.0-beta.22
- PHP version: 7.0.15
- Database driver & version: mysql 5.6.35
- Plugins & versions: My custom dev plugin and Store Hours, Redirect and Inline

**Comment by putyourlightson** [comment] 2017-07-29 22:09
Setting the `maintenance` column to `0` in the `info` table solved this for me. Definitely a bug though.

**Comment by brandonkelly** [comment] 2017-07-31 18:31
Duplicate of #1883

**Closed by brandonkelly** 2017-07-31 18:31 UTC

**Comment by herrajon** [comment] 2018-08-30 17:19
An open composer.json can cause this.
