### ISSUE TITLE
limit the number of versions that are saved for channel entries

### ISSUE THREAD

**Issue by fractorr** [craftcms/cms#1909] opened 2017-08-09 16:18 UTC
### Description
It would be great  to be able to limit the number of versions that are saved for a particular channel.  Even if it was on a global level would work but on a channel by channel basis would be fantastic.  Here is why,  on a personal project I am building most channels are pretty light but one channel has a field that has about 300KB of data in a textarea and there is a 100+ entries in that channel that get updated occasionally.  Being able to limit this particular channel would be great to keep the database from bloating.

**Comment by brandonkelly** [comment] 2019-05-17 22:43
Duplicate of #926

**Closed by brandonkelly** 2019-05-17 22:43 UTC
Labels: enhancement
