### ISSUE TITLE
Hover over CP field name label to reveal the handle

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#951] opened 2017-01-31 03:45 UTC
> Created by: Damon (damonjentree@gmail.com) on 2015/08/10 19:25:29 +0000
> Votes at time of UserVoice import: 8

-----------------------------------

If/when I hover over the CP name of an input, the handle of that input would show. This could be as "simple" as putting the handle in the title attribute. 

For example, if I had a field called "Main Content" in the entry field layout, when I hovered over that input label, "mainContent" would show. I realize 9/10 times it's a 1:1 but a feature like this would be handy instead of having to click back into the fields section to look up the handle for a given input field.

**Comment by brandonkelly** [comment] 2018-02-25 22:37
duplicate of #2360

**Closed by brandonkelly** 2018-02-25 22:37 UTC
Labels: feature
