### ISSUE TITLE
[4.3.1]:  Sorting is broken in the entries index when a search is performed

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#12258] opened 2022-11-03 17:28 UTC
### Description
Sorting is broken in the entries index when a search is performed.

### Steps to reproduce

1. Go to the entries index page, in any section. 
2. Perform a search that produces more than one result. 
3. Try to sort the results by any column.

### Expected behavior
The results should be sorted accordingly.

### Actual behavior
A spinner is briefly displayed in the bottom bar, but the results remain in the sorting order that was selected before the search.

### Craft CMS version

4.3.1

### Installed plugins and versions

-

**Comment by brianjhanson** [comment] 2022-11-03 17:30
This looks like a duplicate of #12256, you can follow along there for progress.

**Closed by brianjhanson** 2022-11-03 17:30 UTC
Labels: bug, craft4
