### ISSUE TITLE
Disabled entries in entry field within Matrix still shown

### ISSUE THREAD

**Issue by TomDeSmet** [craftcms/cms#4865] opened 2019-08-30 13:27 UTC
### Description
I have a 'not translatable' matrix field. So every block I add is added to all sites.
In one of those blocks I have a content field which links to an entry.
That entry is disabled for all but one site.
When I retrieve that entry in my template, the entry is shown in all sites in the language of the site it is enabled for.

When I check this entries `enabledForSite` property, it returns `1`.
When i check its `status` property it returns `live`.
When I check its `site` property, it returns the site where it is enabled in.

I expect this article to be hidden when not enabled or that at least I can check for it with `enabledForSite`. It should return `0` for all the sites except the one it is enabled for.

### Steps to reproduce

1. Create an entry A in multiple sits and disable it in all but one.
2. Create a matrix field in another entry with a content field inside and link to that entry.
3. Show that entry in your template from the matrix block.

### Additional info

- Craft version: 3.2.10
- PHP version: 7.2
- Database driver & version: MySQL

### **UPDATE**
When I fetch the article by passing the `currentSite` it is solved. But it seems to me that should not be necessary.
`{% set article = self.newsArticle.site(currentSite).one() %}`

**Comment by brandonkelly** [comment] 2019-08-30 14:28
This is a duplicate of #4751, and we changed the behavior back to what you expect in v3.3.0 :)

**Closed by brandonkelly** 2019-08-30 14:28 UTC
