### ISSUE TITLE
[4.x]: Problems with custom smtp settings

### ISSUE THREAD

**Issue by JulieVelghe** [craftcms/cms#13413] opened 2023-07-11 08:53 UTC
### Description
I have a site (dutch) with 2 subsites, being french and german.
The client wants the notification mails being send from formie, to come from different email-addresses, depending on the site.
I've made 3 separate forms for the 3 languages.
I use environment variables and try to set them in my app.php file like so:

'mailer' => function() {
            // Get the stored email settings
            $settings = craft\helpers\App::mailSettings();

            // Override the transport adapter settings
            $settings->fromName = Craft::$app->sites->getCurrentSite()->name;

            $siteHandle = Craft::$app->getSites()->getCurrentSite()->handle;

            if ($siteHandle === 'fr') {
                $settings->transportType = craft\mail\transportadapters\Smtp::class;
                $settings->fromEmail = getenv('SYSTEM_EMAIL_FR');
                $settings->transportSettings = [
                    'host' => getenv('EMAIL_HOSTNAME'),
                    'port' => getenv('EMAIL_PORT'),
                    'useAuthentication' => getenv('EMAIL_VERIFICATION'),
                    'encryptionMethod' => getenv('EMAIL_ENCRYPTION_METHOD'),
                    'username' => getenv('EMAIL_USERNAME_FR'),
                    'password' => getenv('EMAIL_PASSWORD_FR'),
                    'timeout' => 10,
                ];
            } else if ($siteHandle === 'de'){
                $settings->transportType = craft\mail\transportadapters\Smtp::class;
                $settings->fromEmail = getenv('SYSTEM_EMAIL_DE');
                $settings->transportSettings = [
                    'host' => getenv('EMAIL_HOSTNAME'),
                    'port' => getenv('EMAIL_PORT'),
                    'useAuthentication' => getenv('EMAIL_VERIFICATION'),
                    'encryptionMethod' => getenv('EMAIL_ENCRYPTION_METHOD'),
                    'username' => getenv('EMAIL_USERNAME_DE'),
                    'password' => getenv('EMAIL_PASSWORD_DE'),
                    'timeout' => 10,
                ];
            }

However, with this code, when I fill in the french form, I get an error from formie that the notifications cannot be send. Are these settings correctly done?

### Steps to reproduce

1.

### Craft CMS version

4.4.13

### PHP version

8.1

### Installed plugins and versions

-
formie: 2.0.30

**Comment by JulieVelghe** [comment] 2023-07-11 15:48
I'm not getting a ton of info in my logs. Below is what is in my queue log:

#17 {main} {"memory":35759360,"exception":"[object] (Exception(code: 0): Failed to send notification email: {\"error\":\"Notification email “Courriel de confirmation” could not be sent for submission “15565”. The mailer service failed to send the notification: “”.\"}. at C:\\Users\\julie\\Documents\\CabinetC\\Repos\\sociaalverwarmingsfonds\\vendor\\verbb\\formie\\src\\jobs\\SendNotification.php:76)"} 

The formie log is more of the same. Is there a way for me to get more precise logging? To see if there is a problem with the mailbox? 

When I tried the dutch mailbox (which is the default website language), I used php craft mailer/test from within phpstorm to test, and that worked, but I cannot use that for my french and german version.

The fact that I get an error does mean that the code gets inside that 'if'-case, because if I put that in comments, the notification mails do get send, albeit using the standard dutch mailbox.

**Comment by JulieVelghe** [comment] 2023-07-11 16:13
I've just tried to comment out the if-case, and use the french mailbox, and that works. So the problem isn't the french mailbox itself.
I do notice, I have an env variable 'SYSTEM_EMAIL', is that one missing from my code? (Or is that the settings->fromEmail ?)

**Comment by JulieVelghe** [comment] 2023-07-11 16:28
I've also removed the if-case, so the settings would always try to override, but still error.

**Comment by i-just** [comment] 2023-07-12 07:31
The error is triggered here: https://github.com/verbb/formie/blob/craft-4/src/services/Emails.php#L387-L402.

More info about it could still be in the `queue.log` - a few lines above the stack trace. When I deliberately triggered the same error message, this is what was in my `queue.log`:
<img width="1241" alt="Screenshot 2023-07-12 at 08 11 40" src="https://github.com/craftcms/cms/assets/4500340/9d740514-dd0b-47f1-9c5f-143b4f7ea07b">

At the bottom, there’s a line that looks like what you’ve pasted, and at the top, there’s a clue as to why the send failed.

The first step should be verifying that you can send an email with each of the 3 sets of details. Go to Control Panel > Settings > Email; change the values to ones for the NL site, click “Test”, and see if you receive the test email; then do the same for FR and DE values.

**Comment by JulieVelghe** [comment] 2023-07-12 07:59
ok, so,
I've slightly changed my code, now I only have 1 if, namely, if the handle is french. (Just to tackle 1 language at a time :p)
I've found some more info as to why it doesn't work:

2023-07-12 07:40:21 [queue.ERROR] [yii\symfonymailer\Mailer::sendMessage] Expected response code "250" but got code "554", with message "554 5.2.252 SendAsDenied; website@fondschauffage.be not allowed to send as website@verwarmingsfonds.be

so somehow, the dutch emailadress is still being used.
When I look in my notifications in Formie, the from-email is there put as 'system-email'.  
If a change that to a fixed email address, being the french one, it works as intended.

It seems to me that the following code : $settings->fromEmail = getenv('SYSTEM_EMAIL_FR');
doesn't change the sender address as I thought it would. I expected that code to override the system email, so that when I would use the system email in my notifications, that would be overriden by whatever I put in app.php in that line of code.

**Comment by i-just** [comment] 2023-07-12 08:11
> so somehow, the dutch emailadress is still being used.
When I look in my notifications in Formie, the from-email is there put as 'system-email'.
If a change that to a fixed email address, being the french one, it works as intended.

Yes. To change `fromEmail` and `fromName` for Formie notifications, you need to do it via Form > Email Notifications > [your notification] > Advanced (I mentioned it in my first reply, but with the amount of info in there, it was easy to miss). 

It’s because of this bit of code: https://github.com/verbb/formie/blob/craft-4/src/services/Emails.php#L80-L92.

For any other emails (e.g. system emails), you need to overwrite them in `app.php`, but `fromEmail` and `fromName` are “special” when it comes to Formie, and it will ignore those 2 parameters. That’s why the Dutch email address is still being used.

(It will respect the adapter changes made via `app.php`.)

**Comment by i-just** [comment] 2023-09-14 06:35
I’m going to close this now, but if you run into any further issues, please feel free to get in touch again.

**Closed by i-just** 2023-09-14 06:35 UTC
Labels: bug, craft4
