### ISSUE TITLE
Regenerate admin pwd from CLI

### ISSUE THREAD

**Issue by mathias-aa** [craftcms/cms#7359] opened 2021-01-07 11:17 UTC
### Description
It would be very handy to be able to regenerate the admin pwd from CLI
In my dev environnement i often miss it and no sendmail available so ... i must reinstall craft from scratch

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.5.11.1 (Pro)
- PHP version: 7.2.34
- OS version: Linux 4.18.0-147.3.1.el7h.lve.1.x86_64
- Database driver & version: MySQL 10.3.27
- Image driver & version: Imagick 3.4.4 (ImageMagick 7.0.10-10)
- Plugins & versions: 
    - Redactor 2.8.1

**Comment by brandonkelly** [comment] 2021-01-11 23:45
This is a duplicate of #7067, and we’ve actually already added a new `users/set-password` console command for Craft 3.6.



> In my dev environnement i often miss it and no sendmail available so ... i must reinstall craft from scratch

You could instead just change the `password` value in the `users` table to:

```
$2a$13$5j8bSRoKQZipjtIg6FXWR.kGRR3UfCL.QeMIt2yTRH1.hCNHLQKtq
```

Then login using the password “`password`”.

**Closed by brandonkelly** 2021-01-11 23:45 UTC
Labels: enhancement, user management :innocent:
