### ISSUE TITLE
[5.x]: Invalid Configuration , Invalid owner ID when upgrading to 5.5.1.1

### ISSUE THREAD

**Issue by AmsalSugihan** [craftcms/cms#16144] opened 2024-11-19 03:55 UTC
### Description

Upgrading to 5.5.1.1 throws a Invalid Configuration / Invalid owner ID error when save an entry that have nested matrix.

### Steps to reproduce

1. Run composer update all to update to 5.5.1.1
2. Open the site, or try to edit and save any entry that have any nested matrix field.

### Expected behavior
Normal Saving entry

### Craft CMS version

5.5.1.1

### Installed plugins and versions

-

**Comment by i-just** [comment] 2024-11-19 10:55
Hi, thanks for getting in touch! I’m not able to reproduce that. Could you please share a full stack trace for this error?

**Comment by mattwardcc** [comment] 2024-11-20 01:34
I'm experiencing something very similar. It appears to be only happening on Matrix blocks where the `View Mode` option had been set to Cards. 

When I try to save the page I get this error:

```
Invalid Configuration – [yii\base\InvalidConfigException](https://www.yiiframework.com/doc-2.0/yii-base-invalidconfigexception.html)
Invalid owner ID: 410
```

I was getting something similar when viewing the page until I converted all my Matrix field to inline-editable blocks. This at lest allowed me to see the entries in the editor. Just can't save them.

The initial part of the stack trace is

```
1. in /app/vendor/craftcms/cms/src/base/NestedElementTrait.phpat line 162
            if (!$primaryOwnerId) {
                return null;
            }
 
            $this->_primaryOwner = Craft::$app->getElements()->getElementById($primaryOwnerId, null, null, [
                'trashed' => null,
                'preferSites' => [$this->siteId],
            ]) ?? false;
            if (!$this->_primaryOwner) {
                throw new InvalidConfigException("Invalid owner ID: $primaryOwnerId");
            }
        }
 
        return $this->_primaryOwner ?: null;
    }
 
    /**
     * @inheritdoc
     */
2. in /app/vendor/craftcms/cms/src/base/NestedElementTrait.php at line 207– craft\elements\Entry::getPrimaryOwner()
            if (!$ownerId) {
                return null;
            }
 
            // If ownerId and primaryOwnerId are the same, return the primary owner
            if ($ownerId === $this->getPrimaryOwnerId()) {
                return $this->getPrimaryOwner();
            }
 
            $this->_owner = Craft::$app->getElements()->getElementById($ownerId, null, $this->siteId, [
                'trashed' => null,
            ]) ?? false;
            if (!$this->_owner) {
3. in /app/vendor/craftcms/cms/src/base/NestedElementTrait.php at line 239– craft\elements\Entry::getOwner()
    public function getField(): ?ElementContainerFieldInterface
    {
        if (!isset($this->fieldId)) {
            return null;
        }
 
        $field = $this->getOwner()?->getFieldLayout()->getFieldById($this->fieldId)
            ?? Craft::$app->getFields()->getFieldById($this->fieldId);
 
        if (!$field instanceof ElementContainerFieldInterface) {
            throw new InvalidConfigException("Invalid field ID: $this->fieldId");
        }
 
4. in /app/vendor/craftcms/cms/src/elements/Entry.php at line 1022– craft\elements\Entry::getField()
    /**
     * @inheritdoc
     */
    public function getSupportedSites(): array
    {
        if (isset($this->fieldId)) {
            return $this->getField()->getSupportedSitesForElement($this);
        }
 
        if (!isset($this->sectionId)) {
            throw new InvalidConfigException('Either `sectionId` or `fieldId` + `ownerId` must be set on the entry.');
        }
```

Also, when I try to resave all entries via the command line, I get errors like:

```
[893/1186] Resaving Entry Title (84) ... error: Skipped resaving Into the Underways (84) due to an error obtaining its root element: Invalid owner ID: 5
```

I suspect this is tied to the updates in 5.5.0 to allow cards to save as provisional drafts.

**Comment by yoannisj** [comment] 2024-11-20 15:47
I am experiencing the same error in **Craft v5.5.1.1** and in **Craft v5.5.2**. Here is the full stack trace of the error that gets thrown when saving the owner entry:

```
2024-11-20 16:43:00 [web.ERROR] [yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid owner ID: 3365 in /var/www/html/vendor/craftcms/cms/src/base/NestedElementTrait.php:162
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/base/NestedElementTrait.php(207): craft\elements\Entry->getPrimaryOwner()
#1 /var/www/html/vendor/craftcms/cms/src/base/NestedElementTrait.php(239): craft\elements\Entry->getOwner()
#2 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1143): craft\elements\Entry->getField()
#3 /var/www/html/vendor/craftcms/cms/src/helpers/ElementHelper.php(133): craft\elements\Entry->getUriFormat()
#4 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1342): craft\helpers\ElementHelper::setUniqueUri()
#5 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1976): craft\services\Elements->setElementUri()
#6 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1222): craft\services\Elements->craft\services\{closure}()
#7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1878): craft\services\Elements->ensureBulkOp()
#8 /var/www/html/vendor/craftcms/cms/src/services/Revisions.php(164): craft\services\Elements->duplicateElement()
#9 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(1123): craft\services\Revisions->createRevision()
#10 /var/www/html/vendor/craftcms/cms/src/elements/NestedElementManager.php(664): craft\elements\NestedElementManager->createRevisions()
#11 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(1301): craft\elements\NestedElementManager->maintainNestedElements()
#12 /var/www/html/vendor/craftcms/cms/src/base/Element.php(6180): craft\fields\Matrix->afterElementPropagate()
#13 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(2716): craft\base\Element->afterPropagate()
#14 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2008): craft\elements\Entry->afterPropagate()
#15 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1222): craft\services\Elements->craft\services\{closure}()
#16 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1878): craft\services\Elements->ensureBulkOp()
#17 /var/www/html/vendor/craftcms/cms/src/services/Revisions.php(164): craft\services\Elements->duplicateElement()
#18 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(2720): craft\services\Revisions->createRevision()
#19 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(2008): craft\elements\Entry->afterPropagate()
#20 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1222): craft\services\Elements->craft\services\{closure}()
#21 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1878): craft\services\Elements->ensureBulkOp()
#22 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1507): craft\services\Elements->duplicateElement()
#23 /var/www/html/vendor/craftcms/cms/src/services/Drafts.php(322): craft\services\Elements->updateCanonicalElement()
#24 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(1853): craft\services\Drafts->applyDraft()
#25 [internal function]: craft\controllers\ElementsController->actionApplyDraft()
#26 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#27 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#28 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#29 /var/www/html/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction()
#30 /var/www/html/vendor/craftcms/cms/src/web/Application.php(649): craft\web\Application->runAction()
#31 /var/www/html/vendor/craftcms/cms/src/web/Application.php(312): craft\web\Application->_processActionRequest()
#32 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#33 /var/www/html/web/index.php(12): yii\base\Application->run()
```

I also note that the same error is thrown when trying to add a nested Matrix entry inside another nested Matrix entry (i.e. 2 levels of Matrix fields). Adding a nested entry to the top-level Matrix field works and triggers a draft auto-save which succeeds (saving manually fails with the error and stack above). However, adding a nested entry to a Matrix field inside the entry created above shows a loader and then nothing happens. Looking at the logs, I can see there was an Ajax request to create the matrix entry and that threw an error. Here is the full stack trace of that error:

```
2024-11-20 16:34:37 [web.ERROR] [yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid owner ID: 3351 in /var/www/html/vendor/craftcms/cms/src/base/NestedElementTrait.php:162
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/base/NestedElementTrait.php(207): craft\elements\Entry->getPrimaryOwner()
#1 /var/www/html/vendor/craftcms/cms/src/base/NestedElementTrait.php(239): craft\elements\Entry->getOwner()
#2 /var/www/html/vendor/craftcms/cms/src/base/Element.php(3519): craft\elements\Entry->getField()
#3 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1810): craft\base\Element->canSave()
#4 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(4317): craft\elements\Entry->canSave()
#5 /var/www/html/vendor/craftcms/cms/src/fields/Matrix.php(567): craft\services\Elements->canSave()
#6 /var/www/html/vendor/craftcms/cms/src/base/Element.php(3519): craft\fields\Matrix->canSaveElement()
#7 /var/www/html/vendor/craftcms/cms/src/elements/Entry.php(1810): craft\base\Element->canSave()
#8 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(4317): craft\elements\Entry->canSave()
#9 /var/www/html/vendor/craftcms/cms/src/controllers/MatrixController.php(116): craft\services\Elements->canSave()
#10 [internal function]: craft\controllers\MatrixController->actionCreateEntry()
#11 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#12 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction()
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(649): craft\web\Application->runAction()
#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(312): craft\web\Application->_processActionRequest()
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#18 /var/www/html/web/index.php(12): yii\base\Application->run()
```

**Comment by i-just** [comment] 2024-11-20 16:21
Thanks for the extra info! 

@yoannisj, any chance you could test if PR #16162 fixed this for you? To do so, change your `craftcms/cms` requirement in `composer.json` to 
```
"craftcms/cms": "5.x-dev#cab2531e1a244ae15d04e122f47d919c83f11772 as 5.5.2",
```
and run `composer update`?

**Comment by yoannisj** [comment] 2024-11-20 19:07
@i-just , great:I just tested and the PR does solve the issue 🥳 . Thanks for this quick fix!

Can we expect the fix to ship with Craft's next release? Than I will revert to Craft v5.5.0.1 and keep an eye out for updates.

**Comment by mattwardcc** [comment] 2024-11-20 22:21
I can also confirm that that PR does seem to solve the problem on my install as well. I tested all 3 areas where the problem happened, and will continue to work on the site locally this evening.

**Comment by i-just** [comment] 2024-11-21 07:32
Thanks for testing! 
Yes, the fix should be included in the next release.

**Comment by brandonkelly** [comment] 2024-11-22 23:36
Craft 5.5.3 is out with the fix for this. Thanks again!

**Closed as completed by brandonkelly** 2024-11-22 23:36 UTC
Labels: bug
