### ISSUE TITLE
Craft 3 Custom 'Login Page Logo' appears cropped on login page.

### ISSUE THREAD

**Issue by William-Owen** [craftcms/cms#1656] opened 2017-04-22 10:28 UTC
### Description

Under 'General Settings'  the 'Login Page Logo' setting states on that "SVG file recommended. The logo will be displayed at 300px wide.". However when uploading a 300px x 300px wide logo image the image appears cropped at the edges.

Looking at the CSS I can see that the inline CSS for the #login-form element is setting the background width to 500px x 500px as follows: -

```css
background-image: url(http://localhost:8082/admin/resources/rebrand/logo/craft-logo-and-title.svg?d=1492855794);
background-size: 500px 500px;
padding-top: 530px;
margin-top: -442px;
```

However if I set the css in the console to the following; it displays the login correctly.

```css
background-image: url(http://localhost:8082/admin/resources/rebrand/logo/craft-logo-and-title.svg?d=1492855794);
background-size: 300px 600px;
padding-top: 450px;
margin-top: -452px;
```

### Steps to reproduce

1. Upload a 300 x 300 SVG logo via General Settings.
2. Logout and view the login page.
3. The image will be cropped at the left and right.

### Additional info

- Craft version: Craft 3 Beta 13

**Comment by benjamindavid** [comment] 2017-04-25 07:01
This is a duplicate of #1428, which has been fixed for the next release.

Thanks for reporting @William-Owen

**Closed by benjamindavid** 2017-04-25 07:01 UTC
Labels: bug, severity: minor
