### ISSUE TITLE
[Users] User Types or something similar

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/cms#6786] opened 2020-09-03 15:20 UTC
My thoughts are to use the Craft Users more often also for Team Members and stuff like that.

Everything in the CP whats a Person should be listed in Users and not within a Custom Sections. I think this is more flexible at the end and also more future proof. And it gives the possibilities to user user roles. 

Sometimes it would be nice to have different fieldsets for different users. Something like Entry Types would be nice for users. User Types ;) 

But they should not be changeable for the user itself but for Admin Users or Users with the right role. 

First thought was to pin it to the user role but a user can have x Roles. 

A other Idea is to have an option for fields in the layouteditor (just within users) where I can choose the roles for which the field is visible. 

That solves also that some fields are not editable for users. Maybe there are settings that not for the user itself but necessary for the page. Then I select Admin as role for this field. 

Questions? Let me know.

**Comment by mmikkel** [comment] 2020-09-03 17:35
It's definitely a recurring annoyance that it isn't possible to somehow have different field layouts for different (types of) users, but in my opinion it sounds unnecessarily complex to introduce an additional concept like user types on top of user groups.

Personally I think field layout conditionals would be the most flexible and robust solution for this, and I hope that when conditionals finally happen in core it'll be possible to create rules like "user is in user group A or B" etc, in the Users field layout. (I also hope it'll be possible to hide/show entire field layout _tabs_ using conditionals, which would especially benefit this particular use case IMO)

My hope is that when field layout conditionals are introduced in core, they'll be robust enough to solve this use case – where conditionals like for example "user is in user group A or B" can be added to the Users field layout.

**Comment by davidhellmann** [comment] 2020-09-03 17:45
I'm with you. The user type is maybe a bit to complex. But conditionals sounds like the solution for this. +1

**Comment by Anubarak** [comment] 2020-09-04 18:10
You can have different field layouts for different users by using hooks and events.
I made a page with a booking system and customers have a different field layout than managers and so on. 

But I agree, would be cool to have a native function in the cp for that instead of using the event.

**Comment by brandonkelly** [comment] 2020-09-05 01:15
This is a duplicate of #5941. Will be resolved by either field-level permissions (#947) and/or conditional fields (#805).

**Closed by brandonkelly** 2020-09-05 01:15 UTC
