### ISSUE TITLE
Craft 3 Database Backups Failing

### ISSUE THREAD

**Issue by alexr8** [craftcms/cms#2319] opened 2018-01-18 10:50 UTC
### Description
When running a database backup, either manually from the admin panel or the auto backup when craft has updated itself, the backup fails with the following error (longer output at the bottom). 

`failed with exit code 2: Warning: World-writable config file '/var/www/storage/runtime/temp/my.cnf' is ignored`

### Steps to reproduce

1. Go to Admin -> Utilities -> Database Backup
2. Click Backup - red warning bar at top appears saying to check the log

### Additional info

- Craft version: Craft 3 RC 5
- PHP version: 7.1
- Database driver & version: MySQL 5.5.55
- Plugins & versions: Inlin 2.0.0, Redactor 1.0.1, Expanded Singles 1.0.1, Eager Beaver 1.0.1

I am using this vagrant box https://box.scotch.io/ but i have additionally updated it to PHP 7.1.

Longer trace from logs:
```
[error][yii\base\Exception] yii\base\Exception: Could not create backup: The shell command "mysqldump --defaults-extra-file="/var/www/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --single-transaction --no-data --result-file="/var/www/storage/backups/test-site-2018_180118_104235_xse8viheuy_v3.0.0-rc5.sql" scotchbox && mysqldump --defaults-extra-file="/var/www/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --no-create-info --ignore-table=scotchbox.assetindexdata --ignore-table=scotchbox.assettransformindex --ignore-table=scotchbox.cache --ignore-table=scotchbox.sessions --ignore-table=scotchbox.templatecaches --ignore-table=scotchbox.templatecachecriteria --ignore-table=scotchbox.templatecacheelements scotchbox >> "/var/www/storage/backups/test-site-2018_180118_104235_xse8viheuy_v3.0.0-rc5.sql"" failed with exit code 2: Warning: World-writable config file '/var/www/storage/runtime/temp/my.cnf' is ignored
mysqldump: Got error: 1045: Access denied for user 'vagrant'@'localhost' (using password: NO) when trying to connect in /var/www/vendor/craftcms/cms/src/controllers/UtilitiesController.php:381
```

**Comment by alexr8** [comment] 2018-01-19 10:20
Ok i tried that, unfortunately I still get the same error.

**Comment by angrybrad** [comment] 2018-01-19 17:35
Hrm... will install that Vagrant box and see if I can reproduce.

**Comment by alexr8** [comment] 2018-01-19 18:59
if its useful, here is my vagrant file with the additional bit for installing php 7.1 on first vagrant up
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    
    # This is Scotch Box 3.0 (the free version)
    # _________________________________________
    # If you want PHP7, MySQL 5.7, Ubuntu 16.04, Build Scripts (customize your own boxes in minutes)...
    # ... an NGINX version, PHPUnit, Yarn, WebPack, improved email testing with MailHog...
    # ... generally Higher versions of things, Ruby (via RVM), Node (via NVM), WebPack ready, and more.
    
    # Just go to https://box.scotch.io/pro
    # Your support will help keep this project alive!

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    
    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }


    config.vm.provision "shell", inline: <<-SHELL
        sudo add-apt-repository ppa:ondrej/php
        sudo apt-get update
        sudo apt-get install -y php7.1 php7.1-xml php7.1-mysql php7.1-curl php7.1-mbstring php7.1-zip

        sudo a2dismod php7.0
        sudo a2enmod php7.1
        sudo service apache2 restart
    SHELL

end
```

**Comment by angrybrad** [comment] 2018-01-23 22:26
Based on my research, the issue is this line:

> config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

Anything in that shared folder will have directory permissions of 777 and file permissions of 666 created, including the files that Craft/PHP generates (like the temp my.cnf file when backing up/restoring a database).

With these subsystems inside of host (Vagrant, Bash on Windows, etc.), it looks like a common limitation is that you can't change permissions inside of the subsystem, only on the host, which is why our `chmod` test earlier didn't work.

I've seen some places where people say using https://github.com/gael-ian/vagrant-bindfs is a way to workaround this in Vagrant, specifically and I see that [Homestead](https://github.com/laravel/homestead) references that plugin in their Vargrant startup logic and uses it if it's available.

I was also not able to reproduce the issue on Homestead, so it seems likely there is a Vagrant config solution to this.

There is likely an existing Craft workaround as well with the [backupCommand](https://github.com/craftcms/cms/blob/develop/src/config/GeneralConfig.php#L85-L105) config setting.  You can completely override the Craft backup logic to run anything you want, including alternate ways of connecting to the database other than a my.cnf file.

Given those and it seems unlikely there is a programmatic way for Craft to address this, going to say this behaves as expected and close it out.

**Closed by angrybrad** 2018-01-23 22:26 UTC

**Comment by alexr8** [comment] 2018-01-23 22:37
Ok gotcha, thanks for your time researching this - will look into those vagrant fixes with bindfs 👍

**Comment by crazyx13th** [comment] 2018-01-25 14:42
hey there,

I think I have the same Problem. At my second CMS I can't backup. The system generates a empty Backupfile. We have a second CraftCMS3 installation at this server, no-problems with backup.

```bash
[error][yii\base\Exception] yii\base\Exception: Could not create backup: 
The shell command "mysqldump --defaults-extra-file="/var/www/vhosts/xxxxx.com/htdocs/cms/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --single-transaction --no-data --result-file="/var/www/vhosts/xxxxx.com/htdocs/cms/storage/backups/xxxxx.com_180125_141424_6y4wn3yame_v3.0.0-rc7.1.sql" cruise-craftcms3 && mysqldump --defaults-extra-file="/var/www/vhosts/xxxxx.com/htdocs/cms/storage/runtime/temp/my.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --no-create-info --ignore-table=cruise-craftcms3.assetindexdata --ignore-table=cruise-craftcms3.assettransformindex --ignore-table=cruise-craftcms3.cache --ignore-table=cruise-craftcms3.sessions --ignore-table=cruise-craftcms3.templatecaches --ignore-table=cruise-craftcms3.templatecachecriteria --ignore-table=cruise-craftcms3.templatecacheelements cruise-craftcms3 >> "/var/www/vhosts/xxxxx.com/htdocs/cms/storage/backups/xxxxx.com_180125_141424_6y4wn3yame_v3.0.0-rc7.1.sql"" 
failed with exit code 2: mysqldump: Got error: 1045: Access denied for user 'xxxxx'@'localhost' (using password: YES) when trying to connect in /var/www/vhosts/xxxxx.com/htdocs/cms/vendor/craftcms/cms/src/controllers/UtilitiesController.php:381
```
thx!

**Comment by brandonkelly** [comment] 2018-01-25 19:05
@crazyx13th looks like a DB account permissions issue?

> Access denied for user 'xxxxx'@'localhost'

**Comment by crazyx13th** [comment] 2018-01-26 08:31
thought the same, but why I can change my entries and everything else is fine?

**Comment by angrybrad** [comment] 2018-01-26 18:15
@crazyx13th my guess is the credentials being generated in the temp my.cnf file are incorrect for some reason, unrelated to this original issue.  Can you create a new issue for this and we can try to debug on it?
