### ISSUE TITLE
Craft3 Beta : Upgrade fails but never leaves maintenance mode

### ISSUE THREAD

**Issue by jaredfolkins** [craftcms/cms#1913] opened 2017-08-10 22:14 UTC
### Description

If HOME or COMPOSER_HOME is unset, upgrade fails but never leaves maintenance mode.

### Steps to reproduce

1. Do not set HOME or COMPOSER_HOME
2. From the CP click upgrade
3. See the following error message
4. Click upgrade again
5. The software will tell you that someone is updating the site
6. Run `update info set maintenance = 0 where id = 1;` to remove maintenance mode

### Additional info

PHP version | 7.0.18-0ubuntu0.16.04.1
MySQL 5.7.19-0ubuntu0.16.04.1
Imagick 3.4.0RC6, ImageMagick 6.8.9-9
Craft Personal 3.0.0-beta.22
2.0.12
2.3.2
6.2.1
0.7-dev

![screen shot 2017-08-10 at 3 09 59 pm](https://user-images.githubusercontent.com/176908/29194448-7ffbcf2e-7dde-11e7-91fd-746b86fcbb78.png)

![screen shot 2017-08-10 at 3 10 18 pm](https://user-images.githubusercontent.com/176908/29194453-87b36042-7dde-11e7-9337-804cf2bee39a.png)

**Comment by brandonkelly** [comment] 2017-08-15 00:57
Duplicate of #1890 (and fixed for the next update in 77680076626f13ec2b11fe340be4e6a85e85f9eb).

**Closed by brandonkelly** 2017-08-15 00:57 UTC
