### ISSUE TITLE
[4.x]: Matrix blocks not propagated properly when blocks contain link plugin field

### ISSUE THREAD

**Issue by tommysvr** [craftcms/cms#12858] opened 2023-03-10 02:41 UTC
### Description
Seeing a strange issue where Matrix blocks are missing after propagating to another entry. The strange part is that I can only reproduce when the entry contains an entry Typed Link Field, LinkIt or Hyper field. I’m not able to reproduce when the entry only contains blocks with native fields.

Seems related to https://github.com/sebastian-lenz/craft-linkfield/issues/233

### Steps to reproduce

1. Have a multisite install with any of Typed Link Field, LinkIt or Hyper installed
2. Add a Section with Propagation Method 'Let each entry choose which sites it should be saved to'
3. Add a Matrix field with a text field block and a block for any other link plugin fields. Propagation Method is 'Save blocks to all sites the owner element is saved in'
4. Create a new entry with a text field block and an *empty* link field
5. Propagate the entry to another site, the link field will be marked as changed
6. View the entry on the other site, only the link field block will have propagated

### Expected behavior
All blocks will be propagated

### Actual behavior
Only the link fields are propagated

https://user-images.githubusercontent.com/867566/224209146-509adfa1-8e1b-46b1-a586-ba3ac3af4ac1.mp4

### Craft CMS version

4.4.1

### Installed plugins and versions

-

**Comment by engram-design** [comment] 2023-03-10 08:40
I'm investigating this issue as well. I've shortened the reproduction slightly:

1. Create a new entry in Site A.
2. Populate the title, then add a Text and Link Matrix block. Populate those fields with a value
3. Save the entry (in Site A)
4. Add the entry to Site B, and notice the change indicators. No need to re-save the entry in Site A
5. Switch to Site B and notice the blocks being incorrect

Here's a video
https://share.cleanshot.com/rfMW6Hzx

The only thing that looks fishy to me is the request payload at step 4 as soon as you pick "Site B" from the status (the initial propagation to the other site):

```
title: 1
newWindow: 
elementId: 157
siteId: 1
slug: 1-2
enabled: 1
enabledForSite[1]: 1
enabledForSite[2]: 1
notes: 
fields[matrix][blocks][161][fields][linkField]: 
fields[matrix][blocks][161][fields][linkField][0][type]: verbb\hyper\links\Url
fields[matrix][blocks][161][fields][linkField][0][handle]: default-verbb-hyper-links-url
fields[matrix][blocks][161][fields][linkField][0][newWindow]: 
fields[matrix][blocks][161][fields][linkField][0][linkText]: 3
fields[matrix][blocks][161][fields][linkField][0][id]: tcpobwynfv
fields[matrix][blocks][161][fields][linkField][0][linkValue]: 
fields[matrix][blocks][161][fields][linkField][0][linkText]: 3
modifiedDeltaNames[]: fields[matrix][blocks][161][fields][linkField]
visibleLayoutElements[e3ef0647-3324-4acb-bce8-47dd23c8ac0c][]: bdaf3f66-ee87-4a6e-a9f8-632ad6b5a734
visibleLayoutElements[e3ef0647-3324-4acb-bce8-47dd23c8ac0c][]: 6487f158-c70e-4f20-898b-35bb5c050693
provisional: 1
selectedTab: tab--content
action: elements/save-draft
```

So what's interesting here is that `linkField` content is included here, but the text content is missing - hence the block isn't created. Or, more to the point maybe it _shouldn't_ be included in this propagation step.

**Comment by engram-design** [comment] 2023-03-10 09:04
This can also be confirmed by simplifying the Hyper field to remove all Vue components and reduce it to a single text field for the Link Text. This at least helps isolate things.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/1221575/224272308-23aec0d0-bebf-4dcb-b623-fd476513a3dd.png">

Again, in Step 4 where I've just picked the other site to add the entry to, you can see the changed content is registered for the Matix field overall, the Hyper field, but not the Text field. Technically, Hyper is in the wrong here, as the content _hasn't changed, so I (and the other plugins) are possibly doing something wrong.

**Comment by engram-design** [comment] 2023-03-10 22:47
And just to simplify it even further (or maybe I'm going down the wrong path here), is that fields are incorrectly marked as being modified on "Site A" when all I've done is propagate to "Site B" - even when outside of a Matrix field.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/1221575/224442262-9b20535e-7e49-4072-b499-00180b0d78d3.png">

After more testing, if I change the value of the Hyper field to be a simple value, and **not** a `LinkCollection` the issue goes away. This makes sense if other plugins are having this issue, as all of them use objects and not simple values.

I did pick up on the below check which thought might be the key to this but omitting it doesn't do anything.

https://github.com/craftcms/cms/blob/73771c5811656a3139087a370e3e729f1d7ff96f/src/services/Elements.php#L1488-L1493

**Closed** 2023-03-11 12:58 UTC
Labels: bug, craft4

**Comment by brandonkelly** [comment] 2023-03-11 13:07
The culprit here was these lines:

https://github.com/craftcms/cms/blob/0f27b7245610d64eb7312848ffa2cc26762c6c3e/src/fieldlayoutelements/CustomField.php#L259-L261

Which tell the element editor to ignore whatever the input’s _actual_ initial post value is, and pretend it was null, if the field type’s `isValueEmpty()` method returned `true`.

That logic was originally added in d13a51f1faa80192b949471bb9ddd802ca861935, to fix a bug where Dropdown fields that had no value weren’t getting their default option to be selected on save, despite it looking like it was, because the input value on save matched what it was on initial page load (#5632).

But that’s actually not needed anymore as of 4.4, thanks to e2eb6518133fd6e4ee1ba8f44dc4dbfd24d82847, which adds a blank option to Dropdown fields that don’t have a value yet (#12235).

So those lines have been removed for the next release, and now Hyper (and theoretically similar fields) now behaves as expected – only being seen as modified when the post data actually changes.

**Comment by brandonkelly** [comment] 2023-03-14 21:09
4.4.2 is out with that change!
