### ISSUE TITLE
Craft 3.5+: ability to drag and drop field group as tab in Sections

### ISSUE THREAD

**Issue by ohbiko** [craftcms/cms#6840] opened 2020-09-16 08:35 UTC
### Description

(under Settings > Sections > Edit Entry Type)
This used to be possible in Craft < 3.5.  Can you please bring this back?  The ability to drag and drop field group directly as tags saves tremendous amount of time.

**Comment by brandonkelly** [comment] 2020-09-16 18:43
This is a duplicate of #6568. It will be resolved with #1674.

**Closed by brandonkelly** 2020-09-16 18:43 UTC
Labels: enhancement

**Comment by ohbiko** [comment] 2020-09-16 23:02
Sweet can't wait for this feature!
