### ISSUE TITLE
Slug generation adds additional hyphen (breaks) when using uppercase letters and numbers

### ISSUE THREAD

**Issue by terryupton** [craftcms/cms#4381] opened 2019-06-07 09:47 UTC
### Description
Also perhaps related to #4295 and #4266 - I am seeing the following:
My title field is setup as follows {hotTubName}{stockCode} and then when I enter the following into the Stock Code field: 18T1018 it is creating the slug as follows:
sundance18-t1018 - I wouldn't expect this behaviour, I would expect the slug to be sundance18t1018

For now I have changed my title field to {hotTubName}-{stockCode|lower}

### Additional info

- Craft version: Craft Pro 3.1.28
- PHP version: 7.2.18
- Database driver & version: 	MySQL 5.5.5 (actually Maria DB 10.3.15)
- Plugins & versions:

**Comment by brandonkelly** [comment] 2019-06-07 14:11
Yeah this is a duplicate of #4295, and as explained there it is expected behavior.

**Closed by brandonkelly** 2019-06-07 14:11 UTC

**Comment by terryupton** [comment] 2019-06-07 15:31
Is there any approach to make the slug present like 'sundance18t1018' instead of 'sundance18-t1018'?
