### ISSUE TITLE
Entry quick edit continuously scrolls to the bottom of the quick edit screen

### ISSUE THREAD

**Issue by JoshStaff** [craftcms/cms#2796] opened 2018-04-24 09:02 UTC
A client informed us there is an issue with the quick edit screen and upon testing, "a weird scroll".

Understand this is going to be the least priority around, just figured it was worth noting.

https://gyazo.com/b85061a222f9ba4babe09178088743c9

### Steps to reproduce

1. Using google chrome
2. Open quick edit screen 
3. Scroll around on the list of entries, scroll within the quick edit screen

### Additional info

- Craft version: Craft CMS 2.6.3014
- PHP version: 7.1
- Plugins & versions: Reasons 1.0.11

**Comment by brandonkelly** [comment] 2018-04-24 13:34
Looks like this is a duplicate of #2100, but the fix never made it to Craft 2. Will make sure it makes it in for the next update!

**Closed by brandonkelly** 2018-04-24 13:34 UTC
