### ISSUE TITLE
Category Fields with a Limit of 1 still have an "Add a Category" button

### ISSUE THREAD

**Issue by Visiluna** [craftcms/cms#5934] opened 2020-04-16 19:38 UTC
### Description

As shown in the attached screenshot, when the `Limit` for an Asset field (_Image_ in the screenshot) is set to 1, the "Add an asset" button is no longer available once an asset has been selected. The selected asset must first be removed before selecting a different asset. This is expected behavior.

The behavior for Category fields is not consistent with this. The _Category_ field shown in the screenshot also has its `Limit` set to 1, but the "Add a category" button is still shown. If clicked, the category picker is shown and the user can select additional categories, but they aren't saved once selected.

Shouldn't the "Add a category" button exhibit the same behavior as the "Add an asset" button, not appearing once that field's `Limit` has been reached?

<img width="251" alt="Screen Shot 2020-04-16 at 2 11 20 PM" src="https://user-images.githubusercontent.com/53744/79498722-62d10c00-7fef-11ea-996a-d38db3740a04.png">

### Additional info

- Craft version: 3.4.15
- PHP version: 7.3.9
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment] 2020-04-17 00:30
Thanks for reporting! This is actually a duplicate of #2423 though.

**Closed by brandonkelly** 2020-04-17 00:30 UTC
