### ISSUE TITLE
[5.x]: Validation message not working in slideout

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#15285] opened 2024-07-02 16:03 UTC
### Description
Continuing on #15161, I think the validation is still not working when you are (multiple levels deep) in slideouts. 

### Steps to reproduce

1. Open an entry in slideout
2. In that entry we have the matrix block like in #15161, with the required field that is empty
3. Try to save that entry --> No validation, just a message "Couldn't save entry"

### Expected behavior
You should see the validations

### Actual behavior
Message "Couldn't save entry"
![image](https://github.com/craftcms/cms/assets/22771556/ea926aa0-6ee7-4219-881b-fe84f4045aab)
![image](https://github.com/craftcms/cms/assets/22771556/24500554-e12e-42fe-af3e-c071d9dd74f9)

### Craft CMS version

5.2.4.1

### PHP version

8.3.7

### Database type and version

MySQL 8.0.37

**Comment by brandonkelly** [comment] 2024-07-02 17:21
This should be fixed for Craft 5.3 via #15165. Would you mind testing to verify?

To test, change your `craftcms/cms` requirement in composer.json to:

```json
"craftcms/cms": "5.3.x-dev as 5.3.0-alpha",
```

Then run `composer update`.

**Comment by WHITE-developer** [comment] 2024-07-03 12:04
Yes, except that my blocks don't have, I guess, a title?
And opening a block doesn't show which field is wrong.
![image](https://github.com/craftcms/cms/assets/22771556/2c95a973-09a8-4785-959f-4e523e644058)

**Comment by brandonkelly** [comment] 2024-07-03 14:52
We’re not able to reproduce that. Can you please send a database backup and your Composer files into support@craftcms.com, and point out where that issue is happening?

**Comment by WHITE-developer** [comment] 2024-07-04 15:23
You've got mail :mailbox:

**Comment by brandonkelly** [comment] 2024-07-04 17:45
@WHITE-developer Thanks, we were able to reproduce with that. We made some adjustments (#15298) and it should be working as expected now. Run `composer update` if you want to test.

**Comment by WHITE-developer** [comment] 2024-07-05 08:24
Yes, perfect :ok_hand:. Thanks!

**Closed as completed** 2024-07-06 16:51 UTC
Labels: bug
