### ISSUE TITLE
FR: Relation field - Select Elements from disabled sites

### ISSUE THREAD

**Issue by tim-pixeldeluxe** [craftcms/cms#4430] opened 2019-06-21 14:23 UTC
At this point in time you are only able to disable sites for sections but since most elements (categories, tags, etc) are going to merged into one content tab I'm calling them elements.

### Suggestion
It would be really useful if you were able to relate Elements from sites that are not enabled for the current Element.

Use case:
I've got a setup with one main site and a few subsites on different domains. The subsites look very similar and are to some extent connected, however, they do not use the same sections as the main site. Both sites have different sections which are disabled for the other site. This means I can't relate between the two sites.

It would be really useful if I could relate Elements between the two. For example relate a news article from the main site on the homepage of the subsite.

**Comment by brandonkelly** [comment] 2019-06-22 04:43
This seems like a duplicate of #3584, which is addressed in Craft 3.2, where relational fields that aren’t locked down to a specific target site can now relate entries from any site.

**Closed by brandonkelly** 2019-06-22 04:43 UTC
