### ISSUE TITLE
RC14 / Redactor / Images with transforms vanish after saving

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#2562] opened 2018-03-13 09:33 UTC
### Description
When you use redactor as a field, and you insert an image **with transform**. It gets inserted just fine and shows the correct image, but if you save the entry and open it back up, its gone.

**Before safe**
![schermafbeelding 2018-03-13 om 10 30 51](https://user-images.githubusercontent.com/23024452/37333450-a988ebbe-26a9-11e8-9bd3-c2fdf3a3bc20.png)

**After safe **
![schermafbeelding 2018-03-13 om 10 30 59](https://user-images.githubusercontent.com/23024452/37333463-b220d200-26a9-11e8-827f-a78f9a6c1352.png)

As you can see, the bottom image, that uses a transform, is now gone.

Instead the HTML/IMG-src is:
`{asset:490:transform:four_one}#asset:490:transform:four_one`

### Steps to reproduce

1. Create a new entry with a redactor field
2. Fill that redactor field with an image, using a transform
3. Save the entry
4. Re-open the entry

### Additional info

- Craft version: RC14
- PHP version: PHP72
- Database driver & version: not relevant
- Plugins & versions: 
Redactor: 1.0.1
AWS-sdk: 1.0.8

**Comment by andris-sevcenko** [comment] 2018-03-13 11:35
Duplicate of #2524 and fixed for the next release.

**Closed by andris-sevcenko** 2018-03-13 11:35 UTC
