### ISSUE TITLE
Feature request: Button to collapse/Expand all matrix blocks at once

### ISSUE THREAD

**Issue by Friksel** [craftcms/cms#6136] opened 2020-05-25 11:23 UTC
### Description

Working on a project where everything is based on (Matrix) blocks, a lot of blocks will be stacked on top of each other to create a page I am really missing a feature in the control panel to expand and collapse all blocks at once, just like found in editors like vs code. 

So I wish to see in the Matrix field (talking about the cp interface for editing the data):
* **A Collapse All Blocks button** 
To create a quick overview of all added blocks, and to be able to quickly turn on just a single block we want to edit after it.
* **An Expand All Blocks button**
Needed to have a detailed overview of the page, used when all blocks are added and we want to check everything before going live for example.

If these buttons were there that would be a huge time saver and less painful to toggle open/close all blocks at once a lot of times while editing!

### Additional info

- Current Craft version: 3.4.20

**Comment by richhayler** [comment] 2020-05-27 02:20
In the meantime @Friksel check out https://github.com/monachilada/craft-matrixtoolbar/blob/master/README.md

**Comment by Friksel** [comment] 2020-05-27 11:20
@richhayler That's exactly what I was looking. Hope this basic functionality could be build into Craft in the near future, but in the meantime this definitely helps indeed as it's exactly how I would like to use it. Thanks!

**Comment by brandonkelly** [comment] 2020-05-27 15:40
This is a duplicate of #1880.

**Closed by brandonkelly** 2020-05-27 15:40 UTC
