### ISSUE TITLE
Live Preview issues with 100vh backgrounds/absolute positioned elements

### ISSUE THREAD

**Issue by moondawg69** [craftcms/cms#6654] opened 2020-08-17 17:07 UTC
### Description

Using live preview on designs that have a 'hero' of 100vh, and then positioning an element with transform/translate method causes the preview to fail and produce an infinite scrollbar.

### Steps to reproduce

1. CraftCMS 3.4 upwards
2. Edit/create an entry using live preview

### Additional info

- Craft version: 3.4 upwards only tested
- Tested in Safari, Chrome, latest versions on Mac Catalina

CSS used for the 'hero' - if this is removed, the issue goes.

```
.fh {height: 100vh;}

.bg-full {
background:no-repeat center center;
-webkit-background-size: cover;
-moz-background-size: cover;
-o-background-size: cover;
background-size: cover;
height: 100vh;
position: relative;
z-index: 0;
}

.bg-full:before {
content: '';
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
background: linear-gradient(180deg, rgba(51,51,51,0.9) 0%, rgba(51,51,51,0.7) 35%, rgba(51,51,51,0.8) 70%, rgba(51,51,51,0.6) 90%);
opacity: 1;
z-index: 1;
}

.intro
{width: 45%;margin: 0 0 0 5%;text-align: left;
position: absolute;
top: 50%;
transform: translate(0%, -50%);
z-index: 10;
}
```

If the above is removed, then the Live Preview ‘works’ and if the image is removed from the field itself.

Example can be seen in this video:

[https://streamable.com/17gbcj](https://streamable.com/17gbcj)

--

**Comment by brandonkelly** [comment] 2020-08-17 22:14
This is a duplicate of #6388, and fixed in Craft 3.5.5 (released today), by disabling the new iFrame Resizer-based behavior by default (see #6645).

**Closed by brandonkelly** 2020-08-17 22:14 UTC
Labels: bug
