### ISSUE TITLE
Craft 3.1.0-beta.1 SQL errors after updating

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#3502] opened 2018-11-28 21:02 UTC
Updated a local dev environment that was running Craft CMS 3.0.32 to Craft CMS 3.1.0-beta.1, reloaded the admin page it was on after `composer update` was done, and see this:

It's almost like migrations never ran... and indeed I didn't see any run in the CP.

```
An Error occurred while handling another error:
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'elements.dateDeleted' in 'where clause' in /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `users`....')
#2 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#5 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1210): craft\db\Query->one(NULL)
#6 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/User.php(365): craft\elements\db\ElementQuery->one()
#7 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity('1')
#8 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/User.php(421): yii\web\User->renewAuthStatus()
#9 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#10 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/assets/cp/CpAsset.php(229): yii\web\User->getIdentity()
#11 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/assets/cp/CpAsset.php(91): craft\web\assets\cp\CpAsset->_craftData()
#12 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/View.php(266): craft\web\assets\cp\CpAsset->registerAssetFiles(Object(craft\web\View))
#13 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/View.php(1476): yii\web\View->registerAssetFiles('craft\\web\\asset...')
#14 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/View.php(264): craft\web\View->registerAssetFiles('craft\\web\\asset...')
#15 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/View.php(1476): yii\web\View->registerAssetFiles('nystudio107\\ric...')
#16 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/View.php(162): craft\web\View->registerAssetFiles('nystudio107\\ric...')
#17 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/View.php(870): yii\web\View->endBody()
#18 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/views/errorHandler/exception.php(526): craft\web\View->endBody()
#19 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/View.php(336): require('/home/vagrant/s...')
#20 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/home/vagrant/s...', Array)
#21 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/ErrorHandler.php(266): yii\base\View->renderFile('/home/vagrant/s...', Array, Object(craft\web\ErrorHandler))
#22 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/ErrorHandler.php(126): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#23 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/ErrorHandler.php(132): yii\web\ErrorHandler->renderException(Object(yii\db\Exception))
#24 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/ErrorHandler.php(111): craft\web\ErrorHandler->renderException(Object(yii\db\Exception))
#25 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/ErrorHandler.php(63): yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#26 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\db\Exception))
#27 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'elements.dateDeleted' in 'where clause'
The SQL being executed was: SELECT `users`.`password`, `elements`.`id`, `elements`.`fieldLayoutId`, `elements`.`uid`, `elements`.`enabled`, `elements`.`archived`, `elements`.`dateCreated`, `elements`.`dateUpdated`, `elements_sites`.`slug`, `elements_sites`.`uri`, `elements_sites`.`enabled` AS `enabledForSite`, `users`.`username`, `users`.`firstName`, `users`.`lastName`, `users`.`email`, `users`.`admin`, `users`.`locked`, `users`.`pending`, `users`.`suspended`, `users`.`lastLoginDate`, `users`.`lockoutDate`, `users`.`photoId`, `users`.`hasDashboard`, `content`.`id` AS `contentId`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `elements` `elements`
INNER JOIN `users` `users` ON `users`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON `content`.`elementId` = `elements`.`id`
WHERE (`elements_sites`.`siteId`='1') AND (`content`.`siteId`='1') AND (`elements`.`id`='1') AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL)
ORDER BY `users`.`username`
LIMIT 1) `subquery`
INNER JOIN `users` `users` ON `users`.`id` = `subquery`.`elementsId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
ORDER BY `users`.`username` in /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT `users`....')
#1 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `users`....')
#2 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#5 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1210): craft\db\Query->one(NULL)
#6 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/User.php(365): craft\elements\db\ElementQuery->one()
#7 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity('1')
#8 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/User.php(421): yii\web\User->renewAuthStatus()
#9 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#10 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/assets/cp/CpAsset.php(229): yii\web\User->getIdentity()
#11 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/assets/cp/CpAsset.php(91): craft\web\assets\cp\CpAsset->_craftData()
#12 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/View.php(266): craft\web\assets\cp\CpAsset->registerAssetFiles(Object(craft\web\View))
#13 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/View.php(1476): yii\web\View->registerAssetFiles('craft\\web\\asset...')
#14 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/View.php(264): craft\web\View->registerAssetFiles('craft\\web\\asset...')
#15 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/View.php(1476): yii\web\View->registerAssetFiles('nystudio107\\ric...')
#16 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/View.php(162): craft\web\View->registerAssetFiles('nystudio107\\ric...')
#17 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/View.php(870): yii\web\View->endBody()
#18 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/views/errorHandler/exception.php(526): craft\web\View->endBody()
#19 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/View.php(336): require('/home/vagrant/s...')
#20 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/home/vagrant/s...', Array)
#21 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/ErrorHandler.php(266): yii\base\View->renderFile('/home/vagrant/s...', Array, Object(craft\web\ErrorHandler))
#22 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/ErrorHandler.php(126): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#23 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/ErrorHandler.php(132): yii\web\ErrorHandler->renderException(Object(yii\db\Exception))
#24 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/ErrorHandler.php(111): craft\web\ErrorHandler->renderException(Object(yii\db\Exception))
#25 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/ErrorHandler.php(63): yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#26 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\db\Exception))
#27 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'elements.dateDeleted' in 'where clause'
)

Previous exception:
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fields.searchable' in 'field list' in /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `fields`...')
#2 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#5 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/services/Fields.php(630): craft\db\Query->all()
#6 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1526): craft\services\Fields->getAllFields()
#7 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1072): craft\elements\db\ElementQuery->customFields()
#8 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#10 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#12 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1210): craft\db\Query->one(NULL)
#13 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/User.php(365): craft\elements\db\ElementQuery->one()
#14 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity('1')
#15 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/User.php(421): yii\web\User->renewAuthStatus()
#16 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#17 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/User.php(360): yii\web\User->getIdentity()
#18 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/User.php(182): yii\web\User->getIsGuest()
#19 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Component.php(139): craft\web\User->getIsGuest()
#20 /home/vagrant/sites/craft3/vendor/yiisoft/yii2-debug/src/panels/UserPanel.php(79): yii\base\Component->__get('isGuest')
#21 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\debug\panels\UserPanel->init()
#22 [internal function]: yii\base\BaseObject->__construct(Array)
#23 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#24 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\debug\\Use...', Array, Array)
#25 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\debug\\Use...', Array, Array)
#26 /home/vagrant/sites/craft3/vendor/yiisoft/yii2-debug/src/Module.php(182): yii\BaseYii::createObject(Array)
#27 /home/vagrant/sites/craft3/vendor/yiisoft/yii2-debug/src/Module.php(154): yii\debug\Module->initPanels()
#28 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\debug\Module->init()
#29 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#30 [internal function]: yii\base\Module->__construct('debug', Object(craft\web\Application), Array)
#31 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#32 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\debug\\Modul...', Array, Array)
#33 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('yii\\debug\\Modul...', Array, Array)
#34 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
#35 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/Application.php(419): yii\base\Module->getModule('debug')
#36 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/Application.php(110): craft\web\Application->debugBootstrap()
#37 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#38 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#39 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/Application.php(97): yii\base\Application->__construct('[<span class="s...')
#40 [internal function]: craft\web\Application->__construct(Array)
#41 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#42 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#43 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#44 /home/vagrant/sites/craft3/vendor/craftcms/cms/bootstrap/bootstrap.php(252): yii\BaseYii::createObject(Array)
#45 /home/vagrant/sites/craft3/vendor/craftcms/cms/bootstrap/web.php(42): require('/home/vagrant/s...')
#46 /home/vagrant/sites/craft3/web/index.php(16): require('/home/vagrant/s...')
#47 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fields.searchable' in 'field list'
The SQL being executed was: SELECT `fields`.`id`, `fields`.`dateCreated`, `fields`.`dateUpdated`, `fields`.`groupId`, `fields`.`name`, `fields`.`handle`, `fields`.`context`, `fields`.`instructions`, `fields`.`searchable`, `fields`.`translationMethod`, `fields`.`translationKeyFormat`, `fields`.`type`, `fields`.`settings`, `fields`.`uid`
FROM `fields` `fields`
WHERE `fields`.`context`='global'
ORDER BY `fields`.`name`, `fields`.`handle` in /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT `fields`...')
#1 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `fields`...')
#2 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#5 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/services/Fields.php(630): craft\db\Query->all()
#6 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1526): craft\services\Fields->getAllFields()
#7 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1072): craft\elements\db\ElementQuery->customFields()
#8 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#10 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#12 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1210): craft\db\Query->one(NULL)
#13 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/elements/User.php(365): craft\elements\db\ElementQuery->one()
#14 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity('1')
#15 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/User.php(421): yii\web\User->renewAuthStatus()
#16 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#17 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/web/User.php(360): yii\web\User->getIdentity()
#18 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/User.php(182): yii\web\User->getIsGuest()
#19 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Component.php(139): craft\web\User->getIsGuest()
#20 /home/vagrant/sites/craft3/vendor/yiisoft/yii2-debug/src/panels/UserPanel.php(79): yii\base\Component->__get('isGuest')
#21 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\debug\panels\UserPanel->init()
#22 [internal function]: yii\base\BaseObject->__construct(Array)
#23 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#24 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\debug\\Use...', Array, Array)
#25 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\debug\\Use...', Array, Array)
#26 /home/vagrant/sites/craft3/vendor/yiisoft/yii2-debug/src/Module.php(182): yii\BaseYii::createObject(Array)
#27 /home/vagrant/sites/craft3/vendor/yiisoft/yii2-debug/src/Module.php(154): yii\debug\Module->initPanels()
#28 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\debug\Module->init()
#29 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#30 [internal function]: yii\base\Module->__construct('debug', Object(craft\web\Application), Array)
#31 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#32 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\debug\\Modul...', Array, Array)
#33 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('yii\\debug\\Modul...', Array, Array)
#34 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
#35 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/Application.php(419): yii\base\Module->getModule('debug')
#36 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/Application.php(110): craft\web\Application->debugBootstrap()
#37 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#38 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#39 /home/vagrant/sites/craft3/vendor/craftcms/cms/src/web/Application.php(97): yii\base\Application->__construct('[<span class="s...')
#40 [internal function]: craft\web\Application->__construct(Array)
#41 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#42 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#43 /home/vagrant/sites/craft3/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#44 /home/vagrant/sites/craft3/vendor/craftcms/cms/bootstrap/bootstrap.php(252): yii\BaseYii::createObject(Array)
#45 /home/vagrant/sites/craft3/vendor/craftcms/cms/bootstrap/web.php(42): require('/home/vagrant/s...')
#46 /home/vagrant/sites/craft3/web/index.php(16): require('/home/vagrant/s...')
#47 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'fields.searchable' in 'field list'
)```

**Comment by khalwat** [comment] 2018-11-28 21:05
After manually running `./craft migrate/all`, everything is good. FWIW, I was on the Plugin Store page in the CP, then did the update, and tried reloading the page... but no migrations ran. I also tried just going to `/admin` to see if it'd pick up the pending migrations, but no dice.

```
vagrant@homestead ~/sites/craft3 $ ./craft migrate/all
Yii Migration Tool (based on Yii v2.0.15.1)

    > add column searchable boolean NOT NULL DEFAULT TRUE AFTER `instructions` to table {{%fields}} ... done (time: 0.050s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.001s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.003s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.001s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.002s)
    > update in {{%fields}} ... done (time: 0.006s)
    > update in {{%fields}} ... done (time: 0.004s)
    > update in {{%fields}} ... done (time: 0.002s)
    > add column config mediumtext NULL DEFAULT NULL to table {{%info}} ... done (time: 0.022s)
    > add column configMap mediumtext NULL DEFAULT NULL to table {{%info}} ... done (time: 0.036s)
    > dropping {{%systemsettings}} if it exists ... done (time: 0.012s)
    > drop column settings from table {{%plugins}} ... done (time: 0.043s)
    > drop column licenseKey from table {{%plugins}} ... done (time: 0.032s)
    > drop column enabled from table {{%plugins}} ... done (time: 0.019s)
    > add column dateDeleted datetime NULL DEFAULT NULL AFTER `dateUpdated` to table {{%sites}} ... done (time: 0.041s)
    > create index sites_dateDeleted_idx on {{%sites}} (dateDeleted) ... done (time: 0.010s)
    > drop index sites_handle_unq_idx on sites ... done (time: 0.011s)
    > create index sites_handle_idx on {{%sites}} (handle) ... done (time: 0.017s)
    > add column dateDeleted datetime NULL DEFAULT NULL AFTER `dateUpdated` to table {{%fieldlayouts}} ... done (time: 0.030s)
    > create index fieldlayouts_dateDeleted_idx on {{%fieldlayouts}} (dateDeleted) ... done (time: 0.010s)
    > add column dateDeleted datetime NULL DEFAULT NULL AFTER `dateUpdated` to table {{%elements}} ... done (time: 0.041s)
    > create index elements_dateDeleted_idx on {{%elements}} (dateDeleted) ... done (time: 0.010s)
    > add column parentId integer AFTER `groupId` to table {{%categories}} ... done (time: 0.024s)
    > add column parentId integer AFTER `sectionId` to table {{%entries}} ... done (time: 0.035s)
    > add foreign key categories_parentId_fk: {{%categories}} (parentId) references {{%categories}} (id) ... done (time: 0.029s)
    > add foreign key entries_parentId_fk: {{%entries}} (parentId) references {{%entries}} (id) ... done (time: 0.041s)
    > update in {{%userpermissions}} ... done (time: 0.001s)
    > update in {{%userpermissions}} ... done (time: 0.001s)
    > add column dateDeleted datetime NULL DEFAULT NULL AFTER `dateUpdated` to table {{%sitegroups}} ... done (time: 0.035s)
    > create index sitegroups_dateDeleted_idx on {{%sitegroups}} (dateDeleted) ... done (time: 0.009s)
    > drop index sitegroups_name_unq_idx on sitegroups ... done (time: 0.005s)
    > create index sitegroups_name_idx on {{%sitegroups}} (name) ... done (time: 0.015s)
    > drop index assets_filename_folderId_unq_idx on assets ... done (time: 0.010s)
    > create index assets_filename_folderId_idx on {{%assets}} (filename,folderId) ... done (time: 0.015s)
    > drop column edition from table {{%info}} ... done (time: 0.025s)
    > drop column name from table {{%info}} ... done (time: 0.018s)
    > drop column timezone from table {{%info}} ... done (time: 0.020s)
    > drop column on from table {{%info}} ... done (time: 0.028s)
    > dropping {{%routes}} if it exists ... done (time: 0.006s)
Migrated up successfully.```

**Comment by brandonkelly** [comment] 2018-11-28 23:11
Duplicate of #3295

**Closed by brandonkelly** 2018-11-28 23:11 UTC
