### ISSUE TITLE
[4.x]: Craft 4.3.1 ignores users desired sorting method in control panel when searching

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#12299] opened 2022-11-11 12:42 UTC
### Description
When you search in the Craft's admin panel, you can select columns to like postDate to sort the entries by your desired field. However, for ever reason, Craft has stared to ignore this sorting. We didn't have these problems in 4.2.x.

Here you can see both the interface, url indicating the sort by postDate
![Schermafbeelding 2022-11-11 om 13 34 56](https://user-images.githubusercontent.com/23024452/201341807-338c2832-3438-4c6f-abce-37e4510c81b5.png)

Here you can see the request actually asking craft to sort by the score
<img width="1103" alt="Schermafbeelding 2022-11-11 om 13 34 30" src="https://user-images.githubusercontent.com/23024452/201342854-0885400d-c39c-49be-8ff7-03b89a721db5.png">

I've tested this with a clean install of Craft 4.3.1, and can confirm it's plug-in related.
### Steps to reproduce

1. Create a craft install
2. Create 2 entries with different postDates
3. Search a query that matches both titles
4. sort by postdate

### Expected behavior
The entries being sorted by postdate

### Actual behavior
the entries being sorted by their score

### Craft CMS version

4.3.1

### PHP version

8.1

### Operating system and version

OSX

### Database type and version

mysql

### Installed plugins and versions

- none

**Comment by i-just** [comment] 2022-11-11 12:59
Sounds like a duplicate of: #12256. You can follow along there for progress.

**Closed by i-just** 2022-11-11 12:59 UTC
Labels: bug, craft4
