### ISSUE TITLE
[4.x]: Missing cp resources when upgrading to Craft 4

### ISSUE THREAD

**Issue by gddotorg** [craftcms/cms#12222] opened 2022-10-28 18:56 UTC
### Description
I'm facing an issue when upgrade to Craft 4. After update and deploying the new version, frontend looks good. But when I call the login screen, all scripts and stylesheets are missing. Browser console shows the following errors:

```
Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Failed to load resource: the server responded with a status of 404 ()
...
```

So I looked up the missing files in the server directory and figured out that the /cpresources folder is missing. I checked the permissions but all seems to be writeable. Also I disabled all plugins and modules, but same result. For test purposes I added alias @webroot, resourceBasePath and resourceBaseUrl as shown here, but nothing changed:

```
        'aliases' => [
            '@web' => App::env('PRIMARY_SITE_URL'),
            '@webroot' => dirname(__DIR__) . '/web',
        ],

        'resourceBasePath' => '@webroot/cpresources',
        'resourceBaseUrl' => '@web/cpresources'
```

As well I checked the server settings and the Craft CMS requirements. Couldn't find any difference to our settings.
Any idea? Did I miss something?

### Steps to reproduce
1. Upgrade Craft CMS version 3.7.46 to 4.3.1
2. Go to /admin/login
3. Styles and Scripts are missing and folder /cpresources is missing

### Expected behavior
Styles and Scripts will be generated and saved under /web/cpresources

### Actual behavior
Styles and Scripts are missing and folder /cpresources is missing

### Craft CMS version

4.3.1 (Pro)

### PHP version

8.1

### Operating system and version

Linux version 5.4.144+

### Database type and version

mariadb 10.5.15

### Installed plugins and versions

-  Asset Rev 7.0.0
-  Blitz 4.2.3
-  CP Field Inspect 1.4.4
-  Empty Coalesce 4.0.0
-  Feed Me 5.0.4
-  Field Manager 3.0.4
-  Formie 2.0.13
-  ImageOptimize 4.0.2
-  KeyChain 4.0.0 
-  MobileDetect 2.0.0
-  Redactor  3.0.2
-  SAML Service Provider 4.0.2
-  SEOmatic 4.0.10
-  Sprig 2.2.1
- Super Table 3.0.3

**Comment by brianjhanson** [comment] 2022-10-28 21:23
Thanks for reaching out! Do you have anything in your `storage/logs` files that might point to the cause? It definitely sounds like a permissions issue as the `cpresources` folder should get created automatically if it's not present (unless you have the [`CRAFT_EPHEMERAL` environment variable](https://craftcms.com/docs/4.x/config/#craft-ephemeral) set)

**Comment by gddotorg** [comment] 2022-10-30 19:26
Thanks for your fast response. Unfortunately I couldn't find any errors or hints in my logs. Only [web.info] and those are "Module loaded" and "Session started". I checked the code for CRAFT_EPHEMERAL but couldn't find anything. I also checked the folder permissions. /web has 755. For test purposes I also checked 777 permissions, but same result.

Do you perhaps have an idea where to find this automatically creation of the resources in the Craft core? Maybe I can find a hint here.

**Comment by brianjhanson** [comment] 2022-10-31 20:35
The creation of that folder will happen [in the `Application::ensureResourcePathExists()`](https://github.com/craftcms/cms/blob/e4e2c151e3831888f75593527f10281791513719/src/web/Application.php#L355-L377) method. That's called within the [main `Application::init()` method](https://github.com/craftcms/cms/blob/e4e2c151e3831888f75593527f10281791513719/src/web/Application.php#L101-L103) as long as Craft isn't set to be ephemeral.

One note, the `CRAFT_EPHEMERAL` setting would be in the `.env` file (or in the environment itself) so it might not show up in a standard search of the code. 

It looks like another possibility is that `resourceBasePath` is getting set to `false` somewhere. 

Can you try adding `CRAFT_RESOURCE_BASE_PATH=@webroot/cpresources` to your `.env` to see if that fixes things? The `CRAFT_` [environment overrides will take priority over other settings](https://craftcms.com/docs/4.x/config/#environment-overrides) so that might help us quickly determine if there's config somewhere messing with things.

**Comment by gddotorg** [comment] 2022-11-03 12:17
@brianjhanson I think I have discovered the problem or I can limit it. In our nginx settings, we set `CRAFT_EPHEMERAL` to `true`. If I set the value to false or delete it, the cpresources files are created.

 I took a closer look at the `App::isEphemeral()` function and found out that there were adjustments from Craft 3 to Craft 4.

// Craft 3
```
    public static function isEphemeral(): bool
    {
        return defined('CRAFT_EPHEMERAL') && CRAFT_EPHEMERAL === true;
    }
```

// Craft 4
```
    public static function isEphemeral(): bool
    {
        return self::parseBooleanEnv('$CRAFT_EPHEMERAL') === true;
    }

```
I had a look what is returned here when `CRAFT_EPHEMERAL` is set to `true`. Craft 3 code returns `false`, and Craft 4 returns `true`.

It's odd because we are running all of our installations with `CRAFT_EPHEMERAL` set to `true`. And we are operating with both Craft major versions. So far we had no problem like this one.

**Comment by brianjhanson** [comment] 2022-11-03 14:01
@gddotorg it sounds like this is working as expected, when `CRAFT_EPHEMERAL` is set, `cpresources` should **not** be created. In Craft 3 `CRAFT_EPHEMERAL` had to be a PHP constant. I'm guessing that means the configuration in nginx config wasn't actually having an effect until 4 when the `isEphemeral()` setting started picking up the environment variable. Admittedly I'm not an expert on nginx configuration, so you might know things I don't there. 

Just to reset a bit, how does this problem manifest? Do the styles & scripts in the CP ever get created? Or are they always broken?

There is a [`buildId`](https://craftcms.com/docs/4.x/config/general.html#buildid) setting which might help here. That will prevent situations where a new node publishes a new cpresources hash, which gets served by an old node and cached by the browser.

**Comment by brianjhanson** [comment] 2022-11-07 14:16
I'm going to close this for the moment, but I'm happy to answer additional questions if you have them.

**Closed by brianjhanson** 2022-11-07 14:16 UTC
Labels: bug, craft4
