### ISSUE TITLE
[4.x]: Creating a draft with unsaved changes overwrite all simple content to other sites

### ISSUE THREAD

**Issue by smcyr** [craftcms/cms#13450] opened 2023-07-18 19:07 UTC
### Description

When you change some content in an entry, it triggers an auto-save with this message "Showing your unsaved changes.". If you create a draft after that, all the non-relational content (textarea, redactor, etc.) from the current site will be copied to the other sites. So, for example, the entry will have all the text fields in English in the French draft except for the matrix or relational fields.

If you create a new draft without doing changes before in the entry, the content isn't copied over the other sites and everything is working as expected.

### Steps to reproduce

1. Do some changes in a text field in an entry in the English site.
2. Click on "Create a draft"
3. Go over the draft in the other site (French for exemple)
4. Now all the text fields are now in English instead of French

### Expected behavior

If you create a draft with unsaved changes, it shouldn't overwrite content in the other sites/languages.

### Actual behavior

If you create a draft with unsaved changes, it overwrites content in the other sites/languages.

### Craft CMS version

4.4.16

### PHP version

8.0.29

### Installed plugins and versions

-

**Comment by i-just** [comment] 2023-07-19 06:45
Closing as duplicate of #13451 (and 13451 has a bit more info).

**Closed by i-just** 2023-07-19 06:45 UTC
Labels: bug, duplicate, craft4
