### ISSUE TITLE
Cannot create a section having the "single" type 

### ISSUE THREAD

**Issue by nstCactus** [craftcms/cms#3508] opened 2018-11-29 17:13 UTC
### Description

Trying to create a *Single* section on Craft 3.1 beta 2 yields the following error:

>`array_keys() expects parameter 1 to be array, null given` in _/app/craft/vendor/craftcms/cms/src/services/Sections.php_ at line 1505

Screenshot of the error attached at the end of the issue.

### Steps to reproduce

1. In the CP, go to Settings > Sections > New section
2. Give it a name and chose the *Single* type  
![Section creation form](https://user-images.githubusercontent.com/353843/49238053-e93b7c80-f3ff-11e8-9caf-175046b6eae7.png)
3. Save

### Additional info

- Craft version: 3.1.0-beta.2
- PHP version: 7.1.20
- Database driver & version: MySQL driver connected to a MariaDB 10 server
- Plugins & versions: 
    * Neo dev-dev-3-port
    * Redactor 2.1.6
    * SEO 3.4.4
    * Super Table 2.0.14
    * Typed link field 1.0.15
    * WebpackAssets 2.0.3
    * ImageOptimize 1.4.44
    * Migration Manager 3.0.10
    * SimpleMap 3.3.3
- Creating *structure* and *channel* sections works as expected. 
- Changing the type of an existing section to *single* doesn't yield an error right away but then the entry in this section can't be edited (`yii\web\NotFoundHttpException` in _/app/craft/vendor/craftcms/cms/src/controllers/EntriesController.php_ at line 822)

### Screenshot
![Error page](https://user-images.githubusercontent.com/353843/49238268-59e29900-f400-11e8-8233-dac088f02dbe.png)

**Comment by brandonkelly** [comment] 2018-11-29 19:57
Duplicate of #3506

**Closed by brandonkelly** 2018-11-29 19:57 UTC
