### ISSUE TITLE
FR: Ability to see field handle in field layout page

### ISSUE THREAD

**Issue by swthate** [craftcms/cms#4158] opened 2019-04-18 20:56 UTC
I apologize if this is a duplicate or is already included in a milestone.

When designing the field layout for an entry type it sometimes would be helpful to have the ability to quickly view the handle of a given field, as sometimes the field name and its handle are not always the same.

**Comment by richhayler** [comment] 2019-04-19 08:43
I second this request but for a slightly different reason. There are times when you have two fields with different handles but the label is the same so occasionally you may have to guess which field you are selecting. You can of course put the two fields in different field groups so it’s easier to identify them from each other but I agree, maybe hovering over the field and it displays its field handle could be a solution.

**Comment by brandonkelly** [comment] 2019-04-22 18:30
Duplicate of #962. And worth noting that Craft will reveal the field handle as `title` text when hovering over a field name.

**Closed by brandonkelly** 2019-04-22 18:30 UTC
