### ISSUE TITLE
Subfolders in assets view are broken

### ISSUE THREAD

**Issue by medoingthings** [craftcms/cms#2287] opened 2018-01-09 11:17 UTC
### Description
The subfolders were already a bit broken in RC3 (icon placement off, a little hard to click the arrow that shows the subfolders) but now, in RC4, it seems to be completely broken.

I don’t see any indicator that there are any folders (even though there are). To show the folders I have to go into the DOM and remove the display:none: from the list with the subfolders. Then I can see the subfolders.

### Steps to reproduce

1. Go to admin/assets
2. Create a subfolder
3. Try to access the subfolder. It’s invisible.

### Additional info
We installed Craft in RC2, updated to RC3 and lately to RC4.

- Craft version: Craft Pro 3.0.0-RC4
- PHP version: 7.2.0
- Database driver & version: MySQL 5.5.5-10.2.12-MariaDB-10.2.12+maria~jessie
- Plugins & versions: 
-- Element API 2.5.2
-- Redactor 1.0.0.1
-- Amazon S3 1.0.8

**Comment by brandonkelly** [comment] 2018-01-09 14:19
This is a duplicate of #2264.

**Closed by brandonkelly** 2018-01-09 14:19 UTC
