### ISSUE TITLE
Site switches when navigating between Entries and Globals

### ISSUE THREAD

**Issue by mijewe** [craftcms/cms#4203] opened 2019-05-01 13:25 UTC
### Description
I've got a multi-site setup.
I'm set to Site B while navigating around the Entries area of the CP.
I go to the Globals area of the CP.
It's switched to Site F (not necessarily the default site, not the previous site I was editing).

I would expect the CP to stay on the site I chose throughout. I've entered content into the wrong sites a few times now :(

### Steps to reproduce

1. Have a multi site set up
2. In the CP, go to Entries and switch to Site 1
3. Navigate to Globals, and observe the CP no longer being on Site 1

Example vid here: https://www.loom.com/share/03d4651ffd724144b4ae63a302c374d0
Turns out my headphone mic wasn't on but you get the idea.

### Additional info

- Craft version: 3.1.25
- PHP version: 7.1.25
- Database driver & version: MySQL 5.5.5
- Plugins & versions: (none - disabled all for the test)

**Comment by brandonkelly** [comment] 2019-05-01 14:01
Duplicate of #4203

**Closed by brandonkelly** 2019-05-01 14:01 UTC
