### ISSUE TITLE
Dropdown in Matrix not preserving value on not enabled elements

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#4142] opened 2019-04-15 17:19 UTC
### Description
On elements that are not enabled, changing the value in a dropdown in a matrix are not preserving. It appears to work fine for elements that are already enabled.

Field settings:
<img width="1215" alt="Screen Shot 2019-04-15 at 1 12 24 PM" src="https://user-images.githubusercontent.com/199985/56151926-66672880-5f80-11e9-9844-187e7bec0388.png">

Video showing bug:
https://drive.google.com/file/d/1O2qE3cbVkpCm4lxy6CQ0x08Njq-rUNxW/view?usp=sharing

### Steps to reproduce

1. Create a matrix field with a dropdown field within it
1. Add matrix field to an element's field layout
1. Try changing the value of the dropdown on a non-enabled element

### Additional info

- Craft version: Craft Pro 3.1.22
- PHP version: 7.0.33
- Database driver & version: MySQL 5.7.25
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Amazon S3</th>
                        <td>1.2.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>6.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Authorize.net for Craft Commerce</th>
                        <td>1.0.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Campaign Monitor Service</th>
                        <td>1.0.6</td>
                    </tr>
                                    <tr>
                        <th class="light">Cookies</th>
                        <td>1.1.11</td>
                    </tr>
                                    <tr>
                        <th class="light">Craft Commerce</th>
                        <td>2.1.3.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Dimensions</th>
                        <td>2.0.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Environment Label</th>
                        <td>3.1.5</td>
                    </tr>
                                    <tr>
                        <th class="light">Inlin</th>
                        <td>2.1.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Pricing Tiers</th>
                        <td>1.1.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.3.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Retour</th>
                        <td>3.1.9</td>
                    </tr>
                                    <tr>
                        <th class="light">Sentry</th>
                        <td>1.5.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Sidebar Toggle</th>
                        <td>2.0.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Smart Map</th>
                        <td>3.2.2.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Spoon</th>
                        <td>3.3.6</td>
                    </tr>
                                    <tr>
                        <th class="light">Sprout Fields</th>
                        <td>3.2.8</td>
                    </tr>
                                    <tr>
                        <th class="light">Sprout Forms</th>
                        <td>3.0.0-beta.50</td>
                    </tr>
                                    <tr>
                        <th class="light">Sprout Import</th>
                        <td>1.0.0-beta.25</td>
                    </tr>
                                    <tr>
                        <th class="light">Sprout Reports</th>
                        <td>1.1.5</td>
                    </tr>
                                    <tr>
                        <th class="light">Video Embed</th>
                        <td>1.2.1</td>
                    </tr>
                            </tbody>
        </table>

**Comment by brandonkelly** [comment] 2019-04-16 15:19
I’m not able to reproduce this. Can you send your `composer.json` and `composer.lock` files, a database backup, and a zip of any other packages you might be requiring via `composer.json` that aren’t on Packagist, over to support@craftcms.com, and reference this issue?

**Comment by davist11** [comment] 2019-04-16 15:47
Sent, thanks!

**Comment by angrybrad** [comment] 2019-04-30 19:03
Successfully resolved in https://github.com/craftcms/cms/releases/tag/3.1.23

**Closed by angrybrad** 2019-04-30 19:03 UTC
