### ISSUE TITLE
[Feature Request] Default focal point setting per Asset volume or field

### ISSUE THREAD

**Issue by stevehurst** [craftcms/cms#3744] opened 2019-01-29 16:12 UTC
We have a large Assets volume of profile pictures and headshots oriented to 5x7, but frequently have a need for square crops of the image. By default on a portrait, this results in a center crop on the chest and chin. There are likely other use cases where a focal point not set to center by default would be useful in transforms. You could set this default per Asset volume or field.

**Comment by brandonkelly** [comment] 2019-01-29 19:58
Duplicate of #1906

**Closed by brandonkelly** 2019-01-29 19:58 UTC
