### ISSUE TITLE
Can't create new content after upgrade to Craft 3.6

### ISSUE THREAD

**Issue by anbod-io** [craftcms/cms#7507] opened 2021-02-05 08:08 UTC
### Description
Over the weekend I upgraded sites for several clients, upgrading from 3.5.17 to 3.6.2 (one of which also later was upgraded to 3.6.3)

On all sites existing live content can mostly still be edited and saved, although lightswitches (to set status enable/disable for example) no longer respond, and the previously present drop-down on the Save button no longer responds. Clicking Save itself will save changes as expected.

When trying to create new content, light-switch elements do not react, the save dropdown is not available. The save as draft button "seems" to work, but I have not found any magic combination of actions which will then actually publish the draft.

This smells liked borked JS in the console, does it not?

At any rate, I have angry clients and no clue what to do. 
Anybody seen this as well?

### Additional info

- Craft version: 3.6.2, 3.6.3
- PHP version: 7.4
- Database driver & version:
- Plugins & versions:

**Comment by angrybrad** [comment] 2021-02-05 19:21
Are you getting any JS errors in your browser's console? Can you share them?

**Comment by brandonkelly** [comment] 2021-02-05 20:36
@anbod-io This is most likely a duplicate of #7492. We just released Craft 3.6.4 with a fix.

**Closed by brandonkelly** 2021-02-05 20:36 UTC
Labels: bug
