### ISSUE TITLE
Dealing with aliases and environment variables containing special characters ($, @)

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#3769] opened 2019-02-01 14:30 UTC
### Description

We store our database credentials, among other things, in the environment and use auto-generated passwords. This has caused an issue with the move to autosuggest fields and the use of environment variables/aliases in the CP since frequently, our passwords contain or even start with "@" or "$". This causes a pretty nasty error in the CP displaying the password in question:

![image](https://user-images.githubusercontent.com/3810939/52128618-7028f300-2603-11e9-83cf-693d12aa1dc2.png)

I'm not sure what the best way around this is, but disallowing these characters in passwords/forcing people to change passwords to less secure ones doesn't feel like the right approach. 

### Steps to reproduce

1. Use a password in env with an "@" or "$"
2. Try to use an autosuggest field in the CP

### Additional info

- Craft version: 3.1.7
- PHP version: 7.2.13
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by brandonkelly** [comment] 2019-02-01 15:04
This seems like a duplicate of #3700, which we fixed in 3.1.4. That `$throwException` variable in the condition shown in your screenshot is set to `false` now (b40d9c76e337657ca3b777b0c7aff91b1a72a34f).

You sure you’re actually running 3.1.7? Check line 85 of `vendor/craftcms/cms/src/Craft.php` and confirm it looks like this:

https://github.com/craftcms/cms/blob/d7d9166144138f7794510f816b776bb1ff6761b3/src/Craft.php#L85

If not, there may have been an issue when updating previously. Try nuking your `vendor/` folder and run `composer update`.

If it does, then maybe it’s a opcache issue?

**Comment by Mosnar** [comment] 2019-02-01 15:39
You're right! After further inspection, it looks like this is specifically affecting my S3 Volumes rather than all of them as I previously thought. It looks like S3's Volume.php is still using parseEnv without silencing exceptions:
```php
Craft::parseEnv($this->cfDistributionId),
```

**Closed** 2019-02-02 08:11 UTC

**Comment by brandonkelly** [comment] 2019-02-02 08:13
Ahhh, thanks for looking into it! Just fixed that for the next release.

You can patch your install to get the fix now by changing your `craftcms/cms` requirement in composer.json to:

```json
"require": {
    "craftcms/cms": "dev-develop#0bf918445ea2db832bdbd843705dfc08d05a678d as 3.1.7",
    "...": "..."
}
```

Then run `composer update`.
