### ISSUE TITLE
Table field with many columns overflows container

### ISSUE THREAD

**Issue by missmatsuko** [craftcms/cms#7317] opened 2020-12-22 07:47 UTC
### Description

I made a big table field and it's overflowing and overlapping the edit entry sidebar.

<img width="944" alt="Screenshot of table field with many columns." src="https://user-images.githubusercontent.com/17884198/102862858-9833c200-43e6-11eb-8c36-7c5cffedff60.png">

### Steps to reproduce
1. Make a table field with a bunch of columns.

### Additional info
- Craft version: 3.5.17.1

**Comment by Mosnar** [comment] 2020-12-23 15:44
Duplicate of #6074

**Closed** 2020-12-23 18:04 UTC
Labels: bug
