### ISSUE TITLE
SQL Error For utils/repair/section-structure console command when running PostgreSQL

### ISSUE THREAD

**Issue by erktime** [craftcms/cms#7753] opened 2021-03-31 19:54 UTC
### Description
When craft is running on PostgreSQL, the `utils/repair/project-config` console command throws a SQL error:

```
Exception 'yii\db\Exception' with message 'SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  CASE types timestamp without time zone and integer cannot be matched
LINE 17: ...WHEN ("structureelements"."lft" IS NOT NULL) THEN 0 ELSE "el.
```

I can't confirm the fix works for mySQL, but I fixed locally by changing this line:
https://github.com/craftcms/cms/blob/b74536290ac47ee3e75cd9903660f1f70f00b378/src/console/controllers/utils/RepairController.php#L124

to:
```php
new Expression('CASE WHEN ([[structureelements.lft]] IS NOT NULL) THEN DATE \'0001-01-01\' ELSE [[elements.dateCreated]] END ASC'),
```

### Steps to reproduce

1. Have craft running on postgresql.
2. Have a section of type structure.
3. Execute the console command: `./craft utils/repair/section-structure [sectionHandle]`

### Additional info

- Craft version: Craft Pro 3.6.10
- PHP version: 7.2.34
- Database driver & version: PostgreSQL 9.6.16
- Plugins & versions:

**Comment by brandonkelly** [comment] 2021-03-31 22:16
This looks like a duplicate of #7699, which was fixed in Craft 3.6.11.

**Closed by brandonkelly** 2021-03-31 22:16 UTC
Labels: bug

**Comment by erktime** [comment] 2021-03-31 23:13
You're right. Thanks @brandonkelly. And here I thought I did a decent search of existing issues before filing the ticket. Sorry for the noise.

**Comment by michaelroper** [comment] 2021-04-13 17:39
Hey @erktime - if you've been using the repair structure command in the last few weeks, you might want to grab the latest Craft v3.6.12, as it has a fix for the fix that fixed this issue. 😁  (ref #7784)
