### ISSUE TITLE
Unable view/activate plugins through the Control Panel (Chrome 63)

### ISSUE THREAD

**Issue by mcntsh** [craftcms/cms#2295] opened 2018-01-11 17:39 UTC
### Description

Trying to open any plugin modal in the Plugin Store results in an infinite spinner while trying to fetch the plugin description. This is problematic when you have installed plugins through composer, and need to activate them through the control panel.

### Steps to reproduce

1. Navigate to the Plugin Store with Google Chrome (incognito mode)
2. Open up any plugin modal

### Additional info

- Craft version: Craft Personal 3.0.0-RC5
- PHP version: 7.1.5
- Database driver & version: MySQL 5.7.19-log
- Plugins & versions: Amazon S3 (1.0.8)
--

**Comment by brandonkelly** [comment] 2018-01-11 18:18
Closing as this is a duplicate of #2289.

> This is problematic when you have installed plugins through composer, and need to activate them through the control panel.

Once you have Composer-installed a plugin, you can finish its installation from Settings → Plugins, not the Plugin Store.

**Closed by brandonkelly** 2018-01-11 18:18 UTC
