### ISSUE TITLE
[Bug] Undefined offset when trying to save a Single

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#2395] opened 2018-02-02 18:45 UTC
### Description
[Here is a screenshot](https://goo.gl/WkquSd) of the error i am getting when trying to save a single.  It looks like in some cases [the value that exists at array[0] does not exist in both arrays](https://goo.gl/1AYhic), so it gets omitted from the combined array.  Then, when the `'siteId' => $persistentSiteIds[0],` assignment is attempted, the above error occurs.

### Steps to reproduce

1. Create a multisite install with at least 3 sites.
2. Enable only 1 site
3. Save
4. Try enabling an additional site
5. For me this fails consistently, however i'm not sure if there are other factors involved or potentials instances where this might succeed.

### Additional info

- Craft version: RC-8
- PHP version: 7
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment] 2018-02-02 23:26
Duplicate of #2385 (& fixed for RC9).

**Closed by brandonkelly** 2018-02-02 23:26 UTC
