### ISSUE TITLE
[3.4beta] Admin CP section edit links point to incorrect page

### ISSUE THREAD

**Issue by michaelroper** [craftcms/cms#5340] opened 2019-12-14 12:16 UTC
### Description

In the admin CP, the section edit links on `/admin/settings/sections` are pointing to entry types listing page (`/admin/settings/sections/2/entrytypes`) instead of the section edit page `/admin/settings/sections/2`. The only way to get back to the section edit page is via the breadcrumb after you're on the entry types listing page.

### Steps to reproduce

1. Go to the _Settings -> Sections_ page, and click on a section name in the first column.
2. You will be on the entry types listing page for that section, instead of the section edit page

### Additional info

- Craft version: 3.4.0-beta.3

**Comment by brandonkelly** [comment] 2019-12-15 15:50
Duplicate of #5339

**Closed by brandonkelly** 2019-12-15 15:50 UTC
