### ISSUE TITLE
Prevent Page Drafts from Being Published by Mistake

### ISSUE THREAD

**Issue by PatrickMessierGoC** [craftcms/cms#6630] opened 2020-08-13 21:10 UTC
### Description
With Craft CMS 3.4:
If a page is published (enabled) then the Save button or the CNTL-S keys saves and publishes the changes. 
If a page is not published (disabled) then the Save button or the CNTL-S keys just saves the changes. 

When working on an page draft, changes are automatically saved as they are entered so there are no need to hit the CNTL-S keys to save changes. Unfortunately, publishers sometime "mechanically" hit the "cntl-s" keys when working on a live (enabled) page draft with the "catastrophic" result of instantly publishing their draft before being done.

Suggestions:
1. Disable the CNTL-S shortcut when editing a page draft; or
1. Prompt the users to confirm the publishing of the draft when CNTL-S is pressed on a live (enabled) page draft; or
1. Always prompt the users to confirm the publishing of their changes when CNTL-S is pressed on a live (enabled) page.

**Comment by brandonkelly** [comment] 2020-08-13 21:40
This sounds like a duplicate of #6199, and we’ve already implemented this change in Craft 3.5.0 :)

**Closed by brandonkelly** 2020-08-13 21:40 UTC
Labels: enhancement

**Comment by PatrickMessierGoC** [comment] 2020-08-13 21:50
Thanks for the quick reply and sorry for not having picked up the duplicate...
