### ISSUE TITLE
Set Status Option "Disabled Globally" shouldn't be available if user is not allowed to edit all languages

### ISSUE THREAD

**Issue by dennismeissner** [craftcms/cms#5280] opened 2019-11-28 11:14 UTC
### Description
If a user is assigned to the following sites:
- english
- german

And he is not assigned to the following sites:
- italian
- french

He is actually able to disable entries in locales he has no rights for by using the dropdown in the Entries Index Page (disabled globally).

It would be useful to have a permission on section level, if this option should be available at all.  (seems more like an admin feature for me)

### Steps to reproduce

1. Be assigned to less than "all" enabled sites
2. Go to entries
3. in the List of entries use the checkbox to select an entry
4. Use the "Set status" dropdown and chose: "Disabled globally"
5. Now the entry is disabled globally, even though i do not have the permission to edit italian or french version of the entry.

### Additional info

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: ...
- Plugins & versions: ...

**Comment by brandonkelly** [comment] 2019-11-30 16:24
This is a duplicate of #2817.

**Closed by brandonkelly** 2019-11-30 16:24 UTC
