### ISSUE TITLE
Craft 3.5.3 - too many redirects error when entering control panel

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6616] opened 2020-08-12 15:47 UTC
This problem occurs on a windows machine with xampp server. When i try to enter control panel, it shows "too many redirects" browser error. 

Happens on any browser, clearing cache/cookies etc did helped. The problem occurs only on `3.5.3`, works fine on `3.5.2`.

**Comment by brandonkelly** [comment] 2020-08-13 12:59
Sounds like a duplicate of #6579, which has been fixed for the next release.

**Closed by brandonkelly** 2020-08-13 12:59 UTC
Labels: bug

**Comment by brandonkelly** [comment] 2020-08-13 13:00
Actually, forgot #6579 was originally about a different issue, so will go with this one as the main issue that that bug fix references. (Redirect report came at https://github.com/craftcms/cms/issues/6579#issuecomment-672371062.)

**Comment by brandonkelly** [comment] 2020-08-13 21:06
Craft 3.5.4 is out now with the fix for this.

**Comment by peimansh** [comment] 2021-04-07 10:00
I'm experiencing same issue on 3.6.11.2
Was working fine on 3.4.30.
It's a bit different in my case as when I try to login using /admin/login , the login process happens as it should and it’s fast. 
But when I try to login using /admin , it then redirects to /admin/login and after entering username and password, the issue occurs and after jumps between /admin and /admin/login a few times, then it returns “Too many redirects” error and then shows /admin/dashboard and opens CP

**Comment by brandonkelly** [comment] 2021-04-07 17:38
@peimansh Sounds like a session bug. Is this on a load-balanced environment? If so be sure to read through the [Configuring Craft for Load Balanced Environments](https://craftcms.com/knowledge-base/configuring-load-balanced-environments) guide, particularly the “PHP Sessions” section.

Either way, please email support@craftcms.com if you need any further help.

**Comment by peimansh** [comment] 2021-04-08 14:14
@brandonkelly I guess it's not related to load-balanced environment.
I can rule out both load-balanced environment and Nginx configs.
It's not Nginx configs because it doesn't happen on local dev (both staging and local dev share same Nginx configs)
and It's not load balancers because when I reach Craft using direct URL to AWS ALB (bypassing Cloudfront) the issue disappears!
So my guess is either Cloudfront or Craft. We have not recently changed anything regarding Cloudfront Configs so I suspect something regarding these has been changed in 3.5/3.6

**Comment by peimansh** [comment] 2021-04-08 14:48
Check out this video @brandonkelly :

https://user-images.githubusercontent.com/32059257/114047748-36f70800-988a-11eb-9dfa-7940e6dace64.mov

**Comment by brandonkelly** [comment] 2021-04-08 16:29
@peimansh We’ll continue following up with you about it in support.
