### ISSUE TITLE
Enabling / Disabling an entry on a tableview ignores required fields

### ISSUE THREAD

**Issue by mathiasgomig** [craftcms/cms#2599] opened 2018-03-19 16:21 UTC
### Description
Let's say we have a disabled entry with some empty required fields. If you try to enable the entry through the edit screen it fails and displays the error message "Couldn’t save entry." and "{attribute} cannot be blank." foreach required field that is not valid. So far, so good.

![saving-on-edit-screen](https://user-images.githubusercontent.com/4096309/37607888-71fd0974-2b99-11e8-8637-f9e1827868ce.png)

If you go to the Channel / Structure or Single tableview (where you can see the list of entries) and enable an entry through the "Set Status" button, there is no validation that would prevent you from enabling the entry. 

![saving-on-tableview](https://user-images.githubusercontent.com/4096309/37607900-772a28b4-2b99-11e8-8216-061945a7534f.png)

Is there a reason why there is no validation for this action?

### Steps to reproduce

1. Mark one or more fields required for any given section
2. Create a new entry in that section, don't fill out the required field(s)
3. Try to publish it – you should see the error message
4. Save it as a draft
5. Go to the Channel / Structure or Single tableview of that section
6. Try to set the status of that entry to enabled – it works and doesn't validate the required fields.

### Additional info

- Craft version: 2.6.3000 (Craft Demo)
- PHP version: 7.2
- Database driver & version: 5.7
- Plugins & versions: none

**Comment by brandonkelly** [comment] 2018-03-21 20:11
Duplicate of #2 (and fixed in Craft 3). Unfortunately it was not possible for us to fix this without some major refactoring, so we aren’t able to backport the fix to Craft 2.

**Closed by brandonkelly** 2018-03-21 20:11 UTC
