### ISSUE TITLE
An author field attached to an entry breaks the recent posts widget

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#2548] opened 2018-03-07 14:52 UTC
### Description
When you have an `author` textfield attached to an entry, and save a new entry. The recent posts widget breaks as it tries to access the object author.

### Steps to reproduce

1. Create a textfield with the handle `author`
2. Attach it to an entry
3. Create a new entry
4. Go to the dashboard and see it fail

### Additional info

- Craft version: 3-RC14
- PHP version: 7.1

**Comment by brandonkelly** [comment] 2018-03-08 11:52
Technically a duplicate of #2522 but this is a little more clear so I’ll keep it open.

**Closed** 2018-03-08 12:45 UTC
