### ISSUE TITLE
FR: Selected Site Persistance Across the Control Panel

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#5756] opened 2020-03-05 00:53 UTC
**It would be great on multi-site setups if the selected site would persist when navigating the CraftCMS control panel.** 

For example if selecting SiteB from the site dropdown on the entries index page and then navigating to globals it would be great if globals were displayed for SiteB by default. Instead the control panel reverts to SiteA. Navigating back to the entries index page persists the selected site, i.e. SiteB.

Additionally it would be great to extend this persistence so plugin developers could leverage the functionality so plugins that have multi-site specific settings would automatically show the settings for the selected site.

Another idea for an alternative approach could be providing a dropdown near the control panel logo (top left) which would allow selection of a specific site and use this deliberate action to set the selected site persistence across the control panel.

_**It's frustrating jumping into the control panel to edit content and settings for a specific site and constantly having to check and then select the site across control panel and plugin page screens.**_

**Comment by brandonkelly** [comment] 2020-05-20 23:12
This is a duplicate of #2779, and has been resolved for Craft 3.5.

**Closed by brandonkelly** 2020-05-20 23:12 UTC
Labels: duplicate
