### ISSUE TITLE
Have a view-only permission level per section

### ISSUE THREAD

**Issue by JoshCoady** [craftcms/cms#6837] opened 2020-09-15 16:39 UTC
### Description

I would like to be able to allow users to view any entries they are not allowed to edit. I imagine this as having "View entries" as the top-level permission checkbox under each section and then "Edit entries" is under that.

At a basic level we could allow users to see the information in sections we do not want to allow them to make modifications in.

A more complex use-case is we have a multi-site that is for a site with multiple subdomains. Certain authors are only allowed to edit content on certain subdomains (sites), but we'd like them to be able to see all of the content because they might want to locate similar content on other subdomains to link to it and other things of that nature.

But I guess this is a little more complicated because we'd also need the ability to set groups/permissions per site (like put someone in the Viewer group for sites A and B and in the Writer group for sites C and D). I have described this aspect in a separate issue (#6836) because it is useful on its own.

**Comment by brandonkelly** [comment] 2020-09-15 17:52
This is a duplicate of #6522. The only aspect that was unique about your request is the per-site part (#6836).

**Closed by brandonkelly** 2020-09-15 17:52 UTC
Labels: enhancement, user management :innocent:
