### ISSUE TITLE
[IMPROVEMENT] After selecting a category in the plug-in store, the other dissapear

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#2629] opened 2018-03-23 08:07 UTC
If you choose a category in the back-end of Craft 3's Plugin Store, the sidebar goes away, and you'd have to use the browsers back button to get them to appear again.

Would be more user friendly if they would remain in the sidebar, making it easier to navigate.

**Comment by brandonkelly** [comment] 2018-03-23 11:51
Duplicate of #2146

**Closed by brandonkelly** 2018-03-23 11:51 UTC
