### ISSUE TITLE
GraphQL: Fetching images in a matrix field within a super table field fails

### ISSUE THREAD

**Issue by peirix** [craftcms/cms#5998] opened 2020-04-30 10:48 UTC
### Description
When trying to fetch assets in a matrix field within a super table field the array is always empty.

### Steps to reproduce

1. Create a super table field
2. Create a matrix field within it
3. Create a block with an asset field
4. Try to fetch those images from Graph QL

### Additional info

- Craft version: 3.4.17
- PHP version: 7.2.29
- Database driver & version: mysql 5.9
- Plugins & versions: super table 2.4.9

**Comment by peirix** [comment] 2020-04-30 10:55
Just realized this might be a bug with super table? Posted an issue there as well. So feel free to close this if you think it's in super table domain.

**Comment by bzin** [comment] 2020-05-01 13:04
Might be something related to Craft and Super Table versions @peirix ?!

I am currently working on a project that has a Matrix fields also with SuperTable fields in it and these have Assets entries. I am able to use GraphQL API without any issue.

Also, do double check that your Assets Volumes are in the enabled in the schema you are using.

I am with SuperTable 2.4.9 and Craft CMS  3.4.17.1

**Comment by peirix** [comment] 2020-05-02 16:47
@bzin Thanks, but I have the opposite setup. A super table field that has matrix fields in it. And fetching assets from regular assets fields works great. And yesterday I tested having a an asset field in a matrix in a neo (instead of super table) and that worked. So I'm guessing this is a super table issue.

**Comment by brandonkelly** [comment] 2020-05-04 23:32
@peirix Can you post the Super Table issue link?

**Comment by peirix** [comment] 2020-05-05 07:25
@brandonkelly Sure: https://github.com/verbb/super-table/issues/354

**Comment by andris-sevcenko** [comment] 2020-05-05 07:45
I'm unable to reproduce this with Craft 3.4.17 and SuperTable 2.4.9

Any chance it's a schema issue? Are the relevant asset volumes in it?

**Comment by peirix** [comment] 2020-05-05 08:09
That's so weird. Both me and a co-worker managed to reproduce it with fresh Craft installations. It can't be schema issue, because fetching images from the same asset source in an asset field that was _not_ in the supertable+matrix setup worked fine. And also, as I noted above, switching it for a matrix inside a neo worked fine.

**Comment by andris-sevcenko** [comment] 2020-05-05 08:22
Hmm. Maybe try clearing Craft caches using the "Clear caches" utility?

**Comment by peirix** [comment] 2020-05-12 06:07
Ooop! Forgot to answer this. Tried this as well. No good. I can send you my setup if you'd like? I tried setting up a new craft from scratch and got the same result.

**Comment by andris-sevcenko** [comment] 2020-05-12 07:18
@peirix sure! Send the database, composer.lock, and composer.json files over to support@craftcs.com and reference this issue.

**Comment by andris-sevcenko** [comment] 2020-05-14 10:52
Okay, so I fixed this for 3.5 (next release).

Essentially, it's because Matrix can't be eager-loaded when nested in SuperTables (https://github.com/verbb/super-table/issues/107#issuecomment-366925381), but GraphQL eager-loads everything aggressively.

3.5 refactored eager-loading condition to a much more maintainable and a little bit smarter behavior, but didn't factor in "broken" eager-loading chains when nested inside an element. Aren't edge-cases fun?

Anyway, this will be fixed in the next 3.5 release, however take note, that instead of O(k + 1) [where k is the number of eager-loaded fields] the query count in such cases will be larger, the key factor being the number of elements returned with the initial query that contain the supertable fields.

**Closed** 2020-05-14 13:00 UTC
