### ISSUE TITLE
Creating an entry as a child removes parent on save

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#6194] opened 2020-06-09 14:26 UTC
### Description

When you create a new entry and try to give it a parent, it doesn't save it as a child of the parent, it just saves it at level 1.

### Steps to reproduce

1. Create a new entry, and select a parent entry using the entries button on the right sidebar
2. Click Save
3. The entry is created at level 1, not under the parent entry

Create entry with parent selected:
![image](https://user-images.githubusercontent.com/1250017/84160112-7b512600-aa76-11ea-8ee5-6d6609537891.png)

After saving, they're both top level pages
![image](https://user-images.githubusercontent.com/1250017/84160133-81470700-aa76-11ea-9f04-09b1dbcc9b8d.png)

This is a Structure, with max level 2

### Additional info

- Craft version: 3.4.22.1
- PHP version: 7.4.6
- Database driver & version: MySQL
- Plugins & versions: None

**Comment by brandonkelly** [comment] 2020-06-09 21:16
This is a duplicate of #6168, and we just released Craft 3.4.23 with a fix for it :)

**Closed by brandonkelly** 2020-06-09 21:16 UTC

**Comment by darylknight** [comment] 2020-06-10 06:07
Thanks Brandon. Sorry, I did search for a duplicate before posting but I was looking for open issues and the duplicate was closed a week ago.
