### ISSUE TITLE
Could not generate a unique URI based on the URI format.

### ISSUE THREAD

**Issue by nmann4789** [craftcms/cms#4791] opened 2019-08-21 17:40 UTC
### Description
Unable to save as new entry after updating slug

### Steps to reproduce

1. Change Title
2. Change Slug
3. Save as New Entry

### Additional info

- Craft version:Craft Pro 3.2.8
- PHP version:7.2.14
- Database driver & version: MySQL 5.7.25
- Plugins & versions:

Can provide DB upon request.

**Comment by brandonkelly** [comment] 2019-08-22 05:09
Sounds like a duplicate of #4759, which has been fixed for the next release.

**Closed by brandonkelly** 2019-08-22 05:09 UTC

**Comment by ljfreelancer88** [comment] 2020-03-13 22:53
I'm seeing this kind of error on my new installation.

**Comment by brandonkelly** [comment] 2020-03-15 11:25
@ljfreelancer88 check your section’s settings – what is your Entry URI Format?

The Title field can be hidden if you had disabled it from your section’s entry type settings.

**Comment by rayhvh** [comment] 2020-04-06 10:17
I've got this issue when making an searchPage entry / section. 
then trying to create an entry for this.

**Comment by Moucky** [comment] 2020-04-17 01:04
I seem to be experiencing a similar problem, my URI format is "section/{slug}". It used to be that if an entry had the same title(there are a lot of Untitled titles) it would have a slug like "untitled-2". Some even seem to have "untitled-1-34" and so forth. It seems I've reached some sort of limit or perhaps something changed in an update?

**Comment by brandonkelly** [comment] 2020-04-17 17:28
@Moucky Have you set a custom [maxSlugIncrement](https://docs.craftcms.com/v3/config/config-settings.html#maxslugincrement) config setting value?

**Comment by Moucky** [comment] 2020-04-17 21:15
I haven't @brandonkelly, that's for the suggestion. I'd say that's the problem. Is it possible to have no limit or should I just set it to a very high number?

**Comment by brandonkelly** [comment] 2020-04-20 16:33
It’s 100 by default. You can set it as high as you want. It just takes a little time to keep checking for a unique slug.

**Comment by Moucky** [comment] 2020-04-20 20:53
Thanks so much, that's solved the issue for me.
