### ISSUE TITLE
Duplicate entry fixtures being appended to each unit test

### ISSUE THREAD

**Issue by aaronbushnell** [craftcms/cms#4663] opened 2019-07-26 21:09 UTC
### Description
When I use entry fixtures in my unit tests the number of entries keeps increasing with each test ran. It appears user fixtures work correctly, though!

Here's how my tests and fixtures are setup:

**tests/fixtures/data/entries.php**
```php
<?php

return [
    [
        "sectionId" => $this->sectionIds['example'],
        "typeId" => $this->typeIds['example']['example'],
        "title" => "My Entry 1"
    ],

    [
        "sectionId" => $this->sectionIds['example'],
        "typeId" => $this->typeIds['example']['example'],
        "title" => "My Entry 2"
    ],

    [
        "sectionId" => $this->sectionIds['example'],
        "typeId" => $this->typeIds['example']['example'],
        "title" => "My Entry 3"
    ]
];
```

**tests/unit/ExampleTest.php**
```php
<?php

namespace myprojecttests;

use Codeception\Test\Unit;
use UnitTester;

use Craft;
use craft\elements\User;
use craft\elements\Entry;

use myprojecttests\fixtures\UsersFixture;
use myprojecttests\fixtures\EntriesFixture;

class ExampleTest extends Unit
{
    // Public properties
    // =========================================================================

    /**
     * @var UnitTester
     */
    protected $tester;

    // Public methods
    // =========================================================================
    public function _fixtures(): array
    {
        return [
            'entries' => [
                'class' => EntriesFixture::class
            ],
            'users' => [
                'class' => UsersFixture::class
            ],
        ];
    }

    // Tests
    // =========================================================================
    public function test1()
    {
        $this->assertEquals(3, User::find()->total()); // PASS - 3
        $this->assertEquals(3, Entry::find()->section(['example'])->total()); // PASS - 3
    }

    public function test2()
    {
        $this->assertEquals(3, User::find()->total()); // PASS - 3
        $this->assertEquals(3, Entry::find()->section(['example'])->total()); // FAIL - 6
    }

    public function test3()
    {
        $this->assertEquals(3, User::find()->total()); // PASS - 3
        $this->assertEquals(3, Entry::find()->section(['example'])->total()); // FAIL - 9
    }
}
```

### Additional info

- Craft version: 3.2.7
- PHP version: 7.1.26
- Database driver & version: MySQL 5.7.24

**Comment by gtettelaar** [comment] 2019-08-06 15:46
@aaronbushnell Not able to reproduce this easily on my side. 

Can you share your `codeception.yml`, `unit.suite.yml` and the `myprojecttests\fixtures\EntriesFixture` class? Also if `projectConfig` is enabled can you share the `project.yml` file?

**Comment by aaronbushnell** [comment] 2019-08-07 14:59
Sure thing! Okay if I send it to you through Discord to not publicly share the schema?

Also, I discovered something when testing this a bit further. It looks to be an issue for just one particular section that uses auto-generated titles through some custom fields. I tried disabling that and using a standard "Title" field and it worked as expected!

Not sure why that would matter but perhaps that helps here a bit?

**Comment by gtettelaar** [comment] 2019-08-07 15:22
@aaronbushnell Of course, no problem!

Re the auto-generated titles. I'll have a look - but that should definitely help me get started.

**Comment by angrybrad** [comment] 2019-08-09 21:25
Not able to reproduce this, either... @gtettelaar if you need help looking into it, feel free to ping me.

**Comment by gtettelaar** [comment] 2019-08-12 11:50
The problem ended up being related to titles generated through a `titleFormat`. If you provided a `title` option in your fixture data file that was different from what `craft\elemements\Entry::updateTitle()` would generate, Craft wouldn't be able to find the title when unloading the fixtures after the test was done. 

Reason for this is because when unloading fixtures Craft tries to find the Element in the DB using `craft\test\fixtures\elements\ElementFixture::unload()`. To do this it calls the `ElementFixture::getElement()` function to find the element in the DB. `getElement()` uses the data from the fixture data file to build an `ElementQuery`. In the case of entries, it builds an `EntryQuery` and set's the `title` property to whatever is supplied from the data file.

This supplied value, however, __may__ be wrong. The __actual__ title as stored in the DB will be the result of rendering the `titleFormat`. The `getElement()` function will thus return nothing if the value in the data file is different from the generated title. This will cause `unload()` to not unload that Entry. 

Fix for this is to edit `craft\test\fixtures\elements\EntryFixture` to take this into account. However, the data file should really also provide the correct `title` in the first place IMO.

**Comment by aaronbushnell** [comment] 2019-08-12 12:54
Thanks a bunch, @gtettelaar! Looks like you've got a branch started that should fix this. If you need a tester just let me know. Otherwise I'll be on the lookout when this hits in a Craft release.

Appreciate your help here!

**Closed** 2019-08-12 18:18 UTC
Labels: ✅ testing
