### ISSUE TITLE
feature request: mass collapse

### ISSUE THREAD

**Issue by pieter-janDB** [craftcms/cms#3214] opened 2018-08-17 10:38 UTC
Hi,

Is it possible to get an option to collapse all fields inside of an entry? sometimes pages just get really long and it gets impossible to find the right content unless you start manually collapsing all fields.. Also the cms sometimes forgets fields that have been collapsed before and reopens them.

I am working on craft 3 3.1.13.1

**Comment by brandonkelly** [comment] 2018-08-17 21:26
This is a duplicate of #1880.

(See my first comment on there for tips on mass-callpse that already exist, too.)

**Closed by brandonkelly** 2018-08-17 21:26 UTC
