### ISSUE TITLE
System messages - allow switching language of messages from list

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#7201] opened 2020-11-29 21:36 UTC
Right now we can only switch message language in message edit modal. It would be useful if we could switch also while browsing messages list.

**Comment by schwarzdesign** [comment] 2021-05-26 08:36
@piotrpog Just to be sure, do you mean the edit modals under Utilities -> System Messages? Because I don't see a way to change the language for the message at all. Instead, the messages are always in the _preferred language of my user account_. Maybe it's because I only have one site defined?

My setup: I have one site defined with its language set to German. My admin account is set to English. When I go to Utilities -> System Messages I can only edit the messages in English. If I want to change the System Messages in German, I have to switch my account preference to German. @brandonkelly Is this intended behaviour or a bug?

**Comment by brandonkelly** [comment] 2021-05-28 13:06
@schwarzdesign That’s a bug. Just posted as a new issue (#7992) and it’s now fixed for the next release.

**Closed** 2021-06-22 06:29 UTC
Labels: enhancement, internationalization :globe_with_meridians:
