### ISSUE TITLE
Branch limit has no effect on Add a category button

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#2351] opened 2018-01-25 11:10 UTC
### Description

_Add a category_ button is still selectable while _Branch Limit_ is set to 1 and a category has been already selected. on Craft 2, this button was hidden as soon as the limit was reached.

### Steps to reproduce

1. Set the category field branch limit to 1
2. When editing the entry with the category field, add a category

### Additional info

- Craft version: 3.0.0-RC7.1
- PHP version: 7.1.8
- Database driver & version: MySQL 5.6.35
- Plugins & versions: N.A.

**Comment by brandonkelly** [comment] 2018-01-25 18:08
Duplicate of #1847

**Closed by brandonkelly** 2018-01-25 18:08 UTC
