### ISSUE TITLE
Provide an event for generating a video (or other) thumbnail

### ISSUE THREAD

**Issue by khalwat** [craftcms/cms#1642] opened 2017-04-19 12:11 UTC
Currently Craft just returns the an icon for video thumbnails. Having Craft actually generate the video thumbnail is probably out of scope, because parsing all of the various video formats is not a road you want to go down (trust me).

However, having an event that fires inside of `$asset->getHasThumb` would at least give enterprising developers a way to latch on to generate an actual video thumbnail.

Generalized, providing this hook to allow thumbnails to be generated for any datatype Craft doesn't know how to make thumbnails for (right now, it's just images) would give it some flexibility.

Filing as per @andris-sevcenko 's request. Asking for a friend: https://github.com/nystudio107/craft3-transcoder

**Comment by andris-sevcenko** [comment] 2017-11-06 10:28
Closed via b4d2393

**Comment by andris-sevcenko** [comment] 2017-11-06 10:28
Didn't even have to lift a finger!

**Closed by andris-sevcenko** 2017-11-06 10:28 UTC
Labels: feature

**Comment by brandonkelly** [comment] 2017-11-06 12:41
Whoops, apparently #2073 was a duplicate of this.
