### ISSUE TITLE
Limit sort options

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/cms#4802] opened 2019-08-22 22:01 UTC
### Description

Now that 3.2 supports more sortable field types, sort menus on entry indexes have become really long because they include all available fields as a sort option, even though the field isn't visible as a table column or isn't used in that entry type. It would be nice to keep the sort options cleaner. Would it be possible to do one of the following?

1. Limit the sort options menu to only include default entry properties (title, post date, etc.) and custom fields that are visible as a table column for the current section 
2. Provide fields with an option to opt out of being used in sort menus, similar to the `Use this field’s values as search keywords?` checkbox

### Steps to reproduce

1. On entry index page, click on sort dropdown
2. Includes all available sort options

### Additional info

- Craft version: 3.2.10
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.27

**Comment by brandonkelly** [comment] 2019-08-23 03:09
This is a duplicate of #4314 / #4514. We can’t do anything about it without breaking backward compatibility, but we plan to fix for Craft 4.

**Comment by brandonkelly** [comment] 2020-05-20 23:42
I found a non-breaking way to fix this for Craft 3.5 🎉

See https://github.com/craftcms/cms/issues/4314#issuecomment-631793986 for details.

**Closed by brandonkelly** 2020-05-20 23:42 UTC
Labels: authoring :writing_hand:, enhancement
