### ISSUE TITLE
[4.x]: Conditional fields on Asset field layout are not appearing/hiding automatically

### ISSUE THREAD

**Issue by Stalex89** [craftcms/cms#12365] opened 2022-11-23 09:49 UTC
### Description

The default behaviour (at least on Entries) is when you change the condition for conditional field, it will toggle visibility for conditional fields. However that doesn't happen automatically if conditional fields are set in Asset layout. You have to manually resave asset  to trigger visibility of conditional fields in control panel

### Steps to reproduce

1. Create Asset volume with conditional fields in asset layout
2. Add a new asset to the volume
3. Try to toggle condition field 

### Expected behavior

Conditional fields should show/hide automatically when condition field is changed

### Actual behavior

Nothing happens when condition field is changed, you have to manually resave asset to trigger visibility of conditional fields  

### Craft CMS version

Craft CMS 4.3.3

### PHP version

8.0.25

### Operating system and version

Darwin 21.6.0

### Database type and version

MySQL 8.0.31

### Image driver and version

GD 8.0.25

### Installed plugins and versions

-

**Comment by i-just** [comment] 2022-11-23 09:59
Hi, thanks for reaching out. That's a duplicate of #12348 and it's currently working as expected. Elements that don't support autosaving drafts (like assets, globals, users) will only show/hide conditional fields after saving your changes.

**Closed by i-just** 2022-11-23 09:59 UTC
Labels: expected behavior, craft4

**Comment by Stalex89** [comment] 2022-11-23 10:01
@i-just Ok, thank you for your fast response, sorry for the duplicate post

**Comment by i-just** [comment] 2022-11-23 10:03
Not a problem :)
