### ISSUE TITLE
autoLoginAfterAccountActivation not working

### ISSUE THREAD

**Issue by mark-chief** [craftcms/cms#7294] opened 2020-12-18 13:17 UTC
### Description

I am using Formie to create the user registration form, it is successfully registering a new account as expected - so i dont suspect it to the that plugin causing the issue.

Once registered, craft doesn't see you as a logged in user. E.g. `{% requireLogin %}` still sends you to the login page and `currentUser` is not working,

```
    // Global settings
    '*' => [
        // Default Week Start Day (0 = Sunday, 1 = Monday...)
        'defaultWeekStartDay' => 1,

        // Whether generated URLs should omit "index.php"
        'omitScriptNameInUrls' => true,

        // Control panel trigger word
        'cpTrigger' => 'admin',

        // The secure key Craft will use for hashing and encrypting data
        'securityKey' => App::env('SECURITY_KEY'),
        
        // Allow email addresses as usernames
        "useEmailAsUsername" => true,
        
        // Auto login after registration
        "autoLoginAfterAccountActivation" => true,
    ],
```

### Additional info

- Craft version: 3.5.17 Pro Trial
- PHP version: 7.4.13

**Comment by mark-chief** [comment] 2020-12-18 13:30
Possibly linked to this too https://craftcms.stackexchange.com/questions/36821/autologinafteraccountactivation-doesnt-seem-to-be-working

**Comment by brandonkelly** [comment] 2020-12-22 15:49
Can you verify that it doesn’t work using a [normal registration form](https://craftcms.com/knowledge-base/front-end-user-accounts#registration-form)? Formie could be providing its own registration controller action, in which case this is a Formie bug.

**Comment by MatoTominac** [comment] 2021-01-12 18:12
@brandonkelly I'm experiencing the same issue on  3.5.17.1. This used to be working but stopped after the last update (I was 3-4 subversions below before the update).

**Comment by brandonkelly** [comment] 2021-01-13 22:03
Just tested locally (sans Formie) and the native code is working as expected.

@MatoTominac Do you have Formie as well?

**Comment by dowadidi** [comment] 2021-09-15 09:54
@brandonkelly We're having the same issue. And we use Formie.

**Comment by brandonkelly** [comment] 2021-09-15 21:56
> Can you verify that it doesn’t work using a [normal registration form](https://craftcms.com/knowledge-base/front-end-user-accounts#registration-form)?

Still waiting to hear back on this. Going to close the issue for now, assuming this is a Formie-specific issue that needs to be reported at https://github.com/verbb/formie.

**Closed by brandonkelly** 2021-09-15 21:56 UTC
Labels: bug

**Comment by simonleadbetter** [comment] 2022-04-12 15:06
Just reopening this conversation to loop @verbb (at Josh’s request) as I have also experienced the same issue using Formie 1.5.12.

**Comment by brandonkelly** [comment] 2022-04-13 00:23
Still waiting to hear back on whether the error is reproducible using a normal registration form.

**Comment by engram-design** [comment] 2022-04-13 01:34
Just stumbled upon this thread, but wanted to check with people if they're using the User element integration with Formie to create the user once they've filled out the form. 

If you are using the element integration, that’ll be (by default) run via the queue, so the user element will be created in the queue environment. As such, they can’t be logged in automatically because it’s a different session. Not to mention that being in a queue job means it could be processed much later than when the user fills out the form.

The only way this will work is if you disable the queue processing for integrations, which I wouldn’t overly encourage if you have other integrations setup. If you have queue processing disabled, it'll run the user-element creation in the same session as the user filling out the form, and it should act as normal.

Feel free to open up an issue on https://github.com/verbb/formie/issues as I imagine this is a Formie-specific issue, and just the nature of how integrations are run.

**Comment by engram-design** [comment] 2022-04-13 11:46
I'd also encourage anyone to chime in here https://github.com/verbb/formie/issues/829
