### ISSUE TITLE
Selection button still shows if a categories field has a limit of 1

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#4597] opened 2019-07-17 19:03 UTC
### Description
Not sure if this is a bug or feature request...

If you have a categories field with the branch limit set to 1, and have it assigned to an asset, when you select a category the selection button still shows in the hud. Seems odd, because the entries field does not do this (the selection button is hidden if an entry is already selected and the limit set to 1).

### Steps to reproduce

1. Create a categories field
2. Set the branch limit to 1
3. Assign it to asset
4. Load up an asset
5. Select a category from your categories field
6. Although set to 1, the select button still shows, which makes it confusing if you're only expecting 1 choice

### Expected behaviour
For the selection button not to show if the branch limit is set to 1 (like the entries field). If i've missed the point of the branch limit, perhaps consider adding a limit field like the entries field.

### Additional info

- Craft version: 3.2.3
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment] 2019-07-18 00:21
Duplicate of #2423

**Closed by brandonkelly** 2019-07-18 00:21 UTC
