### ISSUE TITLE
Categories field type doesn't disable selection label when branch limit reached

### ISSUE THREAD

**Issue by beccasjames** [craftcms/cms#3094] opened 2018-07-13 19:21 UTC
### Description

A field of Field Type `Categories` with a Branch Limit of 1 does not disable the Select Label button once the Branch Limit of one category selection has been reached.

### Steps to reproduce

1. Setup field with Field Type of `Categories` and Branch Limit of 1 and enable on an entry
2. On enabled entry, select a single Category
3. Observe that Selection Label button is still enabled (not grayed out)
4. Select another Category
5. Observe that Category selection fails

### Additional info

- Craft version: 3.0.13.2
- PHP version: 7.0.30
- Database driver & version: MySQL 5.7.22

**Comment by brandonkelly** [comment] 2018-07-13 20:05
Duplicate of #2423

**Closed by brandonkelly** 2018-07-13 20:05 UTC
