### ISSUE TITLE
[4.x]: Search issue (multiple terms on multiple fields, one being a relation)

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#12267] opened 2022-11-06 17:25 UTC
### Description

Best illustrated with an example.

Say I have an entry with title `Bloody Mary` and an entries field ingredients relating to the entry `Vodka`.

Searching for `bloody`or searching for `vodka` returns my entry.

But searching for `bloody vodka` does not. 

It looks like this is tied to relational fields (entries field here). Let's say I add a description field with `vodka` in it, searching for `bloody vodka` does return the entry as expected. Looks like searching for multiple terms does not parse relations (when searching for a single one does).

Note that using OR does work, searching for `bloody OR vodka` includes relational fields.

Note also that using the field name works as expected: `bloody ingredients:vodka` does return the entry. Obviously this is not very user friendly when using a search form on the front end.

### Steps to reproduce

1. Description should be enough to get a good idea of the issue.

### Expected behavior

Searching for `hello world` should search for both in all fields of the entry.

### Actual behavior

Searching for `hello world` only searches for both in non relational fields.

### Craft CMS version

4.3.1

### Installed plugins and versions

-

**Comment by brianjhanson** [comment] 2022-11-08 17:36
First, A+ on an excellent example 🙂 It does, however, sound like this is working as expected. Based on your examples I'm guessing you're already familiar, but you can check the [searching documenation](https://craftcms.com/docs/4.x/searching.html) for the full syntax. Searching for `bloody vodka` is searching for any elements that have *both* `bloody` and `vodka` in any of the indexed fields (`title`, `slug` and any custom fields you have set to include). Your situation gets zero results because the title of "Bloody Mary" only has `bloody` and the title of "Vodka" only has `vodka`, no elements have both. 

If you want queries like "bloody vodka" to return both "Bloody Mary" and "Vodka" you'll need to use `OR` as you stated. If you're building a front-end search I think the best way to approach it would be to parse out each word separately and join them with an `OR` before passing them over to Craft.

I'm going to close this for now, but I'm still here if you have additional questions.

**Closed by brianjhanson** 2022-11-08 17:36 UTC
Labels: bug, craft4

**Comment by JeanLucEsser** [comment] 2022-11-08 18:21
Thank you for getting back to me on this @brianjhanson.

I am indeed familiar with the documentation and still think the issue is valid. Let me try to illustrate my example in a better way.

> Searching for bloody vodka is searching for any elements that have both bloody and vodka in any of the indexed fields (title, slug and any custom fields you have set to include)

Precisely, see in the following screenshot, I have **"Bloody"** in `title` and **"Vodka"** in `descriptions`. The search `bloody vodka` does return the entry as a result:

<img width="724" alt="image" src="https://user-images.githubusercontent.com/14908712/200642079-0a7f75b3-46a6-4794-b9f7-034562057ccd.png">

Now, let's clear the description field and add **"Vodka"** as an `ingredients` relation (see screenshot below):

<img width="726" alt="image" src="https://user-images.githubusercontent.com/14908712/200643393-0b2004d4-078b-41fd-853a-96042e1dde05.png">

It gets interesting as searching for `vodka` does return the entry (which it rightly should), but searching for `bloody vodka` does not! Even more interesting, searching using the field handle does actually work as `bloody ingredients:vodka` does return the entry.

> Your situation gets zero results because the title of "Bloody Mary" only has bloody and the title of "Vodka" only has vodka, no elements have both.

The entry with the title of **"Vodka"** is a custom field (relational) of the entry "Bloody Mary" which is proven by the fact that `bloody ingredients:vodka` does actually return the entry. `bloody vodka` should return the entry as well. I see no reason it shouldn't.

**Comment by brianjhanson** [comment] 2022-11-08 20:29
> Precisely, see in the following screenshot, I have "Bloody" in title and "Vodka" in descriptions. The search bloody vodka does return the entry as a result:

I'm not seeing the same behavior in a minimal project over here. With that setup, searching for "bloody vodka" still returns 0 results. Here's a quick video so hopefully we can determine if I'm doing anything different from you. I am using the CP search, but I see the same results when I do `{% craft.entries().search('bloody vodka').all() %}`. I also have "Use this field’s values as search keywords" checked on the `description` field. 

https://user-images.githubusercontent.com/1843073/200664172-d52aab3e-6382-4cd0-a2f9-8d16497ced7b.mp4

> The entry with the title of "Vodka" is a custom field (relational) of the entry "Bloody Mary" which is proven by the fact that `bloody ingredients:vodka` does actually return the entry. 

This still makes sense to me. A search for "bloody ingredients:vodka" is saying, "Give me all the entries with 'bloody' in the title or slug AND 'vodka' in the title or slug of the element in ingredients field". But when you just search 'bloody vodka' you're saying, "Give me all the entries with 'bloody' AND 'vodka' in the title or slug field". 

I think the crux of the issue is that searches are `AND` by default, but it sounds like you'd like the ability to switch that to `OR`. It feels like that kind of thing is much better handled via the front end or custom code than by Craft since everyone's use case is different. I completely recognize that it's annoying for your use case though.

**Comment by brandonkelly** [comment] 2022-11-10 01:20
Worth noting that the search results will be affected by:

- the fields’ “Use this field’s values as search keywords” settings
- whether the “Updating search indexes” job has completed after saving the entry
- caching, possibly (if caches were warmed before the “Updating search indexes” job completed)
