### ISSUE TITLE
[Bug] Invalid entry type ID

### ISSUE THREAD

**Issue by jan-dh** [craftcms/cms#5276] opened 2019-11-27 20:44 UTC
### Description
I have a website with both a local setup (local db/mamp) and a remote setup, project config is enabled.
I made the site locally and pushed everything to live. So far, so good. I have a section with multiple page types. In that section I made a couple of entries (on the server) with a specific entry type (with ID:5).

After that, I changed those entries to another entry type. I removed the entry type with id 5 locally and pushed that project config to the server. 

Now, when I try to edit those entries in the CMS I keep getting this:

```
Invalid Configuration – yii\base\InvalidConfigException
Invalid entry type ID: 5
1. in /var/www/vhosts/smak.be/releases/70/vendor/craftcms/cms/src/elements/Entry.php
```

The entries appear fine on the front.

I checked the database, the specific entry has the right entry type (ID:22). I ssh'ed onto the server and did:

`./craft resave/entries `
`./craft clear-caches/all`

All ran well, still the same error.

Funny thing is, I can edit that entry from the index page, but I can't change the page type from there.

@AugustMiller mentioned on Discord that it might have something to do with revisions, as he didn't think they're loaded in the Element editor HUD.

### Additional info

- Craft version: 3.3.16.3
- PHP version: 7.3.12
- Database driver & version: MySQL 5.7.25

*Edit* : disabling the versioning of the section did not solve the issue

**Comment by jan-dh** [comment] 2019-11-28 08:46
Ok, so I removed all the entries from the DB table "entries" with a typeID 5, even though no entries were visible in the CMS. This resolved the issue. Somehow there were about 20 entries still with this entry type ID. Very very strange.

**Comment by SayChi** [comment] 2019-11-28 12:44
I got the same issue, 2 different entry types in my case, one of which had 15 unused entries in the db and the other just 1. Deleting them did indeed fix it.
We build directly on live, so it's not likely to do with local to live syncing.

We did also change those entry types and deleted the old ones.

And our craft version is also 3.3.16.3

**Comment by brandonkelly** [comment] 2019-12-01 02:20
I suspect this is a duplicate of #5270, which was just fixed for the next release.

**Closed by brandonkelly** 2019-12-01 02:20 UTC
