### ISSUE TITLE
[4.x]: Long category titles can overflow the field if the field is narrow

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#13386] opened 2023-07-05 15:58 UTC
### Description

The selected categories in a category can overflow if the field is narrow (e.g. 1/4):

![Screenshot 2023-07-05 at 17 56 14](https://github.com/craftcms/cms/assets/10146880/e3abfe8e-1f2a-47e1-9119-f741977672d5)

This only happens when _Maintain hierarchy_ is active. If the option is turned off, the category titles are truncated with an ellipsis.

### Craft CMS version

4.4.15

### PHP version

8.2

**Comment by i-just** [comment] 2023-07-06 06:42
Hi, thanks for reporting. It looks like a duplicate of #13382, and the PR for it works for this one too.

**Closed by i-just** 2023-07-06 06:42 UTC
Labels: bug, duplicate, craft4

**Comment by MoritzLost** [comment] 2023-07-06 08:47
@i-just Ah sorry, missed that one. Thanks!
