### ISSUE TITLE
[5.x]: Frontend User Login / Password Reset

### ISSUE THREAD

**Issue by sarahschuetz** [craftcms/cms#15921] opened 2024-10-18 13:30 UTC
### Description

I'm trying to implement a login and password reset logic for Frontend-Users. The Craft 5 documentation states "Once you set up your site to allow public user registration, the last step is to create a front-end [user registration form(opens new window)](https://craftcms.com/knowledge-base/front-end-user-accounts#registration-form)." Whereas the link takes me to a site which states "Applies to Craft CMS 4 and Craft CMS 3."

### Steps to reproduce

Implement https://craftcms.com/knowledge-base/front-end-user-accounts#set-password-form with Craft 5 Project.

### Expected behavior

Input field and user can reset the password.

### Actual behavior

Error because get params are not parsed correctly:
`Variable "code" does not exist.
 `

```
{% set errorMessage = craft.app.session.getAllFlashes()['error'] ??? null %}
 
<form method="post" accept-charset="UTF-8">
  {{ csrfInput() }}
  {{ actionInput('users/set-password') }}
  {{ hiddenInput('code', code) }}
  {{ hiddenInput('id', id) }}
...
```
Url: ..../in/setpassword?code=NtmAatS21tKerGc0Nv8cL0lQyqsCdpYN&id=3ae4d0e6-b5cf-4508-9450-f60ae6fc399c

### Additional Problem:

I also had the problem that error messages were not shown on the login page when implementing it according to the knowledge base.
The code 
```
  {% if errorMessage is defined %}
    <p>{{ errorMessage }}</p>
  {% endif %}
```
is not working because errorMessage is not defined automatically.

I fixed that problem using
```
{% set errorMessage = craft.app.session.getAllFlashes()['error'] ??? null %}
```

### Craft CMS version

5.4.7.1

### PHP version

8.3

**Comment by brandonkelly** [comment] 2024-10-21 13:29
Have you updated your [setPasswordPath](https://craftcms.com/docs/4.x/config/config-settings.html#setpasswordpath) config setting to match the actual URI? Looks like it should be `in/setpassword`.

**Comment by tommysvr** [comment] 2024-10-21 14:13
Resolved in support. The issue was `with_context=false` on an include.

**Closed as completed by tommysvr** 2024-10-21 14:13 UTC
Labels: bug

**Comment by masiorama** [comment] 2024-12-19 13:29
Sorry to bother with an already closed issue, but I'm trying to achieve the same goal as @sarahschuetz.
Overriden `setPasswordPath` with `shop/customer/_includes/setpassword` and placed the new template file `setpassword.twig` in `templates/shop/customer/_includes/`.


I had luck with `setPasswordSuccessPath` setting for the submit of the default form but no luck on overriding the `setPasswordPath`.

Missing anything?

edit: on craft 5.5.7

**Comment by brandonkelly** [comment] 2024-12-27 13:14
Hey @masiorama, the issue is that `setPasswordPath` can’t be set to a private template path.

That config setting actually defines two things:

- The URI for the Set Password page
- The template path for the Set Password page

Craft handles Set Password pages like normal template-driven pages (step 4 in the [Routing](https://craftcms.com/docs/5.x/system/routing.html) docs), however in your case it doesn’t want to expose the `shop/customer/_includes/setpassword.twig` template because `_includes` is a private template folder (per the [`privateTemplateTrigger`](https://craftcms.com/docs/5.x/reference/config/general.html#privatetemplatetrigger) config setting).

Ideally, `setPasswordPath` should be set to a more user-friendly URI, like `setpassword` (the default) or `shop/setpassword`, and then you can move your `setpassword.twig` file accordingly.
