### ISSUE TITLE
Allow default "Title" text in table columns view to use its custom "Label" as defined in a section's entry type

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#6776] opened 2020-09-02 17:17 UTC
### Description

The ability to customize title text on entries is awesome. For instance, in an FAQ section, I can now display fields as "Question" and "Answer".

It'd be nice if in this could also be used in a table column view, either automatically (potential issues with multiple entry types?) or some other method.

**Comment by brandonkelly** [comment] 2020-09-02 19:21
This is a duplicate of #3814, and we actually resolved it in 3.5 via the new “Header Column Heading” element source setting. (We couldn’t pull in the custom Title label automatically unfortunately, as explained in that thread.)

**Closed by brandonkelly** 2020-09-02 19:21 UTC
Labels: enhancement

**Comment by jsunsawyer** [comment] 2020-09-02 20:07
Oh rad, totally missed the Header Column Heading option. Works perfectly. Thanks!
