### ISSUE TITLE
Multi-Site Permissions - Part 2 - Entry Authorization

### ISSUE THREAD

**Issue by zmetcalf** [craftcms/cms#2058] opened 2017-10-26 14:04 UTC
We are looking to add additional permission filtering based off of multi-sites in the control panel. What we had in mind was only showing entries that are enabled and able to edited by a user for a particular site. 

We need to be able to prevent people from being able to just type in IDs to get to unauthorized entries in the CP, so is there a way to get a hook/event in this code so we can prevent this: https://github.com/craftcms/cms/blob/develop/src/controllers/BaseEntriesController.php#L38

I can submit a pull request if this is ok?

**Comment by brandonkelly** [comment] 2017-10-26 19:25
Same answer as #2057 - struggling to see how this is not a duplicate?

**Comment by zmetcalf** [comment] 2017-10-26 19:35
I emailed support first, and Brad asked that I create separate issues.

**Comment by brandonkelly** [comment] 2017-10-27 04:24
Closing this as duplicate of #2057 (they both are the same basic request; just different side effects of the proposed permission).

**Closed by brandonkelly** 2017-10-27 04:24 UTC
