### ISSUE TITLE
[4.x]: Custom sources that include structured sections should be possible to reorder

### ISSUE THREAD

**Issue by outline4** [craftcms/cms#11163] opened 2022-05-09 13:06 UTC
### Description

When adding a filter in a structure, you can reorder entries. 

<img width="757" alt="Bildschirmfoto 2022-05-09 um 12 33 14" src="https://user-images.githubusercontent.com/145828/167410716-154e8929-5dc0-4358-811d-7804dd439938.png">

The exact thing should be possible when creating a custom source. 

<img width="766" alt="Bildschirmfoto 2022-05-09 um 12 33 53" src="https://user-images.githubusercontent.com/145828/167410828-d0002749-f956-48da-9db8-2920af404f5b.png">

but it's not: 

<img width="692" alt="Bildschirmfoto 2022-05-09 um 12 33 36" src="https://user-images.githubusercontent.com/145828/167410928-f9456d1f-c727-45cb-bcfd-56fdc2a7cf3b.png">

### To clarify: 

Our customer needs to sort entries based on categories. This also applies to a lot of craft commerce customers we have. So we've been waiting a looong time to have this kind of possibility. I was so happy to hear the rise of custom structures, where I thought this was possible. 

### Also:
Per custom source there should be an independent order. 
Like have a **global order** of entries without a filter and **an order** per filter or especially **per custom source**. 

For instance: in certain shops you list all entries (without any category) in a certain order, and when applying a category, in a different order. This was possible with Low Reorder in EE, and we were waiting such a long time to be able to recreate this. 

### What exactly happens when I reorder an entry within a filtered structure? 

From what I've just tested the global order is destroyed and the element will be in a completely different order below the first entry with a different relation...  
Can you elaborate what exactly happens? 

### Features I miss
Custom sources should have a "create new entry" in that source. With the option of "Default Entry Placement" (before or after existing entries).

### Toughts
Now I am a bit underwhelmed of custom structures and most certainly with the filter. 

Why do you show ALL available fields to choose in a filter?  
IMHO you should only show relevant fields to the end user. 
Filters should be savable, reordable, duplicatable etc. Like Zenbu from EE.  

This whole thing should have gotten an update before 4.0 already. Now it's really necessairy to rethink the whole experience. Talking of technical depth and user whishes... 

– Stefan

### Craft CMS version

4.01

### PHP version

8.1.5

### Installed plugins and versions

-

**Comment by thupsi** [comment] 2022-05-09 23:10
A lot to unpack here. I'm guessing this will be converted to a discussion (maybe even split in multiple discussions) since it's clearly not a bug.

In any case, here are my two cents:

**Generally speaking:**

The index filters and custom sources are new features, so it's to be expected that they are somewhat basic. IMO they are very pleasant enhancements to an already flexible CMS, and I'm certain that they will become more full-featured and powerfull in future iterations. I'm also of the opinion that it's unfair to compare them to features and plugins in other systems without taking into account the different scope, priorities and complications of each project.

**Ordering in filtered views and custom sources:**

When **filtering** entries in a structure I'm (pleasantly) suprised that I can still reorded things. That is because, as you found out, it can be unclear how the reordering will persist when you clear the filter. I guess that each entry goes as high as it can, while maintaining the order between the entries that are displayed when the filter is active. 

In **custom sources** I agree that it would be very usefull to have a custom order, and the order would persist in a more predictable manner than in filtered views. I do think it's a little out-of-scope and not trivial to implement at this first iteration, so I'm not complaining yet. Don't forget that each new feature introduces opportunities for bugs (or it can take a toll on performance), so P&T are wise to not take on more than they can hanlde for each release.

**Create new entry in source**

At first what you ask seems logical, but there are conditions that are difficult to handle automatically in order to create a matching entry. For example, how would you handle a "less than" condition on a number field? What value would you assign to this field to make a matching entry for your custom source? I'm not saying it's unsolvable, but surelly it will take some planning to implement.

**Appearence of ALL fields in filters**

Maybe there are some performance considerations, but I agree that showing only fields that apply to the current source would be optimal. It hasn't caused me any trouble for the time being, but I imagine with many fields it becomes unwieldy.

**Filters should be savable, reordable, duplicatable etc**

OK, yes, but, again, we can't expect everything at once. It goes without saying that you are entitled to your own (and your clients') priorities, but P&T have a huge backlog of ideas and wishes from the community and it's only natural that they can't please everyone all the time.

Anyway, it will be great to hear from the team and/or other members of the community!

**Comment by brandonkelly** [comment] 2022-05-10 05:48
Appreciate the feedback, but this does need to be split out into multiple discussions. Please post new [discussions](https://github.com/craftcms/cms/discussions/new?category=ideas) (not issues – these are not bug reports) for each individual request.

**Closed by brandonkelly** 2022-05-10 05:48 UTC
Labels: bug, craft4

**Comment by outline4** [comment] 2022-05-10 20:08
Ok here they are: 

Conditional fields should be able to access values from other fields:  
https://github.com/craftcms/cms/discussions/11188

Features I miss with filters:  
https://github.com/craftcms/cms/discussions/11187

What exactly happens when I reorder an entry within a filtered structure?  
https://github.com/craftcms/cms/discussions/11185

Custom sources that include structured sections should be possible to reorder and have their own order:  
https://github.com/craftcms/cms/discussions/11184

**Comment by outline4** [comment] 2022-05-10 20:11
Thanks [thupsi](https://github.com/thupsi) for taking the time to answer and explain the situation.  

I was so much looking forward to test out craft 4 and none of the stuff I wanted was possible. I didn't participate in the beta because I didn't have the time. I regret that now. 

Anyway thanks and I hope my suggestions make sense and will be in 4.1 ;)

**Comment by thupsi** [comment] 2022-05-11 07:07
@outline4 I hope I didn't sound dismissive, because I agree with most of your ideas! 

I'm looking forward to expand on the discussions you created! :)
