### ISSUE TITLE
I can't invite someone to be a user

### ISSUE THREAD

**Issue by deanwheel** [craftcms/cms#6627] opened 2020-08-13 20:09 UTC
### Description
Every time I invite someone to be a user it sends them an activation link that leads them to a 404 page. 

### Steps to reproduce

1. I can invite you as a user
2. Click the activation link and it will lead to a 404 page

### Additional info

- Craft version: 3.5.3 (Pro)
- PHP version: 7.2.24
- OS version: Linux 4.15.0-111-generic
- Database driver & version: MySQL 5.7.31
- Image driver & version: Imagick 3.4.3RC2 (ImageMagick 6.9.7-4)
- Plugins & versions: 
    - Anchors 2.2.0
    - Field Manager 2.1.8
    - ImageOptimize 1.6.14
    - Navigation 1.3.25
    - nethooks 1.1.2
    - Redactor 2.7.0
    - Redactor Anchors 1.1.0
    - SEO 3.3.14
    - Typed link field 1.0.23

**Comment by brandonkelly** [comment] 2020-08-13 21:43
What URL does the email link to? And what is your site’s Base URL set to?

**Comment by deanwheel** [comment] 2020-08-13 21:49
This is the URL link I got when I sent it to myself
https://www.wheel.com/setpassword?code=Glia6xCNxvV-JS0-Bl9I4mPCMAfth-6P&id=2f3f6e45-2351-46ef-b911-f71920980a57

and this is what's in the settings for base URL
[image: image.png]

**Comment by deanwheel** [comment] 2020-08-13 21:49
![image](https://user-images.githubusercontent.com/69650950/90190608-31d1cf80-dd74-11ea-8cf2-7b7376cf1e40.png)

**Comment by brandonkelly** [comment] 2020-08-13 21:58
Is `www.wheel.com` your actual site host name?

**Comment by deanwheel** [comment] 2020-08-14 15:34
wheel.com points to Netlify through an A record, www does the same but
directly to the Netlify app with a CNAME record, and www is listed as the
primary domain on Netlify

**Comment by brandonkelly** [comment] 2020-08-15 13:24
Gotcha – in that case this is a duplicate of #6226. See that issue for a discussion about this. Improving documentation around Headless Mode is high on our list.

**Closed by brandonkelly** 2020-08-15 13:24 UTC
