### ISSUE TITLE
postDate isn't updated properly.

### ISSUE THREAD

**Issue by chainzhang** [craftcms/cms#1694] opened 2017-05-06 10:55 UTC
### Description

Without installing the `php-intl` extension, `postDate` will not be updated properly.

I tracked down to the core and found that the bug occurred when craft are trying to parse the `$entry->postDate` in `$this->_populateEntryModel($entry);`

I don't know if it is a kind of **BUG**, but it seems that the `php-intl` is not a MUST extension. So I think the cms should works properly even without the extension. Or just making the extension MUST?

Note: My environment is in Japanese.

### Steps to reproduce

1. save an entry under an environment without php-intl extension
2. n/a

### Additional info

- Craft version: 3
- PHP version: 7.1
- Database driver & version: mysql
- Plugins & versions:

**Comment by brandonkelly** [comment] 2017-05-07 17:02
Duplicate of #1495

**Closed by brandonkelly** 2017-05-07 17:02 UTC
Labels: bug, status: duplicate
