### ISSUE TITLE
Categories field UI doesn't respect the limit

### ISSUE THREAD

**Issue by alecrios** [craftcms/cms#2986] opened 2018-06-12 23:05 UTC
### Description

The "+" button to add another category should be hidden if you've reached the limit, but the button is still present and clickable. It seems to correctly ignore the extra categories when you try to select them, but the UI is misleading.

### Steps to reproduce

1. Create a Categories field with a limit of 1.
2. Add this field to a section.
3. Edit an entry in this section.
4. Select one category.
5. Try to select a second category.

### Additional info

- Craft version: 3.0.10.3
- PHP version: 7.1.18
- Database driver & version: MySQL 5.5.56
- Plugins & versions: None

**Comment by brandonkelly** [comment] 2018-06-12 23:48
Duplicate of #2423 / #1847

**Closed by brandonkelly** 2018-06-12 23:48 UTC
