### ISSUE TITLE
UI context of category field limited to 1 category

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/cms#3395] opened 2018-10-24 09:04 UTC
### Description
A category field that is limited to allow selection of a single category retains its "Add a category" button after a category is added.
Clicking the button allows the selection of a different category, but the field doesn't update and no error is given.
I feel that if the field is limited to allow only a single category selection then the "Add a category" button should be greyed out and disabled, or removed completely, until the currently selected category is removed by clicking the 'X' next to its name.

### Steps to reproduce

1. Create a category field and restrict it to allow only 1 category selection
2. Add a category to an entry using that field
3. Click the "Add a category" button, choose a different category

### Additional info

- Craft version: 3.0.27.1
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment] 2018-10-25 10:58
Duplicate of #2423

**Closed by brandonkelly** 2018-10-25 10:58 UTC
