### ISSUE TITLE
Multiple fields in one row

### ISSUE THREAD

**Issue by mendiomon** [craftcms/cms#1763] opened 2017-06-07 13:59 UTC
This is proposal for improving backen ux experience.

Simply put, allowing for multiple fields to be placed in one row (next to each other) instead of each field having its own row.

**Comment by takobell** [comment] 2017-06-07 16:42
Are you referring to fields on element (entry, category, tags, user, etc.) edit pages?

**Comment by mendiomon** [comment] 2017-06-07 17:41
Eas, thats what i am reffering to.
For example, october cms have this functionality, with builder plugin

http://octobercms.com/storage/app/uploads/public/56b/aca/a7d/56bacaa7d7fb4296066556.png

**Comment by takobell** [comment] 2017-06-07 20:06
Going to close as a dupe of https://github.com/craftcms/cms/issues/825.  Feel free to add any additional comments on that one.

**Closed by takobell** 2017-06-07 20:06 UTC
Labels: duplicate
