### ISSUE TITLE
Template caches are not correctly cleared

### ISSUE THREAD

**Issue by martinhellwagner** [craftcms/cms#2760] opened 2018-04-17 13:13 UTC
### Description
Even though I've cleared the template caches (Utilities -> Clear Caches), the corresponding entries are not removed in the table `templatecaches` in the database.

### Steps to reproduce

1. Clear template caches (Utilities -> Clear Caches)
2. Table `templatecaches` should be empty (it is not)

### Additional info

- Craft version: 3.0.2
- PHP version: 7.1.4
- Database driver & version: MySQL, 5.7

**Comment by brandonkelly** [comment] 2018-04-17 13:38
Duplicate of #2720, and fixed for today’s update :)

**Closed by brandonkelly** 2018-04-17 13:38 UTC
