### ISSUE TITLE
Feature Request: Filter by entry type in Field Type "entries".

### ISSUE THREAD

**Issue by hwong93** [craftcms/cms#5204] opened 2019-11-04 19:28 UTC
### Description

_New Feature request_
When creating an entries field, it would be great to be able to select entry types of the different channels/structures to filter entries from.

### Steps for Feature

1. Create a new entries field
2. Selecting sources also allows you to select different entry types within each source.

### Real Life Example

A user wants to create a page that has entries from a 'blog' channel, but they only want to choose blog entries that have the entry type "XYZ" and not "ABC".

**Comment by brandonkelly** [comment] 2019-11-05 09:51
This is a duplicate of #4299.

**Closed by brandonkelly** 2019-11-05 09:51 UTC
