### ISSUE TITLE
Bug / FR: "Default Upload Location" isn't working as expected

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#4966] opened 2019-09-20 11:39 UTC
### Description

I have several local asset volumes set up on a site I'm building, and I'm using various asset fields to encourage the user to put the images in the right place, but make them available everywhere. For example, the News section field:

![image](https://user-images.githubusercontent.com/1250017/65324206-3ae20d00-dbb4-11e9-8644-94b0960951bf.png)

This makes assets selectable from anywhere, but should put them in the News folder by default. However, when I create a new article and click that field to add a cover image for the article, it opens "Images" instead of "News:

![image](https://user-images.githubusercontent.com/1250017/65324245-59480880-dbb4-11e9-93b8-e760cc846e4d.png)

This should open the asset upload field on "News". I know the description for Default Upload Location says "when they are dragged directly onto the field, or uploaded from the front end", but the most common use-case is clicking "Add asset" on the field itself, and this doesn't work like it should.

### Steps to reproduce

1. Create multiple asset volumes
2. Set a field to upload to a specific asset volume by default (not the top one in the list)
3. Try and upload an image. It opens the top asset volumne.

### Additional info

- Craft version: 3.3.4.1
- PHP version: 7.3
- Database driver & version: mySQL

Own Reference: QEP

**Comment by andris-sevcenko** [comment] 2019-09-20 14:00
This is essentially a duplicate of #2778

**Closed by andris-sevcenko** 2019-09-20 14:00 UTC

**Comment by darylknight** [comment] 2019-09-20 14:11
Thanks Andris. I did search first but couldn't find any results. That issue has been open for 18 months; it would be nice to see progress on it for a better client editing experience.
