### ISSUE TITLE
[5.x]: Default title field not being indexed for entry types

### ISSUE THREAD

**Issue by pascalminator** [craftcms/cms#15025] opened 2024-05-18 18:51 UTC
### Description

The default title field is being indexed correctly for sections, and I can search and get results appropriately. However, the same default title field is not being indexed when used inside an entry type for a Matrix block (see attached screenshot below for better context).

### Steps to reproduce

1. Add an entry type to a section and keep the default title field.
2. Save any value in the title field.
3. Try to search for the value saved in the title field.
4. No results are found for the title field within the Matrix block entry type.

### Expected behavior

All "title" fields should be indexed, no matter where they are used. Ideally, the system should index the title fields within Matrix blocks just as it does for sections. Alternatively, there should be an option to control this indexing behavior with a checkbox, similar to custom fields.

### Actual behavior

The default title field within Matrix block entry types is not being indexed, preventing searches from returning results for values in these title fields.

![index-issue-title](https://github.com/craftcms/cms/assets/13754636/2a4dfa64-dc0e-45b8-81b3-286cad0b9f7f)

### Craft CMS version

5.1.3

### PHP version

8.2

**Comment by i-just** [comment] 2024-05-20 09:45
Hi, thanks for reaching out. The title field is always indexed, even for the entries inside a matrix field. 

For example, I have a top-level entry titled “vegetables” with a CKEditor and Matrix fields in it (both have “Use this field’s values as search keywords” off). CKEditor has a nested entry titled “carrots”, and the matrix field has two nested entries titled “broccoli” and “okra”; all 4 keywords are showing in the `searchindex` table.
<img width="464" alt="Screenshot 2024-05-20 at 10 31 31" src="https://github.com/craftcms/cms/assets/4500340/7f47af91-ca6c-47c0-8b23-484f75a0ef99">

In the control panel > Entries > All, I can search for “vegetables” and get one entry as a result, but searching for “broccoli” returns zero results. This is expected behaviour as the control panel search will search for the entries in the specified sections, and the nested entries don’t belong to a section.

There’s also this discussion, which you might find helpful. It clarifies the opposite of the behaviour you’re describing: https://github.com/craftcms/cms/discussions/14978.

I hope this helps!

I’ll close this now, but feel free to reply if you run into any further problems.

**Comment by pascalminator** [comment] 2024-05-21 14:42
This situation is problematic for the search feature on the front-end in my eyes. The only workaround I've found is to disable the default title field and create a custom title field with the "Use this field’s values as search keywords" checkbox checked.

For example, I created a matrix to manage the content of my "about" page. However, I can't get search results for "Christine Tremblay" (because it's using the default title field), while I can get results for "Directrice générale" (because it's a custom field with "Use this field’s values as search keywords" enabled).

This discrepancy means that default title fields within Matrix blocks are not behaving as expected in search functionality, leading to incomplete search results.

![image](https://github.com/craftcms/cms/assets/13754636/472efa06-8849-40c7-8731-4ca80edc0d50)
![image](https://github.com/craftcms/cms/assets/13754636/5d9a069c-3802-4926-8cd4-9837ab9b5b48)
![image](https://github.com/craftcms/cms/assets/13754636/03810d4f-e790-4be8-8093-f6a7a498110c)

This problem makes the default title field pointless for many user cases IMHO. Replacing it with a custom title field fixes my problem, but I'd rather use the default field because, well, it's already there. 

Thank you for your time and sorry if I don't get it maybe?

**Closed as completed** 2024-05-28 20:44 UTC
Labels: bug

**Comment by brandonkelly** [comment] 2024-05-29 00:15
I was able to reproduce this, and fixed for the next release.

Realized there’s a related bug, where entries’ search indexes don’t get updated automatically for nested entries within Matrix fields, when the nested entries are edited directly. That’s fixed as well, but for Craft 5.2+ since the fix was a bit involved (a7d1780075100d6073f2c1a323bb32a4c91ed331).

**Comment by brandonkelly** [comment] 2024-06-03 17:54
Craft 5.1.8 is out with that fix. Thanks again!

**Comment by pascalminator** [comment] 2024-06-03 19:51
I can confirm the problem is fixed now, after updating Craft to 5.1.8. Right in time to deploy this site in production!
