### ISSUE TITLE
Feature request: be able to add limit on a block type in a Matrix field

### ISSUE THREAD

**Issue by bzin** [craftcms/cms#3350] opened 2018-10-05 14:18 UTC
### Description

So I am using `Matrix` field to create data structure for twig components that stack on top of each other in a generic page. I do not want to create any limitation on the number of blocks but it would be  interesting and useful to be able to set a limit also on a specific block type. 

Would this be something you see being added in a future release?

### Additional info

- Craft version: Craft Pro 3.0.26.1
- PHP version: 7.2.7

**Comment by richardcalahan** [comment] 2018-10-07 22:09
Often times I'll use a matrix field to build a modular page. Each matrix block is a module, and the modules types would include: hero, image + copy, video, map, etc. 

"Hero" or "Map" might only make sense to be included in the page once, but still orderable within all modules.

**Comment by Anubarak** [comment] 2018-10-08 21:44
Another use case are social media channels. Imagine you have a channel of persons and each person should be able to insert social media links or whatever information we require (different api tokens and what not)

Of course one could argue this is better off as a separate field type but I like to use a matrix where the different block types represents different platforms and limit them via JavaScript to one since it doesn't make sense to show the Facebook icon twice next to each other in a teaser or whatever

**Comment by bzin** [comment] 2018-10-09 08:44
That reminds another usage I give to this field. Depending on the project I might use a Matrix on a Global set to create a `Menu` and `Footer` elements. Moreover, in this Matrix, I might want to limit certain buttons, links, text, etc...

**Comment by IndigoViking** [comment] 2019-02-20 16:47
I've needed this on several occasions. We use matrix blocks for main content or homepage blocks and typically only want one of each block, or sometimes just one block of a few types.

**Comment by BridgingUnit** [comment] 2019-05-29 19:04
Yep, could really do with this.

Some use cases I've hit recently:

Homepage with matrix with blocks (because client would like to reorder output of sections), but each block should only be displayed once.

Matrix used for Slideshow, or display of any set of same blocks (e.g. Bios etc), but where there's a block used for headline/intro first. That should only display once, but block type of slide (or bio etc) should be multiple.

Matrix used to display set of 4 panels within a page, but should only use each once. Reason being each has slightly different fields to provide content. Again, using Matrix so client can rearrange the order of them.

**Comment by narration-sd** [comment] 2019-05-29 20:18
Seems to want to occur to me that if you do this, it would be good to have some flexibility in what accounts for uniqueness. 

Type is one factor, but a string or numeric match (make use  of PHP''s looseness??) on a chosen field could be another. Thus you could assure you didn't try to make an employee bio, a product card, etc. over again, due to differing or updated information.

Likely a field opens here also of providing a facility to _find_ duplicated blocks, remind you if you try to save them, etc....

**Comment by bzin** [comment] 2019-06-21 11:04
Any idea if this will see the light of day @brandonkelly? Missing this so much! 🙏

**Comment by daltonrooney** [comment] 2019-09-11 21:57
This can be done with [MatrixMate](https://github.com/vaersaagod/matrixmate). Invaluable plugin, IMHO. Look for the 'maxLimit' config option for each block type.

**Comment by siffring** [comment] 2019-11-23 04:08
I could use this on a specification table for a product. Imagine a series of key/value pairs that describe specs for a product (e.g. height: 10, weight: 20, etc.).

The layout we're working with has a one column option for products with a few specs and a two column layout for products with a lot of specs.

With a block type limit I could have a block type of "column break" that can only be used once. Without the limit I'll end up creating two matrix fields for "Specs first column" and "Specs second column" which is a little less elegant.

**Comment by brandonkelly** [comment] 2019-11-25 14:09
This is a duplicate of #3350.

We’re planning on getting this into v4. In the meantime you can use the Neo plugin, which has this feature.

**Comment by bzin** [comment] 2019-11-26 21:54
Wondering if you made a mistake with the last comment @brandonkelly . You closed the issue mentioning this is a duplicate of the issue itself 😅

**Comment by brandonkelly** [comment] 2019-11-27 03:27
Doh, not sure what I was thinking there :)

**Closed** 2021-06-22 06:22 UTC
Labels: enhancement, matrix :dark_sunglasses:
