### ISSUE TITLE
See the field handle in the Entry Type edit view

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1067] opened 2017-01-31 03:49 UTC
> Created by: Chris Southam (chris@rallyagency.co.uk) on 2015/09/23 12:44:32 +0000
> Votes at time of UserVoice import: 4

-----------------------------------

Would be a neat trick if you could use the Sections > Entry Type edit screen as reference when building up a Twig template.

All it really needs is the ability to see the field handle within the blueprint to cross-reference with Twig.

**Comment by brandonkelly** [comment] 2018-02-25 22:03
Not quite the same, but as of 2.6.3006, field handles are now shown as tooltips when you hover over field names in Field Layout Designers.

**Comment by brandonkelly** [comment] 2018-02-25 22:26
Duplicate of #962

**Closed by brandonkelly** 2018-02-25 22:26 UTC
Labels: duplicate
