### ISSUE TITLE
Project config YAML files different depending on how they are generated

### ISSUE THREAD

**Issue by nickdunn** [craftcms/cms#7772] opened 2021-04-07 10:44 UTC
I'm finding some oddities in the way that project config files are generated.

I have created a Neo field, and it has created a `neoBlockTypes` file e.g.

```
childBlocks: ''
field: ca6e522f-3f8c-4df8-92fd-4854b0324fe9 # Page content
...
```

However when I go to Utilities > Project config > Rebuild all of the Neo blocktype fields have a single diff change:

```
-childBlocks: ''
+childBlocks: null
 field: ca6e522f-3f8c-4df8-92fd-4854b0324fe9 # Page content
```

I was expecting them to be identical. Is this a bug specific to Neo, or the way in which Craft is serialising things?

### Additional info

- Craft version: 3.6.11.2
- PHP version: 7.4
- Database driver & version:
- Plugins & versions: Neo 2.9.5

**Comment by brandonkelly** [comment] 2021-04-07 22:36
This is a duplicate of #7115. Will be fixed in Craft 4 thanks to typed properties in PHP 7.4.

**Closed by brandonkelly** 2021-04-07 22:36 UTC
Labels: bug
