### ISSUE TITLE
SQLSTATE[54000]: Program limit exceeded: [...] for index "craft_searchindex_keywords_idx"

### ISSUE THREAD

**Issue by noandrea** [craftcms/cms#1815] opened 2017-07-06 21:10 UTC
### Description
SQL error when inserting large text in a rich text field

from the error page:
```
Database Exception – yii\db\Exception
SQLSTATE[54000]: Program limit exceeded: 7 ERROR: index row size 4496 exceeds maximum 2712 for index "craft_searchindex_keywords_idx"
HINT: Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
The SQL being executed was: INSERT INTO "craft_searchindex" ("elementId", "attribute", "fieldId", "siteId", "keywords", "keywords_vector") VALUES (6, 'field', 21, 1, ' lorem ipsum  ....
```
and also:
```
Error Info: Array
(
    [0] => 54000
    [1] => 7
    [2] => ERROR:  index row size 4496 exceeds maximum 2712 for index "craft_searchindex_keywords_idx"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
)
↵
Caused by: PDOException

SQLSTATE[54000]: Program limit exceeded: 7 ERROR: index row size 4496 exceeds maximum 2712 for index "craft_searchindex_keywords_idx"
HINT: Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
```
### Steps to reproduce

1. create a *section* with a field type *Rich Text*
2. create a new entry for the section just created
3. go to [http://www.lipsum.com/](http://www.lipsum.com/) and generate 20 paragraph of text
4. paste the generated text to the rich text field
5. save and the error should appear

### Additional info

PHP version	7.0.18-0ubuntu0.16.04.1
Database driver & version	PostgreSQL 9.6.3
Image driver & version	GD 7.0.18-0ubuntu0.16.04.1
Craft edition & version	Craft Pro 3.0.0-beta.19
Yii version	2.0.11.2
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev

**Comment by brandonkelly** [comment] 2017-07-06 22:00
Closing as a duplicate of #1768

**Closed by brandonkelly** 2017-07-06 22:00 UTC
