### ISSUE TITLE
Rich Text within Matrix does not appear

### ISSUE THREAD

**Issue by jstewartdesign** [craftcms/cms#2941] opened 2018-06-01 09:18 UTC
### Description

When using Internet Explorer 11, when more than one Redactor field is loaded on a entry only the first field gets rendered. 

### Steps to reproduce

In Internet Explorer 11:

1. Create multiple redactor fields
2. Add these fields to the same entry type
3. Redactor will only appear for the first field on the page

This bug also prevents redactor fields within Matrix block from appearing if there are another redactor field on the page outside of the block.

Console throws and error:

> jQuery.Deferred exception: Object doesn't support property or method 'includes' TypeError: Object doesn't support property or method 'includes'
>    at initRedactor (/cpresources/349b6808/js/RedactorInput.min.js?v=1527681289:1:2024)
>    at init (/cpresources/349b6808/js/RedactorInput.min.js?v=1527681289:1:1597)
>    at constructor (/cpresources/d073375c/garnish.js?v=1527607584:1:9881)
>    at s.constructor (/cpresources/d073375c/garnish.js?v=1527607584:1:308)
>    at s.constructor (/cpresources/d073375c/garnish.js?v=1527607584:1:308)
>    at Anonymous function (/acn-admin/entries/events/82-test:938:1)
>    at e (/cpresources/61c13c0c/jquery.js?v=1527607584:1:29788)
> SCRIPT438: Object doesn't support property or method 'includes'
> jquery.js (3869,3)

### Additional info

- Craft version: Craft CMS 3.0.9
- PHP version: 7.1.18
- Database driver & version: MySQL

<img width="367" alt="screen shot 2018-06-01 at 10 07 06" src="https://user-images.githubusercontent.com/1353764/40832649-b3fa1a78-6583-11e8-8cf7-48ad6d5f1a9e.png">

<img width="981" alt="screen shot 2018-06-01 at 10 05 26" src="https://user-images.githubusercontent.com/1353764/40832651-b417755a-6583-11e8-9eca-6ea12d64aac5.png">

**Comment by brandonkelly** [comment] 2018-06-02 18:40
Duplicate of craftcms/redactor#46 (and fixed in craftcms/redactor@10d0b22bf34d3bf349c494f20a732dc8d22526cd).

**Closed by brandonkelly** 2018-06-02 18:40 UTC
