### ISSUE TITLE
[3.x]: DB export columns are mixed up

### ISSUE THREAD

**Issue by jamiematrix** [craftcms/cms#13356] opened 2023-06-26 11:25 UTC
### Description
Just under 2 weeks ago we had an issue with a site that producing db exports that were jumbled up (so we couldn't import the export).

`create table` would be like the following for 'assets':
```
  `id` int NOT NULL,
  `volumeId` int DEFAULT NULL,
  `folderId` int NOT NULL,
  `uploaderId` int DEFAULT NULL,
  `filename` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `kind` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT 'unknown',
  `width` int unsigned DEFAULT NULL,
  `height` int unsigned DEFAULT NULL,
  `size` bigint unsigned DEFAULT NULL,
  `focalPoint` varchar(13) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `deletedWithVolume` tinyint(1) DEFAULT NULL,
  `keptFile` tinyint(1) DEFAULT NULL,
  `dateModified` datetime DEFAULT NULL,
  `dateCreated` datetime NOT NULL,
  `dateUpdated` datetime NOT NULL,
  `uid` char(36) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL DEFAULT '0',
```
Then the `insert into` for 'assets' would be:
```
('2022-11-07 16:55:34','2022-11-07 16:55:36','2022-11-07 16:55:34',NULL,'hero.jpg',NULL,3,754,10,NULL,'image',60841,'63072ae0-45b1-4788-8313-5fa66376aea3',5,3,988),
```
As you can see the insert data doesn't match the column order. It's not even in a shifted order making it hard to work out which column should be where

The error during the import would be something like there is already an ID of '2022'. I worked out the `insert into` command was reading a date value instead of an int.

Thinking it was either a plugin or Craft related we installed all available updates and the issue was fixed.

Return to Friday just gone and the same site has the same issue, and today another site has the same issue.

Reading the live data in the database, all the columns are correct, so it must be something in the export process.

A colleague has managed to find adding `--complete insert` to a manual `mysqldump` works, but it would be nice to just get an export from the site when needed.

### Steps to reproduce

1. Use the DB Export feature in Utilities 
2. Import DB into a site (we're using DDEV) and see an error with duplicate IDs

### Craft CMS version

3.8.14

### PHP version

8.1.18

### Operating system and version

AWS Lightsail LAMP stack

### Database type and version

MySQL 8.0.31

### Installed plugins and versions

- Colour Swatches 1.7.0
- Contact Form 2.5.2
- Contact Form Extensions 1.3.2
- Minify 1.2.11
- Navigation 1.4.33
- Redactor 3.10.12
- SEOMatic 3.4.57
- Sprig 1.13.0
- Super Table 2.7.5.1
- Typed Link Field 1.0.25
- oEmbed 1.13.19

**Comment by jamiematrix** [comment] 2023-06-26 20:28
- Yes, the dump's are from Craft (both sites)
- No. No custom backup command, both sites are using the default backup setup.
- `mysqldump --version` returns `mysqldump  Ver 10.19 Distrib 10.11.2-MariaDB, for Linux (x86_64)`

I'll take a look at overriding the command. Thankyou

**Comment by angrybrad** [comment] 2023-06-26 21:26
Sorry... the Craft 3 link for that setting is here: https://craftcms.com/docs/3.x/config/config-settings.html#backupcommand

My first guess as to a root cause would be that your server version appears to be MySQL 8.0.31 from the initial report, but you’re using a `mysqldump` client from MariaDB 10.11.

Given the inconsistencies between MariaDB `mysqldump` versions and MariaDB server versions (same with MySQL `mysqldump` versions and MySQL server versions), much less mixing MySQL and MariaDB, I’d suspect that is the underlying issue.

i.e., if you used a MySQL 8.0.31 compatible `mysqldump`, I guess this wouldn’t be an issue.

Going to go ahead and close this out as it sounds like you’ve got a workaround and a likely root cause, but comment back here if we’re missing anything, and we’ll re-open.

**Closed by angrybrad** 2023-06-26 21:26 UTC
Labels: bug, craft3

**Comment by jamiematrix** [comment] 2023-06-27 09:04
I got the server version from Crafts "System Report", then the `mysqldump` is from a Amazon Lighthouse instance.

I don't think we can change off MariaDB on Amazon RDS (I'm still learning), so I guess we'll need to change the Craft DB export command to be MariaDB compatible for any sites we put on AWS?

**Comment by angrybrad** [comment] 2023-06-27 18:22
@jamiematrix i'm not that familiar with Lighthouse - does it use an actual RDS instance? If so, you should be able to see what the database server and version are easily enough through the RDS console.

**Comment by jamiematrix** [comment] 2023-07-11 11:24
Sorry @angrybrad - hadn't seen the reply.

I meant Lightsail (oops). Yes, LightSail just provides another interface to an RDS instance. I'll see if I can get more details but most of what I can see shows MySQL, but clearly the mysqldump command is running MariaDB
