### ISSUE TITLE
Unknown error at every step in CP (cannot reproduce)

### ISSUE THREAD

**Issue by JeanLucEsser** [craftcms/cms#4033] opened 2019-03-22 10:13 UTC
### Description

This is a very strange issue.
I'm starting with a fresh install (via composer).
I create a single section for my home, nothing else, no fields, no assets, nothing, only one section with an almost empty template. No plugins whatsoever.

Each and every time I save the home entry (or change its status), I get an Unknown Error Occurred message after the Saved entry message. Same thing if I go back into the Section and hit Save... Almost anything I do in the CP brings an unknown error.

Here's the weird thing: nothing gets logged. No errors, not in logs/web.php (no [error]) not in runtime/logs (no files). If I look at what my hosting provider allows me to see from apache logs, I see no errors either.

Also, every time I save the entry, I get a "Delete Stale Template Caches" that waits for ever until I click on another link in the CP. If I change something in the Section, I get a second task "Resaving Home entries" that also waits "pending" forever until I go somewhere else.

To minimize the risk of errors, I set permissions on storage, vendor and co at 777. This happens either in devMode or production environments.

This HAS something to do with my shared hosting as I cannot reproduce it locally. But I have no idea where to look... Without any errors in logs, any hint would be much appreciated.

Save for this annoying error message, everything works as expected.

### Steps to reproduce

I cannot reproduce this outside of my shared hosting platform.

### Additional info

- Craft version: Latest
- PHP version: 7.3
- Plugins & versions: None

**Comment by JeanLucEsser** [comment] 2019-03-22 10:52
I created an admin user for you in the CP in case you wanted to have a look, and on each and every page of the process of adding a user I got the same Unknown Error Occurred. Even though the process completed successfully and the user is created.

I also created an ssh access to the shared server for you should you want to take a quick look, tell me where to send the credentials.

**Comment by jamesmacwhite** [comment] 2019-03-22 11:14
Does your sharing hosting environment meet the requirements in: `/admin/utilities/system-report`. At a guess it's related to the PHP configuration.

**Comment by JeanLucEsser** [comment] 2019-03-22 11:40
Yes that’s the first thing I checked. I even cleaned all caches, via the CP as well as via the command line. It’s a maddening situation!

**Comment by Mosnar** [comment] 2019-03-22 14:05
This might be caused by some overly aggressive mod_security rules on your shared hosting environment. I would take a look down that route. I'm also not sure Craft is 100% compatible with PHP 7.3 yet, you might try downgrading to 7.2 to see if it helps.

**Comment by JeanLucEsser** [comment] 2019-03-22 14:18
I'm now on 7.2.14, same issue. I also checked that no firewall is installed and just in case to make sure deactivated via htaccess. No luck.

**Comment by jamesmacwhite** [comment] 2019-03-22 15:14
You might want to open up a support ticket with your web host to see if they can assist, you seem to have determined that their platform is the problem, so it suggests you'll need to get more information from them about this issue. They may be able to advise if a specific configuration within their environment is causing issues.

Worst case scenario. Maybe a new web host?!

**Comment by JeanLucEsser** [comment] 2019-03-22 15:21
Well the thing is that nothing gets logged. I don't get how Craft can throw an error without logging anything about it, and my web host says they have nothing in their logs either. Plus it looks like everything works as intended except for this Unknown Error. The problem arises on their platform, it could happen on others, the only thing I'm sure of is that I can't seem to reproduce it on my local environment.

**Comment by jamesmacwhite** [comment] 2019-03-22 15:26
It is strange. Without any logs you're flying blind though. Given these errors occur in the CP. Have you tried opening up Developer Tools i.e. Chrome and having console open when these errors occurs, it will give you at least an indication of what error's are happening i.e. 500 server error or maybe timeouts like 503/504.

**Comment by JeanLucEsser** [comment] 2019-03-22 15:48
Yes I have nothing in the console, and nothing else than 200 OK when I monitor the network activity. I even have the craft debug toolbar opened live. I don't see anything out of the ordinary. This is driving me crazy... Thank you for your time btw.

**Comment by narration-sd** [comment] 2019-03-22 16:10
@JeanLucEsser  I just had a look over Craft source, and found what I suspected about these errors.

The main source of them would be scrambled (or missing) returning messages from the AJAX communication that Craft's Control Panel carries out with the Php application, whenever you do actions on that screen.

This would explain no logging on the Php side, as it isn''t responsible for generating them in such a case -- it's already done what you asked, as you indicate, and its acknowledgement (with proper screen message enclosed) is getting disturbed.

In this quick scan, I find comment notes such as 'This shouldn't happen', again indicating this is unexpected behavior. It's true the messages could be more explicit as to where unexpected happened, or likely better, that a browser console logging could be done for that.

Why would such happen? This is where your conversation above has good ideas from others that this is likely to be some sort of security platform from the web host that's over-running its boundaries. Telling them this is likely about broken AJAX communication should give them a good clue as to what to turn off. 

Or, as suggested, another vendor. You can even get managed droplets these days, which might possibly be the best of both worlds so your site has performance independence, but much or all of of the others-manage-the-Linux etc. side of shared hosting. Haven't tried that particular path out, but maybe an idea.

Anyway, Craft developers should pick up on this today anyway with you, but  these ideas should help the calm. I know it can be frustrating until you know a fix can come.

I think we've all seen those messages once in a great while due to some setup problem on a server, and it is true that there are other ways for them to occur, so the best suggestion I can offer in Bend's direction is that any 'Unknown' status ought to visibly report where it came from. Console or when possible Php logs are likely the best place, rather than scattering what can be a customer screen with internal details...!

**Comment by JeanLucEsser** [comment] 2019-03-22 16:42
What you say makes sense but I would expect that if an Ajax request is broken it would show when analyzing the xhr network traffic no? Or are you saying that the request is successful but the returned message is not what is expected? How would that be possible? I'm lost.

**Comment by JeanLucEsser** [comment] 2019-03-22 16:47
(If a craft developer wants to debug live on the platform, it is made for testing purposes for now so no risk of breaking anything, just ask.)

**Comment by narration-sd** [comment] 2019-03-22 17:16
@JeanLucEsser, answers here would get complicated rapidly -- I am just trying to offer you reassurance.

There are at least two paths for getting 'Unknown error' messages  which exist only in the JavaScript -- the browser side independent of PHP.

- the _content_ of Ajax message replies being disturbed. This would take quite knowledgeable instrumentation to see from the outside.
- a session flash message getting disturbed. This is not an Ajax path, but would occur if the hosting didn't provide sessions in a normal way that Craft expects. 

Sessions are a temporary web server storage to share information between browser page invocations, which Php can also write to.

I think I'd be patient here -- let your hosting know what's discussed here about Ajax or sesssions, and then hear from the Craft central team in Bend, Oregon, US for their attuned advice...

**Comment by JeanLucEsser** [comment] 2019-03-22 17:58
If sessions didn't work as expected, I guess I would "see" it while using the CP, things wouldn't be persisted and so on, as sessions are not used to just flash messages. As to Ajax issue, that would be the most plausible thing going wrong. But again, I wouldn't expect for everything to work and show as intended. There's something really fishy going on here. Or so obvious I don't see it.

I'll keep talking with my hosting provider, but he looks as lost as I am. I'll update him on your ideas, but in the meantime if a craft team member wants to chime in, be my guest :)

**Comment by narration-sd** [comment] 2019-03-22 18:20
Good thoughts, but in bugs, it's the unexpected, no?

The point that seems relevant on the Ajax is that the action _requests_ are getting through, thus Craft does what you asked. The messages appear when the _reply_ isn't as expected.

And yes, again, Craft 'Bend Central' -- or Latvia, France, etc., is where you hear from the creators...usually at certain times of the day, but they are always exceptional...

**Comment by JeanLucEsser** [comment] 2019-03-23 13:03
Talking about France, that's where I'm from, and my company is trying to push Craft in the country to its clients and prospects. My hosting provider (OVH) is the front runner in the country, that's why I need to find a way to resolve this issue, it would be too bitter a pill to swallow to ask those clients to switch to another provider... 

One more thing, the issue exists only on Craft 3, previous Craft 2 installs have no issues at all.

Thank you for your time.

**Comment by brandonkelly** [comment] 2019-03-23 16:29
I’m going to close this because it’s probably something specific to your install. Please send in your `composer.json`, `composer.lock` and any custom package files, plus a database backup, over to support@craftcms.com and we can help you from there.

**Closed by brandonkelly** 2019-03-23 16:29 UTC

**Comment by narration-sd** [comment] 2019-03-23 19:06
@JeanLucEsser  just to say, be sure to take Brandon up on this offer. They'll run your site up on a testbed, and will be able to see if the problem's anything on your end. I'm imagining it took until this morning PST to get an answer because Craft were holding something like an off-site planning meeting yesterday.

As far as the hosting side, one can be pretty surprised by the code they run, which is hidden and can be nefarious, against constant threats to their own installation. I certainly have met some cases. Given you're dealing with a top-of-line provider, it's actually more likely there could be something hoping to be sophisticated there.

Anyway, I'm sure I've offered enough advice. I'm no longer in Europe, and Craft's French person is very bright but more the developer of character, sends you a code fix typej as far as I know, so he may not be appropriate here. The Bend team is also probably much better set up for emulating a range of possibilities, and if it comes to that, will further likely get hold of you rapidly for access to probe the installation where it's trying to work.

There is a line, of course, and when it's evident to be the hosting provider's responsibility for the failure, they're the ones who will have to understand and provide the fix.

I will wish you good fortune, of course, and as I'm not sure enough of the nuance to say it properly in what remains of my French...

**Comment by JeanLucEsser** [comment] 2019-03-25 10:27
@narration-sd First of all thank you very much for your time and advised thoughts. The team behind Craft is incredible, I'm well aware of that, it's one of many reasons I can't see myself using anything else... But the community behind Craft is also amazing and receiving contribution from people like you is very valuable, so again, thank you.

@brandonkelly Thank you for your offer, I just sent you the details you requested.

**Comment by narration-sd** [comment] 2019-04-02 07:29
@JeanLucEsser  Jean-Luc, I don't know where you and @brandonkelly got on this, but I just hit something while peeking at history of something fereor a friend which specifically treats things big hosters may do to Ajax.  

And if one does it, they talk and source together, so you may draw your own conclusions, still remembering you're dealing with a respected group.

Here's the link, which is on Github:  [https://github.com/interconnectit/Search-Replace-DB/issues/256](https://github.com/interconnectit/Search-Replace-DB/issues/256)

I hope you resolved the problem without too much issue.
Clive
