### ISSUE TITLE
Unstable "add an asset" modal

### ISSUE THREAD

**Issue by phoob** [craftcms/cms#2215] opened 2017-12-14 09:01 UTC
### Description

Something wrong with "add an asset modal".

### Steps to reproduce

1. Edit entry with an "Add an asset" field, click on "Add an asset".
2. Expand the first level (the volume) by clicking the arrow next to the heading.
3. Try to expand heading on the next level (inside the volume). Observe that this do not work.
4. *optional:* Try to click again for about half an hour or so in frustration.
5. Close the first level and open it again
6. Try to expand level two heading. It opens!
7. *optional:* 🤦‍♂️ 

### Additional info

- Craft version: 3 RC2
- Browser: Safari, Chrome, Firefox on Mac OS 10.13.1

**Comment by andris-sevcenko** [comment] 2017-12-14 09:13
Instructions unclear, stuck at step 4!

**Comment by phoob** [comment] 2017-12-14 09:25
@andris-sevcenko step 4 is optional. As is step 7.

**Comment by andris-sevcenko** [comment] 2017-12-14 09:26
Too late, I broke my glasses.

**Comment by phoob** [comment] 2017-12-14 09:27
haha

**Comment by phoob** [comment] 2017-12-14 09:34
![unstable modal](https://user-images.githubusercontent.com/1475800/33985261-66f7a392-e0ba-11e7-9406-f16170c5c367.gif)

**Comment by carlcs** [comment] 2017-12-14 10:52
This seems to be related or a duplicate of #2210

**Closed** 2017-12-14 13:23 UTC
Labels: bug
