### ISSUE TITLE
FR: Add ability to register custom fields in the details sidebar

### ISSUE THREAD

**Issue by rynpsc** [craftcms/cms#4623] opened 2019-07-19 20:31 UTC
### Description

This is a request to add a way of adding a custom field to the Element details sidebar. At the moment you can register custom HTML via the `cp.entries.edit.details` hook but you can't store input field values. Looking through the source things like revision notes are handled uniquely and have various methods though Craft to retrieve and set the value. Perhaps there could be a generic meta object that plugins can add to `<input name="meta['my-input-name']">`?

These meta fields would follow the same propagation method as the other fields (slug, parent, etc).

I don't see these fields being managed via the field layout editor but controlled by plugins.

### Context

I'm currently working on a custom module where we need to create a custom field that is best suited to the Element details sidebar. It's defining meta relation information sort of like the Parent field and doesn't make sense as a standard field.

At the moment this can be achieved by intercepting the post date on `EVENT_BEFORE_SAVE_ELEMENT` and having a separate database table, but it feels a little brittle and you lose out on draft functionality, multisite, etc unless you reinvent the wheel.

**Comment by brandonkelly** [comment] 2019-07-22 13:31
This is a duplicate of #4175

**Closed by brandonkelly** 2019-07-22 13:31 UTC
