### ISSUE TITLE
[4.9.4]: Autosave draft looping in combination with Neo in a multisite environment

### ISSUE THREAD

**Issue by pnpaes** [craftcms/cms#15046] opened 2024-05-22 06:08 UTC
### Description
I have a multisite installation with Neo plugin being used as a content builder.
The behaviour happens on entries that can be enabled on several sites and also on entries that are individual to each site.
When a new entry is created in a channel or structure, before saving it (or manually creating a draft), if a Neo matrix block is added and any of its content is changed, it causes the autosave to kick in (as expected) but it loops indefinitely.
When I check the logs there is there is a request to `admin/actions/neo/input/update-visible-elements`.
When i check the session values in the logs, in the `__js` property, for every time there is a new call in that loop, there is an extra element added. After a few minutes that was already an array with more than 350 element with this structure:
`    '__js' => [
        0 => [
            0 => 'Craft.MatrixInput.forgetCollapsedBlockId(117006);'
            1 => 4
            2 => null
        ]
        1 => [
            0 => 'Craft.MatrixInput.forgetCollapsedBlockId(117008);'
            1 => 4
            2 => null
        ]
        ....
        352 => [
            0 => 'Craft.MatrixInput.forgetCollapsedBlockId(117710);'
            1 => 4
            2 => null
        ]
`

### Steps to reproduce

1. Create a new structure or channel entry
2. Add a Neo block
3. Edit the content
 Autosave kicks in for an entry that wasn't previously saved or had a draft.

### Expected behavior

Is should only auto save once and as usual

### Actual behavior

Auto save loops indefinitely

I have attached a snippet from the logs

[snippet.log](https://github.com/craftcms/cms/files/15398642/snippet.log)

### Craft CMS version

Craft Pro 4.9.4

### PHP version

8.33.3

### Operating system and version

Linux 6.4.16-linuxkit

### Database type and version

MariaDB 10.7.8

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

CKEditor	3.8.3
Colour Swatches	4.4.0
Control Panel Nav	4.0.12
Cookies	4.0.1
DigitalOcean Spaces Filesystem	2.0.0
Feed Me	5.4.0
Field Manager	3.0.8
Image Resizer	3.0.11
Neo	4.1.2
Redactor	3.0.4
SEOMate	2.2.1
Super Table	3.0.14

**Comment by i-just** [comment] 2024-05-23 11:52
Hi, thanks for getting in touch! Is this still happening if you to edit the affected page in a private/incognito mode?

**Comment by pnpaes** [comment] 2024-05-24 08:26
Hi @i-just , and thank you for reaching out. Yes, this happens also in incognito mode....

**Comment by i-just** [comment] 2024-05-24 08:47
Thanks for confirming! I’m not able to reproduce this. Could you please send your `composer.json`, `composer.lock` and database export to support@craftcms.com (and point to the section where this is happening) so we can try to reproduce and dig deeper?

**Comment by pnpaes** [comment] 2024-05-27 06:22
@i-just i sent the contents to the support email and I also attached the .env just in case (I removed sensitive data)...
I also have contents in the custom config.php file, but that is frontend related. anyhow let me know if you need it.

**Comment by pnpaes** [comment] 2024-05-28 05:50
@i-just can you confirm if you received the file?
i sent it via wetransfer so probably the sender wasn't my email. just thought about it now.

**Comment by i-just** [comment] 2024-05-28 07:20
Hi @pnpaes, it doesn’t look like we received those files. Can you please try sending again?

**Comment by pnpaes** [comment] 2024-05-30 10:30
Hi @i-just, I sent the email again now.
I referenced the issue number in the subject :)

**Comment by i-just** [comment] 2024-05-30 11:48
Thanks @pnpaes. We got it this time!

**Comment by i-just** [comment] 2024-05-30 12:54
Thanks again for the files. I can see the issue you described using your files. 

As per @ttempleton’s [suggestion](https://github.com/spicywebau/craft-neo/issues/888), updating to Neo 4.2.0 resolves this issue.

FWIW, setting `'enableLazyLoadingNewBlocks' => false,` via the `config/neo.php` file (while still on Neo 4.1.3) seems to fix the problem.

I’ll close this now, but feel free to reply if you run into any further problems.

**Closed as completed by i-just** 2024-05-30 12:54 UTC
Labels: bug, craft4

**Comment by pnpaes** [comment] 2024-05-31 07:33
@i-just 
@ttempleton
I would like to inform that the solution(s) proposed didn't work here.
Can you reopen the issue?

![Screenshot 2024-05-31 at 9 30 13 AM](https://github.com/craftcms/cms/assets/1720918/16ac572d-e049-4d02-9eaa-59f728514b8a)

![Screenshot 2024-05-31 at 9 31 59 AM](https://github.com/craftcms/cms/assets/1720918/f3ed0e23-8d5c-4f44-a690-882f56a249bd)

https://github.com/craftcms/cms/assets/1720918/0a3783cb-c2ea-4f1f-a404-cf1064a1d15b

**Comment by pnpaes** [comment] 2024-05-31 07:37
@i-just 
Updating to 4.2.0 did the trick!
Thank you very much for the support. Highly appreciated ;)

**Comment by i-just** [comment] 2024-05-31 07:39
Great news! Thanks for confirming.
