### ISSUE TITLE
[5.x]: Upgrade from 4 has caused element data to move around

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/cms#16323] opened 2024-12-12 12:14 UTC
### Description
Bit of a strange one, but since upgrading from 4 > 5, I have noticed a few instances where asset data has moved from one field to another! See screenshots below. 

Before:
![Image](https://github.com/user-attachments/assets/4d8c1941-18a6-4cc3-8d68-ff952b11874a)

After:
![Image](https://github.com/user-attachments/assets/d794a642-568a-4a4c-adf5-6b2443fec2eb)

This field has been migrated from super table to a matrix field, so could be linked with that?

### Steps to reproduce

1. Upgrade from 4 > 5
2. Migrate Super Table fields to Matrix

### Craft CMS version

5.5.5

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment] 2024-12-13 07:52
Hi, thanks for getting in touch! I’m not able to reproduce that. Any chance you could send your pre-upgrade database export and post-upgrade `composer.json` and `composer.lock` to support@craftcms.com so we can try to reproduce and dig deeper?

**Comment by iamtompickering** [comment] 2024-12-13 08:43
@i-just sure thing, I've done that now!

**Comment by i-just** [comment] 2024-12-13 15:22
Closing as it’s being covered in support.

**Closed as completed by i-just** 2024-12-13 15:22 UTC
Labels: bug
