### ISSUE TITLE
Project config UUID comments not being applied consistently.

### ISSUE THREAD

**Issue by RedLucas** [craftcms/cms#7843] opened 2021-04-27 17:41 UTC
### Description
Since upgrading to 3.6, I noticed that UUIDs in Project config have been being appended with the ID of the field name. This is very convenient, but inconvenient in git if you haven't applied them all. 100s of changes in your diff.
I went ahead and executed a project config rebuild, which made all the necessary changes, which was great.

The problem is that when we make field changes (such as adding helper text to the field) itself, it is going through and removing those same comments. if I run another project config rebuild using the CLI, it fixes it, removing those changes from my diff again. It's like it hasn't decided if it wants to append those comments to UUIDs or not.

### Steps to reproduce

1. Run a Project config rebuild and commit all the changes, which appended many field names to the end of UUIDs.
2. Go into field settings and choose a field that is used in a few different locations. (A commonly used field).
3. Make a change to this field, such as adding helper text or changing its title. 
4. View git changelog, in my case I am seeing an inappropriate amount of changes, it having removed the previously appended field name from the ends of UUIDs.
5. Run a project config rebuild again, and you should see that only your one change remains.

### Additional info

- Craft version: 3.6.12
- PHP version: 7.3.25
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment] 2021-04-28 00:04
I’m not able to reproduce this locally – the field name is _updated_ wherever it was referenced in YAML comments, but the comments aren’t deleted.

Perhaps you imported a production database backup between steps 1 and 2? If the component names aren’t cached in the production DB (`projectconfignames` table), then future changes to the project config would cause regressions in the component name comments throughout your YAML files. See #7795 for a discussion on that.

**Comment by khalwat** [comment] 2021-04-29 16:23
Related? https://craftcms.stackexchange.com/questions/37580/how-to-prevent-inconsistent-comments-in-generated-project-config-yaml-files

**Comment by RedLucas** [comment] 2021-05-05 21:37
Circling back to be polite. I haven't run into this again so I admit it's possible that @brandonkelly you were correct in your assessment.

**Comment by brandonkelly** [comment] 2021-05-09 22:24
I’ll close this for now then. We’re hoping to have a resolution on #7795 for Craft 3.7.

**Closed by brandonkelly** 2021-05-09 22:24 UTC
Labels: bug
