### ISSUE TITLE
[5.x]: Link field options not passed by GraphQL

### ISSUE THREAD

**Issue by thomascoppein** [craftcms/cms#16328] opened 2024-12-13 11:00 UTC
### Description
When I use the Link field with GraphQL it's not passing the "Open in new tab" option.
Currently I only receive the url, which is for most cases enough.

### Steps to reproduce

1. Create a Link field 
2. Create GraphQL query for this field

### Expected behavior
I expect to receive the options of the Link field as an object.

### Actual behavior
I currently only receive the url.

### Craft CMS version

5.5.6.1

### PHP version

8.2

### Database type and version

MYSQL

**Comment by i-just** [comment] 2024-12-13 12:17
Hi, thanks for reaching out! It sounds like a duplicate of https://github.com/craftcms/cms/discussions/16104. It’s been [actioned for 5.6](https://github.com/craftcms/cms/pull/16237).

**Closed as completed by i-just** 2024-12-13 12:17 UTC
Labels: bug

**Comment by thomascoppein** [comment] 2024-12-13 12:29
Hi @i-just , oh didn't see that one. Any date on 5.6 release? 🙏🏻

**Comment by i-just** [comment] 2024-12-13 12:34
Most likely January 2025
