### ISSUE TITLE
Editing modals should only be closable by using the 'cancel' button.

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#4610] opened 2019-07-18 20:56 UTC
### Description

Currently clicking out of an editing modal will close it, even if there is unsaved work. This can be especially aggravating for users entering data who have opened multiple modals.

### Steps to reproduce

1. Double click an entry inside of another entry.
2. Click away from the modal dialog.
3. The modal closes and all unsaved work is lost.

### Additional info

- Craft version: 3.1.x

**Comment by brandonkelly** [comment] 2019-07-19 12:30
This is a duplicate of #2512

**Closed by brandonkelly** 2019-07-19 12:30 UTC
