### ISSUE TITLE
Sidebar falls off screen on certain viewports

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#2171] opened 2017-12-06 14:06 UTC
### Description

As seen in the image below, the only fix is resizing the screen to a tiny width and then back to full.

![image](https://user-images.githubusercontent.com/3626559/33665299-c1f97556-da96-11e7-8dd5-640e8feebb4d.png)

### Steps to reproduce

1. Open an entry on a viewport of about 1440px
2. See the sidebar disappear

### Additional info

- Craft version: 3.0.0-RC1

**Comment by Radiergummi** [comment] 2017-12-07 08:03
Duplicate of #2169, already fixed in 8cb8dce 😄

**Closed** 2017-12-07 21:55 UTC
