### ISSUE TITLE
Sidebar disappears when rich text fields are collapsed

### ISSUE THREAD

**Issue by abinggeli** [craftcms/cms#2177] opened 2017-12-07 21:11 UTC
### Description

When a rich text field of a matrix component is collapsed, the text in the titlebar is not truncated. The editor then becomes too wide and the right sidebar is no longer visible.

### Steps to reproduce

1. Add a rich text field (Redactor) to a matrix component.
2. Fill rich text field with long text
3. Collapse field to only show the titlebar

### Steps to solve

As a workaround, I installed the "Control Panel CSS" plugin an added the following CSS rules:

```
@media (min-width: 998px) {
    #fields {
        max-width: calc(100vw - 350px);
    }
}
@media (min-width: 1224px) {
    #fields {
        max-width: calc(100vw - 575px);
    }
}
```

### Additional info

- Craft version: Craft Pro 3.0.0-RC1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.5.5-10.0.32-MariaDB-0+deb8u1
- Plugins & versions: Control Panel CSS v2.0.0, Redactor 1.0.0

**Comment by brandonkelly** [comment] 2017-12-07 22:18
Duplicate of #2169, fixed in 8cb8dce

**Closed by brandonkelly** 2017-12-07 22:18 UTC
