### ISSUE TITLE
FR: Users fields, per user group

### ISSUE THREAD

**Issue by bymayo** [craftcms/cms#5069] opened 2019-10-09 10:55 UTC
It would be great if we could specify different user fields, per member group.

A problem we've got at the moment is we can't set required fields on a user due to the fields being added to ALL member groups, and not all member groups need the same required fields.

Maybe the fields could be editable within the member group itself.

**Comment by brandonkelly** [comment] 2019-10-09 17:18
This is a duplicate of #1649, but it’s not possible because users can belong to multiple user groups.

That said we will be resolving this in Craft 4 with conditional fields (#805), where one of the available conditions could be whether the user belongs to / doesn’t belong to a particular group.

**Closed by brandonkelly** 2019-10-09 17:18 UTC

**Comment by bymayo** [comment] 2019-10-10 09:01
Whoops - Sorry, I did have a look to see if someone had posted it before.

Thats good to hear that it will work with conditional fields! Will wait for Craft 4 :)
