### ISSUE TITLE
[5.x]: Color Selection Improvement for disabled/enabled elements

### ISSUE THREAD

**Issue by jarheadcore** [craftcms/cms#15199] opened 2024-06-14 12:33 UTC
### Description
Due to red-green color blindness, the difference between an active and an inactive/disabled element is difficult to distinguish. (green or gray...)

![CleanShot 2024-06-14 at 14 32 24@2x](https://github.com/craftcms/cms/assets/11466445/2c4b6acc-d628-4829-8543-78cf635bd024)

### Improvement Recommendation
Change color value of disabled elements to a lighter color and add a slight border? (e.g. )

![CleanShot 2024-06-14 at 14 31 58@2x](https://github.com/craftcms/cms/assets/11466445/adb79976-cc63-454a-b2bb-efecc6d9b358)

### Craft CMS version

5

### PHP version

---

### Operating system and version

---

### Database type and version

---

### Image driver and version

---

### Installed plugins and versions

---

**Comment by i-just** [comment] 2024-06-14 15:47
Hi, thanks for reporting! It looks like a duplicate of https://github.com/craftcms/cms/issues/15195, so I’ll close this one, and you can follow along there.

**Closed as completed by i-just** 2024-06-14 15:47 UTC
Labels: bug

**Comment by brandonkelly** [comment] 2024-06-14 23:49
This is now resolved for the next release! (#15206) Thanks again.

**Comment by brandonkelly** [comment] 2024-06-17 20:24
Craft 5.2.1 is out with that change. Thanks again!
