### ISSUE TITLE
SQL Error when search

### ISSUE THREAD

**Issue by effer89** [craftcms/cms#4157] opened 2019-04-18 18:31 UTC
### Description
Trying to searh by user or entries, i get this error:

```
SQLSTATE[42000]: Syntax error or access violation: 1064 syntax error, unexpected $end, expecting FTS_TERM or FTS_NUMB or '*'
↵The SQL being executed was: SELECT * FROM `searchindex` WHERE MATCH(`keywords`) AGAINST('+"icastro gmail com"*' IN BOOLEAN MODE) AND `siteId` = 1 AND `elementId` IN (
  1,878919,878920,878921
```

This issue is related to #3862.

And if I try change SQL to

```
SELECT * FROM `searchindex` WHERE MATCH(`keywords`) AGAINST('+"icastro gmail com*"' IN BOOLEAN MODE)
```

almost resolve the issue, there any way I can reflect this in code that generates the query?

### Steps to reproduce

1. Search Users and Entries

### Additional info

- Craft version: Craft Pro 3.1.22
- PHP version: 7.1.18
- Database driver & version: MySQL 5.7.14
- Plugins & versions: -

**Comment by brandonkelly** [comment] 2019-04-22 18:21
SQL changes for reference:

```diff
- WHERE MATCH(`keywords`) AGAINST('+"icastro gmail com"*' IN BOOLEAN MODE)
+ WHERE MATCH(`keywords`) AGAINST('+"icastro gmail com*"' IN BOOLEAN MODE)
```

**Comment by angrybrad** [comment] 2019-04-22 22:35
Have you changed the `searchindex` table to use InnoDB?  If so, it seems like you're running into the exact same issues as #3862, which is a result of a [MySQL bug](https://bugs.mysql.com/bug.php?id=78485).

**Comment by northamerican** [comment] 2019-05-14 17:39
what temporary workarounds have worked for you?

using the [search](https://docs.craftcms.com/v3/searching.html) method with dashes triggers the issue. adding `|replace({'-': ' '})` to the end of our query temporarily resolves this.

**Comment by effer89** [comment] 2019-05-22 02:22
Hey guys, sorry for the delay, and thanks for the help!

Well, that's tricky, my craft db is quite large and I using Google Cloud SQL second generation to run the database, and they do not allow MyISAM, I can't change the engine of `searchindex`.

So I change:
https://github.com/craftcms/cms/blob/d6847d80baec90a397a06af05cc4297b03e8aa8c/src/services/Search.php#L590
To: `$keywords = StringHelper::insert($keywords, '"', StringHelper::length($keywords));`

And it's "kinda" working but not good enough (If composer run I need remake the same code :P), some entries I found, others don't.
Some of those cases i didn't found on search, o did go on the entry and just click "SAVE", and starts showing up on search again, saving a entry generate some index or something?

Any ideas on "can't change engine of table" situation would really be welcome?

Thanks for the help! Really appreciate it.

**Comment by effer89** [comment] 2019-05-22 18:13
> Some of those cases i didn't found on search, o did go on the entry and just click "SAVE", and starts showing up on search again, saving a entry generate some index or something?

Well, it does, it's added 2 rows on `searchindex` with title & slug and I think was not there because was used feedme to import, solved.

I just need help with this:
> Well, that's tricky, my craft db is quite large and I using Google Cloud SQL second generation to run the database, and they do not allow MyISAM, I can't change the engine of `searchindex`.
> 
> So I change:
> https://github.com/craftcms/cms/blob/d6847d80baec90a397a06af05cc4297b03e8aa8c/src/services/Search.php#L590
> 
> 
> To: `$keywords = StringHelper::insert($keywords, '"', StringHelper::length($keywords));`

Thanks! :)

**Comment by effer89** [comment] 2019-05-27 17:56
> Well, it does, it's added 2 rows on `searchindex` with title & slug and I think was not there because was used feedme to import, solved.

About that, there's any way I could regenerate this? Or update with missing entries indexes?

**Comment by jkorff** [comment] 2019-06-02 09:11
I had unexplained 500 errors on some of my pages and missing live previews. 

The error message I found in /craft/storage/logs was:
"Next yii\db\Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 syntax error, unexpected $end, expecting FTS_TERM or FTS_NUMB or '*'
The SQL being executed was: SELECT * FROM `searchindex` WHERE `elementId` IN (3001, 3515) AND MATCH(`keywords`) AGAINST('+"mcgee sippel"*' IN BOOLEAN MODE) AND `siteId` = 1 AND `elementId` IN (2607,...,17874) in /home/creativ6/craft/vendor/yiisoft/yii2/db/Schema.php:664"

Which brought me here, because I thought it was related to the "AGAINST" part of the db query.

But it's not. Once I had converted the searchindex table from InnoDB to MyISAM the pages worked again. But I didn't change the searchindex table. Could it be that during the migration to Craft 3.1 it's changed to InnoDB (which is what all other tables are too)?

Craft 3.1.27

**Comment by angrybrad** [comment] 2019-09-24 04:33
Going to go ahead and close this as it seems like a dupe of an existing issue, which is a MySQL bug. https://github.com/craftcms/cms/issues/4157#issuecomment-485575668

**Closed by angrybrad** 2019-09-24 04:33 UTC

**Comment by effer89** [comment] 2019-09-24 19:18
@angrybrad but I can't change the search engine on that table, I need another solution. Maybe if you detect it's innoDB run the search like I pointed out? Which

> > So I change:
> > https://github.com/craftcms/cms/blob/d6847d80baec90a397a06af05cc4297b03e8aa8c/src/services/Search.php#L590
> > 
> > To: `$keywords = StringHelper::insert($keywords, '"', StringHelper::length($keywords));`

Thanks!
