### ISSUE TITLE
Make add a Block dropdown scrollable

### ISSUE THREAD

**Issue by adnankussair** [craftcms/cms#2912] opened 2018-05-22 19:03 UTC
### Description

This issue has been the #1 item my clients using craft have complained about, the long dropdown that opens up on the page. This needs to ideally scroll and not force the user to scroll the whole page as it currently does. The answer is simple and only needs to be applied to desktop breakpoints. Add overflow-y: scroll and a max height on the Add a block menu button. Could this be fixed for the next release of craft 2 and craft 3.

I’ve shown what this would look like in this video: https://drive.google.com/a/trns.fm/file/d/1-vFbo1vOkqTd1DuBql6JyyePpv-4BN4H/view?usp=sharing

### Steps to reproduce

1. Add a lot of block options for the content editor to select from.

### Additional info

- Craft version: 2 & 3
- PHP version: n/a
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by d--j** [comment] 2018-06-04 15:27
Duplicate of #2942?

**Comment by brandonkelly** [comment] 2018-06-05 16:11
Yep! So this is done for today’s release :)

**Closed by brandonkelly** 2018-06-05 16:11 UTC
Labels: enhancement, feature: ax :writing_hand:

**Comment by adnankussair** [comment] 2018-06-05 16:20
Whoot!

ADNAN KUSSAIR (AK)
O 916.273.8716 M 916.796.9891
Transform Studios
www.transformstudios.com
