### ISSUE TITLE
[4.x]:  Cannot assign string to property craft\fields\Tags::$_tagGroupId of type int|false|null

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#10850] opened 2022-03-31 18:10 UTC
### What happened?

I created tag group, then tag field and assigned tag field to section field layout.
When i try to enter entry edit page, this error shows up:

```
Cannot assign string to property craft\fields\Tags::$_tagGroupId of type int|false|null
1. in C:\xampp\htdocs\test\vendor\craftcms\cms\src\fields\Tags.phpat line 190
181182183184185186187188189190191192    {
        if (isset($this->_tagGroupId)) {
            return $this->_tagGroupId;
        }
 
        if (!preg_match('/^taggroup:([0-9a-f\-]+)$/', $this->source, $matches)) {
            return $this->_tagGroupId = false;
        }
 
        return $this->_tagGroupId = $matches[1];
    }
}
```

### Craft CMS version

4.0.0-beta.3

### PHP version

8.1.2

### Installed plugins and versions

-

**Comment by AugustMiller** [comment] 2022-03-31 21:16
Duplicate of #10808? Looks like a fix will be part of Beta 4. :v:

**Comment by brandonkelly** [comment] 2022-04-06 04:22
Yep!

**Closed by brandonkelly** 2022-04-06 04:22 UTC
Labels: bug, craft4

**Comment by brandonkelly** [comment] 2022-04-06 20:36
For posterity, Craft 4.0.0-beta.4 is out now with a fix for this.
