### ISSUE TITLE
Colour swatch doesn't show colour on entries listing

### ISSUE THREAD

**Issue by joshua-martin** [craftcms/cms#2648] opened 2018-03-28 08:52 UTC
### Description

When using the colour field in the entries listing on the admin, it doesn't show the colour, only the placeholder.

![screen shot 2018-03-28 at 09 48 00](https://user-images.githubusercontent.com/1694957/38018672-78deae52-326d-11e8-891c-8214e791fc01.png)

It looks like the correct markup is there, just _.colorpreview_ doesn't have a height set.

![screen shot 2018-03-28 at 09 51 57](https://user-images.githubusercontent.com/1694957/38018741-b2f562b6-326d-11e8-94e5-a1707efb75f7.png)

### Steps to reproduce

1. Create a field with type of Color and show it in the entires listing 

### Additional info

- Craft version: RC 15

**Comment by brandonkelly** [comment] 2018-03-28 10:17
Duplicate of #2587, and this was fixed in RC16.

**Closed by brandonkelly** 2018-03-28 10:17 UTC

**Comment by joshua-martin** [comment] 2018-03-28 10:35
Thanks Brad. Sorry—must've missed it on my search.
