### ISSUE TITLE
Ability to install all plugins from CLI

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#4625] opened 2019-07-20 20:47 UTC
### Description

I just installed loads of plugins through composer by making changes to my Composer file because it's quicker than doing it through the store when I know which plugins I wanted. But there was no method to just install everything in the CMS afterwards.

I had to go through and click 'install' on each plugin. This would be a nice command, although I acknowledge it's a rare occurrance this happens.  

### Steps to reproduce

1. Install plugins via composer
2. Go to CMS and see that you have to click 'install'

**Comment by gtettelaar** [comment] 2019-07-20 21:02
Duplicate of #2405. Pull request to resolve this can be found [here](https://github.com/craftcms/cms/pull/4442) (Don't worry about the 'closed' status), this was done because the PR's base Branch was `3.2` which was removed with the `3.2 GA` release). 

The PR will be part of the `3.3` release tract. If you have any ideas to improve it I'd be happy to hear it :)!

**Comment by JayBox325** [comment] 2019-07-20 21:05
Oh bugger, apologies. I searched the open tasks but not the closed ones 😫.

Buzzing, thanks for this! You guys rule 👏🏻

**Comment by brandonkelly** [comment] 2019-07-22 13:33
It’s also possible to install plugins one-by-one from the CLI using the `./craft install/plugin <plugin-handle>` command.

**Closed by brandonkelly** 2019-07-22 13:33 UTC
