### ISSUE TITLE
After upgrade to 3.2, some entries refuse to save.

### ISSUE THREAD

**Issue by marcushouse** [craftcms/cms#4538] opened 2019-07-12 05:08 UTC
### Description
We've just upgraded a tiny site to Craft 3.2 and we now cannot save SOME entries (others save fine). I can't see anything in field setup that differs between one entry VS another that does save. 

When saving, this is the error we are seeing in dev mode. The site was fine prior to update to 3.2.

REQUEST URL
https://host.name/index.php?p=craftadmin%2Factions%2F/entry-revisions/save-draft

RESPONSE
```
{"error":"SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`pivot_craft`.`craft_drafts`, CONSTRAINT `craft_drafts_revisionId_fk` FOREIGN KEY (`revisionId`) REFERENCES `craft_revisions` (`id`) ON DELETE SET NULL)\nThe SQL being executed was: INSERT INTO `craft_drafts` (`sourceId`, `revisionId`, `creatorId`, `name`, `notes`) VALUES (70, 187, 1, 'Draft 1', NULL)"}
```

### Steps to reproduce

1. Try to update an entry. The Update Entry button stays disabled. We also can't make the Preview mode work on that same entry.

### Additional info

- Craft version: 3.2.1
- PHP version: 7.1.30
- Database driver & version: MySQL 5.7.26
- Plugins & versions:

Imager | v2.1.10
Redactor | 2.3.3.2
Wheel Form | 2.1.1

**Comment by gregorterrill** [comment] 2019-07-12 12:47
I'm getting this too. I also think it's probably the same error @khalwat was mentioning here: https://github.com/craftcms/cms/issues/4515#issuecomment-510322813

To add a few notes - in 3.2 when making changes to an affected entry, it was showing the "An unknown error has occurred" alert repeatedly in the CP. In 3.2.1 the entry still refuses to save but that alert no longer appears - the spinner next to the revision dropdown just appears and disappears but the "Update Entry" button just remains greyed out. Also on affected entries I'm seeing a JS error in the console: `Uncaught TypeError: Cannot read property 'errors' of null at s.constructor.<anonymous> (Craft.js:13144)` This error pops up on initial load of the entry edit screen and every time it tries to autosave. It doesn't show up on other entries that are saving properly.

Live Preview mode _does_ work for me on these entries (maybe because they were saved previously?) but obviously changes aren't reflected as you make them since it can't save.

**Comment by brandonkelly** [comment] 2019-07-13 15:09
Yes, this is a duplicate of #4515, which is fixed for the next release. See https://github.com/craftcms/cms/issues/4515#issuecomment-511011247.

**Closed by brandonkelly** 2019-07-13 15:09 UTC
