### ISSUE TITLE
Double click editing of asset custom fields not saving

### ISSUE THREAD

**Issue by moldedjelly** [craftcms/cms#5816] opened 2020-03-20 04:44 UTC
### Description
I have an asset field within an entry, with some custom fields on it for plaintext fields for Caption and Photo-credit. When double-clicking an asset from within the Entry edit page in control panel, I enter values for the custom fields for the asset and hit Save in the lightbox, and all appears to save. But refreshing the page, the custom fields were not saved. When accessing the Asset from the Assets area of the Control Panel, I'm able to save the custom fields.

### Additional info
- Craft version: 3.4.10.1
- PHP version: 7.2.12
- Database driver & version: MySQL 5.7.17

**Comment by brandonkelly** [comment] 2020-03-20 15:24
I’m not able to reproduce this. Please send your `composer.json` and `composer.lock` files, plus a database backup, over to support@craftcms.com, and point us to an entry where this is happening.

**Comment by cliveportman** [comment] 2020-05-07 09:20
I was experiencing this earlier but have updated to 3.4.18 and all is well.

**Comment by brandonkelly** [comment] 2020-05-07 23:10
Guessing this was related to #5966, which was fixed in 3.4.16.

**Closed by brandonkelly** 2020-05-07 23:10 UTC
