### ISSUE TITLE
Asset index utility - prograss bar covers asset deletion popup 

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#7119] opened 2020-11-11 12:24 UTC
Here's the error:

![image](https://user-images.githubusercontent.com/42622545/98811371-0a48dc80-2421-11eb-84af-cfea6368acd8.png)

Craft version: 3.5.15.1
Browser: chrome 86

**Comment by andris-sevcenko** [comment] 2020-11-11 13:54
Thanks for reporting! However, this is a duplicate of #7111. It is fixed for the next release!

**Closed by andris-sevcenko** 2020-11-11 13:54 UTC
Labels: bug
