### ISSUE TITLE
Asset fields don't respect "view mode" setting if file is dragged into field

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3854] opened 2019-02-18 01:50 UTC
### Steps to reproduce

1. Set field "view mode" to "large thumbnails".
2. Drag file into field, without opening modal.
3. File is displayed as "list".
4. After saving entry that fiels is assigned to, asset is displayed correctly again.

Application Info
PHP version	7.2.12
OS version	Linux 3.10.0-862.14.4.el7.x86_64
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.2.12
Craft edition & version	Craft Solo 3.1.12
Yii version	2.0.15.1
Twig version	2.6.2
Guzzle version	6.3.3
Imagine version	0.7-dev
Plugins
Content Stats	2.1.0
Enupal Translate	1.2.0
Imager	v2.1.4
Image Resizer	2.0.4
MobileDetect	1.0.2
Position Fieldtype	1.0.14
Redactor	2.3.1
Retour	3.1.6
Searchit	1.0.6
SEOmatic	3.1.43
Smart Map	3.2.1
Super Table	2.1.7
Template Comments	1.0.5
Typed link field	1.0.17
Wordsmith	3.0.4

**Comment by brandonkelly** [comment] 2019-02-19 00:04
This is a duplicate of #3578

**Closed by brandonkelly** 2019-02-19 00:04 UTC
