### ISSUE TITLE
Update from 3.0.3.1 to 3.0.4 - Database error: "Duplicate key name"

### ISSUE THREAD

**Issue by MrGlasspoole** [craftcms/cms#2807] opened 2018-04-25 20:54 UTC
Just started with Craft yesterday and today there was the update to 3.0.4 at the backend.
I clicked it and now i have the message that there is an migration error:

```
Database Exception: SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'plugins_handle_unq_idx'
The SQL being executed was: ALTER TABLE plugins ADD UNIQUE INDEX plugins_handle_unq_idx (handle)

Migration: craft\migrations\m150403_184247_plugins_table_changes

Output:

> create unique index plugins_handle_unq_idx on {{%plugins}} (handle) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'plugins_handle_unq_idx'
The SQL being executed was: ALTER TABLE plugins ADD UNIQUE INDEX plugins_handle_unq_idx (handle) (/var/www/proteus-iv/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /var/www/proteus-iv/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE pl...')
#1 /var/www/proteus-iv/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE pl...')
#2 /var/www/proteus-iv/vendor/yiisoft/yii2/db/Migration.php(495): yii\db\Command->execute()
#3 /var/www/proteus-iv/vendor/craftcms/cms/src/db/Migration.php(372): yii\db\Migration->createIndex('plugins_handle_...', '{{%plugins}}', Array, true)
#4 /var/www/proteus-iv/vendor/craftcms/cms/src/migrations/m150403_184247_plugins_table_changes.php(42): craft\db\Migration->createIndex('plugins_handle_...', '{{%plugins}}', Array, true)
#5 /var/www/proteus-iv/vendor/craftcms/cms/src/db/Migration.php(42): craft\migrations\m150403_184247_plugins_table_changes->safeUp()
#6 /var/www/proteus-iv/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#7 /var/www/proteus-iv/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m150403_184247_plugins_table_changes))
#8 /var/www/proteus-iv/vendor/craftcms/cms/src/services/Updates.php(206): craft\db\MigrationManager->up()
#9 /var/www/proteus-iv/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(435): craft\services\Updates->runMigrations(Array)
#10 /var/www/proteus-iv/vendor/craftcms/cms/src/controllers/UpdaterController.php(207): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /var/www/proteus-iv/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /var/www/proteus-iv/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/proteus-iv/vendor/craftcms/cms/src/web/Controller.php(76): yii\base\Controller->runAction('migrate', Array)
#15 /var/www/proteus-iv/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 /var/www/proteus-iv/vendor/craftcms/cms/src/web/Application.php(272): yii\base\Module->runAction('updater/migrate', Array)
#17 /var/www/proteus-iv/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('updater/migrate')
#18 /var/www/proteus-iv/vendor/craftcms/cms/src/web/Application.php(203): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /var/www/proteus-iv/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /var/www/proteus-iv/web/index.php(21): yii\base\Application->run()
#21 {main}
```

### Additional info

- Craft version: update from 3.0.3.1 to 3.0.4
- PHP version: 7.2.4
- Database: MariaDB 10.2.14
- PDO Driver for MySQL: mysqlnd 5.0.12

**Comment by brandonkelly** [comment] 2018-04-25 21:05
Are you running Craft in a Vagrant box by chance?

**Comment by MrGlasspoole** [comment] 2018-04-25 22:08
No. In a Debian VM in Proxmox.

**Comment by brandonkelly** [comment] 2018-04-25 22:52
The migration that Craft is trying to run here is super old – from 2015. When you install Craft, it is [supposed to](https://github.com/craftcms/cms/blob/develop/src/controllers/InstallController.php#L282-L285) mark all existing migrations as “applied”, so that future updates won’t try to re-run these old migrations.

The code for finding all migrations [is pretty standard](https://github.com/craftcms/cms/blob/develop/src/db/MigrationManager.php#L404-L418), so not a lot of room for a logic bug.

I have seen that process skip a single migration before, however, and it ended up being due to a filesystem bug between Vagrant and APFS, which was resolved by moving the host to a non-APFS filesystem.

I know you said you’re not running Vagrant, but I suspect the bug here is similar. For whatever reason, `readdir()` skipped this `m150403_184247_plugins_table_changes` migration when you were installing Craft.

You can temporarily fix the bug by going into your `migrations` database table and add a new row with these values:

- pluginId: `null`
- type: `app`
- name: `m150403_184247_plugins_table_changes`
- applyTime: any timestamp, e.g. `2018-04-25 06:56:40`
- dateCreated: any timestamp, e.g. `2018-04-25 06:56:40`
- dateUpdated: any timestamp, e.g. `2018-04-25 06:56:40`
- uid: any UUID, e.g. `5e7fbf70-6c2b-4d87-ad21-966cc045df04`

That should get you past this error, but you’ll still likely run into other issues down the road, if `readdir()` is unreliable.

**Comment by MrGlasspoole** [comment] 2018-04-29 03:52
> The migration that Craft is trying to run here is super old
Sorry i don't understand? This was a fresh installation and the update came a day later?

If this is just a temporarily fix and i later get problems then it doesn't really help.

**Comment by narration-sd** [comment] 2018-04-29 04:04
What @brandonkelly is telling you, is that where the problem has been seen, an error in the runtime environment caused it -- not Craft.  

The experience was with Vagrant, and he is suggesting similar problem could  possibly be in ProxMox, though I would agree if you felt a filesystem bug should be unusual under *nix.

The error may have come from something else, anything in particular that might have caused the migration file to be missing or perhaps empty or corrupted.  

From here, it looks like your options are to do a full clean and fresh install of Craft, or to do the fixup he gave you as a shortcut.

After that, observation should tell you if you have a problem with the vm filesystem aspect of ProxMox or the hardware it's running on. 

bestes Vermögen, Herr Glasspoole

**Comment by MrGlasspoole** [comment] 2018-05-02 12:41
Since composer is new to me:
Do i need to to run  "composer create-project" again or just "/var/www/mydomain/craft setup" and select another database?

**Comment by brandonkelly** [comment] 2018-05-02 19:38
@MrGlasspoole Just re-run the `setup` command.

**Comment by MrGlasspoole** [comment] 2018-05-03 00:52
Ok, that did work.
95 tables and the folder had 96. But only CreateMatrixContentTable is a exception? Install.php not?
After the login i did the update to 3.0.5 and that also did work.

Now, how do i restore the stuff i already did from the other database where the update failed?

**Comment by brandonkelly** [comment] 2018-05-03 11:00
>  But only CreateMatrixContentTable is a exception?

Correct - that migration will get executed any time you create a new Matrix field, but it’s not part of an actual migration track like the others.

> Now, how do i restore the stuff i already did from the other database where the update failed?

That was just to see if your issue was a fluke or something we could reproduce. It sounds like it was just a fluke though. I’m guessing that your original database is fine, with the exception that it’s missing that one row in your `migrations` table for some reason. So your best bet is to just recreate that one missing row (see https://github.com/craftcms/cms/issues/2807#issuecomment-384458606).

**Comment by MrGlasspoole** [comment] 2018-05-04 09:55
This is killing me.

I did add that row. Then in .env i changed DB_DATABASE from the test one to the old one.

After going to the site i had:
To complete the update, some changes must be made to your database.

Then:
It looks like someone is currently performing a system update.
Only continue if you’re sure that’s not the case.

So sure i did continue and then:
```
Database Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft.assetsources' doesn't exist
The SQL being executed was: ALTER TABLE assetsources CHANGE type type varchar(255) NOT NULL

Migration: craft\migrations\m150403_184729_type_columns

Output:

> alter column type in table {{%assetsources}} to string NOT NULL ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft.assetsources' doesn't exist
The SQL being executed was: ALTER TABLE assetsources CHANGE type type varchar(255) NOT NULL (/var/www/proteus-iv/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /var/www/proteus-iv/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE as...')
#1 /var/www/proteus-iv/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE as...')
#2 /var/www/proteus-iv/vendor/yiisoft/yii2/db/Migration.php(420): yii\db\Command->execute()
#3 /var/www/proteus-iv/vendor/craftcms/cms/src/migrations/m150403_184729_type_columns.php(102): yii\db\Migration->alterColumn('{{%assetsources...', 'type', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /var/www/proteus-iv/vendor/craftcms/cms/src/db/Migration.php(42): craft\migrations\m150403_184729_type_columns->safeUp()
#5 /var/www/proteus-iv/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#6 /var/www/proteus-iv/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m150403_184729_type_columns))
#7 /var/www/proteus-iv/vendor/craftcms/cms/src/services/Updates.php(206): craft\db\MigrationManager->up()
#8 /var/www/proteus-iv/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(435): craft\services\Updates->runMigrations(Array)
#9 /var/www/proteus-iv/vendor/craftcms/cms/src/controllers/UpdaterController.php(207): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /var/www/proteus-iv/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/proteus-iv/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/proteus-iv/vendor/craftcms/cms/src/web/Controller.php(76): yii\base\Controller->runAction('migrate', Array)
#14 /var/www/proteus-iv/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#15 /var/www/proteus-iv/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('updater/migrate', Array)
#16 /var/www/proteus-iv/vendor/craftcms/cms/src/web/Application.php(627): craft\web\Application->runAction('updater/migrate')
#17 /var/www/proteus-iv/vendor/craftcms/cms/src/web/Application.php(205): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /var/www/proteus-iv/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /var/www/proteus-iv/web/index.php(21): yii\base\Application->run()
#20 {main}
```

Now i have the option to restore database or ask for help :-(

**Comment by brandonkelly** [comment] 2018-05-04 10:13
OK so apparently `m150403_184247_plugins_table_changes` wasn’t the only migration row that didn’t get added when you first installed. How many rows are in your `migrations` table anyway?

Looking at Craft’s [migrations/ folder](https://github.com/craftcms/cms/tree/develop/src/migrations), I just realized that `m150403_184247_plugins_table_changes` is the second-oldest migration, and `m150403_184729_type_columns` is the fourth. So it sounds like my original assumption was wrong, and something was just blocking Craft from adding any of those rows.

So that’s good news. Probably just permissions-related or something, which has obviously been sorted out now that Craft _is_ seeing these migratons now.

To sort this out, just make a backup of your `migrations` table in that test database, and restore just that one table into your main database. Then open up the table and make sure it doesn’t have a row for `m180418_205713_widget_cleanup` (which is the one migration that’s actually _new_ since 3.0.3.1).

If you need any help with that, feel free to send a full database backup to support@craftcms.com and we can get you sorted.

Sorry for all the trouble :(

**Closed by brandonkelly** 2018-05-04 10:13 UTC

**Comment by MrGlasspoole** [comment] 2018-05-04 14:44
Thanks now it works.
There was a m180418_205713_widget_cleanup row and i deleted it and then the update worked.
Is there something i need to do to make sure everything is ok (integrity check)?

**Comment by brandonkelly** [comment] 2018-05-04 22:13
Glad to hear that!

You should be good to go. In the future just take a quick glance at the `migrations` table after creating fresh Craft installs, to make sure it looks like it got filled up. I think this was probably just a permissions-related fluke.
