### ISSUE TITLE
project.yaml version error after upgrading to Craft 3.2.1

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#4546] opened 2019-07-12 13:26 UTC
### Description

I get this error whereas Craft CMS and plugins are up-to-date:
`Your project.yaml file was created for different versions of Craft and/or plugins than what’s currently installed.`

### Steps to reproduce

1. Visit the CP after upgrading to Craft 3.2.1 or run `project-config/sync` command

This still happens after:
- Running `composer update`
- Deleting `/vendor` and running `composer install`
- Deleting the `project.yaml` file
- Running the `project-config/rebuild` command

### Additional info

- Craft version: Craft Pro 3.2.1
- PHP version: 7.2.20
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Control Panel CSS 2.2.0, Control Panel JS 2.2.0, Dumper 2.0.0, Element API 2.5.4, Embedded Assets 2.0.10, Expanded Singles 1.0.7, Forms 3.2.1, Imager v2.1.10, Mandrill 1.3.1, Minify 1.2.9, Neo 2.3.5, Redactor 2.3.3.2, Retcon 2.0.12, Retour 3.1.17, SEO 3.2.13, Typogrify 1.1.18

**Comment by brandonkelly** [comment] 2019-07-13 15:21
This error occurs when you are attempting to sync changes from `project.yaml`, but the version of Craft that is installed on the server – and/or the versions of your plugins on the server – are different than the versions specified in the `project.yaml` file. It’s a safeguard because if the versions are different, there’s a chance that the system isn’t going to know how to correctly process the changes you want to sync from `project.yaml`.

(Example: after updating a site to Craft 3.2, sections and Matrix fields are now going to be saved with new `propagationMethod` settings, which will end up in `project.yaml`. If you then were to try to sync that `project.yaml` file to a new server _before_ it was also running Craft 3.2, then it would end up having an error because it didn’t know what to do with those `propagationMethod` values.)

The way around this is to always ensure that you are running `composer install` (**not** `composer update`) before syncing new changes from `project.yaml`. At least on production environments. On development environments, at least remember to run `composer install` when you get this error (as the error goes on to suggest).

The reason `composer update` won’t help is because that could update you to a Craft/plugin version that is _beyond_ the versions `project.yaml` was created with (so it would be an overcorrection). Whereas `composer install` will give you the _exact_ same versions of all your Composer packages that the previous environment had which committed the changes to `project.yaml` and `composer.lock`.

As far as getting you out of this situation now, copy the `composer.lock` and `project.yaml` files from the previous environment into the environment you’re getting this error on. Then run `composer install`.

**Closed by brandonkelly** 2019-07-13 15:21 UTC

**Comment by camaulay** [comment] 2019-07-16 02:19
This is happening for me too. I can confirm that the composer.json/lock files are identical in both my environments even after running composer install I still get this issue.

It happens when I add create new fields in my development environment and attempt to deploy them to my staging environment via the project.yaml. It happens even when composer dependencies haven't changed.

The only way I can get my staging environment work again is by overwriting the staging database with the development database - no ideal because content on staging is being modified by a client and those changes are susceptible to overwrite when I do this.

This makes me think its a database issue, not a composer dependency issue - despite the message "Your `project.yaml` file was created for different versions of Craft and/or plugins than what’s currently installed. Try running `composer install` from your terminal to resolve."

**Comment by romainpoirier** [comment] 2019-07-16 10:47
Thank you @brandonkelly for these explanations, and thank you @camaulay for sharing your experience. In my case, I think it was caused by a push of a Craft  3.2 project config file to a Craft 3.1 website.

Unfortunately, neither `composer update` neither `composer install` solved the error. I had to retrieve a previous DB dump used just before the deployment. I have deployed again, by updating to Craft  3.2  before to sync the file and it has work.

**Comment by brandonkelly** [comment] 2019-07-16 15:53
@camaulay Hmm, next time you see it, please send the following files to support@craftcms.com and reference this GitHub issue:

- `composer.json`
- `composer.lock`
- `vendor/composer/installed.json`
- `config/project.yaml`
- a database backup
