### ISSUE TITLE
Cannot add a column or row to table field

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#2658] opened 2018-03-28 23:29 UTC
### Description

Following the update to RC17 when creating a new field of table field type you can’t add additional columns or rows. Clicking on the “add a column” or “add a row” button is unresponsive.

Verified on Chrome, not tested in other browsers

### Steps to reproduce

1. Create a new field
2. Select “table” for the field type
3. Click on the “add a column” or “add a row” buttons

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by Radabaugh** [comment] 2018-03-28 23:49
duplicate of #2654

**Closed by Radabaugh** 2018-03-28 23:49 UTC

**Comment by brandonkelly** [comment] 2018-03-29 23:11
We just released Craft 3 RC17.1 with a fix for this.
