### ISSUE TITLE
Deselecting all "Sources" and "Transforms" options from a Rich Text field's settings and saving it causes them to be selected again

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1436] opened 2017-02-27 20:24 UTC
### Description

If you go to a Rich Text field's settings and deselect all of the "Available Sources" and "Available Image Transforms" checkboxes, then save the RTF, they will be selected again.

### Steps to reproduce

1. Make sure you have Asset sources/volumes and transforms defined.
2. Go to a Rich Text field's settings.
3. Uncheck all asset sources and transforms.
4. Save the field and go back to its settings.
5. Notice asset sources and transforms are checked.

### Additional info

- Craft version: 2.x and 3.x
- PHP version: n/a
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by brandonkelly** [comment] 2017-02-27 23:09
Duplicate of #21

**Closed by brandonkelly** 2017-02-27 23:09 UTC
Labels: bug, severity: minor
