### ISSUE TITLE
[5.x]: Multi-instance lightswitch issues in element index

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14767] opened 2024-04-08 10:23 UTC
### Description

I have encountered some buggy behaviour on a multi-instance lightswitch field. 

First part of the issue is with the **display of the field in the entry index table** and second part is with **inline editing** on the same table.

### Steps to reproduce

1. Create a lightswitch field with label `Boolean A` and handle `booleanA`
2. Create an section and inside it an entry type with this field. Leave the field label and handle unchanged.
3. To the same entry type add a second instance of the field with label `Boolean B` and handle `booleanB`
4. Create four entries with titles `Boolean A`, `Boolean A AND Boolean B`, `Boolean B` and `None` and in each entry configure the corresponding field values.
5. Go to the section index and add those two fields as table columns.
6. Try to edit the table inline.

### Expected behavior

1. The table columns should display the correct field values
2. Both of those fields should be editable inline.

### Actual behavior

1. The columns are displaying incorrect values:

![image](https://github.com/craftcms/cms/assets/19857599/5a1ee19f-2c32-451a-9244-7f75213c2d4d)

2.  Only one field is editable.

![image](https://github.com/craftcms/cms/assets/19857599/e9ffef4f-c8cc-4d98-a745-9bf6c4199646)

### Craft CMS version

5.0.2

### PHP version

8.3.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment] 2024-04-08 23:19
> The columns are displaying incorrect values

I’m not able to reproduce that:

![An entry index table, listing Boolean A and Boolean B values as expected based on the steps to reproduce](https://github.com/craftcms/cms/assets/47792/3cf4b22c-a8d7-46a8-8978-ba5d2c6267d9)

I was able to reproduce the second issue though, and that’s now fixed for the next release (5dd93e900aabe883fd8bb7ee572601243ec92f4c).

**Comment by thupsi** [comment] 2024-04-09 05:53
You could not reproduce the first part, because there is an additional condition (I just discovered this one):

The first field (the non-overriden one) must be below the second field (the overridden one) in the field layout.

![image](https://github.com/craftcms/cms/assets/19857599/1b40aac0-6bab-4df8-84a6-a65366d2ec1e)

**Comment by i-just** [comment] 2024-04-09 08:46
Thanks! I can reproduce it now, and I raised a PR for this.

**Comment by brandonkelly** [comment] 2024-04-09 22:46
Craft 5.0.3 is out with fixes for both of those issues. Thanks again!

**Closed as completed by brandonkelly** 2024-04-09 22:46 UTC
Labels: bug
