### ISSUE TITLE
`JSONHelper::*code` doesn't process `DateTime`s

### ISSUE THREAD

**Issue by msbit** [craftcms/cms#2114] opened 2017-11-20 04:22 UTC
### Description

Encoding a `DateTime` via `JSONHelper::encode` and then decoding via `JSONHelper::decode` doesn't return a `DateTime` object, rather an associative array with a copy of the fields.

### Steps to Reproduce

Running:

```
$date = new DateTime();
$json = JsonHelper::encode($date);
$decoded = JsonHelper::decode($json);
var_dump($date);
var_dump($json);
var_dump($decoded);
```

Gives:

```
class Craft\DateTime#464 (3) {
  public $date =>
  string(26) "2017-11-20 15:17:31.000000"
  public $timezone_type =>
  int(3)
  public $timezone =>
  string(19) "Australia/Melbourne"
}

string(89) "{"date":"2017-11-20 15:17:31.000000","timezone_type":3,"timezone":"Australia\/Melbourne"}"

array(3) {
  'date' =>
  string(26) "2017-11-20 15:17:31.000000"
  'timezone_type' =>
  int(3)
  'timezone' =>
  string(19) "Australia/Melbourne"
}
```

### Additional info

- Craft version: 2.6.2994

**Comment by narration-sd** [comment] 2017-11-20 07:56
Looks like you might need to be setting the second parameter of the call to false, which will tell it not to return an object as an array,  i.e.:

`$decoded = JsonHelper::decode($json, false);`

JsonHelper::decode looks like it's either passing that argument on to PHP json_decode, or replicating the ability if that function's not available.  

See https://secure.php.net/manual/en/function.json-decode.php for reference

**Comment by msbit** [comment] 2017-11-20 08:00
@narration-sd that is better, but it's still a `stdClass`, not a `DateTime`:

```
class stdClass#464 (3) {
  public $date =>
  string(26) "2017-11-20 18:58:29.000000"
  public $timezone_type =>
  int(3)
  public $timezone =>
  string(19) "Australia/Melbourne"
}
```

when changing to:

```
$decoded = JsonHelper::decode($json, false);
```

**Comment by narration-sd** [comment] 2017-11-20 08:08
could have to do with what I've just checked -- if you're using PHP below 5.4 (is that possible with Craft 2?), the helper library code looks like it will make an array out of an object on the encode side.

All in all, if you need the answer as an object (maybe not for Craft fields) you might  be safer to use straight PHP json_encode() and json_decode() -- and with the appropriate JSON constants, some of which have to do with this object-or-array behavior....

https://secure.php.net/manual/en/json.constants.php

**Comment by narration-sd** [comment] 2017-11-20 08:10
hmm - it's late here -- it could be just that you need to cast the StdClass to a DateTime; not sure about behavior  in PHP around such, but might well work...

**Comment by narration-sd** [comment] 2017-11-20 08:23
@msbit see considerably updated comments above, if you're just watching this over email...

**Comment by narration-sd** [comment] 2017-11-20 08:32
As well, this funkyness of php-json behavior in general might point to the idea that you'd be best to create a DateTime object yourself, if that's what you want, from the json-returned field values. 

That would be safe, and might well be why the Craft helper class defaults the way it does. They are pretty good indeed at thinking out such things.

**Comment by msbit** [comment] 2017-11-20 11:38
@narration-sd thanks for the follow up.

> In fact, I think you're going to need this cast whether it is the helper or straight PHP json_decode, because there's no information in that json string to identify what class of object it is, right?

I guess that's part of this issue, as both `JsonHelper::encode` and `JsonHelper::decode` are provided by the Craft project, more information could be stored at `encode` and used in the `decode`.

This came up because saving a `DateTime` to the settings of our plugin would not work, due to the stored format being the array which, when passed to `DateTime::createFromString` returns `false`. Perhaps in this case a modification to `DateTime::createFromString` would be enough.

**Comment by andris-sevcenko** [comment] 2017-11-20 15:13
I'd like to chime in to say that JSON is used to store data, not objects. As such, when converting an object to JSON, it's only natural that you get the data that the object has, but lose the object's identity. If you're looking for a way to preserve an actual object, you should check out [serialize](http://php.net/manual/en/function.serialize.php) instead.

Storing more information when encoding and using that when decoding doesn't make a lot of sense (especially, since you can use `serialize()` and `unserialize()`), but nothings stopping anyone from wrapping around the `JsonHelper` and adding some magic there as a plugin :)

Given that this is the expected behaviour, I'm closing this issue, but feel free to re-open if I'm just being grumpy and wrong.

**Closed by andris-sevcenko** 2017-11-20 15:13 UTC

**Comment by brandonkelly** [comment] 2017-11-20 16:41
Right, JsonHelper::encode() can convert lots of things to JSON, but you will only ever get either an array or `stdClass` object.

Craft does have a feature that makes JSON-encoding/decoding DateTime objects a little easier though: If your DateTime object is stored on a Model, you can overrides `craft\base\Model::datetimeAttributes()` to include its property name in the returned array:

```php
protected function datetimeAttributes()
{
    $attributes = parent::datetimeAttributes();
    $attributes[] = 'postDate';
    $attributes[] = 'expiryDate';
    return $attributes;
}
```

With that, your DateTime attribute(s) will automatically get converted to an ISO 8601 string when the model is converted to an array or JSON encoded, and automatically converted back to DateTime objects when the model is instantiated.

**Comment by narration-sd** [comment] 2017-11-20 19:07
Nice, guys. And as Leonard Nimoy would have said in his alter ego, 'fascinating'.

Having come up in the time when types were everything in the consideration of objects,, and serialization was the expected way if you were going to transfer over a wire, it's easy to misconceive. 

I've been using JSON a lot, lately, but indeed only as a data coding, and in fact went to sleep last night with intentions of looking into the Javascript originations and seeing whether  they could include any type information -- and  thus what could happen if Php naïvely tried to reconstruct. So much for imagination, if useful, and thanks for the backgrounding, Andris.

That's a neat trick with Models, Brandon, and saves having to wrap with a type indicator yourself, which could go awry of course if crossing system boundaries where the object typename might imply a little differently. It also gets around concern for inner structure vs. the various reconstructors behind the scenes, and per deployment environments, which you;d have if attempting a cast.

Not the worst to meet on a Monday morning, and imagine the framing lets you move ahead well, Tom @msbit.

**Comment by msbit** [comment] 2017-11-20 20:43
Thanks guys, makes sense given the use of JSON.

> Craft 3 does have a feature that makes JSON-encoding/decoding DateTime objects a little easier though
@brandonkelly this would likely solve my problem, how likely are we to see a backport of this functionality to 2.x?

**Comment by brandonkelly** [comment] 2017-11-20 20:58
With Craft 2 you can define actual "date" attributes in your models, which will give it the same features.

```php
protected function defineAttributes()
{
    return array(
        'postDate' => AttributeType::DateTime,
        'expiryDate' => AttributeType::DateTime,
    );
}
```

**Comment by msbit** [comment] 2017-11-21 00:42
Hey @brandonkelly we're currently setting that in the settings model that we return as part of `getSettingsModel`, and there is some code checking the attribute type in `BaseModel::setAttribute` at `BaseModel.php:368`:

```
case AttributeType::DateTime:
```

but this then funnels the JSON decoded array into `DateTime::createFromString` which doesn't deal with the specific format and returns `false`.

I've created a small reproducible plugin at https://github.com/msbit/settingstest which shows this issue.

**Comment by brandonkelly** [comment] 2017-11-21 00:50
You should be setting the value to a `Craft\DateTime` object, not an array with `date` and `time` keys.

**Comment by msbit** [comment] 2017-11-21 01:12
@brandonkelly same outcome with https://github.com/msbit/settingstest/commit/8a8fd69d2783598f8d277b330c2546a6ec8834bc.

**Comment by narration-sd** [comment] 2017-11-21 03:15
Tom, not going to dig into the sources involved this time, as Brandon's on it, also busy here, but a thought or two:

- I wonder what version of php you're on in this case -- and you can think towards deployment.
- in any case, do you find the json_encode/decode twins present at php level?

The point of these two would be the various branch points within the helper depending on what facilities are available, intending to keep straightforward JSON data conversion consistent.

- But in any case, it seems a quite safe way to get your DateTimes would be simply to construct them from the decoded attribute values, whether object or array. This way you are in control, and get what you want if you need to have the correct type objects. I know I've liked some of the comparisions etc. that they can do.

No doubt of cases where this wouldn't be the most fitting, but you can decide.

**Comment by brandonkelly** [comment] 2017-11-21 04:33
Looks like we weren’t actually converting DateTime's to strings for plugin settings. Just tweaked that for the next Craft 2 release.

**Comment by msbit** [comment] 2017-11-21 23:30
@narration-sd 

```
$ php -v
PHP 7.0.25-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 27 2017 13:43:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.25-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
$ php -a
Interactive mode enabled

php > var_dump(function_exists('json_encode'));
php shell code:1:
bool(true)
php > var_dump(function_exists('json_decode'));
php shell code:1:
bool(true)
```
