### ISSUE TITLE
Slug generated keeps some of the special characters accents

### ISSUE THREAD

**Issue by melissadoyon** [craftcms/cms#7828] opened 2021-04-23 18:50 UTC
### Description
When typing or copy-pasting in the Entry Title field content with special characters, the slug generated keeps the accents for some of them.

### Steps to reproduce

1. In the control panel create a new entry with the title "Éléphant"
2. When entering the title, you will see the slug in the right hand side generated is "éléphant" when the result expected would be "elephant"

<img width="1187" alt="Capture d’écran, le 2021-04-23 à 14 41 52" src="https://user-images.githubusercontent.com/78555821/115916058-3e99dd80-a442-11eb-8e1a-30d640d6b6c9.png">

*Note: Do not have this issue with a project currently on Craft version 3.6.3.

### Additional info

- Craft version: 3.6.12
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Amazon S3 (1.2.11) and Redactor (2.8.6)

**Comment by brandonkelly** [comment] 2021-04-23 22:20
That’s expected, as non-ASCII characters are allowed in URLs.

If you wish to limit the automatically-generated slugs to ASCII characters, enable the [limitAutoSlugsToAscii](https://craftcms.com/docs/3.x/config/config-settings.html#limitautoslugstoascii) config setting in `config/general.php`.

```php
'limitAutoSlugsToAscii' => true,
```

**Comment by melissadoyon** [comment] 2021-04-23 23:03
It is indeed what I already have in my config. limitAutoSlugsToAscii is set to true. Therefore I would expect that this behaviour would not occur.

**Comment by brandonkelly** [comment] 2021-04-23 23:28
Are you typing/pasting the non-ASCII characters directly into the Slug field? In that case the setting won’t apply. “Auto” refers to the _auto_-generated slugs that are created based on the entry title.

**Comment by melissadoyon** [comment] 2021-04-23 23:31
No I am typing/pasting the non-ASCII characters into the Title field.

**Comment by brandonkelly** [comment] 2021-04-24 13:21
Sorry, I see what you mean now. Able to reproduce…

**Comment by brandonkelly** [comment] 2021-04-24 14:25
Fixed now for the next release. Sorry about the confusion, and thanks for the report!

**Closed** 2021-04-24 14:25 UTC

**Comment by melissadoyon** [comment] 2021-04-25 15:56
Amazing! Thank you and you're welcome!!

**Comment by brandonkelly** [comment] 2021-04-29 17:34
Craft 3.6.12.1 is out now with the fix for this. Thanks again!

**Comment by vitalijalbu** [comment] 2023-03-21 09:29
> 

Hi, how it will be in craft4? 
`->limitAutoSlugsToAscii(true)` Because i added it, and if i edit the slug with special accents or characters, it still keeps them

**Comment by i-just** [comment] 2023-03-21 09:46
@vitalijalbu`limitAutoSlugsToAscii` only applies to auto-generated slugs: https://craftcms.com/docs/4.x/config/general.html#limitautoslugstoascii.
Nothing stops a user from amending the slug to contain non-ASCII characters.
