### ISSUE TITLE
[4.x]: Asset and folder paths get mangled when updating indexes

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#11174] opened 2022-05-10 09:33 UTC
### Description

I upgraded three different sites from the latest 3.x version to latest 4.x (one of them was a fresh 3.x install that I used to test the update to craft 4)

The sites have assets on local filesystems.

When I complete the upgrade all seems well, but when I try to index my assets, all found assets are tagged as new, and the old records are tagged as missing. 

From what I can tell looking at the index command output, something is wrong with the asset paths, as craft.

This is the output on the fresh 3.x install -> to 4.x

```
Indexing assets in My volume ...
    > #0: party_maske_2022_wide.png ... done
    > #1: Party_Maske_wide.png ... done
    > #2: _1000x374_crop_center-center_none\party_maske_2022_wide.png ... skipped: File “_1000x374_crop_center-center_none\party_maske_2022_wide.png” is in a directory that cannot be indexed.
    > #3: _1000x374_crop_center-center_none\Party_Maske_wide.png ... skipped: File “_1000x374_crop_center-center_none\Party_Maske_wide.png” is in a directory that cannot be indexed.
    > #4: _120x44_crop_center-center_none\Party_Maske_wide.png ... skipped: File “_120x44_crop_center-center_none\Party_Maske_wide.png” is in a directory that cannot be indexed.
    > #5: _240x89_crop_center-center_none\Party_Maske_wide.png ... skipped: File “_240x89_crop_center-center_none\Party_Maske_wide.png” is in a directory that cannot be indexed.
    > #6: _34x12_crop_center-center_none\Party_Maske_wide.png ... skipped: File “_34x12_crop_center-center_none\Party_Maske_wide.png” is in a directory that cannot be indexed.
    > #7: _350x131_crop_center-center_none\party_maske_2022_wide.png ... skipped: File “_350x131_crop_center-center_none\party_maske_2022_wide.png” is in a directory that cannot be indexed.
    > #8: _350x131_crop_center-center_none\Party_Maske_wide.png ... skipped: File “_350x131_crop_center-center_none\Party_Maske_wide.png” is in a directory that cannot be indexed.
    > #9: _5120x5120_fit_center-center_none\Party_Maske_wide.png ... skipped: File “_5120x5120_fit_center-center_none\Party_Maske_wide.png” is in a directory that cannot be indexed.
    > #10: _68x25_crop_center-center_none\party_maske_2022_wide.png ... skipped: File “_68x25_crop_center-center_none\party_maske_2022_wide.png” is in a directory that cannot be indexed.
    > #11: _68x25_crop_center-center_none\Party_Maske_wide.png ... skipped: File “_68x25_crop_center-center_none\Party_Maske_wide.png” is in a directory that cannot be indexed.
    > #12: _700x262_crop_center-center_none\party_maske_2022_wide.png ... skipped: File “_700x262_crop_center-center_none\party_maske_2022_wide.png” is in a directory that cannot be indexed.
    > #13: _700x262_crop_center-center_none\Party_Maske_wide.png ... skipped: File “_700x262_crop_center-center_none\Party_Maske_wide.png” is in a directory that cannot be indexed.
Done indexing assets in My volume.

2 recorded assets are missing their files:
- My volume/Party_Maske_wide.png (104)
- My volume/party_maske_2022_wide.png (106)
```

Worth noting that **when I do the index update via the CP** all the transform subfolders appear in my asset index page as regular folders and all newly detected files have a wrong path (with the full system file path appended at the end of the volume base path).

I'm not sure if this also happens on fresh 4.x installs or/and files are on a remote file system. Will try to test when I have time.

### Steps to reproduce

1. Update a Craft 3 project with local assets to Craft 4
2. Index the assets via CLI or CP

### Expected behavior

The assets are found, no missing files, no new records

### Actual behavior

All assets are tagged as new, the old records are tagged as missing, and there is some confusion with folders and paths in the CP.

### Craft CMS version

Craft Pro 4.0.1

### PHP version

8.1.3

### Operating system and version

Windows 11

### Database type and version

MySQL 8.0.28

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-18)

### Installed plugins and versions

-

**Comment by thupsi** [comment] 2022-05-10 15:10
I _think_ something is amiss with the handling of backward and forward slashes in the Windows filesystem. And this "handling" seems to differ between the Craft CLI and CP indexing of assets, as they produce different results and get all mixed up.

**Comment by angrybrad** [comment] 2022-05-10 16:19
@thupsi are you running this natively on the Windows host machine or inside WSL or something else?

**Comment by thupsi** [comment] 2022-05-10 17:46
I'm running it on Laragon. Haven't had anything similar happen before.

**Comment by angrybrad** [comment] 2022-05-11 04:48
Installed Laragon on a Windows box I can reproduce bits of this, but not others.

To start, Windows works with both `/` and `\` as filesystem path separators. Even though it might look weird in CLI output, it's fine as far as Craft/PHP operations.

> When I complete the upgrade all seems well, but when I try to index my assets, all found assets are tagged as new, and the old records are tagged as missing.

This part:

```
2 recorded assets are missing their files:
- My volume/Party_Maske_wide.png (104)
- My volume/party_maske_2022_wide.png (106)
```

Is a bug, but it happens on both macOS and Windows. I've created an issue for it here: https://github.com/craftcms/cms/issues/11194

Note that from my testing, it doesn't actually affect assets or anything in the control panel, it's just misleading CLI output. Using the asset index utility from the control panel worked fine for me.

I also tested a Craft 3 => 4 migration on Windows with existing assets to ensure that migrations worked as expected and didn't notice any unexpected asset changes.

This output:

> _1000x374_crop_center-center_none\party_maske_2022_wide.png ... skipped: File “_1000x374_crop_center-center_none\party_maske_2022_wide.png” is in a directory that cannot be indexed.

is expected because the transform filesystem on Craft 4 is the same as the volume filesystem on the Craft 3 => 4 upgrade. It can be adjusted after the update, but Craft explicitly ignores transform folders (starting with a `_`, which is what the CLI output is telling you.

> Worth noting that when I do the index update via the CP all the transform subfolders appear in my asset index page as regular folders and all newly detected files have a wrong path (with the full system file path appended at the end of the volume base path).

This I can't reproduce at all, so if you have any additional steps to provide, happy to dig back in.

**Comment by thupsi** [comment] 2022-05-11 07:02
Thanks for getting back @angrybrad! The example output that I included with the ignored files (expected behaviour) was just to show the "missing files" part, but wasn't telling the full story (my bad). You have to have  user created subfolders for more weirdness to happen. I'm providing example steps with screenshots bellow:

1. Have some files in your volume root. Like so: 
<img width="953" alt="01" src="https://user-images.githubusercontent.com/19857599/167786096-d312fc6c-1afe-437b-8a4a-fd83de599bf5.png">

2. Create a subfolder and move a file or more in it: 
<img width="959" alt="02" src="https://user-images.githubusercontent.com/19857599/167786340-47326215-2d27-466a-a4b3-2393094d97f6.png">

3. Try the ```update asset indexes``` in the CP. It produces something like this: 
<img width="281" alt="03" src="https://user-images.githubusercontent.com/19857599/167786625-0a532284-9a9e-46a9-8374-b4facd029ced.png">

4. Go back to the assets page in the CP. You will see something like this:
<img width="959" alt="04" src="https://user-images.githubusercontent.com/19857599/167787075-b1788c2a-d973-466c-9731-59ca60e287dc.png">

Finally, the last part bellow has indeed happened to me but I will have to try to reproduce it again to show the actual steps.

> … newly detected files have a wrong path (with the full system file path appended at the end of the volume base path)

In any case I think there is an underlying issue demonstrated here that when resolved will fix all related problems.

If you still can't reproduce or need additional info just let me know! Thanks!

**Comment by thupsi** [comment] 2022-05-12 17:19
I'm trying to further investigate and from my tests there are two observations:
1. When I use an alias as part of the file system ```Base Path``` it doesn't work as it should
2. When I use a use an environment variable or the full path in the file system ```Base Path``` I **must** use a trailing slash to get somewhat normal results. Still, there continues to be a problem with subfolders, because when I reindex via the CP the transform subfolders inside the volume subfolders show up in the assets page as shown in step 4 above.
3. I also tried a fresh Craft 4 install and I encountered similar issues.

**Comment by thupsi** [comment] 2022-05-13 11:19
This seems to be related: #11219 . As I mentioned before (just didn't have time to describe in detail):

> When I use an alias as part of the file system Base Path it doesn't work as it should

**Comment by angrybrad** [comment] 2022-05-13 23:56
Think I've got a fix for this if you want to test @thupsi .

To get it early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-feature/fix-asset-index-windows as 4.0.2",
  "...": "..."
}
```

Then run `composer update` and let me know how you get along.

**Comment by thupsi** [comment] 2022-05-14 06:56
I just did a quick test and there is definitely progress:

- The alias as part of the base path is working
- The transform subfolders are not indexed. 
- But still the old records are identified as missing their files, and if I run the index via the CP I am presented with the option to delete them. If I choose to keep them, everything seems to work as expected.

I think the fix for #11194 should fix this last point. If this is true we are good! :)

**Closed** 2022-05-18 03:49 UTC
Labels: bug, craft4

**Comment by brandonkelly** [comment] 2022-05-18 03:50
We believe this is fully resolved now for the next release. Would appreciate any additional testing though!

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 4.0.2"` and run `composer update`.

**Comment by maxstrebel** [comment] 2022-05-18 08:08
Nice, solves it for me. Thanks Brandon 👍🏻😅

**Comment by brandonkelly** [comment] 2022-05-20 16:57
Craft 4.0.3 is out now with that fix.
