### ISSUE TITLE
Cannot install: missing package bower-asset/timepicker

### ISSUE THREAD

**Issue by emiliolodigiani** [craftcms/cms#1684] opened 2017-05-02 16:02 UTC
### Description

Trying to install I get this error:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for craftcms/cms ^3.0.0-beta.13 -> satisfiable by craftcms/cms[3.0.0-beta.13].
    - craftcms/cms 3.0.0-beta.13 requires bower-asset/timepicker 1.11.10.0 -> no matching package found.

Potential causes:
 - A typo in the package name
...
```
turns out that in [this commit](https://github.com/craftcms/cms/commit/0ef7e514bd8496b78fb5b90242f739b50e0bd7c2) was inserted in package.json dependency `bower-asset/timepicker` that does not exists in packagist

### Steps to reproduce

1. `composer create-project craftcms/craft test -s beta`

### Additional info

- Craft version: 3.0.0-beta.13
- PHP version: 7.1.2
- Database driver & version: --
- Plugins & versions: --

**Comment by brandonkelly** [comment] 2017-05-02 16:19
Duplicate of #1681

**Closed by brandonkelly** 2017-05-02 16:19 UTC

**Comment by brandonkelly** [comment] 2017-05-02 20:37
Beta 14 was just released with a fix.
