### ISSUE TITLE
Twig not instantiated properly after Twig 2.7 release

### ISSUE THREAD

**Issue by larsboldt** [craftcms/cms#3988] opened 2019-03-13 08:25 UTC
### Description
Problem: Declaration of craft\web\twig\Environment::compileSource(Twig_Source $source) should be compatible with Twig\Environment::compileSource(Twig\Source $source)

From Twig 2.7 changelog:
deprecated passing a Twig\Template to Twig\Environment::load()/Twig\Environment::resolveTemplate()

From CraftCMS composer:
"twig/twig": "^2.5.0"

### Steps to reproduce

1. Update to latest composer libs

### Additional info

- Craft version: 3
- PHP version: 7.3
- Database driver & version: mysql 5.7
- Plugins & versions:

**Comment by andris-sevcenko** [comment] 2019-03-13 08:31
Duplicate of #3983

**Closed by andris-sevcenko** 2019-03-13 08:31 UTC
