### ISSUE TITLE
Reliable Way to Determine if GQL request

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6603] opened 2020-08-10 20:09 UTC
Especially with mutations in the mix, plugins will need to know when they are in a GQL context.

For example, something that hooks into `Entry::EVENT_BEFORE_SAVE` to add a captcha might need to know to bail if this is a GQL request.

AFAIK, the only way to determine this now is to just compare `Craft::$app->request->pathInfo` with the path to your graphql route.

`craft\web\Request::getIsGraphql` sounded promising, but actually is only related to the application/graphql mime-type, which a GQL request may or may not have.

**Comment by brandonkelly** [comment] 2020-08-11 00:06
Duplicate of #6602.

**Closed by brandonkelly** 2020-08-11 00:06 UTC
Labels: enhancement
