### ISSUE TITLE
Ability to hide or disable fields based on a user group

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#813] opened 2017-01-31 03:38 UTC
> Created by: Chris Chiles (chris@mightyinthemidwest.com) on 2015/03/11 18:06:19 +0000
> Votes at time of UserVoice import: 115

-----------------------------------

It would be nice to be able to hide or disable fields based on a user group. I imagine this would happen in the Layout Designer, so that it can be based on section, rather than always tied to a field.

**Comment by brandonkelly** [comment] 2017-07-17 21:00
Duplicate of #947

**Closed by brandonkelly** 2017-07-17 21:00 UTC
Labels: feature
