### ISSUE TITLE
Live Preview IE Error

### ISSUE THREAD

**Issue by b8ne** [craftcms/cms#2015] opened 2017-10-03 23:16 UTC
### Description
In IE live preview is rendering correctly the first time, however on update an exception is being thrown to prevent iFrame update.

I am getting 'Object expected' on the line `this.$iframe[0].contentWindow.document.write(html)` in Live Previews `handleSuccess` method in craft.js.

This is working fine on safari, chrome and firefox.

### Steps to reproduce

1. Open live preview on any entry
2. Change content to force update

### Additional info

- Craft version: 2.6.2989
- PHP version: 7.1.8 (VM), 5.5 (Production) - rushed setup to test but issue is consistent on both
- Database driver & version:

**Comment by takobell** [comment] 2017-10-04 00:40
What version of IE/Edge are you seeing this on?

**Comment by b8ne** [comment] 2017-10-04 00:58
@takobell IE: 11.0.9600

**Comment by takobell** [comment] 2017-10-04 01:45
I'm not able to reproduce this on IE 11.608.15063 on Windows 10 on a fresh install of Craft.  Is your version of IE on Windows 8?

**Comment by b8ne** [comment] 2017-10-09 00:02
Thanks @takobell 
I am testing in a Windows 7 VM with no add-ons, however the client has experienced the issue on windows 10 too.  Given you are unable to replicate the issue im leaning towards it being a site specific issue.  Ill do some more research and comment back here if I find something.  Appreciate your help.

**Comment by takobell** [comment] 2017-10-09 15:32
Cool... going to close this, but just comment here if you find anything and can re-open.

**Closed by takobell** 2017-10-09 15:32 UTC
