### ISSUE TITLE
[Bug] Order of applied element query parameters in templates effects results of subsequent queries.

### ISSUE THREAD

**Issue by monachilada** [craftcms/cms#2227] opened 2017-12-18 17:20 UTC
### Description

Unexpected behaviour when set several variables derived from the same field in an entry. Consider the following:

```
{% set materialTypes = film.materials.all() %}
{% set poster = film.materials.type('poster').one() %}
{{ dump(materialTypes|length) }}
```

Result is `int(4)`

```
{% set poster = film.materials.type('poster').one() %}
{% set materialTypes = film.materials.all() %}
{{ dump(materialTypes|length) }}
```

Result is `int(3)`

Where `film` is an entry and `materials` is an Entries field. The field has 4 entries attached, 3 of which are of type `poster`.

What I would expect is `int(4)` in both cases for the length of `materialTypes` as the Element criteria is being referenced from the film and therefore shouldn't be effected by other queries executed elsewhere. It appears to me that applying the criteria of `.type('poster')` is persisting to the next line.

I'm attaching a DB dump and a simplified version of the template where this is occurring.

[coproduction-office_171218_171716_967vyr5h7l_v3.0.0-rc2.zip](https://github.com/craftcms/cms/files/1568851/coproduction-office_171218_171716_967vyr5h7l_v3.0.0-rc2.zip)

[films copy.twig.zip](https://github.com/craftcms/cms/files/1568861/films.copy.twig.zip)

### Additional info

- Craft version: 3.0.0-RC2 (Pro)
- PHP version: 7.1.12-2+ubuntu16.04.1+deb.sury.org+2
- Database driver & version: MySQL 5.7.20-0ubuntu0.16.04.1
- Plugins & versions: 
    - Redactor 1.0.0.1
    - CP Field Inspect 1.0.2
    - Asset Rev v6.0.0

**Comment by brandonkelly** [comment] 2017-12-18 20:00
Duplicate of #2160

**Closed by brandonkelly** 2017-12-18 20:00 UTC
