### ISSUE TITLE
[3.5 beta 3] Structure order not saving / reverting after a certain period of time

### ISSUE THREAD

**Issue by daltonrooney** [craftcms/cms#6297] opened 2020-07-01 15:09 UTC
### Description
I haven't quite figured out how to reproduce this, but we're using a hierarchical structure and are trying to reorder the entries within. We can successfully drag and drop items into the correct position and see the "New Position Saved" flash, and the change persists for some time, but inevitably when we log in the next day the items have reverted back to the previous position. Odd?

### Additional info

- Craft version: 3.5 beta 3
- PHP version: 7.4.6
- Database driver & version: MySQL 5.5.5

**Plugins**
Amazon S3	1.2.8
Control Panel CSS	2.2.1
Element API	2.6.0
Entry Instructions	1.0.7
Expanded Singles	1.1.2
Field Manager	2.1.6
GraphQL Srcset	1.0.0
Mailchimp Subscribe	dev
Mailgun	1.4.3
MatrixMate	1.2.5
Navigation	1.3.21
Redactor	2.6.1
Redactor Tweaks	2.0.4
Relabel	1.3.5.4
SEOMate	1.1.4
Snitch	3.0.1
Sprout Forms	3.12.2
Super Table	2.5.1
Typed link field	2.0.0-beta.7
Webhooks	2.3.2

**Comment by brandonkelly** [comment] 2020-07-01 22:22
Suspect this is a duplicate of #6250, which was fixed in Craft 3.4.25, but we haven’t released a 3.5 Beta with the fix quite yet.

**Closed by brandonkelly** 2020-07-01 22:22 UTC
