### ISSUE TITLE
Category field - dont allow selecting more categories than branch limit setting allows

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3319] opened 2018-09-20 21:16 UTC
For each category field, admin can set Branch Limit. But even if we set it to specific number, while trying to add categories into field, in category selection window we can select infinite branches. Its just that branches that exceed that number wont be actually added when we click "select" and close window.

What I propose is adding some kind of limiter to category selection window itself.

**Comment by brandonkelly** [comment] 2018-09-23 08:49
Duplicate of #1847

**Closed by brandonkelly** 2018-09-23 08:49 UTC
