### ISSUE TITLE
Some zendframework packages are marked abandoned

### ISSUE THREAD

**Issue by xavierdemoor** [craftcms/cms#5439] opened 2020-01-14 09:55 UTC
During installation of CraftCMS to last version, composer tell me this:

```
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.
```

I'm sure you already know this, but I didn't find it in Issues, so...

**Comment by brandonkelly** [comment] 2020-01-15 01:36
This is a duplicate of #5400, which is fixed in Craft 3.4.

**Closed by brandonkelly** 2020-01-15 01:36 UTC
