### ISSUE TITLE
[4.x]: Switching between Entry Types removes some of the field values.

### ISSUE THREAD

**Issue by pdaleramirez** [craftcms/cms#11791] opened 2022-08-17 07:30 UTC
### Description

Switching between Entry Types removes some of the field values.

### Steps to reproduce

1. Create 2 entry types for a section
2. Add plaintext fields for both entry types.
3. Input values on those 2 plaintext fields and save the entry.
4. Keep switching entry types, on the 3rd or 4th switch one if the field value gets removed.

### Expected behavior
The values should not be removed when switching entry types.

https://user-images.githubusercontent.com/4172750/185057606-6bdf409e-aa16-41dd-a93e-bf51616b7fb3.mp4

### Craft CMS version

4.1

### PHP version

8

### Installed plugins and versions

-

**Comment by olivierbon** [comment] 2022-08-17 13:43
Same as #11746

**Comment by angrybrad** [comment] 2022-08-17 20:37
Closing as a dupe of https://github.com/craftcms/cms/issues/11746 which we're investigating in support.

**Closed by angrybrad** 2022-08-17 20:37 UTC
Labels: bug, craft4
