### ISSUE TITLE
 [5.x]: `Save as new Entry` causes matrix blocks need to resave 

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [craftcms/cms#15331] opened 2024-07-10 17:37 UTC
### Description

For w/e reason when we use the `Save as new Entry` option in an Entry, the new entry forces a user to resave each matrix block again. Running `./craft resave/entries --touch=0 --section="mySectionHandle"` fixes that but shouldn't Craft resave all of the attached components on the creation of the Entry?

### Steps to reproduce

1. Run a feedme import
2. `Save as new Entry` 
3. Go to new entry
4. Try to save the main entry

When saving in this scenario the child blocks' title turns red and you can't save the entry. To correct this we have to open up child blocks attached to the entry and resave it.

### Craft CMS version

5.2.5

### PHP version

8.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment] 2024-07-11 15:13
I’m not able to reproduce that. Any chance you can share your database and Composer files with us so we can try to reproduce on your install? If so please send them to support@craftcms.com.

**Comment by DynamiteGoesBoom** [comment] 2024-07-15 17:33
@brandonkelly it's happening after we run a FeedMe feed, then go to the entry. Craft continues ti make us resave any entry attached to the main entry.

**Comment by brandonkelly** [comment] 2024-07-16 15:05
@DynamiteGoesBoom Can you update your steps to reproduce to include that, and also clarify what you mean by “the new entry forces a user to resave each matrix block again”? Maybe post a screenshot that demonstrates how it’s forcing you?

**Comment by DynamiteGoesBoom** [comment] 2024-07-16 16:07
@brandonkelly sure thing and I added that step in the initial issue. I can't seem to replicate it on my end again, but it did happen yesterday. When saving in this scenario the child blocks' title turns red and you can't save the entry. To correct this we have to open up child blocks attached to the entry and resave it.

**Comment by DynamiteGoesBoom** [comment] 2024-07-16 22:34
@brandonkelly okay i'm able to reproduce this again after running a Feedme feed.I'll email support now with the composer files + the db. Thanks again for the help!

**Comment by DynamiteGoesBoom** [comment] 2024-07-16 22:37
Here's the screenshot:

![Screenshot 2024-07-16 at 3 56 46 PM](https://github.com/user-attachments/assets/d7a57255-79c1-4b8d-a683-809db38b8517)

**Comment by tommysvr** [comment] 2024-07-17 04:56
Received files in support and I can reproduce in a fresh install. It seems to be happening due to a blank value being imported for the Dropdown field.

Reproducible site files: [import-test.zip](https://github.com/user-attachments/files/16260369/import-test.zip)
`admin` / `password`

**Steps to reproduce from the files attached:**
1. Feed Me -> setup Feed URL to use the dummy feed below
2. The 'Dropdown' field inside 'Matrix' is mapped to `dropdown` from the feed.
3. Import the Feed
4. Entry One/Two -> resave -> no error
5. Entry Three -> resave -> error

Unsure of the expected behaviour in this case. I've tested with 'Default Value' set in the feed and also on the Dropdown field, both give the same result.

**Dummy Feed:**
```
[{
  "title": "Entry One",
  "matrix_title": "Matrix Entry One",
  "dropdown": "One"
}, {
  "title": "Entry Two",
  "matrix_title": "Matrix Entry Two",
  "dropdown": "Two"
}, {
  "title": "Entry Three",
  "matrix_title": "Matrix Entry Three",
  "dropdown": ""
}]
```

![screenshot_2024_07_17 _13 51](https://github.com/user-attachments/assets/353a1862-3753-4596-aba8-bb9efd0177d2)

![screenshot_2024_07_17 _13 52](https://github.com/user-attachments/assets/480b0cff-e23e-4ce1-ae85-dc57d31c6afa)

**Comment by i-just** [comment] 2024-07-17 09:50
The same thing happens in v4 (with feed me v5), except it might be less noticeable there as the matrix fields are always shown as blocks, so you only need to save the owner and not the blocks (entries in v5).

The CMS part of this works as expected - the dropdown has an invalid value, so an error is shown and when the nested entry is opened, the field gets marked as modified. More info on this behaviour can be found here: https://github.com/craftcms/cms/issues/14731#issuecomment-2035743817.

I’ll have a look at making an adjustment in Feed Me.

**Closed as completed** 2024-07-17 18:22 UTC
Labels: bug

**Comment by angrybrad** [comment] 2024-07-18 18:51
Feed Me 5.6.1 and 6.2.1 are out with the fix for this.
