### ISSUE TITLE
[5.x]: Craft Date column header not sortable by clicking on column header, but sortable from dropdown

### ISSUE THREAD

**Issue by matthewstick** [craftcms/cms#15335] opened 2024-07-11 20:15 UTC
### Description

There are some column headers like lightswitches and dates that aren't sortable fromt he column header.  However, these are sortable by Craft if i click View -> Sort By -> Custom Field name in the top right.

I undersand entry fields you don't make sortable (I have another ticket for that).  But this is different.  These columns are actually sortable in Craft.  Craft lets you sort them.  Just you can't do it by clicking the column header.  Craft 4 let you do this.

### Steps to reproduce

1. Click on a column header for a data or lightswitch field (probably more)

### Expected behavior

1. It should sort.

### Actual behavior

1. It does not sort.

### Craft CMS version

5.X

### PHP version

8.2

### Installed plugins and versions

-

**Comment by brandonkelly** [comment] 2024-07-13 16:02
I’m not able to reproduce that. “Date Created” and “Date Updated” columns are both clickable for me, like other sortable columns. What specific Craft version do you have installed? Are you getting any JavaScript errors on the page?

**Comment by matthewstick** [comment] 2024-07-13 16:21
Thank you @brandonkelly - I do not see any console errors.  I'm running 5.2.5.  I made a pretty detailed video, which I will now email to your support address.  This screenshots the console and the entire process.  Thanks!

**Comment by brandonkelly** [comment] 2024-07-15 11:46
Sorry, missed that this was a custom field.

This bug was fixed in 5.2.6 (#15297).

**Closed as completed by brandonkelly** 2024-07-15 11:46 UTC
Labels: bug
