### ISSUE TITLE
Migrating existing User Photos from Craft 2 to 3 does not match URL schema; existing photos not found.

### ISSUE THREAD

**Issue by pixleight** [craftcms/cms#5373] opened 2019-12-23 17:24 UTC
### Description
User photos in Craft 2 are uploaded in individual directories of the format `/craft/storage/{username}/original/{filename.ext}` (as well as transforms like `...{username}/60/{filename.ext}`)

After migrating to Craft 3, assets are still being associated with users, but the URL path does not match the file path in the `userphotos` directory. Example:

Original photo uploaded in Craft 2 for john.doe@domain.com and moved to Craft 3 is stored at `/public/uploads/userphotos/john.doe@domain.com/original/photo.jpg`. A function like `currentUser.photo().url()` outputs `http://domain.tld/uploads/photo.jpg`.

Also tried updating user photo location in User Settings. See ![screenshot-01](https://user-images.githubusercontent.com/1278274/71370805-e5771c80-2563-11ea-99b1-869f515eac98.png). Output URL of existing user photos does not change, but new userphoto uploads in Craft 3 get stored in `/public/uploads/userphotos/email@domain.com/photo.jpg` and echoed URL matches.

### Steps to reproduce

1. Moved user photos directory from `/craft/storage/userphotos` to `/storage/userphotos` as outlined in step 4 of https://docs.craftcms.com/v3/upgrade.html#performing-the-upgrade and at https://docs.craftcms.com/v3/changes-in-craft-3.html#user-photos
2. Installed Craft 3 & ran database update
3. Moved user photos directory to a publicly-accessible location; in my case `/public/uploads/userphotos`. 
4. Updated User Photos volume paths from `@storage/userphotos` to match new directory. See 
![screenshot-02](https://user-images.githubusercontent.com/1278274/71366798-f02bb480-2557-11ea-96bb-760604db83f2.png)

### Additional info

- Craft version: Craft Pro 3.3.8 (migrating from 2.7.10)
- PHP version: 7.2.21
- Database driver & version: MySQL 5.7.26
- Plugins & versions: (also tested without plugins)
    - Delete Account 1.0.2
    - Element API 2.6.0
    - Environment Label 3.1.5
    - Express Forms 1.0.4
    - Guest Entries 2.2.4
    - Mailchimp Subscribe 3.0.0
    - Navigation 1.1.13
    - Neo 2.5.3
    - Position Fieldtype 1.0.14
    - reCAPTCHA 1.3.0
    - Redactor 2.4.0
    - Retour 3.1.26
    - Section Field 1.1.0
    - SEOmatic 3.2.28
    - Sprout Reports 1.2.8
    - Template Comments 1.1.2
    - Typogrify 1.1.18
    - Video Embedder 1.1.4

**Comment by brandonkelly** [comment] 2019-12-24 21:03
After updating to Craft 3 (step 2 in your list), does your `users` table (or `craft_users`) have values for the `photoId` column, for users that had photos in Craft 2?

**Comment by pixleight** [comment] 2019-12-28 23:05
@brandonkelly Yes it does, and they point to the right assets.

**Comment by brandonkelly** [comment] 2019-12-30 19:58
Can you double-check that the correct Volume is selected in the User Photo Location setting in Settings → Users → Settings? And also go into that volume’s settings and make sure you’ve definitely got the `userphotos` segment in the Base URL setting?

**Comment by pixleight** [comment] 2020-01-02 20:15
Yes, User Photo Location is set to the User Photos volume. I've tried it both with and without `{username}` or `{email}` set as the subfolder path.

The `userPhotos` volume base URL and path are `@baseUrl/uploads/userphotos` and `@basePath/uploads/userphotos`, respectively.

**Comment by andris-sevcenko** [comment] 2020-01-08 10:30
@pixleight Any chance this is on a site where it's possible to get CP and FTP access? If so, can you get in touch via email (support@craftcms.com) and reference this issue, please?

**Comment by andris-sevcenko** [comment] 2020-01-08 11:06
@pixleight or, a pre-update DB config would also suffice. I could probably mock a few photos and observe the issue myself after upgrading, then.

**Comment by atdotslashdot** [comment] 2020-01-23 10:44
the docs say "Craft will automatically create a new asset volume called “User Photos” at storage/userphotos/ (where Craft previously stored all user photos, but without the <Username>/ subfolders)."
This isn't true, the username is still present in the storage (e.g. storage/userphotos/John.Doe/original/johndoe.jpg)

If i move this folder into web space and set
User photos file system path to
@webroot/userphotos

and set 
User Photo Location to
{username}/original

a new upload will match the same structure but a re-index of User Photos produces lots of
 errors for the existing users that were in craftcms2
```
Missing files
The following files could not be found. Should they be deleted from the index?
User Photos/johndoe.jpg
```
I can see that
User Photos/johndoe.jpg  
doesn't exist (it's actually User Photos/John.Doe/original/johndoe.jpg) but I don't want to delete them from the index and have to reupload a couple of hundred user pictures

is there any solution to this?

**Comment by atdotslashdot** [comment] 2020-01-23 11:38
If it helps, on further investigation, the folder id for all existing users in the assets  table all point toward the userphotos folder (not the individual {username}/original  subfolder)

**Comment by atdotslashdot** [comment] 2020-01-23 12:27
....so it looks like  _moveUserphotos in m160804_110002_userphotos_to_assets.php
failed or didn't get run
no errors were reported on the web page when the update happened .
I'm still looking for a solution how to untangle this :-)

**Comment by andris-sevcenko** [comment] 2020-01-24 11:41
@atdotslashdot when you look at the `migrations` table, do you see the `m160804_110002_userphotos_to_assets ` migration there?

**Comment by atdotslashdot** [comment] 2020-01-24 11:57
@andris-sevcenko 

yes it's in the there, if its useful  the apply time, date created and date updated fields are all exactly the same time

**Comment by andris-sevcenko** [comment] 2020-01-24 12:06
@atdotslashdot Okay. I'm working on reproducing this locally.

**Comment by atdotslashdot** [comment] 2020-01-24 12:11
Thanks

**Comment by andris-sevcenko** [comment] 2020-01-24 13:16
@atdotslashdot unfortunately, I'm unable to reproduce this when migrating a site locally from Craft 2.7.4 to the latest.

Is it possible for you to zip up your site and pre-update DB and send them over to support@craftcms.com referencing this ticket? Otherwise, it's really hard to figure out what's going wrong without being able to trigger it.

**Comment by atdotslashdot** [comment] 2020-01-24 13:32
@andris-sevcenko 
Sadly not, but I'm working on  a migration route here so will have to go through the migration steps again once I've sorted out the new templates. Instead of upgrading via the web page would I be better off running `craft migrate/all  ` to see if any errors are reported next time I try? I would prefer to migrate entirely via the command line if it's possible.
Thanks for your help.

**Comment by andris-sevcenko** [comment] 2020-01-24 14:20
> Instead of upgrading via the web page would I be better off running craft migrate/all to see if any errors are reported next time I try? I would prefer to migrate entirely via the command line if it's possible.

That is preferable, yeah. Let me know how it goes!

**Comment by atdotslashdot** [comment] 2020-01-28 09:44
@andris-sevcenko  I've put  `craft migrate/all`  in a script I'm writing to convert a site and it appears to have worked(and I much prefer the output I'm getting from the command rather than a progress bar on the web page :-) If I was a betting man I'm guessing I may not have had the correct file permissions the first time I tried but I would have expected the web page to have reported that problem rather than fail silently? I will be running the script a few times before swapping a live site so will report back if it fails again with any more clues. Thanks for your help.

**Comment by andris-sevcenko** [comment] 2020-02-17 08:44
Closing this, since it appears to have worked :)

**Closed by andris-sevcenko** 2020-02-17 08:44 UTC
