### ISSUE TITLE
Entry type selector is not visible when quick editing an entry.

### ISSUE THREAD

**Issue by monachilada** [craftcms/cms#4102] opened 2019-04-05 09:21 UTC
### Description
When quick editing (triggered by double click) an entry from an entry field or from the Entries page, the dropdown to select entry type is absent. Creating a new entry in an entry field context provides the option as expected.

### Steps to reproduce

1. Double click an entry from an Entry page or from an entry field that has multiple entry types available to choose from
2. Observe that the expected entry type dropdown is absent

### Additional info

- Craft version: 3.1.21.1

**Comment by brandonkelly** [comment] 2019-04-05 22:19
That’s expected behavior, so I’m marking this as an enhancement.

**Comment by monachilada** [comment] 2019-04-10 09:49
Ok, that's interesting. Could you elaborate on why it is designed to work that way?

My use case is that I have an entries field within a matrix block, and my section has a four entry types that provide slight variations on content — a title and some descriptive text accompanied by either a pull quote, image or video, or nothing at all.

Sometimes I might start typing in the description for a vanilla entry only to realise I need to add an image. I can then select from the dropdown my alternate entry type and my descriptive text is still there, only now I'm offered my additional field for adding the image asset.

But situations might also occur where one of these entries has already been defined, but its variant needs to be switched to one of the other types. I would like to have the same convenience to be able to make this switch from within the quick edit in my entries field rather than having to go back out to my Entries, finding the right entry without the help of the convenience of the context of my related related "parent" element and make the switch from the full entry edit page.

To me it seems inconsistent to offer the option when creating the new entry with quick edit, but not when editing an existing one, when there appears to be no technical reason not to — this can after all be done from the full edit page with no adverse effects.

Would you be open to a PR for the enhancement?

**Comment by brandonkelly** [comment] 2019-04-10 16:38
> Could you elaborate on why it is designed to work that way?

Because it’s not something people tend to change once they’ve created an entry, and we don’t want to add extra fields to the quick edit HUD that we know most people won’t touch. (This is the first time anyone has asked about it, for example.)

> Would you be open to a PR for the enhancement?

Not really, see above. I think we’d want to give the editor HUD a multi-tab UI where extra details like the entry type could be accessed from a separate tab, out of normal view. Something to consider in Craft 4 where we will be making a lot of other field layout enhancements.

**Comment by brandonkelly** [comment] 2021-06-05 22:35
This has been resolved for 3.7. The new entry editor [slideouts](https://github.com/craftcms/cms/pull/8017) include an Entry Type field in the sidebar, regardless of whether it’s a new or existing entry.

**Closed by brandonkelly** 2021-06-05 22:35 UTC
Labels: content modeling :notebook:, enhancement
