### ISSUE TITLE
Craft 3.7.27 => 3.7.27.1 repo priority issue

### ISSUE THREAD

**Issue by wuhhh** [craftcms/cms#10311] opened 2022-01-05 09:50 UTC
### Description

Trying to update craft 3.7.27 => 3.7.27.1 produces the following error. Version was initially at 3.6.4.1 so I started upgrading through specific versions to locate version with the error. Passed through 3.7.0 and all the way up to 3.7.27 without issues.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires craftcms/cms 3.7.27.1, it is satisfiable by craftcms/cms[3.7.27.1] from composer repo (https://repo.packagist.org) but craftcms/cms[3.0.0-beta.1, ..., 3.7.27] from composer repo (https://composer.craftcms.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
  Problem 2
    - clubstudioltd/craft-asset-rev is locked to version 6.0.2 and an update of this package was not requested.
    - clubstudioltd/craft-asset-rev 6.0.2 requires craftcms/cms ^3.0.0-beta.29 -> found craftcms/cms[3.0.0, ..., 3.7.27] but it conflicts with your root composer.json require (3.7.27.1).
    - ...
```

### Steps to reproduce

1. `./craft update craft`

**Comment by nordentwickler** [comment] 2022-01-05 09:55
I can confirm this behavior - wanted to update from 3.7.20 to 3.7.27.1 and got the same error.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires craftcms/cms 3.7.27.1, it is satisfiable by craftcms/cms[3.7.27.1] from composer repo (https://repo.packagist.org) but craftcms/cms[3.0.0-beta.1, ..., 3.7.27] from composer repo (https://composer.craftcms.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
```

**Comment by mudechs** [comment] 2022-01-05 12:01
same issues here on 4 craft installs

**Comment by MoritzLost** [comment] 2022-01-05 13:50
I'm having the same issue. Had a look inside the update command, looks like Craft [forces the use of `composer.craftcms.com` instead of packagist](https://github.com/craftcms/cms/blob/develop/src/services/Composer.php#L441-L444). Looks like that repository hasn't been updated to include the newest version yet, hence the error.

I'm sure this will be fixed soon, but here's a temporary workaround in case someone needs this. Add the `composer.craftcms.com` repository to your `composer.json` and mark it as non-canonical:

```json
    "repositories": [
        {
            "type": "composer",
            "url": "https://composer.craftcms.com",
            "canonical": false
        }
    ],
```

This will force Composer to use the default packagist repository which includes the new version. With this, `php craft update all` works normally. After that, you can remove the repository from `composer.json` again and run `composer update --with-all-dependencies` to update the lock file.

**Comment by brandonkelly** [comment] 2022-01-05 14:42
Sorry about this. All fixed now.

**Closed by brandonkelly** 2022-01-05 14:42 UTC
Labels: bug

**Comment by brandonkelly** [comment] 2022-01-05 19:02
@MoritzLost Not all plugins are necessarily on Packagist, and we didn’t want to force them to be, which is why we manage our own package repo at `composer.craftcms.com`. I wasn’t aware that you could mark a repo as non-canonical though. That seems like a perfect solution. Changed that for the next release.

**Comment by brandonkelly** [comment] 2022-01-05 20:21
Craft 3.7.28 is out now with that change, so hopefully we don’t see this ever again! 🤞🏻
