### ISSUE TITLE
[4.x]: assets native field "alt" not translatable

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/cms#11997] opened 2022-09-22 14:41 UTC
### Description
The assets native field "alt" isn't translatable.

### Craft CMS version

4.2.5.1

**Comment by brianjhanson** [comment] 2022-09-22 19:15
This is a duplicate of #11576. We agree it's not ideal, and is something we're looking to support in Craft 5.

**Closed by brianjhanson** 2022-09-22 19:15 UTC
Labels: bug, craft4

**Comment by WHITE-developer** [comment] 2022-09-23 07:19
@brianjhanson Sorry missed that issue,
But looks like the alt handle isn't a reserved handle, so I can create a custom field with that handle but can't select it than in the layout editor.

**Comment by brianjhanson** [comment] 2022-09-23 16:16
No worries! There are lots of issues to keep track of, a duplicate here or there is expected.

`alt` is a reserved field handle [since 4.0](https://github.com/craftcms/cms/blob/a458fa2c8f4c7b7fc96a903788c8d23b20f539a9/src/models/Volume.php#L185-L189) but only on Volume field layouts. This is similar to words like `group` which is normally allowed, except within users or category field layouts.
