### ISSUE TITLE
[5.x]: Entry Condition not working on tab

### ISSUE THREAD

**Issue by yeboJoseph** [craftcms/cms#15987] opened 2024-10-31 22:32 UTC
### What happened?

We have a matrix with multiple blocks. Within one of the blocks I have a tab with fields. I want to hide the tab based on the section. 
If the rule is Section is one of academicsPages - it doesn't display on academicsPages entries or any other section entries
If the rule is Section is not one of academicsPages - it displays on academicsPages entries and any other section entries

### Craft CMS version

5.4.9

### PHP version

8.2

### Installed plugins and versions

![Image](https://github.com/user-attachments/assets/bb327fd9-8439-4138-afbe-1381a8bff9a3)
-

**Comment by i-just** [comment] 2024-11-01 12:28
Hi, thanks for getting in touch! It sounds like a duplicate of https://github.com/craftcms/cms/issues/15260. 

In a nutshell, it’s working as expected because the matrix entries (formerly called blocks) don’t belong to a section. They belong to the “Online Learning” entry, which belongs to the “Academics Pages” section. 

You can find more info on this in #15260.

**Closed as completed by i-just** 2024-11-01 12:28 UTC
Labels: bug
