### ISSUE TITLE
Cannot resolve env file after update 

### ISSUE THREAD

**Issue by Zsavajji** [craftcms/cms#10581] opened 2022-02-16 10:08 UTC
Hi, i updated one of my instances of Craft to 3.7.33, but i ended up with this error after the update (performed through the cli)

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/6460348/154242317-b08ede69-d0f7-42f0-94fb-80111880ea53.png">

It seems like it's going up the directory structure to find the .env file, which has not been touched by the update.
What could be the culprit? 

### Steps to reproduce

1. Update to 3.7.33
2. Error

### Additional info

- Craft version: 3.7.30.1
- PHP version: 8.1.2
- Database driver & version: MariaDB

**Comment by brandonkelly** [comment] 2022-02-17 00:16
Craft doesn’t ever read or write to your `.env` file directly, except when running the `setup` command for a new install. Beyond that it’s just read by [PHP Dotenv](https://github.com/vlucas/phpdotenv) via your `index.php` file – and only if you still have that library included via `composer.json`, and only if you actually have a `.env` file, exactly where you tell it to find one.

So this is almost certainly not caused by 3.7.33, but perhaps a change to PHP Dotenv if you updated that at the same time, or an environmental change, etc.

Will close this, but feel free to write into support@craftcms.com if you need any additional help.

**Comment by Zsavajji** [comment] 2022-02-17 14:31
I understand this, but i also understand that i'm using the .env file exactly as recommended in the documentation. 
No updates to Dotenv or to any other package were done, and there were no further changes to the environment.
The only difference between this production environment and the local development server are in the usage of the open_basedir setting, which was not changed after the update. 

In fact, rolling back the version of Craft to 3.7.32 makes the system usable again with no changes required except for a restore of the last database backup.

I still consider this as a bug.

**Closed** 2022-02-17 19:30 UTC
Labels: bug

**Comment by brandonkelly** [comment] 2022-02-17 19:31
Doh, I forgot Craft is looking for `.env` files when Dev Mode is enabled, for asset bundle HMR. And there in fact was a change to that logic in 3.7.33 (f1b1315559c33025e13d7b593c52c2ec98c69fbd).

Just fixed this for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.33"` and run `composer update`.

**Comment by Zsavajji** [comment] 2022-02-18 09:28
Thank you for the quick feedback! 
I noticed that HMR was taken into account too, i'll provide better feedback on the issue next time (hopefully there'll be no need!)
For now, removing the basedir restriction works as expected so i'll stick to that until next release.

**Comment by brandonkelly** [comment] 2022-02-18 15:38
Should probably also mention this was only an issue if `open_basedir` was in place _and_ Dev Mode was enabled. Typically `open_basedir` is only ever set on production environments, and Dev Mode should never be set on production environments. So… if this is production, you should probably ensure Dev Mode is not enabled there.

**Comment by brandonkelly** [comment] 2022-02-22 18:36
Craft 3.7.34 is out now with the fix for this.
