### ISSUE TITLE
Users restricted to editing one site can globally disable an entry

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#5411] opened 2020-01-08 15:59 UTC
### Description

I have a multi-site installation with a user group that is restricted to editing one site, but I've noticed that they have the option to set the status of an entry to "Disabled Globally" which changes the status of the entry for every other site, even though their user permissions are restricted to only one site.

![image](https://user-images.githubusercontent.com/24975058/71993718-7a9a3680-322f-11ea-9f70-19745fa333f5.png) 

### Additional info

- Craft version: 3.3.19

**Comment by brandonkelly** [comment] 2020-01-09 18:40
Duplicate of #2817.

**Closed by brandonkelly** 2020-01-09 18:40 UTC
