### ISSUE TITLE
Craft 3: "Undefined variable: allOldSiteSettingsRecords" creating new Structure section

### ISSUE THREAD

**Issue by iliaivanov** [craftcms/cms#1621] opened 2017-04-12 08:48 UTC
### Description
Creating new structure section causes 
```
PHP Notice – yii\base\ErrorException 
Undefined variable: allOldSiteSettingsRecords
in /app/vendor/craftcms/cms/src/services/Sections.php at line 528
```

### Steps to reproduce
1. Navigate to the admin/settings/sections/new
2. Fill form inputs
3. Select *Structure* as a section type
4. Press save

### Additional info

- Craft version: Craft Personal 3.0.0-beta.9
- PHP version: 7.0.17
- Database driver & version: MySQL 5.7.17
- Plugins & versions: Element API 2.0.1

**Comment by brandonkelly** [comment] 2017-04-12 11:16
Duplicate of #1573, and this was fixed in Beta 10.

Just run `composer update` to get the fix.

**Closed by brandonkelly** 2017-04-12 11:16 UTC
Labels: bug, status: duplicate

**Comment by iliaivanov** [comment] 2017-04-12 11:46
Oh, I see. Still can't use Beta 10 due to the Matrix field issue #1610, which is not yet released. But anyway, it's my problem. Thank you @brandonkelly  for the info!

**Comment by brandonkelly** [comment] 2017-04-12 17:52
If you update your `craftcms/cms` package version requirement to `dev-develop` in `composer.json` and run `composer update`, you will get the latest commit on our [`develop`](https://github.com/craftcms/cms/tree/develop) branch, which will include that Matrix fix ;)
