### ISSUE TITLE
Assets field type crashes entry editing

### ISSUE THREAD

**Issue by sjadema** [craftcms/cms#1414] opened 2017-02-22 22:16 UTC
### Description

I created an `Assets` field type with an upload restriction to a single folder and added it to a section. When i try to edit the section, the CP crashes. See the attached screenshots for configuration and the triggered error.

### Steps to reproduce

1. Create a volume
2. Create an `Assets` field type with a restriction to a single folder
3. Add the field to a section
4. Try to edit the section

### Additional info

- Craft version: 3.0.0-beta.4
- PHP version: 7.1.1
- Database driver & version: MySQL 5.7.17
- Plugins & versions:

![image](https://cloud.githubusercontent.com/assets/5380502/23235154/b41f708a-f954-11e6-93bf-684992c29684.png)

![image](https://cloud.githubusercontent.com/assets/5380502/23235176/d2ec75e4-f954-11e6-8b11-5bdf2c5d7d99.png)

**Comment by andris-sevcenko** [comment] 2017-02-23 07:36
This is pretty much a duplicate of #1374, however some more bugs still remain there so keeping this open.

**Comment by andris-sevcenko** [comment] 2017-03-07 07:42
Fixed via  192341b

**Closed by andris-sevcenko** 2017-03-07 07:42 UTC
Labels: bug, severity: normal
