### ISSUE TITLE
Feature Request: Two-Factor Authentication

### ISSUE THREAD

**Issue by iapparatus** [craftcms/cms#4869] opened 2019-09-01 17:10 UTC
Implement native support for Two-Step Authentication for the control panel and front-end templates.

**Comment by Mosnar** [comment] 2019-09-01 17:35
There is [at least one plugin](https://plugins.craftcms.com/two-factor-authentication) for this, but I think in the current social and political environment, native U2F and/or password policies would be a pretty big selling point for Craft. 

As an additional note, I know there are some [issues](https://github.com/born05/craft-twofactorauthentication/issues/11) with 2-factor plugins at this point due to the lack of ability to extend the re-authorization modal. Perhaps as a short-term solution, the authentication dialog could be given some events to listen for.

**Comment by brandonkelly** [comment] 2019-09-03 20:17
This is a duplicate of #1916

**Closed by brandonkelly** 2019-09-03 20:17 UTC
