### ISSUE TITLE
Scrollbar in sidebar when nothing is set

### ISSUE THREAD

**Issue by stoneandstorm** [craftcms/cms#1702] opened 2017-05-12 10:57 UTC
### Description
I got on a fresh installation a layout issue at the fields and assets settings. When there are no fields or groups available you see an scroll bar. I got this with the latest versions of FF, Chrome, Edge and IE. Looks like the max-height is not calculated good by java-script?

Here an screenshot at the Fields settings, but this happen also at Assets.
![craftcms_bug](https://cloud.githubusercontent.com/assets/5113702/25995248/a262dfd0-3711-11e7-8c88-01e6bf5f2f43.JPG)

### Steps to reproduce

1. Go to the Fields or Assets page when nothing is set.

### Additional info

- Craft version: 3.0.0-beta.14
- PHP version: 7.0.13
- Database driver & version: MySQL 5.6.34-log
- Plugins & versions: none

**Comment by brandonkelly** [comment] 2017-05-12 11:31
Duplicate of #1364

**Closed by brandonkelly** 2017-05-12 11:31 UTC
