### ISSUE TITLE
Site-specific Assets don't function now, in beta7

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1497] opened 2017-03-11 20:41 UTC
### Description
This used to work, I think, before the basic issue in Sites was straightened out in #1472.

I have tried the four general permutations in setting the (both quite obscure meaning, both need clarifying) 'Manage relations on a per-site basis' and 'Target Site Which site do you want to select assets in?' items of the field definition. I think only the 'Manage relations' one ought to affect.

In all cases now, beta7, changing the image asset on any Site of the entry changes all the others, rather than being separated, which again I am pretty strongly confident it was before the #1472 fix.

What you see on the web, as expected thus, is now improperly the same image for each site.

N.b. I would remind while you're at it on this one CRAFT_SITE appeared to be used independently of the Sites object and its currentSite, visible when other things were broken, and so probably you wantmow to center all Sites-related information on that Sites object?

### Steps to reproduce

1.
2.

### Additional info

PHP version	7.1.2-3+deb.sury.orgxenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-3+deb.sury.orgxenial+1
Craft edition & version	Craft Personal 3.0.0-beta.7
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins: none

**Comment by brandonkelly** [comment] 2017-04-04 19:09
This looks like a duplicate of #1560 (fixed in Beta 8).

**Closed by brandonkelly** 2017-04-04 19:09 UTC
Labels: bug, status: duplicate

**Comment by narration-sd** [comment] 2017-04-05 00:52
Yes, this works now, great, as far as per-site assets, thanks -- if with a bit of further assete funkiness though.

I'll issue an issue separately...!
