### ISSUE TITLE
ElementQuery::search inconsistent with `BaseOptionsField` fields

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#2300] opened 2018-01-12 14:39 UTC
### Description

Searching on a `BaseOptionsField` yields inconsistent results.
Examples:

```php
// Works
Entry::find()->search('myCheckboxField:someValue');

// Works (oddly enough)
Entry::find()->search('myCheckboxField::someValue');

// Doesn't work (no results)
Entry::find()->search('myDropdownField:someValue');

// Works
Entry::find()->search('myDropdownField::someValue');
```

As you can see, there seem to be inconsistencies depending on if the field has `SingleOptionFieldData` or `MultiOptionsFieldData`, and what type of search is performed (contains `:` vs strict `::`).

### Additional info

- Craft version: 3 RC5
- PHP version: 7.1

**Comment by brandonkelly** [comment] 2018-01-12 17:28
> ```php
> // Works (oddly enough)
> Entry::find()->search('myCheckboxField::someValue');
> ```

FWIW, this should only work if the checkbox field only has a single option selected.

**Comment by timkelty** [comment] 2018-01-12 17:46
> FWIW, this should only work if the checkbox field only has a single option selected.

Ah, that makes sense.

**Comment by timkelty** [comment] 2018-01-12 17:51
FWIW, if it were up to me, I wouldn't use `ElementQuery::search` for this, and instead use the fields as parameters directly. I just happen to notice the current behavior working on someone else's code.

**Comment by brandonkelly** [comment] 2018-01-12 19:16
Any chance `someValue` was actually a 3-(or less)-character-long word? If so, this is a duplicate of #1735, which I just fixed for the next Craft 3 release.

**Comment by brandonkelly** [comment] 2018-01-12 19:16
(I was able to reproduce with a 3-character dropdown option value, but not a longer one.)

**Comment by timkelty** [comment] 2018-01-12 19:46
It was!

**Comment by brandonkelly** [comment] 2018-01-12 23:01
Sweet! Fixed for next release, then :)

**Closed by brandonkelly** 2018-01-12 23:01 UTC
