### ISSUE TITLE
entry not found but exists.

### ISSUE THREAD

**Issue by rperrot** [craftcms/cms#6222] opened 2020-06-16 20:15 UTC
### Description

Hi, 

since last update of CMS, I've got some strange issues on some newly created entries. Theses entries belongs to a structure. However, on the entry panel, if I click on the structure name on the left side, I can't see the element. It only appears if I click on "all entries". Then if I click on the entry to edit it, I got a "entry not found" page. I can quick edit it if I check the box and select edit entry. 

To what I understand, the entry doesn't look like to belong to the structure.

I checked in the DB and the entry exists, it's type is ok but as I suggested I didn't see it in the structureelements table. 

Is there a way to: 
- (cleanly) Delete these entries (since I cannot edit it, I can't delete) ?
- Update the database to insert theses entries in the structureelements table  ?
- check database integrity to detect elements like this (ie: they have structure type but they are not listed in structureelements table) ?

### Steps to reproduce

I don't have a specific way to reproduce it: just create the entry. Some of the entries are Ok, some are not (less than 5 I think). Entries don't have special characters.

### Additional info

- Craft version: Craft Solo 3.4.23
- PHP version: 7.2.31
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 

Bootstrap 4.1.3.1
Child Me!  1.1.1
Cloner  1.1.2
Content Stats  2.1.1
Fix FKs  1.0.2.1
Redactor 2.6.1
Sentry 1.5.1
SEO 3.6.5.1
Spreadsheet Tools 3.0.0-beta.1
Table Maker 2.0.1

**Comment by brandonkelly** [comment] 2020-06-16 20:20
This is a duplicate of #6204. We just released Craft 3.4.24 with a fix. Once you’ve updated, you will need to run the following CLI command to repair your entries:

```sh
./craft utils/repair/section-structure <sectionHandle>
```

**Closed by brandonkelly** 2020-06-16 20:20 UTC

**Comment by rperrot** [comment] 2020-06-16 20:30
I'm sorry, I didn't find this issue in my investigations. That's perfect.

A very huge thank you for your support !
