### ISSUE TITLE
Enhancement: Multi-Site Asset Titles

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4233] opened 2019-05-08 23:50 UTC
It would be nice to have an option so changes to individual asset "titles" (for a particular volume or asset field) would replicate across each site in a multi-site setup.

**Currently if you rename a specific asset title (from the CP) on one site, that title change is not reflected across the other sites.**

An alternative approach may be to provide an option to define a single instance asset volume i.e. one that is setup where changes to any assets within it are global and would be the same across all sites in a multi-site setup (a single "global" view of the asset data).

**Comment by richhayler** [comment] 2019-05-08 23:59
Related: #3586

**Comment by brandonkelly** [comment] 2019-05-09 11:39
This is a duplicate of #2856

**Closed by brandonkelly** 2019-05-09 11:39 UTC

**Comment by samlising** [comment] 2020-11-13 10:04
It seems currently (craft 3.5.15.1) the title for Sections can be set to non-translatable, but for Assets titles I do not seem to see a non-translatable option. Is there a way to make Asset titles non-translatable?

**Comment by brandonkelly** [comment] 2020-11-13 19:15
@samlising Correct, that option has only been added for entries. Please post a new issue if you’d like that option for assets.
