### ISSUE TITLE
Creating a new child entry fails

### ISSUE THREAD

**Issue by ragnarfrosti** [craftcms/cms#6221] opened 2020-06-16 13:26 UTC
### Description
There seems to be an issue when creating a child entry to a parent entry that is disabled.
The child entry does only exist under "All entries" but not in the structure. But the child entry returns 404 when trying to edit the entry from the "All entries" view. 

### Steps to reproduce

1. Create a new structure entry that is disabled
2. Add a child to that entry
3. The child entry is only visible under "All entries" but can't be accessed in the CP as that url returns 404.

### Additional info

- Craft version: 3.4.23

**Comment by brandonkelly** [comment] 2020-06-16 13:56
This is a duplicate of #6204. Fixed for today’s release :)

**Closed by brandonkelly** 2020-06-16 13:56 UTC

**Comment by brandonkelly** [comment] 2020-06-16 20:19
For posterity, Craft 3.4.24 is out now with that fix.

**Comment by brandonkelly** [comment] 2020-06-16 20:23
For posterity, Craft 3.4.24 is out now with that fix.

Once you’ve updated, you will need to run this CLI command to repair your entries:

```sh
./craft utils/repair/section-structure <sectionHandle>
```
