### ISSUE TITLE
An error occurs when uploading (replacing) a file that already exists but is not a Craft asset yet

### ISSUE THREAD

**Issue by thijskaspers** [craftcms/cms#6216] opened 2020-06-15 08:17 UTC
### Description

An error occurs when uploading and replacing a file that already exists in storage but is not a Craft asset in the db yet. This can happen when you upload a file from localhost to a Google Cloud bucket for example, and then try to upload that same file again on the staging server that is connected to the same bucket, but has a different db.

### Stacktrace

At first

````
2020-06-15 10:06:33 [-][1][-][warning][craft\elements\Asset::_dimensions] Asset  is missing its width or height
2020-06-15 10:06:33 [-][1][-][warning][craft\elements\Asset::_dimensions] Asset  is missing its width or height
2020-06-15 10:06:33 [-][1][-][info][application] $_GET = [
    'p' => 'beheer/actions/assets/upload'
]
````

And then:

````
2020-06-15 10:06:36 [-][1][-][warning][craft\services\AssetTransforms::deleteAllTransformData] Unable to delete the file "/var/www/storage/runtime/assets/sources/576.png".
2020-06-15 10:06:36 [-][1][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Trying to get property 'filename' of non-object in /var/www/vendor/craftcms/cms/src/controllers/AssetsController.php:475
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(74): craft\web\ErrorHandler->handleError()
#1 /var/www/vendor/craftcms/cms/src/controllers/AssetsController.php(475): craft\web\ErrorHandler->handleError()
#2 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\AssetsController->actionReplaceFile()
#3 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/var/www/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#4 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#5 /var/www/vendor/craftcms/cms/src/web/Controller.php(178): craft\controllers\AssetsController->runAction()
#6 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\controllers\AssetsController->runAction()
#7 /var/www/vendor/craftcms/cms/src/web/Application.php(291): craft\web\Application->runAction()
#8 /var/www/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction()
#9 /var/www/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest()
#10 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#11 /var/www/web/index.php(21): craft\web\Application->run()
#12 {main}
2020-06-15 10:06:36 [-][1][-][info][application] $_GET = [
    'p' => 'beheer/actions/assets/replace-file'
]

$_POST = [
    'sourceAssetId' => '576'
    'targetFilename' => 'Screenshot-10.06.05.png'
]
````

### Steps to reproduce

1. Upload a file to a Google bucket (or your own storage driver)
2. Go to assets in Craft and try to upload that same file which is not an asset yet
3. Choose "Replace it" in the popup

Refreshing the page afterwards shows that the asset has been successfully added, but before that it will give the default red warning in the top center.

### Additional info

- Craft version: Craft CMS 3.4.23
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment] 2020-06-15 22:25
This seems like a duplicate of #6193, which was fixed in 3.4.23. Are you sure you were getting this error while running that version?

**Comment by andris-sevcenko** [comment] 2020-06-16 08:01
@brandonkelly it's not a duplicate. It's definitely related, but it's in a different `assets` controller action.

**Comment by andris-sevcenko** [comment] 2020-06-16 10:43
Alright, fixed both of those for the next 3.4 release!

**Closed** 2020-06-16 10:43 UTC

**Comment by thijskaspers** [comment] 2020-06-16 11:15
Thanks guys!

**Comment by brandonkelly** [comment] 2020-06-16 19:42
Craft 3.4.24 is out now with this fix.

**Comment by cap-akimrey** [comment] 2020-06-18 19:01
We noticed this issue last week, and it came up again today. I've now updated to 3.4.24, but the issue persists.

![Screen Shot 2020-06-18 at 2 00 13 PM](https://user-images.githubusercontent.com/41020122/85061224-167b8700-b16c-11ea-863e-093f33b935a9.png)

**Comment by andris-sevcenko** [comment] 2020-06-19 07:49
@cap-akimrey If you're trying to just upload a file and such a file already exists but is not indexed, I would say that's the expected behavior. Are you uploading a file or are you replacing a file using the "Replace" action?

**Comment by cap-akimrey** [comment] 2020-06-26 16:09
@andris-sevcenko I guess I'm confused. As I read the notes in this issue and in 4c6d22f, my understanding is that the idea was to change this behavior, restoring the option to replace the file?

I'm uploading a file to replace one that's not indexed. No "Replace" option is given. If that's the expected behavior, I'm in a corner. I know I could just sftp into the bucket and delete the existing file, but with S3's 999 file listing limit, there are a number of files that aren't ever visible via sftp. We have a lot of assets.

**Comment by andris-sevcenko** [comment] 2020-06-26 17:01
@cap-akimrey well maybe I'm confused - I do that a lot...

Are you just uploading the file or are you trying to replace a file for an existing asset?

**Comment by cap-akimrey** [comment] 2020-06-26 17:44
@andris-sevcenko I'm trying to upload a file which is not in the index, but is, apparently, on the server already.

**Comment by andris-sevcenko** [comment] 2020-06-26 17:55
Ah. Next 3.4 release should fix things for you, then. It’s due next Tuesday!

**Comment by cap-akimrey** [comment] 2020-06-26 18:37
Thank you!

**Comment by andris-sevcenko** [comment] 2020-07-02 05:37
@cap-akimrey 3.4.26 just dropped yesterday - give it a shot now!
