### ISSUE TITLE
Collapse/expand all for matrix blocks

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#7355] opened 2021-01-06 10:29 UTC
### Description
It would be nice to have the ability to collapse/expand all blocks within a matrix field at the click of a button.

Currently, the only way is to click the checkbox for the first block, scroll to the end of the field, `Shift + click` the last block, then click the cog icon and click Collapse/Expand.

I would suggest a button to the right of the field name and instructions:

![screenshot](https://user-images.githubusercontent.com/6672331/103758330-f4fbc300-5009-11eb-9a0f-4a3f35868a70.png)

**Comment by brandonkelly** [comment] 2021-01-11 19:07
This is a duplicate of #1880.

**Closed by brandonkelly** 2021-01-11 19:07 UTC
Labels: enhancement
