### ISSUE TITLE
Feature Request: Fields Based on User Groups

### ISSUE THREAD

**Issue by theskyfloor** [craftcms/cms#1651] opened 2017-04-21 02:47 UTC
### Description

I think it would be a great addition if Craft allowed extra fields to be assigned to users via the user groups concept. Would be great for profile data that relates to specific groups but would also allow for a flexibility for use cases I am sure none of us can think of yet. The concept would be that you can assign profile fields that come with a user group... when someone is added to that group those fields automatically are assigned to their profile.

**Comment by samstevens** [comment] 2017-07-17 04:33
Allowing required fields on a per user group basis would also be a great feature.

**Comment by brandonkelly** [comment] 2017-07-17 21:01
Duplicate of #947

**Closed by brandonkelly** 2017-07-17 21:01 UTC
Labels: feature
