### ISSUE TITLE
Multi-select fields do not allow adding or removing options.

### ISSUE THREAD

**Issue by kr37** [craftcms/cms#2659] opened 2018-03-29 06:25 UTC
### Description
This seemed to work (I think) on RC16.1, but not on RC17.

In the CP, when creating a multi-select field, I cannot add more options, nor can I delete the one option which appears by default. This behavior seems to be browser independent, and it happens on both local testing and on our main shared-hosting site.
EDIT: Is this similar to issue #2654 ?

### Steps to reproduce

1. Create a field of type multi-select
2. Attempt to add or remove rows to the table of options

### Additional info

- Craft version: 3.0.0-RC17 (Personal)
- PHP version: 7.1.15
- Database driver & version: MySQL 5.5.5
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.8.9-9)
- Plugins & versions: 
    - Amazon S3 1.0.8
    - Calendar Links 1.0.0
    - Environment Label 3.1.3
    - Importable 1.0.1
    - Redactor 1.0.1
    - Wordsmith 3.0.2

**Comment by nordentwickler** [comment] 2018-03-29 09:52
Same here: Craft version: 3.0.0-RC17 

Seems to be a js-problem - made a screenshot of the console. Adding an option ist not working. 

[Screenshot of matrix-field with not working select-field]( https://www.evernote.com/l/AAd_HjbdB2VPp7YnwhuFc3Fe1qdXNaMDoXY)

**Comment by juresrpcic** [comment] 2018-03-29 10:57
This has been fixed in this commit: https://github.com/craftcms/cms/commit/e642e504bf5778d7af4d393a323c61eb279ab821
Same issue as here: https://github.com/craftcms/cms/issues/2654

It's not released yet, so if you need it to work right now, replace this line in `composer.json`:
```    "craftcms/cms": "^3.0.0-RC1",```
to use the dev branch (temporarily, until this is released in RC17.1 probably):
```    "craftcms/cms": "dev-develop as 3.0.0-RC99",```

And run composer update afterwards.

**Comment by brandonkelly** [comment] 2018-03-29 12:55
Yep this is a duplicate of #2654. We’ll get a RC17.1 release out later today.

**Closed by brandonkelly** 2018-03-29 12:55 UTC

**Comment by brandonkelly** [comment] 2018-03-29 23:11
We just released Craft 3 RC17.1 with a fix for this.

**Comment by kr37** [comment] 2018-03-30 00:18
Thank you, Brandon!

**Comment by kr37** [comment] 2018-03-30 07:00
Hi again,

It doesn't seem to be fixed. I'm running Craft 3 RC17.1, and cannot add or
remove rows in either a multi-select field or also in a matrix field radio
button.

**Comment by brandonkelly** [comment] 2018-03-30 11:31
Hm, just re-tested and those are working on my end. Can you try clearing your cache, and deleting the contents of your web/cpresources/ folder?

**Comment by kr37** [comment] 2018-03-30 20:49
Thank you, Brandon, clearing cpresources did the trick!
