### ISSUE TITLE
[3.5-RC1.1] GraphQL public schema returns a 400 Missing Authorization header error

### ISSUE THREAD

**Issue by pixleight** [craftcms/cms#6444] opened 2020-07-23 16:05 UTC
### Description
When sending a simple `{ ping }` request to the public graphql schema, it returns a 400 Missing Authorization header error. If I understand correctly, this should be publicly available with no authorization header necessary.

Testing the same configuration on `3.4.29.1` returns 200 OK with the following:

```json
{
  "data": {
    "ping": "pong"
  }
}
```

### Steps to reproduce

1. Download Craft according to instructions at https://docs.craftcms.com/v3/installation.html#step-1-download-craft
2. Update `craftcms/cms` composer dependency to `^3.5.0-RC1`
3. Install Craft according to instructions at https://docs.craftcms.com/v3/installation.html
4. Enable GraphQL in `/config/general.php`: `'enableGql' => true`
5. Add route in `/config/routes.php` to GraphQL endpoint: `'api' => 'graphql/api'`
6. Post a graphql request to domain.tld/api: `{ ping }`

### Additional info

- Craft version: Craft Pro 3.5.0-RC1.1
- PHP version: 7.2.21
- Database driver & version: MySQL 5.7.26
- Plugins & versions: None

**Comment by andris-sevcenko** [comment] 2020-07-27 09:02
If you never go to your GraphQL Schema settings and edit the Public Schema, it is not enabled. It's not on by default.

Please update this issue if I'm misunderstanding something.

**Comment by pixleight** [comment] 2020-07-27 14:52
@andris-sevcenko it appears that public schema is enabled by default (at least it is when I navigate to its settings in CP), however I think I found the bug:

If I install & setup Craft, enable graphql in `config/general.php`, and enable Craft Pro in the CP, then requests to the public schema return 400 errors.

**But,** if I do the above and then navigate to GraphQL in the CP, (not even opening the Public Schema settings), requests return 200 OK.

I also noticed that project config files related to GraphQL (like `config/project/graphql/graphql.yaml`) are not added until you navigate to `/admin/graphql` for the first time.

**Comment by brandonkelly** [comment] 2020-07-27 15:22
Yeah, this was definitely a bug. Thanks for looking into it @pixleight! Just fixed for the next release.

**Comment by brandonkelly** [comment] 2020-07-28 14:20
Craft 3.5 RC4 is out now with the fix.

**Comment by ruralaccent** [comment] 2022-02-04 12:46
We've just had a similar issue on a dev site moved to a live environment, both running Craft Pro 3.7.30.1. 

The endpoint worked fine on the dev site - we had first tried a few api calls using the public schema to test a concept - but on the live site, as we didn't need a public schema and had everything set up, we set up a token/private schema and nothing worked, we just got 400 missing auth errors. 

I came across this thread, thought it sounded familiar, so I set up a public schema on the live site, then disabled it again, and hey presto, the token/private schema began working. 

So, it seems that even if you only want to use a private schema with a token, you still have to enable a public schema so that Craft will set up the dependencies. You can then disable the public schema again, if you don't want/need it. But it's not immediately obvious in Craft's CP instructions or documentation that this is the case (unless I've managed to overlook something).

**Comment by andris-sevcenko** [comment] 2022-02-08 11:56
"we just got 400 missing auth errors."

If the error is "Missing Authorization header" this means that Craft wasn't even able to look for a schema, because no token was provided at all.

Can you get the exact wording of the error, please?

**Comment by andris-sevcenko** [comment] 2022-02-08 12:00
To clarify, this is the logic flow:

1) If `x-craft-gql-schema` header is present and this is a CP request, get the schema or throw "Invalid X-Craft-Gql-Schema header".
2) Otherwise, if at least one `authorization` header is present and matches `/^Bearer\s+(.+)$/i` try to get a matching token. If no token or the token is disabled, throw "Invalid Authorization header"
3) If step (2) did not produce a token because no `authorization` headers were available or none of them matched the Bearer token syntax, try to use the public token. If it's disabled, throw "Missing Authorization header".

If (3) is the error you got, that would indicate a problem with step (2), such as authorization headers being stripped from the request, perhaps.

**Comment by ruralaccent** [comment] 2022-02-09 00:28
> "we just got 400 missing auth errors."
> 
> If the error is "Missing Authorization header" this means that Craft wasn't even able to look for a schema, because no token was provided at all.
> 
> Can you get the exact wording of the error, please?

I'm afraid I no longer have a copy, as we resolved it and moved on (it was part of a much larger project). There was a two-part issue in the end: one related to apache stripping auth headers, which we resolved with the assistance of the Craft documentation, and I think that is what my error reference above would have related to. Prior to that, we experienced the issue I mentioned in more detail, with Graphql dependencies not being set up unless/until we had activated the public schema at least once.

**Comment by ruralaccent** [comment] 2022-02-09 00:31
Having typed all that, the penny has just dropped! The auth header issue was the issue, and because we hadn't set up the public schema, we were getting the other error because there was no public schema to fall back to. I must have been snow blind! My apologies. So, no, not a bug.

**Comment by andris-sevcenko** [comment] 2022-02-09 07:38
@ruralaccent ah, glad to have it sorted, so all good :)

**Closed by andris-sevcenko** 2022-02-09 07:38 UTC
Labels: docs :notebook_with_decorative_cover:

**Comment by ruralaccent** [comment] 2022-02-09 10:40
Sometimes you're so deep in it, you don't see the wood for the trees! Thanks for your help :)
