### ISSUE TITLE
Layout doesn't resize properly when changing browser zoom-level

### ISSUE THREAD

**Issue by shuckster** [craftcms/cms#2266] opened 2018-01-04 02:30 UTC
### Description

From the Craft CP, changing the browser zoom-level does not work correctly, keeping the same height/width when zooming out instead of filling the space.

It seems to affect only Safari Version 11.0.2. Firefox and Chrome (up-to-date at time of post) behave as expected, as does the current Safari Developer Preview.

### Steps to reproduce

1. Login to Craft CP
2. Press CMD + - to zoom-out

### Additional info

- Craft version: 3.0.0-RC4
- PHP version: 7.2.0
- Database driver & version: MySQL 5.5.28
- Plugins & versions: None

**Comment by brandonkelly** [comment] 2018-01-06 15:01
Able to reproduce – looks like Safari isn’t correctly calculating viewport unites (e.g. `100vw`) when zoomed. Considering it’s already been fixed in the Safari Developer Preview, I’d rather just wait for the fix to hit the main distribution of Safari rather than hack around it.

**Closed by brandonkelly** 2018-01-06 15:01 UTC
Labels: bug, severity:minor, wontfix
