### ISSUE TITLE
Rich Text Asset checkboxes within a Matrix field not saving

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#1866] opened 2017-07-25 08:10 UTC
### Description

"Available Asset Sources" & "Available Image Transforms" fields within a Matrix aren't saving.

### Steps to reproduce

1. Create a new Matrix field
2. Add a Rich Text field type
3. Uncheck the "Available Asset Sources" & "Available Image Transforms" fields
4. Save the Matrix field
5. Open up the Matrix field again
6. "Available Asset Sources" & "Available Image Transforms" fields are still checked, the changes haven't saved.

### Additional info

- Craft version: 2.6.2987
- PHP version: 7.0.18

**Comment by takobell** [comment] 2017-07-25 17:23
Dupe of https://github.com/craftcms/cms/issues/21 which was fixed via https://github.com/craftcms/cms/commit/c264aea22a8bce8621707d9c933b4238b814321f in the Craft 3 branch.

**Closed by takobell** 2017-07-25 17:23 UTC
Labels: duplicate

**Comment by lukeyouell** [comment] 2017-07-25 17:34
@takobell just to clarify there's no plan to fix this bug in Craft 2?

**Comment by brandonkelly** [comment] 2017-07-25 18:34
@lukeyouell It was a breaking change for plugins, so no, we aren’t going to backport the fix for Craft 2.

**Comment by lukeyouell** [comment] 2017-07-25 23:30
Ah I see. Cheers!

**Comment by lukeyouell** [comment] 2017-07-25 23:31
@brandonkelly Ah I see. Cheers!
