### ISSUE TITLE
Project config un-generating files after a new save

### ISSUE THREAD

**Issue by davist11** [craftcms/cms#7795] opened 2021-04-13 21:50 UTC
### Description
This one is going to be pretty tricky to track down because it happens inconsistently, but figured I would at least submit an issue in case anyone else was having an issue or it turned out easy to figure out the problem...

I'm creating a number of Commerce product types in a row (although I've seen this happen with sections/entry types too), and every time I save the product type, I do a `git status` to make sure the file is generated.

```
config/project/commerce/productTypes/handlesFolInt--2fb93dee-1759-4644-bc0a-d7b6c26540e2.yaml
config/project/commerce/productTypes/handlesFolMou--241f41dc-e174-485b-a778-69172b8de31d.yaml
config/project/commerce/productTypes/handlesSid--f7b9ac12-a81c-44d7-a3ce-4b77fe660981.yaml
config/project/commerce/productTypes/nuts--a9ac978d-af26-4606-a546-644989e4d34a.yaml
config/project/commerce/productTypes/nutsBli--a979ca16-dffb-4f9c-af44-4d496b2ee5cb.yaml
config/project/commerce/productTypes/nutsHexMacScr--a9a5d90d-7087-4e62-9e32-025008c256ec.yaml
config/project/commerce/productTypes/nutsHexPot--bdb53db2-6c21-4f51-8a22-a07236be8032.yaml
config/project/commerce/productTypes/nutsSlo--bba963d9-21f1-4108-ae8c-7b0397d6dd54.yaml
config/project/commerce/productTypes/nutsThu--49b8ee65-97fb-4091-8ca9-e7074abf74b2.yaml
config/project/commerce/productTypes/nutsThuCol--5b4107d8-6bb5-4127-a3ca-9ee3b500e208.yaml
config/project/commerce/productTypes/nutsWin--71a231b8-0bd9-4dac-aa56-40aa9a531756.yaml
```

Then I created another new product type for `studsCon`, and did a `git status`

```
config/project/commerce/productTypes/handlesFolInt--2fb93dee-1759-4644-bc0a-d7b6c26540e2.yaml
config/project/commerce/productTypes/handlesFolMou--241f41dc-e174-485b-a778-69172b8de31d.yaml
config/project/commerce/productTypes/handlesSid--f7b9ac12-a81c-44d7-a3ce-4b77fe660981.yaml
config/project/commerce/productTypes/nuts--a9ac978d-af26-4606-a546-644989e4d34a.yaml
config/project/commerce/productTypes/nutsBli--a979ca16-dffb-4f9c-af44-4d496b2ee5cb.yaml
config/project/commerce/productTypes/nutsHexMacScr--a9a5d90d-7087-4e62-9e32-025008c256ec.yaml
config/project/commerce/productTypes/nutsHexPot--bdb53db2-6c21-4f51-8a22-a07236be8032.yaml
config/project/commerce/productTypes/nutsSlo--bba963d9-21f1-4108-ae8c-7b0397d6dd54.yaml
config/project/commerce/productTypes/nutsThu--49b8ee65-97fb-4091-8ca9-e7074abf74b2.yaml
config/project/commerce/productTypes/nutsThuCol--5b4107d8-6bb5-4127-a3ca-9ee3b500e208.yaml
config/project/commerce/productTypes/studsCon--dff19933-c813-4e0f-9350-7fa7ab76d9bf.yaml
```

Notice that `studsCon--dff19933-c813-4e0f-9350-7fa7ab76d9bf.yaml` is now there, which is the new product type I created, but `nutsWin--71a231b8-0bd9-4dac-aa56-40aa9a531756.yaml` is gone!

Going back and re-saving the `nutsWin` product type doesn't generate the file either. I have been adding a character to the name, saving it, and then the file gets generated. Then I go back and delete that character and re-save and all is good. It seems like it's always the last file (alphabetically) that gets removed.

This process just makes it super time consuming to be consistently concerned about files being removed from project config.

I also checked the `projectconfig` table and can see the data for the `nutsWin` product type exists.

### Steps to reproduce

1. Keep creating new sections/entry types/product types in a row until you notice a file being removed?
2. Sorry, hard to give specific steps since I can't identify any pattern
3. Let me know if sending my DB or project config or what could be helpful

### Additional info

- Craft version: Craft Pro 3.6.11.1
- PHP version: 7.4.15
- Database driver & version: MySQL 5.7.29
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Amazon S3</th>
                        <td>1.2.11</td>
                    </tr>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>6.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Classnames</th>
                        <td>1.0.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Command Palette</th>
                        <td>3.1.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Craft Commerce</th>
                        <td>3.2.15.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Feed Me</th>
                        <td>4.3.5.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Imgix</th>
                        <td>2.1.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Linkit</th>
                        <td>1.1.12.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Navigation</th>
                        <td>1.4.14</td>
                    </tr>
                                    <tr>
                        <th class="light">Ray</th>
                        <td>1.1.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.8.5</td>
                    </tr>
                                    <tr>
                        <th class="light">Retour</th>
                        <td>3.1.49</td>
                    </tr>
                                    <tr>
                        <th class="light">Scout</th>
                        <td>2.3.1</td>
                    </tr>
                                    <tr>
                        <th class="light">SEOmatic</th>
                        <td>3.3.35</td>
                    </tr>
                                    <tr>
                        <th class="light">Super Table</th>
                        <td>2.6.7</td>
                    </tr>
                                    <tr>
                        <th class="light">Table Maker</th>
                        <td>2.0.1</td>
                    </tr>
                            </tbody>
        </table>

**Comment by ul8** [comment] 2021-04-23 14:31
+1 one we're also seeing similar odd behaviors since we updated to 3.6.11.2 (from 3.4)

I didn't yet have time to do a systematic analysis but what seems to be happening is:
- project config files being removed that were previously there
-  saving entry types or fields not resulting in any project config file changes, but resaving them with a minor change will sometimes work (I keep doing that until it works)
- deleting fields not resulting in the corresponding project config file being deleted as it should be

PHP version | 7.4.14
Linux 4.19.121-linuxkit
PostgreSQL 11.6
Imagick 3.4.3 (ImageMagick 6.9.10-23)
Craft Pro 3.6.11.2

AsyncQueue	2.2.0
Bulk Edit	2.0.5
CP Field Inspect	1.2.4
Easy Search	1.0.1
Element API	2.6.0
Environment Label	3.2.0
Feed Me	4.3.6
Incognito Field	1.2.0
Inventory	2.1.1
Jason	2.0.1
Minify	1.2.10
Redactor	2.8.5
Sentry Logger	1.1.4
Smith	1.1.13
Super Table	2.6.7
Twigpack	1.2.10
Typed link field	1.0.25

**Comment by brandonkelly** [comment] 2021-04-23 22:18
I’m not able to reproduce this, but I suspect it is cache related. Are you seeing this on a load-balanced environment or something? What happens if you clear your data caches before each change?

**Comment by ul8** [comment] 2021-04-26 10:52
@brandonkelly No load-balancing etc. in use here (this is in local dev / docker). This exact setup has been in use without such problems for over a year though. It only started with the update to 3.6. 

I'll try your suggestion for a while and will report back.

**Comment by davist11** [comment] 2021-04-26 14:04
Mine is also a local docker setup. I'll likely have to add some new changes this afternoon that will trigger project config changes and will report back testing clearing the data cache.

**Comment by davist11** [comment] 2021-04-28 13:35
I got into this situation again and captured it by recording my screen.

I should have tried to clear the cache and re-save the entry type that removed the `relatedProductCategories` field from being written out to project config, but instead re-saved the field. Next time I get into the situation I'll remember to do that, but figured this could still be helpful.

https://user-images.githubusercontent.com/199985/116412323-90f14a80-a804-11eb-829a-c5c514dffc48.mp4

**Comment by joshuapease** [comment] 2021-04-29 22:32
I'm working with @davist11 on the same project and ran into this issue. I was modifying the `uriFormat` for a few singles. Any time I would modify a new single, the project config file for the previous single would go back to its original state.

He recommended the possible fix of clearing my data cache. 

Re-saving one of the previously edited singles didn't bring back the missing project config changes. But making a change to a *new* single brought back all of the changes.

I also did the following in my project right before hitting this issue:
- `composer install` - We had updated Craft Commerce yesterday
- `craft migrate/all` - I had some outstanding migrations
- `craft project-config/apply --force` - I occasionally do this before making project config changes to make sure my DB doesn't have any field or section changes hanging out from another branch.

**Comment by brandonkelly** [comment] 2021-04-29 23:05
> Re-saving one of the previously edited singles didn't bring back the missing project config changes. But making a change to a _new_ single brought back all of the changes.

Did you actually make any changes to the previously-edited single? Or just open its Edit page and click Save?

**Comment by joshuapease** [comment] 2021-04-29 23:12
> Did you actually make any changes to the previously-edited single? Or just open its Edit page and click Save?

@brandonkelly Just opened and clicked save. So no edits.

**Comment by brandonkelly** [comment] 2021-04-29 23:18
That wouldn’t have actually resulted in a project config change then.

When exactly did you clear your cache?

**Comment by joshuapease** [comment] 2021-04-29 23:27
@brandonkelly After editing 2 or 3 sections and noticing that each change wiped out the previous change. Then I cleared the data cache and made a change to new section. That change resulted in all my previous section changes being reflected in the project config files. 

It seems like clearing the data cache got things working as expected.

**Comment by joshuapease** [comment] 2021-04-30 21:52
Just a single DB for this project (both locally and in production).

**Comment by andris-sevcenko** [comment] 2021-05-05 07:01
@joshuapease @davist11 the next time it happens, before fixing it, can you check/confirm that the changes that are missing from the project config files are present in the `projectconfig` table?

**Comment by davist11** [comment] 2021-05-05 12:50
@andris-sevcenko yep, we can confirm next time. Although, I _think_ I did confirm that in my video here: https://github.com/craftcms/cms/issues/7795#issuecomment-828460160

**Comment by andris-sevcenko** [comment] 2021-05-05 12:54
@davist11 ah, you're right.

Can you get in touch over support@craftcms.com and reference this issue? I'll see if I can cook up some debugging code to further help us figure this out.

**Comment by davist11** [comment] 2021-05-05 13:01
@andris-sevcenko email sent, thanks!

**Comment by angrybrad** [comment] 2021-05-27 14:30
@davist11 @joshuapease @ul8 This one is tricky... if anyone is experiencing this on a public box with a test/staging site we could get access to, that'd probably be the best way for us to debug.

Short of that, we can try to reproduce locally with 1) your Dockerfile 2) a database dump 3) composer.json/lock files 4) your config/app.php, config/project folder, and config/general.php 4) any custom plugins/modules you're using.

In either case, if you could send that info over to support@craftcms.com, that'd be great.

**Comment by davist11** [comment] 2021-05-27 14:43
Thanks @angrybrad. I've got a request (13877) in and I've gone back and forth with @andris-sevcenko. Based on his most recent investigation, it _seems_ like it could be something in our docker config that could be affecting this. I sent my `docker-compose.yaml` file and will continue to work with Andris and send whatever is helpful to figure this out.

**Comment by davist11** [comment] 2021-06-08 13:50
We think it might be something with `:cached` or `:delegated` from our PHP volume mounts:

```yaml
volumes:
  - cpresources:/var/www/html/web/cpresources
  - storage:/var/www/html/storage
  - .:/var/www/html:cached
  - ./vendor:/var/www/html/vendor:delegated
  - ./storage/logs:/var/www/html/storage/logs:delegated
```

Haven't had a chance to test yet, but hopefully have a bunch of project config changes to make this week so I can test.

**Comment by khalwat** [comment] 2021-06-30 20:25
I believe I've run into this bug as well. Here's what is in the `config/project/project.yaml`:
```
  seomatic:
    enabled: '1'
    licenseKey: M65XDRPJO2CO7957WNGDFRSK
    schemaVersion: 3.0.9
```

Meanwhile, in the actual install plugin code, the schema version is:

```php
    /**
     * @var string
     */
    public $schemaVersion = '3.0.10';
```

...but in the Project Config table in the db, we have the correct value:

```
"path","value"
"plugins.seomatic.schemaVersion","""3.0.10"""
```

Here's what I think is going on...

* Craft starts up, reads in the Project Config cache using the key from the `info` table
* Composer Install is run, and my scripts clear all caches: https://github.com/nystudio107/craft/blob/craft-webpack/cms/composer.json#L39
* Project Config says "huh, no changes have been made to PC" and so the cached data that it has memoized is then written back into the cache

What we did is we listened to Redis via `redis-cli monitor` and got the following output, where you can see entire db being flushed (all caches cleared), but then it sets the Project Config cache with the schemaVersion is 3.0.9 from the cache:

```
;s:13:\"schemaVersion\";s:5:\"3.0.9\";}s:8:\"seomatic\";a:4:{s:7:\"enabled\";s:1:\"1\";s:10:\"licenseKey\";s:24:\"M65X
```

So I haven't looked at the code, but it _feels like_ a caching issue with Project Config where it can get into a state where the memoized version of the Project Config is written back out to the cache despite the caches being cleared in the interim.
[pc-redis-dump.txt](https://github.com/craftcms/cms/files/6743824/pc-redis-dump.txt)

**Comment by khalwat** [comment] 2021-07-01 02:47
If I pull the production db down, then do `php craft project-config/rebuild` this sorts everything out... I think what I mentioned before about the memoized version of Project Config being written out to the cache may not be right, but I do have a local environment where this can all be reproduced if it helps you sort out what is going on here.

**Comment by AugustMiller** [comment] 2022-02-12 21:31
I finally took a moment this afternoon to record myself making changes and speculate along the way about what was going on… hopefully this helps validate the reports of inconsistently-applied changes!

Not sure what else to add… using Nitro 2, PHP 8.0.14, MySQL 5.7.

https://www.dropbox.com/s/5ui15hkrxzzexk3/20220212%20Craft%20Project%20Config.mov?dl=0

**Comment by andris-sevcenko** [comment] 2022-02-14 08:48
@AugustMiller thanks for the extensive investigation.

This has been an issue we've seen but have not been able to reproduce locally and we haven't had access to an environment where we could reproduce that.

From our investigation, the problem seems to be a stuck cache. Here's what we've deduced happens:

There are multiple copies of project config instantiated at the same time for comparison and other reasons. 

1) Whenever a project config value is requested for the first time, the entire project config gets loaded from the cache (we'll re-visit this part later). I'll refer to this as intermediate layer.

2) When you make some changes, they get accumulated over request as a changeset, that contains the values that are changing + a message (you can see a rolling log of these in your `storage/config-deltas` folder). At the same time, the changes get applied to the intermediate layer.

3) At the end of each request, provided that (2) happened, the changesets accumulated in (2) get processed, the obsolete entries get deleted from the  project config DB table, and the new ones get added. At the beginning of this, the project config version also gets updated to a random string (also important).

4) If (3) happened, project config files get written out based on what's in the intermediate layer.

So, to sum up, Craft keeps track of what's changing over a course of request and, once the request ends, writes the changes both to DB and project config files.

Now, what causes this issue (or, rather, what causes the visible part of the issue) is that step (1) uses the project config version number for busting the cache. This is stored in `info.configVersion`. And, it seems, in these cases either the config version does not get updated or it gets cached somewhere in queries or something. But, what ends up happening is that the cache from step 1 does not get busted. Which means that Craft keeps using the _previous_ iteration of Project Config as the intermediate layer. Which, in turn, means that _most_ of the operations yield the expected result, however, when exporting the project config to yaml files, the previous changes end up missing from the files, since the intermediate layer cache did not bust.

I would be extremely interested and grateful to get access to an environment where I'm able to reproduce this and have SSH access, too so I can figure out which part ends up breaking and why. If you think you can make a tunnel or something for us to get access to your environment where this happens, I'd love to hear all about it via support@craftcms.com :)

**Comment by FrankZwiers** [comment] 2022-02-21 10:05
We are also periodically experiencing problems with differences in the project config that are seemingly not applied correctly. Only after clearing the cache the changes are visible. We mostly notice it when saving plugin settings(from different plugins). We're currently testing whether the problem will be fixed(for us) when we don't generate the files on disk(using [this](https://craftcms.com/docs/3.x/project-config.html#manual-yaml-file-generation)). There doesn't seem to be a way to consistently reproduce the issue but what i've noticed is that it seems to happen more often on live environments, so perhaps requests being handled while you're making changes is part of the problem.

**Comment by FrankZwiers** [comment] 2022-02-22 10:18
I've managed to consistently reproduce the issue, it is visible here: https://www.dropbox.com/s/fs3zzu1l4z6jtsx/config%20problem2.mov?dl=0
I've also tried to run this plugin in a bare Craft project here the problem is not reproducible. I'll try if I can set up an environment on our server where this is also reproducible.

**Comment by brandonkelly** [comment] 2022-02-24 22:59
Think we’ve gotten to the bottom of this, and I’ve just pushed up a couple changes that should fix it (#10647).

If anyone wants to help test, you can update your `craftcms/cms` requirement in composer.json to `"dev-feature/project-config-locking as 3.7.34", then run `composer update`.

**Closed** 2022-02-25 22:48 UTC
Labels: bug

**Comment by FrankZwiers** [comment] 2022-03-01 06:48
I tested the fix and the issue doesn't happen anymore. I also managed to bump into the StaleResourceException when trying to save the settings of 2 plugins at once, so that works as expected as well.

**Comment by andris-sevcenko** [comment] 2022-03-01 07:05
Have to say, @FrankZwiers, when I saw you respond, I had a mini heart attack.

Glad it's all working for you!
