### ISSUE TITLE
Live Preview header cuts off content on Chrome and not on Firefox

### ISSUE THREAD

**Issue by thiagorossener** [craftcms/cms#6340] opened 2020-07-07 20:35 UTC
### Description

When editing an entry and clicking on "Preview", I've got different behaviors from Chrome and Firefox.

Chrome cuts off the template:

![image](https://user-images.githubusercontent.com/1750826/86838195-408edd80-c076-11ea-8c87-1dda32ae04ca.png)

Firefox doesn't:

![image](https://user-images.githubusercontent.com/1750826/86837858-e5f58180-c075-11ea-99b7-dc12d3f47abc.png)

The issue is in this piece of code:

```
.lp-editor-container,
.lp-preview-container {
  ...
  header {
    ...
    @supports (backdrop-filter: blur(10px)) {
      & {
        position: absolute;
        z-index: 2;
        top: 0;
        left: 0;
        width: 100%;
        background-color: transparentize($grey100, 0.25);
        backdrop-filter: blur(10px);

        & + .lp-editor {
          padding-top: #{10 + 34 + 10 + 24}px;
        }
      }
    }
   ...
  }
}
```

As [Firefox doesn't support the backdrop-filter property](https://caniuse.com/#search=backdrop-filter), it ends up positioning the header differently.

I tried to fork the repo and submit a PR, but couldn't find how this CSS is added to the project. Hopefully it's and easy fix.

### Steps to reproduce

1. Create an entry of a section with more than one preview target
2. Click on "Preview"

### Additional info

- Craft version: 3.4.25
- PHP version: 7.2.10
- Plugins & versions:
```
"aelvan/inlin": "^2.1",
"carlcs/craft-redactorcustomstyles": "3.0.3",
"craftcms/cms": "^3.4.0",
"craftcms/feed-me": "4.2.2",
"craftcms/mailgun": "1.4.2",
"craftcms/redactor": "^2.6.0",
"nystudio107/craft-fastcgicachebust": "1.0.9",
"nystudio107/craft-retour": "3.1.37",
"nystudio107/craft-seomatic": "^3.2.0",
"nystudio107/craft-typogrify": "^1.1.0",
"solspace/craft-express-forms": "1.0.5",
"spicyweb/craft-embedded-assets": "2.2.6",
"thejoshsmith/craft-prism-syntax-highlighting": "1.0.2",
"twig/cssinliner-extra": "^3.0",
"verbb/knock-knock": "^1.2.0",
"vlucas/phpdotenv": "^3.4.0",
"weareferal/asset-versioner": "^v1.0.8",
"weareferal/matrix-field-preview": "1.0.5",
"weareferal/remote-backup": "^1.1.0",
"weareferal/remote-sync": "^1.2.0"
```

**Comment by brandonkelly** [comment] 2020-07-15 23:22
This is a duplicate of #5547, which has been fixed for Craft 3.5.

**Closed by brandonkelly** 2020-07-15 23:22 UTC
Labels: bug
