### ISSUE TITLE
[4.x]: Images not using the filesystem baseUrl

### ISSUE THREAD

**Issue by thomascoppein** [craftcms/cms#12524] opened 2023-01-11 16:04 UTC
### Description
For development we use a preview server for the client to add content. So we use this preview server as Base Url for the assets on our local project. Both of this setups are using the same database.
When using the preview server as baseUrl for our public filesystem, the images are still loaded from the current site url.

### Steps to reproduce

1. Upload images on the preview server.
2. Assign image to entry.
3. Change Public filesystem Base URL to preview url.
4. Open project locally
5. Open page where image is visible

### Expected behavior
WIth previous Craft versions this method worked. The images where loaded from preview server

### Actual behavior
The images are loaded from local site url instead of the Filesystem Base Url.

### Craft CMS version

Craft Pro 4.3.6.1

### PHP version

8.2

### Operating system and version

macOS Monterey 12.6

### Database type and version

Mysql

### Installed plugins and versions

-

**Comment by brianjhanson** [comment] 2023-01-13 00:33
Thanks for reaching out! I'm having some trouble wrapping my head around this. Can you clarify a few things?

> Both of this setups are using the same database.

Do you mean both of these are literally connected to the same DB (via a remote connection of some kind)? 

> When using the preview server as baseUrl for our public filesystem

Are you setting the base URL directly via the CP or via an environment variable? I'm also curious, is the transform filesystem set to the same as the asset filesystem?

**Comment by thomascoppein** [comment] 2023-01-13 09:09
@brianjhanson Thank you for your quick response. To answer your questions:

> Do you mean both of these are literally connected to the same DB (via a remote connection of some kind)?

The database is hosted, allowing us to easily connect to it both locally and on the preview server. On the preview server, the 'allowAdminChanges' setting is set to 'false' to prevent any issues with 'project.yaml' conflicts.

> Are you setting the base URL directly via the CP or via an environment variable? I'm also curious, is the transform filesystem set to the same as the asset filesystem?

The 'baseURL' is set through an environment variable, and the 'transform filesystem' is set to 'Same as asset filesystem' while the 'asset filesystem' is set to 'Public'.

Hopefully this will clear some things up.

**Comment by brianjhanson** [comment] 2023-01-13 18:01
@thomascoppein I think I'm on to something, but I'm not totally sure it's responsible yet. What version of Craft were you using when this worked?

**Comment by thomascoppein** [comment] 2023-01-13 23:03
@brianjhanson hmm, I can't tell you a specific version where it worked... I just know it worked like this a while ago :/

**Comment by brianjhanson** [comment] 2023-01-16 19:40
All good! The TL;DR is that this method should still work, but only when you’re not using any transforms. 

A full explanation is below. It's probably more than you need, but it might be helpful for future travelers. 

Let’s make things more tangible and Let’s make things more concrete and call our sites `preview.website.com` and `local.website.com`. Both of these sites are connected to the same database via a remote connection but `preview.website.com` is where most of the action takes place. When an asset is uploaded to `preview.website.com` it is stored locally on the `preview.website.com` server and given a URL of something like `preview.website.com/uploads/filename.jpg`. 

When viewing things locally, your filesystem has the “Base URL” set to `preview.website.com/uploads`. If you use `asset.url`, this will work fine, but when you use `asset.getUrl(transform)`, things get a little more complicated. That will return a transform URL formulated based on the base URL of your site. In this case, it would be `local.website.com/actions/assets/generate-transform?transformId=X`. 

The `local.website.com` server will read that request and do its best to return the URL for the transformed image. A part of that process is [checking if the file exists on the server](https://github.com/craftcms/cms/blob/4c61c780fcb791f8e31852de937799d6c97442c9/src/imagetransforms/ImageTransformer.php#L92). In this case, it doesn’t (it only lives on the `preview.website.com` server). This causes the transform to fail and the URL of the tranform to be returned. 

That local file check was added in 3.5, so it's possible this worked before then. It’s also possible that a plugin like [Image Optimize](https://plugins.craftcms.com/image-optimize?craft4) would cause a different behavior because that plugin will generate the transforms on upload instead of on demand.

I will close this out, as this is currently the expected behavior. We only support instances where the base URL points to the same server as the file system path for local filesystems. I’m still here if you have any other questions, though.

**Closed by brianjhanson** 2023-01-16 19:40 UTC
Labels: bug, craft4
