### ISSUE TITLE
Changing a field from type "plain text" to "Date/Time" throws DB Exception

### ISSUE THREAD

**Issue by ul8** [craftcms/cms#5894] opened 2020-04-06 11:28 UTC
### Description

Changing a field from type "plain text" to "Date/Time" throws DB Exception.

```
Database Exception – yii\db\Exception
SQLSTATE[42804]: Datatype mismatch: 7 ERROR: column "field_admissionDate" cannot be cast automatically to type timestamp without time zone
HINT: You might need to specify "USING "field_admissionDate"::timestamp(0) without time zone".
The SQL being executed was: ALTER TABLE "craft_content" ALTER COLUMN "field_admissionDate" TYPE timestamp(0), ALTER COLUMN "field_admissionDate" DROP DEFAULT, ALTER COLUMN "field_admissionDate" DROP NOT NULL

Error Info: Array
(
    [0] => 42804
    [1] => 7
    [2] => ERROR:  column "field_admissionDate" cannot be cast automatically to type timestamp without time zone
HINT:  You might need to specify "USING "field_admissionDate"::timestamp(0) without time zone".
)
```
### Steps to reproduce

1. Create and save a new field of type plain text, all default options
2. Edit the field, change type to "Date/Time", save.

### Additional info

- Craft version:  3.4.13
- PHP version: 7.3.13
- Database driver & version: PostgreSQL 11.6
- Plugins & versions:

AsyncQueue 	2.1.1
CP Field Inspect 	1.1.3
Element API 	2.6.0
Feed Me 	4.2.2
Incognito Field 	1.1.1.1
Minify 	1.2.10
Redactor 	2.6.1
Smith 	1.1.1
Super Table 	2.4.7
Twigpack 	1.2.0
Typed link field 	1.0.21

**Comment by brandonkelly** [comment] 2020-04-06 22:25
This is happening because the field’s column contains values that aren’t compatible with a DATETIME column type. It’s one of the reasons Craft puts ⚠️ icons on some of the Field Type options for an existing field type – because you run the risk of getting this error, or losing data, when switching types.

To work around it, create a whole new Date/Time field rather than converting an existing Plain Text field.

**Comment by ul8** [comment] 2020-04-07 09:01
Thanks Brandon. Not to be nit-picky, but the warning message just says "Changing this may result in data loss.", which is immediately comprehensible to anyone that you can't expect data to remain there when you change the field. However IMHO no generally accessible action in a UI should ever predictably throw an exception. So maybe prevent saving the field completely if an invalid change is selected.

By the way I later noticed that in project config this changed for the field:
```
- columnType: text
+ columnType: null
```
...when I saved it and got the exception. Seems to work fine still, and I'll be deleting the field anyway, but thought you may want to know.

**Comment by ul8** [comment] 2020-04-07 09:04
I do agree with this being minor severity though, so no worries about that. Thanks!

**Comment by brandonkelly** [comment] 2020-09-18 18:10
Related: #5266

**Comment by brandonkelly** [comment] 2020-09-18 18:12
Actually this is a duplicate of #3605. Will close this one in favor of that.

**Closed by brandonkelly** 2020-09-18 18:12 UTC
Labels: bug, severity:minor
