### ISSUE TITLE
setPasswordPath doesn't follow custom routes setup within control panel settings

### ISSUE THREAD

**Issue by icreatestuff** [craftcms/cms#6334] opened 2020-07-07 12:34 UTC
### Description
In the `general.php` config file if I set `'setPasswordPath' => 'set-password'` and have a route set in `/admin/settings/routes` for set-password » account/set-password the default Craft set password template is shown instead of my custom frontend form at account/set-password.

If however I set the config variable to `'setPasswordPath' => 'account/set-password'` the email link successfully takes me to the /account/set-password URL.

As far as I can see this exhibits different behaviour to other similar config variables such as `postLoginRedirect`, `activateAccountSuccessPath`, `setPasswordSuccessPath` and `invalidUserTokenPath` that **do** seem to follow custom routes.

### Additional info

- Craft version: 3.4.27
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment] 2020-07-15 23:42
This looks like a duplicate of #5722, which has been addressed for Craft 3.5.

**Closed by brandonkelly** 2020-07-15 23:42 UTC
Labels: bug
