### ISSUE TITLE
[4.x]: Error running codeception Acceptance tests with module setting in config/app.php

### ISSUE THREAD

**Issue by yoannisj** [craftcms/cms#12090] opened 2022-10-11 18:50 UTC
### Description
Running Codeception acceptance tests with modules defined in `config/app.php` throws error `[TypeError] get_class(): Argument #1 ($object) must be of type object, string given`.

To make sure this is not an issue with my project's module configuration, I tried with a fresh Craft-CMS 4.2 install, and could reproduce the error.

### Steps to reproduce

1. Get a fresh Craft-CMS 4.2 installation
_I downloaded the zip file from the [Installation Instructions](https://craftcms.com/docs/4.x/installation.html#downloading-an-archive-file-manually) to get up and running inside a DDEV project._
2. Install Codeception ^4.1 with `composer require codeception/codeception:^4.1 --dev`
_Codeception ^3.1 is not compatible with PHP 8, and I did not manage to setup Craft-CMS tests with Codeception ^5.0._
3. Follow steps to [Setup Tests](https://craftcms.com/docs/4.x/testing/testing-craft/setup.html) for Craft-CMS from the documentation
_To run the example unit test  (steps 4-5), I had to run `composer require codeception/module-yii2:^1.1 --dev` first_
4. Add an example Acceptance test in `tests/acceptance/ExampleCest.php` like so:
```
<?php
namespace yournamespace\tests\acceptance;

class ExampleCest
{
    public function testExample( \AcceptanceTester $I )
    {
        // when
        $I->amOnPage('/admin/login');

        // then
        $I->seeInTitle('Login');
    }
}
```
5. Rename the `SECURITY_KEY` env variable in `tests/.env` to `CRAFT_SECURITY_KEY` and make sure it has a value
6. Remove the conflicting `PhpBrowser` module from `tests/acceptance.suite.yaml > modules > enabled`
7. run `php vendor/bin/codecept run acceptance`

### Expected behavior

The acceptance test should run and pass.

### Actual behavior
The `[TypeError] get_class(): Argument #1 ($object) must be of type object, string given` error is thrown.

The `[TypeError] get_class(): Argument #1 ($object) must be of type object, array given` error is thrown if I define the module as an array in `tests/_craft/config/app.php`:
```
   'modules' => [
       'my-module' => [ 'class' => \modules\Module::class ],
   ],
```

The test runs and passes if I comment out the `'modules'` setting altogether in `tests/_craft/config/app.php`.

### Craft CMS version

4.2.7

### PHP version

8.0.21

### Operating system and version

Linux 5.10.124-linuxkit (DDEV v1.20.0)

### Database type and version

MySQL 10.4.25 (MariaDB 10.4)

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- codeception/codeception 4.2.2
- codeception/module-yii2 1.1.5
- codeception/module-asserts 1.3.1
- codeception/module-phpbrowser 1.0.3

**Comment by brianjhanson** [comment] 2022-10-11 20:58
Thanks for reporting! I'm going to close this as a duplicate of #12088.  Craft 3 & 4 share a base, so this will make it through to 4 when it's merged into 3.

**Closed by brianjhanson** 2022-10-11 20:58 UTC
Labels: bug, craft4

**Comment by yoannisj** [comment] 2022-10-11 21:55
Ok, yes I was not sure if this should be a separate ticket or not, but in doubt... Thanks @brianjhanson!
