### ISSUE TITLE
Creating Global set with a Matrix field with minimum blocks throws a validation error.

### ISSUE THREAD

**Issue by adampatpattison** [craftcms/cms#2362] opened 2018-01-26 17:31 UTC
### Description

When creating a Global set with a Matrix field with minimum blocks it throws an validation error saying that the field should have minimum blocks. We're just creating the global set at this point though, not adding any content.

### Steps to reproduce

1. Create a field with type Matrix and set it's minimum blocks value. 
2. Create or edit a global set in the settings and assign the field as a value

### Additional info

- Craft version:  3.0.0-RC7.1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
Eager Beaver	1.0.1
Minify	1.2.6
Typogrify	1.1.6
Social	2.0.0-beta.5
Agnostic Fetch	2.0.0
Anchors	2.0.3
Calendar Links	1.0.0
Child Me!	1.0.0
Control Panel Nav	2.0.2
Cookies	1.1.8
CP Field Inspect	1.0.2
Default Tab	1.2.2
Dumper	1.1.2
Element API	2.5.2
Element Map	1.0.2
FastCGI Cache Bust	1.0.4
Geo Cookie	1.0.2
Hexdec	2.0.2
Google Cloud Storage	1.0.5
Incognito Field	1.0.0
Instant Analytics	1.0.4
Mailgun	1.2.0
MobileDetect	1.0.1
Query	2.0.2
Redactor	1.0.1
Rich Variables	1.0.15
schema	1.0.3
Simple Text	2.0.2
Snitch	2.0.0
Sprout Active	2.0.1
Template Select	2.0.0
Videos	2.0.0-beta.6
XML Sitemap	v1.0.7
Craft Redactor Script Buttons	1.1.1
Importable	1.0.1
Many to Many Field Type	1.0.2
Position Fieldtype	1.0.7
Advanced Url Field	1.0.0
Useful Twig Filters	1.0.0
Lat/Lng Field Type	1.0.0
Section Field	1.0.0
Command Palette	3.1.1
NSM Fields	0.0.7
Category Group Field	1.0.0
Logs	3.0.0
Hubspot API Integration	0.0.1
Stripe Checkout	1.0.2
Notifications	1.0.1
Expanded Singles	1.0.1
Entry Instructions	1.0.0
Colour Class Field Type	1.0.0
Icon Picker Field Type	1.0.0
Sprite Picker Field Type	1.0.0
AsyncQueue	1.1.5
Module Picker Field Type	1.0.0

**Comment by adampatpattison** [comment] 2018-01-26 17:34
I also realised it was this by adding a print_r of the validation errors to see the validation error:

File: \vendor\craftcms\cms\src\services\Globals.php
Line 256:
 `Craft::info('Global set not saved due to validation error: '.print_r($globalSet->errors, true), __METHOD__);`

**Comment by brandonkelly** [comment] 2018-01-26 21:58
This is a duplicate of #2350, and is already fixed in Craft 3.0.0-RC7.1.

**Closed by brandonkelly** 2018-01-26 21:58 UTC
