### ISSUE TITLE
Response code when failed to login

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#5129] opened 2019-10-20 22:51 UTC
I have recently tested logging in using ajax request. It works, but it returns a response with code `200` even if login failed. Shouldn't it use some other code instead in such situation? Like `401`.

**Comment by brandonkelly** [comment] 2019-10-21 12:50
Duplicate of #3890.

It probably should, yes, but fixing it would be a breaking change, so we will need to wait until Craft 4.

**Closed by brandonkelly** 2019-10-21 12:50 UTC

**Comment by nicbou** [comment] 2022-03-17 13:03
To add a bit of context, this makes it hard to block repeated failed login attempts with fail2ban, since they are indistinguishable from successful login attempts in the nginx logs.

This is not a high priority issue for me. I just wanted to add a data point.

**Comment by nicbou** [comment] 2022-03-17 15:24
That's quite fine. Looking forward to see what you have in store for us with Craft 4!
