### ISSUE TITLE
BaseElementIndex.js:688 Uncaught (in promise) TypeError: Cannot read property 'displayError' of undefined     at BaseElementIndex.js:688

### ISSUE THREAD

**Issue by cstudios-slovakia** [craftcms/cms#7641] opened 2021-03-03 15:32 UTC
### Description
When clicking on asset or entry select field under the new or existing entry,  the selection popup menu is shown, but the items can not be clicked, while a console error is shown in the chrome developer options:

```
Double-instantiating a menu button on an element
BaseElementIndex.js:688 Uncaught (in promise) TypeError: Cannot read property 'displayError' of undefined
    at BaseElementIndex.js:688
(anonymous) @ BaseElementIndex.js:688
Promise.catch (async)
updateElements @ BaseElementIndex.js:685
init @ BaseElementIndex.js:288
init @ CategoryIndex.js:14
e @ garnish.js? [sm]:79
constructor @ garnish.js? [sm]:768
s.constructor @ garnish.js? [sm]:40
s.constructor @ garnish.js? [sm]:40
s.constructor @ garnish.js? [sm]:40
createElementIndex @ Craft.js:1575
(anonymous) @ BaseElementSelectorModal.js:191
o @ jquery.js? [sm]:10771
u @ jquery.js? [sm]:3496
fireWith @ jquery.js? [sm]:3626
S @ jquery.js? [sm]:9786
(anonymous) @ jquery.js? [sm]:10047
load (async)
send @ jquery.js? [sm]:10066
ajax @ jquery.js? [sm]:9682
postActionRequest @ Craft.js:542
_createElementIndex @ BaseElementSelectorModal.js:182
onFadeIn @ BaseElementSelectorModal.js:57
e @ garnish.js? [sm]:79
(anonymous) @ garnish.js? [sm]:4242
s.complete @ velocity.js? [sm]:4745
C @ velocity.js? [sm]:4563
T @ velocity.js? [sm]:4461
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
requestAnimationFrame (async)
T @ velocity.js? [sm]:4468
m @ velocity.js? [sm]:4001
(anonymous) @ velocity.js? [sm]:4057
dequeue @ jquery.js? [sm]:4604
$ @ velocity.js? [sm]:4075
(anonymous) @ velocity.js? [sm]:4088
each @ jquery.js? [sm]:381
y @ velocity.js? [sm]:4085
d.each.g.Redirects.<computed> @ velocity.js? [sm]:4759
(anonymous) @ velocity.js? [sm]:2919
each @ jquery.js? [sm]:381
y @ velocity.js? [sm]:2897
show @ garnish.js? [sm]:4236
show @ BaseElementSelectorModal.js:147
e @ garnish.js? [sm]:79
init @ garnish.js? [sm]:4179
init @ BaseElementSelectorModal.js:33
e @ garnish.js? [sm]:79
constructor @ garnish.js? [sm]:768
s.constructor @ garnish.js? [sm]:40
s.constructor @ garnish.js? [sm]:40
s.constructor @ garnish.js? [sm]:40
createElementSelectorModal @ Craft.js:1593
createModal @ BaseElementSelectInput.js:299
showModal @ BaseElementSelectInput.js:292
(anonymous) @ garnish.js? [sm]:893
o @ jquery.js? [sm]:10771
dispatch @ jquery.js? [sm]:5429
v.handle @ jquery.js? [sm]:5233
trigger @ jquery.js? [sm]:8715
(anonymous) @ jquery.js? [sm]:8793
each @ jquery.js? [sm]:381
each @ jquery.js? [sm]:203
trigger @ jquery.js? [sm]:8792
click.garnish-activate @ garnish.js? [sm]:960
dispatch @ jquery.js? [sm]:5429
v.handle @ jquery.js? [sm]:5233
Show 37 more frames
AuthManager.js:49 Uncaught TypeError: Craft.getActionUrl is not a function
    at s.constructor.checkRemainingSessionTime (AuthManager.js:49)
    at o (jquery.js? [sm]:10771)
checkRemainingSessionTime @ AuthManager.js:49
o @ jquery.js? [sm]:10771
```

### Steps to reproduce

1. create new entry
2. select an asset field

### Additional info

Application Info
PHP version	7.4.15
OS version	Linux 4.15.0-122-generic
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.4.15
Craft edition & version	Craft Pro 3.6.7
Yii version	2.0.40
Twig version	v2.14.3
Guzzle version	6.5.5
Plugins
Admin Bar	3.1.11
Calendar	3.2.1
Craft Color Mixer	1.0.9
Craft Commerce	2.2.22
Expanded Singles	1.1.3
Inlin	2.1.1
Json Client	1.0.3
Mailchimp Subscribe	3.0.3
Maps	3.7.7
Matrix Toolbar	1.0.6
OpenWeather	1.0.2
QRCode	1.0.5
Redactor	2.8.5
Retour	3.1.33
Sentry	1.5.1
SEO	3.6.7
Site Switcher	2.2.0
Smith	1.1.12
Super Table	2.6.7
Table Maker	2.0.1
Turbo	1.4.1
Twig Perversion	2.2.0
Typogrify	1.1.18
Video Embedder	1.1.4
Wordsmith	3.3.0.1

**Comment by brandonkelly** [comment] 2021-03-03 17:53
Not able to reproduce this.

The line referenced in the error is:

https://github.com/craftcms/cms/blob/5ef456281de838d9180c6bfb2f1b8de74268b424/src/web/assets/cp/src/js/BaseElementIndex.js#L688

If `Craft.cp` is undefined, either there’s some other JS error occurring earlier that is preventing it from getting set in the first place, or a plugin/module is tampering with Craft’s JS.

You can disable all plugins via the [disabledPlugins](https://craftcms.com/docs/3.x/config/config-settings.html#disabledplugins) config setting:

```php
'disabledPlugins' => '*',
```

**Comment by hunwalk** [comment] 2021-03-04 13:26
Hi, we've found the problem.
https://github.com/monachilada/craft-matrixtoolbar
This plugin has been causing that js issue with the latest craft.

We will reference this issue in that repo.
Thx

**Comment by brandonkelly** [comment] 2021-03-04 13:43
Cool, will close this one now.

**Closed by brandonkelly** 2021-03-04 13:43 UTC
Labels: bug
