### ISSUE TITLE
Adding link to a list item sometimes ends up replacing the previous list item

### ISSUE THREAD

**Issue by sjcallender** [craftcms/cms#3351] opened 2018-10-05 18:01 UTC
### Description
This screen recording is the best way to explain this issue: https://cl.ly/4bd3af6a5c49

Adding a link to a list item ends up replacing the previous list item with what should be the current list item. Seems to only happen when the previous list item is a link and when the link I'm adding to the current list item is either an entry or category.

### Additional info

- Craft version: 3.0.26.1
- PHP version: 7.0.x and 7.2.x

**Comment by andris-sevcenko** [comment] 2018-10-05 18:12
Duplicate of craftcms/redactor#69

Sorry :(

**Closed by andris-sevcenko** 2018-10-05 18:12 UTC
