### ISSUE TITLE
Add postLogoutRedirect config setting

### ISSUE THREAD

**Issue by siebird** [craftcms/cms#1712] opened 2017-05-16 22:56 UTC
Add `postLogoutRedirect` config setting similar to [`postLoginRedirect`](https://craftcms.com/docs/config-settings#postLoginRedirect) which will allow us to set a URL or path that users should be redirected to after logging out from the front-end site.

**Comment by brandonkelly** [comment] 2017-05-18 22:38
Duplicate of #1003 (and already implemented in Craft 3).

**Closed by brandonkelly** 2017-05-18 22:38 UTC
Labels: feature
