### ISSUE TITLE
Image thumbnails within inactive tabs don't load when their tab is activated

### ISSUE THREAD

**Issue by weotch** [craftcms/cms#7890] opened 2021-05-06 05:39 UTC
### Description

Image thumbnails within inactive tabs don't load when their tab is activated, see example here.

![](https://p-9WF55W9.t1.n0.cdn.getcloudapp.com/items/RBuYRGmP/2acfdd6a-6fef-4450-bc50-50f7f8a30a30.gif?v=ffbf5aa5fb97949462683374563901f9)

The field type of the pictured "Listing Image" is a normal Craft Asset type.

### Steps to reproduce

1. Created a Section with multiple tabs including an asset field in the second tab.
2. Upload an image to the asset field on the second tab.
3. Switch back to the first tab and reload the page.
4. Switch to the second tab, the image thumbnail won't be loaded.

### Additional info

- Craft version: Craft Pro 3.6.13
- PHP version: 7.3.23
- Database driver & version: MySQL 8.0.21
- Plugins & versions:

![image](https://user-images.githubusercontent.com/77567/117247160-a5c87200-adf2-11eb-96b7-5267e50412e3.png)

**Comment by brandonkelly** [comment] 2021-05-09 22:26
I’m not able to reproduce that. Are you seeing any JavaScript errors on the page?

**Comment by weotch** [comment] 2021-07-13 17:05
This may be a duplicate of #6621 ... I'll check if 3.6.18 fixes then when we deploy it next month.

**Comment by brandonkelly** [comment] 2021-07-14 02:46
Ah yeah almost certainly. I’ll go ahead and close this.

**Closed** 2021-07-14 02:46 UTC
Labels: bug

**Comment by Samuel91** [comment] 2022-04-21 11:18
Still seeing this issue.
It fails regardless of whether there is a redactor field or not.

Craft version: Craft Pro 3.7.38
Redactor 2.10.6

**Comment by brandonkelly** [comment] 2022-04-21 23:34
@Samuel91 Yeah it recently cropped up again. Fixed for the next release. (#10918)
