### ISSUE TITLE
Collapsing Blocks - Feature Request

### ISSUE THREAD

**Issue by mediagirl** [craftcms/cms#1912] opened 2017-08-10 20:24 UTC
I'd like to request "Collapse All Blocks" be returned for Blocks. I recall this being an option previously but it's been removed. Currently an editor needs to collapse each block individually to close them all.

https://www.screencast.com/t/2HtkvaheJ 

Also, would be nice to have the option to show all blocks in a collapses state by default when the entry is loaded for editing.

**Comment by michaelrog** [comment] 2017-08-10 21:56
c.f. #1880, especially the [nifty trick](https://github.com/craftcms/cms/issues/1880#issuecomment-318780438) Brandon described there.

**Comment by mediagirl** [comment] 2017-08-10 22:56
Thank you Michael. The editor for this project is very non-tech so not the best option but I'll see if I can train her.

"Collapse All" and "Expand All" used to be options when viewing the option for each block. I'd love to see it added back. 

My goal is to not have the editor overwhelmed by the volume of blocks on projects where lots of them are used in an entry.

**Comment by brandonkelly** [comment] 2017-08-15 00:58
Closing as a duplicate of #1880 (which remains open).

**Closed by brandonkelly** 2017-08-15 00:58 UTC
