### ISSUE TITLE
[3.x]: Unable to turn website offline

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#11581] opened 2022-07-10 23:00 UTC
### Description

It has long been an issue that the Live-switch (online/offline) isn't working in the control panel.
An issue is open for a long time now, because at the time the setting was constantly overriden by the project yaml: https://github.com/craftcms/cms/issues/9855

But now it seems like even setting `live: false` in the yaml doesn't even trigger a yaml change in the CP when going to utilities. And to me it feels too unreliable/critical to force apply all yaml files there just for that one boolean. If even needed.

After trying for a very long time I give up now. It seems to be impossible to do such a simple thing; just turn a Craft website offline with a single switch :(

IMO this issue should get way more attention and priority. Please people, this really needs a solution by now!! It's getting ridiculous to me that a simple thing like remembering a single boolean state takes so long to make it work...

### Steps to reproduce

1. CP --> Settings --> General --> Turn the switch to 'Offline'
2. Click 'Save'
3. See that NOTHING happens

### Expected behavior

User switches to OFFLINE --> Website goes offline
User switches to ONLINE --> Website goes online

### Actual behavior

User switches to OFFLINE --> Craft just ignores the user -->  User starts to panic and gets frustrated and even a developer needs to waste hours just to put the site offline an elegant way (so without the need to rename files, edit an .htaccess or whatever). while it's just a simple switch that says 'OFFLINE', but it isn't ...

### Craft CMS version

3.7.47.1

### PHP version

8.x

### Installed plugins and versions

-

**Comment by bencresty** [comment] 2022-07-11 07:47
Today I woke up and suddenly remembered that websites don't go offline when in the same session being logged in on the control panel. As a developer I ALWAYS work with two browser tabs open, one with the CMS and one with the site frontend. And I'm sure many (front-end) developers work like that. So it's very easy to (keep) falling in this trap, because we normally don't put a site offline on a daily basis and it's mentioned nowere in the interface that the site doesn't show the offline state while logged into the CMS in the same session. It's not very intuitive that a site frontend keep showing while being offline and it's easy to keep forgetting about this 'feature'.

This took me hours to figure out again, so it's clearly not intutive by itself and I'm sure I'm not the only one falling in this trap. It would help if there would be a clear indication-label or popup next to the switch in the CP that clearly indicates that the front-end keeps showing while being logged into the CMS (As administrator?). 

Thanks in advance!

**Comment by brandonkelly** [comment] 2022-07-11 13:36
If you feel the UI could be improved, please open a discussion with your idea. Going to close this though, because the System Status setting is definitely working as intended.

**Closed by brandonkelly** 2022-07-11 13:36 UTC
Labels: bug, craft3
