### ISSUE TITLE
3.7 Entries can get the "Edited" post state after saving changes

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#9568] opened 2021-07-14 20:58 UTC
### Description
This is a bit of a weird one, and only seemed to be an issue because posts seem to save slowly compared to before updating to 3.7 (which might be a separate issue).

In testing some content locally, I noticed that saving entries was slow. In an attempt to test, I simply updated the entry title by appending a letter, then typed **cmd + s** to save. While I was waiting for things to save, I clicked into, then out of the title field. The end result was that my content was saved, but my entry showed the "Edited" state, saying that I have unsaved changes.

It probably shouldn't be possible to make new changes during the save process.

### Steps to reproduce

1. Edit an entry (add text to a title)
2. Save the entry
3. While saving, click into a title field, then click out a couple times

### Additional info

- Craft version: 3.7.0

**Comment by brandonkelly** [comment] 2021-07-14 22:15
I’m unable to reproduce this. The form is locked then saving, so any further changes shouldn’t register until the next page load:

https://github.com/craftcms/cms/blob/6948a8ab4b64a0224ba69cccb5c5a4deea196b19/src/web/assets/cp/src/js/DraftEditor.js#L1084

https://github.com/craftcms/cms/blob/6948a8ab4b64a0224ba69cccb5c5a4deea196b19/src/web/assets/cp/src/js/DraftEditor.js#L1051-L1054

I’ll keep my eyes peeled for it, and will keep this issue open in case anyone else runs into it and has more info to add.

**Comment by jsunsawyer** [comment] 2021-07-14 22:27
@brandonkelly Here's a recording showing the issue. I'm noticing that it's also inconsistently showing that there are changes to matrix fields, sometimes in various blocks (blue), but also for the full matrix field (yellow).

https://user-images.githubusercontent.com/1007191/125700859-1a73e7ba-4a7f-4d5a-95d5-f50e838d1a7a.mov

I'm saving with `cmd + s` in the video.

Hope this helps.

**Comment by brandonkelly** [comment] 2021-07-15 00:08
Aha… I’m seeing this when pressing <kbd>Command</kbd> <kbd>S</kbd> when the provisional draft is getting created. No need to click around on the page.

Just released 3.7.1 with a fix for this.

**Closed** 2021-07-15 00:07 UTC
Labels: bug
