### ISSUE TITLE
[4.x]: Asset filenames not saved with spaces

### ISSUE THREAD

**Issue by andyra** [craftcms/cms#11475] opened 2022-06-21 23:40 UTC
### Description

When uploading a file with space characters in the filename, it gets saved on the volume with dashes instead of spaces. This is a problem because the filename in the database URL encodes the spaces as `%20`, but the file on the volume uses dashes, so the assets always return a 404.

I'm using DigitalOcean Spaces as my volume.

### Steps to reproduce

1. Upload a file with spaces in the name (ex: `This is an image.jpg`)
2. Output the URL of the asset in a view (ex: `{{ url }}`)
3. The rendered URL (`This%20is%20an%20image.jpg`) doesn't match the actual file that was uploaded to the volume (`This-is-an-image.jpg`)

### Expected behavior

Files uploaded to the volume should retain spaces (`This is an image.jpg`)

### Actual behavior

Files uploaded to the volume replace spaces with dashes (`This-is-an-image.jpg`)

### Craft CMS version

4.0.5

### PHP version

8.1.4

### Operating system and version

Darwin 21.5.0

### Database type and version

MySQL 8.0.28

### Image driver and version

GD 8.1.4

### Installed plugins and versions

- Control Panel Nav: 4.0.2
- DigitalOcean Spaces Filesystem: 2.0.0
- Expanded Singles: 2.0.0-beta.1
- Feed Me: 5.0.4
- Redactor: 3.0.0
- Super Table: 3.0.0-beta.6

**Comment by brandonkelly** [comment] 2022-06-22 05:12
I’m not able to reproduce this. How are you uploading the files, exactly?

Also, are you overriding the `convertFilenamesToAscii` or `filenameWordSeparator` config settings?

**Comment by andyra** [comment] 2022-06-22 15:16
Oh wow, I didn't see that there was a preference for this! Changing `filenameWordSeparator` to `false` fixed the issue. It might make sense to either have this be `true` by default, or at least have the URL returned by the asset match the uploaded file. Thanks for the quick response!

**Comment by brandonkelly** [comment] 2022-06-22 17:43
@andyra I’d still like to get to the bottom of why the URLs are incorrect, though. When I leave the setting to its default value (`'-'`), uploaded asset URLs reflect their filenames, with dashes.

So can you tell me how you are uploading the assets? And for assets where this issue occurred, do their filenames in the control panel show dashes or spaces?

**Comment by andyra** [comment] 2022-06-23 22:44
I tried creating assets from the Assets page in the CP, via an Asset field (within a Matrix block), and via a FeedMe import, and they all had the same issue.

The filenames in the CP all had spaces. The only reason I knew they were saved with dashes was by looking on the Spaces volume on my Digital Ocean account.

**Comment by brandonkelly** [comment] 2022-06-24 17:31
We’re still unable to reproduce, either with a Local filesystem or with DO Spaces. Going to leave the issue open in case anyone else runs into it. Maybe another clue will come up.

**Comment by robinbeatty** [comment] 2024-12-17 14:34
Maybe related to this, or maybe its to do with how my webserver is configured, but when clicking a link to an asset folder in the CP which has a space in e.g. "/admin/assets/master/Activities/Horseback%20riding" the craft router doesn't detect it and I get a 403. Any insight that might be helpful would be great – or is there an easy way to enforce converting spaces to hyphens in the config? I imagine if I hack into the before save folder event it might start getting messy ensuring the source filenames follow the same pattern through the pipeline (e.g. some assets have already been transformed and stored offsite etc etc).

**Comment by brandonkelly** [comment] 2024-12-17 22:11
@robinbeatty Sounds a bit like #15236, which was fixed in Craft 5.2.4. Not sure why we didn’t fix it for Craft 4 as well though. Just backported the fix for the next Craft 4 release (dda033d3c93a9a7cd1c26a67cea6af474324f9b0).

**Closed by brandonkelly** 2024-12-17 22:11 UTC
Labels: bug, craft4

**Comment by robinbeatty** [comment] 2024-12-17 22:51
Thanks Brandon, just checking the changes and looks like this is only likely to affect asset elements - the issue I mentioned was the url navigating to an asset folder.. will that need sorting too? Many thanks for speedy update.

**Comment by brandonkelly** [comment] 2024-12-17 23:08
@robinbeatty Ah shoot, that one is trickier because the path leading up to the filename actually gets involved in routing, whereas assets’ filenames are only included in the URI to make them a bit more human-friendly (and are totally ignored by routing). You’ll need to either fix your web server config so it routes those requests to Craft, or remove the spaces from the folder names.

**Comment by brandonkelly** [comment] 2025-01-03 00:05
Craft 4.13.8 is out now with the backported fix for the asset edit URL bug.
