### ISSUE TITLE
Numeric fields should also have the option to set a default value.

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1040] opened 2017-01-31 03:48 UTC
> Created by: Steve Adams (pixeljitsu@gmail.com) on 2015/08/05 16:40:23 +0000
> Votes at time of UserVoice import: 4

-----------------------------------

I have a case where I need to use a numeric field which also has a default value.

For example: numericField needs to have a minimum value of 100 and a max value of 1000, but when the user adds a new entry, the field value should default to 256 in the entry form.

Unfortunately, I cannot trust the user to enter the correct default value, even if it is clearly indicated in the field notes.

Right now, when the user adds a new entry, numericField will always be set to 100 the minimum value.

It would be awesome if I could just set a default value in the Craft's number field type.  This feels like it should be part of the core and not a plugin for such a simple feature.

**Comment by Visiluna** [comment] 2017-04-26 16:12
Upvote, a thousand times!

**Comment by brandonkelly** [comment] 2017-05-01 23:01
Duplicate of #927

**Closed by brandonkelly** 2017-05-01 23:01 UTC
Labels: feature request
