### ISSUE TITLE
FR: Save and add another hotkey

### ISSUE THREAD

**Issue by swthate** [craftcms/cms#4719] opened 2019-08-07 01:18 UTC
When writing or editing an entry you can use cmd+S to save and remain on the same entry. I don't find myself in need of it often, but when I do use the "Save and add another" option I find myself needing to do it a number of times. It isn't super important, but it'd be nice to be able to do something like cmd+shit+S, or whatever, to quickly "Save and add another" using the keyboard.

I searched and didn't find any similar "issues," hope this isn't a duplicate!

Thanks :)

**Comment by brandonkelly** [comment] 2019-08-07 13:11
Duplicate of #974

**Closed by brandonkelly** 2019-08-07 13:11 UTC
