### ISSUE TITLE
FR: Copy or Move Entries to Another Site

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4162] opened 2019-04-19 16:19 UTC
It would be neat if you could simply (e.g. via a context menu in the control panel entries listing), copy or move selected entries from one site to another site for a multi-site setup.

_This assumes the entries are for a section where (_propagate entries_ is **unchecked**) and the target is the same section but a different site in a multi-site setup._ 

There are instances where this would be useful to have:
- adding a new site to a multi-site setup and wanting to populate an entries section with content from another site
- restructuring / re-architecting a site and moving content to a different site
- using a site in a multi-site setup for archiving off or storing unused content or pages for another site

**Comment by brandonkelly** [comment] 2019-04-22 21:54
Duplicate of #4080

**Closed by brandonkelly** 2019-04-22 21:54 UTC
