### ISSUE TITLE
[4.x]: Server error when editing a node in Verbb's Navigation plugin

### ISSUE THREAD

**Issue by daafbleumink** [craftcms/cms#13871] opened 2023-10-23 11:27 UTC
### Description
When using the plug-in Navigation by Verbb on a fresh installation, there's no problems.
But after using the plug-in for some time, from one moment to another (can't point out when), this error pops up.

It's when I want to edit a node in a navigation. Then a slide-over appears, but it stays blank. At the same time there is also a server error showing up in the left bottom of my screen. The logs say:

````
/Users/xx...')
#9 {main} {"memory":5385984,"exception":"[object] (TypeError(code: 0): craft\\web\\View::namespaceInputs(): Argument #1 ($html) must be of type callable|string, null given, called in /Users/xx/Herd/xx/vendor/craftcms/cms/src/web/View.php on line 1669 at /Users/xx/Herd/xx/vendor/craftcms/cms/src/web/View.php:1657)"
````

### Steps to reproduce

I'm sad to say there aren't any. I can't pinpoint what exactly I did before this behavior appeared.

### Expected behavior

When clicking the edit button I would expect the slide-over to open and show the fields that I can then edit and save. 

### Actual behavior

When I click the edit button the slide-over appears, but it remains blank (no fields) and I get a server error.

### Craft CMS version

Craft Solo 4.5.8

### PHP version

8.2

### Operating system and version

MacOS Sonoma 14.0

### Database type and version

MySQL 8.0.27

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.1-13)

### Installed plugins and versions

Breadcrumb | 2.0.0
Bulk Edit | 4.0.1
Category Groups Field | 2.0.1
Contact Form  | 3.0.1
Contact Form Honeypot  | 2.0.0
Craft Commerce  | 4.3.1
Elements Panel  | 2.0.0
Expanded Singles | 2.0.5
Feed Me | 5.2.0
Navigation | 2.0.21
Postmark | 3.0.0
Redactor | 3.0.4
SEOmatic | 4.0.33
Servd Assets and Helpers | 3.5.0
Sprig | 2.7.2
Super Table | 3.0.12
Twigpack | 4.0.0-beta.4
Typed linkl field | 2.1.5

**Comment by daafbleumink** [comment] 2023-10-23 11:30
FYI: Disabling all plug-ins didn't help.

**Comment by i-just** [comment] 2023-10-23 11:55
Hi, thanks for reaching out. Sounds like a duplicate of: https://github.com/craftcms/cms/issues/13867, which already has a PR raised. I'm going to close this one, but you can follow along there.

**Closed by i-just** 2023-10-23 11:55 UTC
Labels: bug, craft4

**Comment by brandonkelly** [comment] 2023-10-23 19:27
Craft 4.5.9 is out with a fix for this.
