### ISSUE TITLE
Assets subfolders broken

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#2278] opened 2018-01-06 21:15 UTC
### Description
Opening and closing the list of subfolders seems broken. I can reproduce this on 2 sites running RC4, don't remember this being broken on RC3.

### Steps to reproduce

1. Right-click the volume name and create a subfolder
2. The open/close toggle icon appears out of place and cannot be clicked:
![screen shot 2018-01-06 at 22 14 25](https://user-images.githubusercontent.com/755428/34644007-fe244e10-f32e-11e7-9559-1b7f0f79d090.png)

### Additional info

- Craft version: Craft 3 RC4
- PHP version: 7.1.8
- Database driver & version: MySQL 5.6.35
- Plugins & versions:

**Comment by brandonkelly** [comment] 2018-01-06 21:22
Duplicate of #2264.

**Closed by brandonkelly** 2018-01-06 21:22 UTC
