### ISSUE TITLE
Can't scroll using mouse wheel when editing entry type field layout

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#3277] opened 2018-09-06 12:42 UTC
### Description
I always remembered being able to do this, it seems you can't anymore? Is this by design or a bug?

I'm aware you can drag the field/field group to the top of the page and it will scroll up for you, but it doesn't work as smoothly as simply scrolling with the mouse wheel whilst dragging.

### Additional info

- Google Chrome 69.0.3497.81 (latest)
- Craft version: 3.0.23.1
- PHP version: 7.2.2
- Database driver & version: MySQL 5.7.23

Related https://github.com/craftcms/cms/issues/3276

**Comment by brandonkelly** [comment] 2018-09-06 18:13
Duplicate of #2340

**Closed by brandonkelly** 2018-09-06 18:13 UTC
