### ISSUE TITLE
When duplicating a structure entry with descendants it should not contain references to the content that was copied.

### ISSUE THREAD

**Issue by nilsnh** [craftcms/cms#4994] opened 2019-09-25 21:10 UTC
### Description

I work with a client where they need to duplicate a large tree of structure entries. 

Ideally I want to take a top level entry and click "Duplicate (with descendants)", the copy would:

1. Update any entries fields to point to the copied entries (if the entry was copied). Presently, any entries fields and matrix block with entries field are not updated to point to the copies. Instead they point to the original entries that we plan to delete. 
2. Not put "Copy" in the title because the editors will have a lot of pages to comb through.

I've started to develop the functionality I need here, based on Craft's existing Duplicate.php action: https://github.com/netliferesearch/BetterDeepDuplicate/blob/master/src/BetterDeepDuplicateAction.php 

It doesn't quite work yet. Much because I don't know how to update the MatrixBlock fields and fields in general programmatically. Any tips would be helpful.

I understand that this might not be the direction that you want to develop the duplicate with descendants functionality. But if it is, then maybe I could create a pull request. 

### Steps to reproduce

1. create a structure with descendants like A -> B -> C.
2. attach an entries field where you have a reference from A->B
3. select A entry in the dashboard and click "duplicate with descendants". 
4. When you get the new tree D -> E -> F, you'll see that D refers to B and not the copy E.

### Additional info

- Craft version: 3.1.34.3
- PHP version: 7.2
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment] 2019-09-26 12:33
I don’t think that it’s safe to assume that just because a related element is getting duplicated in the same batch, that the relation should be updated to point to the new element. The parent element would no longer be a true duplicate of its original element.

I think ultimately if we’re going to make this sort of thing easier, it’s going to be via full-featured import & exporting (#994). For example given this JSON file to be imported:

```json
[
  {
    "id": 1,
    "title": "Entry A"
  },
  {
    "id": 2,
    "title": "Entry B",
    "relationField": [1]
  }
]
```

When importing, if the user chooses to import the entries as new elements, even if the IDs match existing entry IDs, then Entry A ends up getting an ID of `3` instead of `1`, and that change should carry over to the `relationField` value of Entry B.

**Closed by brandonkelly** 2019-09-26 12:33 UTC
