### ISSUE TITLE
[4.x]: Condition Builder does not work correctly in Globals

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/cms#11121] opened 2022-05-06 10:12 UTC
### Description

I have two fields, the second field should only be shown when the first field (a lightswitch) is on.
I use the Condition builder to achieve this. It works fine when this is done in Entries. 
It doesn't work at all when the same thing with the same fields is done in Globals; instead the second field is hidden and never revealed.

### Actual behaviour
![Screenshot 2022-05-06 at 11 08 12](https://user-images.githubusercontent.com/814039/167112339-aa7aa0b0-3a03-4193-aaa1-e83e897bb41b.jpg)
![Screenshot 2022-05-06 at 11 08 38](https://user-images.githubusercontent.com/814039/167112343-883e0c38-b9a6-4225-bdff-bbc9f140cc61.jpg)
![Screenshot 2022-05-06 at 11 09 12](https://user-images.githubusercontent.com/814039/167112344-9f97ea9b-8f6b-4d50-990a-f284ad7a7936.jpg)

### Craft CMS version

4.0.1

### PHP version

8.0

### Operating system and version

Nitro2

### Database type and version

Nitro2

### Image driver and version

Nitro2

**Comment by bencroker** [comment] 2022-05-07 07:10
This is a duplicate of https://github.com/craftcms/cms/issues/10776

**Closed** 2022-05-07 11:14 UTC
Labels: bug, craft4
