### ISSUE TITLE
Inline-editable/matrix-style elements Field

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6676] opened 2020-08-19 13:04 UTC
Often, it makes the most sense to use a section+entries field, instead of matrix field to house related data.
However, sometimes I'd like that relationship to be more transparent to the client/entry form.

What I'm thinking about is an option on an entries/elements field to "display field layout on publish form", turning it into a more matrix-style publishing process. In fact, the user probably wouldn't even be able to distinguish the difference, especially now that Matrix blocks can have UI layouts.

I realize the HUD is there for a similar purpose, but I haven't ever had much success in getting clients (or myself) to use it.

**Comment by brandonkelly** [comment] 2020-08-21 00:23
This is a duplicate of #6591. Though I don’t think those fields should be editable – see https://github.com/craftcms/cms/issues/6591#issuecomment-671638085.

**Closed by brandonkelly** 2020-08-21 00:23 UTC
Labels: enhancement
