### ISSUE TITLE
No way to get entries from multiple sites or a site group

### ISSUE THREAD

**Issue by Harry-Harrison** [craftcms/cms#3481] opened 2018-11-21 11:19 UTC
### Description
Currently there is no way to get all entries or perform an entry query on an array of site IDs or handles or even on a site group. The docs read as if `enabledForSite` should do this, or `anyStatus` should also do this but neither do.

I'd like to propose the two following ideas.

```
Entry::find()
    ->section('businesses')
    ->site(['siteHandle1', 'siteHandle2', 'siteHandle3'])
    ->orderBy('title asc')
    ->limit(100)
    ->anyStatus();
```
```
Entry::find()
    ->section('businesses')
    ->siteGroup(['siteGroupHandle1', 'siteGroupHandle2'])
    ->orderBy('title asc')
    ->limit(100)
    ->anyStatus();
```

### Steps to reproduce

1. Write an element query
2. Try and provide it an array of site handles or ids

### Additional info

- Craft version: Craft Pro 3.0.31
- PHP version: 7.2.12
- Database driver & version: MySQL 5.7.24
- Plugins & versions: N/A

**Comment by brandonkelly** [comment] 2018-11-21 14:39
Duplicate of #2854

**Closed by brandonkelly** 2018-11-21 14:39 UTC

**Comment by Harry-Harrison** [comment] 2018-11-21 15:15
My bad, @brandonkelly! Couldn't find that though all my searching. Ta.
