### ISSUE TITLE
Feature: Allow Override of Primary Entry Page for Live Preview or setting a default live preview.

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/cms#4888] opened 2019-09-04 17:37 UTC
### Description

When you have a site that is only using Craft CMS as a headless source it would be nice to be able to either set one of the preview targets as default or override the Primary Entry Page. This would enable life preview to default to the actual application particularly when in development.

For example, I have Craft running in a VM on one url (i.e. http://local.site.pizza) and the Next.JS site running in development localhost (i.e. http://localhost:4000). It would be great if I could make the live preview default to the Next.JS app.

Also, it would be great if I could use env variables and aliases in the live preview urls so that I could set just one target and change to domain using an env or alias per environment.

**Comment by brandonkelly** [comment] 2019-09-05 21:17
This is a duplicate of #4520. See discussion there.

**Closed by brandonkelly** 2019-09-05 21:17 UTC
