### ISSUE TITLE
Unwanted sort fields show up in list view

### ISSUE THREAD

**Issue by timbertens** [craftcms/cms#5054] opened 2019-10-05 13:42 UTC
### Description
Some fields show up in the list of fields that can be sorted in the list view on the CMS, see screenshot
<img width="501" alt="Screenshot 2019-10-05 at 15 32 37" src="https://user-images.githubusercontent.com/1016655/66255633-39087400-e786-11e9-9d5e-1b31248ee10c.png">

These are actual fields that are used in different channels and of different types (lightswitch or dropdown in my case) 

### Steps to reproduce
That the hard part, I have no clue why they are been shown, why only those 3 fields are being shown (and why they are not translated properly ...)

### Additional info
PHP version	7.3.1
OS version	Linux 4.15.0-45-generic
Database driver & version	MySQL 5.7.25
Image driver & version	GD 7.3.1
Craft edition & version	Craft Pro 3.3.6
Yii version	2.0.21
Twig version	2.11.3
Guzzle version	6.3.3
Imagine version	1.2.3-dev

PLUGINS
Activity Log	1.0.1
CodeMirror	1.0.1
CP Field Inspect	1.0.6
Do It Yourself widget	2.0.1
Field Manager	2.1.0
GeoField	1.0.0
Imager	v2.3.0
Matrix Toolbar	1.0.6
Migration Assistant	3.1.5
Redactor	2.4.0
SEOMate	1.1.1
Site Switcher	2.1.0
Stamp	2.1.0
Table Maker	2.0.1
Two-Factor Authentication	2.2.0
Typed link field	1.0.19
Wheel Form	2.3.4
Wheelform Helper	1.0.0
Wordsmith	3.1.1

**Comment by brandonkelly** [comment] 2019-10-08 22:12
This is a duplicate of #4314 & #4514. See explanation here: https://github.com/craftcms/cms/issues/4514#issuecomment-510610070

**Closed by brandonkelly** 2019-10-08 22:12 UTC

**Comment by brandonkelly** [comment] 2020-05-20 23:42
For posterity, this has been fixed for Craft 3.5. See https://github.com/craftcms/cms/issues/4314#issuecomment-631793986 for details.
