### ISSUE TITLE
$event->isNew not working as expected after Craft 3.2 update

### ISSUE THREAD

**Issue by rswhite7** [craftcms/cms#4621] opened 2019-07-19 16:44 UTC
### Description
Pre Craft 3.2, you could do something like this if you wanted to perform an action in the event you just saved a new entry:

```
use craft\elements\Entry;
use craft\events\ModelEvent;

Event::on(
    Entry::class,
    Entry::EVENT_AFTER_SAVE,
    function(ModelEvent $event) {
        $entry = $event->sender;
        $isNew = $event->isNew;

        if ($isNew) {
            // do something...
        }
    }
);
```

However, after the update, this code doesn't work as it used to. `$isNew` always gets evaluated to `true` whether resaving a pre existing entry or editing a yet-to-be-saved entry (the autosave kicks in after a couple of seconds while you're editing).

I've tried doing something like this to check if the entry is being resaved but it still gets evaluated to `true`:
```
$isBrandNew = false;
if ($event->isNew && ! $entry->propagating && ! $entry->resaving) {
    $isBrandNew = true;
}

if ($isBrandNew) {
    // do something
}
```
I've read through this similar issue (#4589) but how that issue got resolved and how it can be applied to my example wasn't very clear.

How do I fix this so that my code only runs after a *brand new* entry was just created, like it did before Craft 3.2?  Or is this a bug?

### Additional info
- Craft version: 3.2.4.1

**Comment by brandonkelly** [comment] 2019-07-19 17:54
This is a duplicate of #4589. And we just released 3.2.5 which resolves it.

**Closed by brandonkelly** 2019-07-19 17:54 UTC

**Comment by rswhite7** [comment] 2019-07-20 13:17
I updated to version 3.2.5.1 and it's still behaving like before. My plugin code is
```
use craft\elements\Entry;
use craft\events\ModelEvent;

Event::on(
    Entry::class,
    Entry::EVENT_AFTER_SAVE,
    function(ModelEvent $event) {
        /** @var Entry $entry */
        $entry = $event->sender;
        $isNew = $event->isNew;

        // section 5 is the channel that contact form submissions go to
        if ($entry->sectionId === '5' && $isNew) {
            $this->forms->sendNotificationEmail($entry);
        }
    }
);
```
If I submit my contact form on the front end, I receive 2 identical emails with the entry data.  If I create a new entry in the contact form channel in the CMS, I get an additional 3rd email with all the entry data blank (presumably because it saved a draft of blank content before pressing "save").

**Comment by brandonkelly** [comment] 2019-07-20 17:35
You need to modify your event handler to ignore revisions and drafts:

```php
use craft\helpers\ElementHelper;
use craft\elements\Entry;
use craft\events\ModelEvent;

Event::on(
    Entry::class,
    Entry::EVENT_AFTER_SAVE,
    function(ModelEvent $event) {
        /** @var Entry $entry */
        $entry = $event->sender;

        if (ElementHelper::isDraftOrRevision($entry)) {
            return;
        }

        $isNew = $event->isNew;

        // section 5 is the channel that contact form submissions go to
        if ($entry->sectionId === '5' && $isNew) {
            $this->forms->sendNotificationEmail($entry);
        }
    }
);
```
