### ISSUE TITLE
[4.x]: Exception thrown in execute() method of a QueueJob hangs the job

### ISSUE THREAD

**Issue by nitriques** [craftcms/cms#13820] opened 2023-10-12 15:18 UTC
### Description

Any exception/errors thrown in a queue should fail the job.

### Steps to reproduce

1. Create a simple `craft\queue\BaseJob` class
2. In the `public function execute($queue): void` method
   a. Log the process to something `$this->setProgress($queue, 0.2, 'Doing stuff');`
   b. `throw new \Error('!');` 

### Expected behavior

I would expect the job to be marked as FAILED and get the error message in the cp.

### Actual behavior

They hang forever, in a "progress" state.

<img width="688" alt="image" src="https://github.com/craftcms/cms/assets/771169/acabb19a-cec8-4d12-91b8-c7a9bc244eb2">

This as been going on for a very long time ;) 
I've just had the bug with 4.5.6.1.

### Craft CMS version

4.x

### PHP version

8.2

### Operating system and version

linux

### Database type and version

mysql

### Installed plugins and versions

- cloudflare-stream

But it does not mater, even a job from a module gets the same treatment.

**Comment by nitriques** [comment] 2023-10-12 15:59
here's another example, where we log the exception before throw it

<img width="720" alt="image" src="https://github.com/craftcms/cms/assets/771169/255f212f-73ca-41db-a687-40d39d101ec9">

**Comment by nitriques** [comment] 2023-10-12 16:00
We also get a "task not found" error when clicking on it

**Comment by brandonkelly** [comment] 2023-10-15 17:29
I’m not able to reproduce this. Using the same error code, the job is marked as failed and displays the exception message:

<img src="https://github.com/craftcms/cms/assets/47792/5a212e70-64be-4ba3-a7c3-6512727e7ff4" width="542" height="213" alt="A failed queue job">

Are you overriding the `queue` component in `config/app.php`? If so, can you share the config code?

**Comment by nitriques** [comment] 2023-10-15 22:31
Hi @brandonkelly 

You can see the code here: https://github.com/DeuxHuitHuit/craft-cloudflare-stream/tree/dev/src/jobs

I've tried with both Error and Exception

> Are you overriding the queue component in config/app.php? If so, can you share the config code

No!

We have one or 2 modules, that's it.

```php

return [
    'id' => App::env('APP_ID') ?: 'CraftCMS Headless',
    'modules' => [
        'agency-auth' => \modules\agencyauth\AgencyAuth::class,
    ],
    'bootstrap' => [
        'agency-auth',
    ],
];
```

**Comment by nitriques** [comment] 2023-10-15 22:32
It also happens with exception thrown here in the ctor: https://github.com/DeuxHuitHuit/craft-cloudflare-stream/blob/dev/src/client/CloudflareVideoStreamClient.php

**Comment by nitriques** [comment] 2023-10-16 17:58
Ok so I was able to get rid of the 404 on de details page (turns out, mod_sec does not like get-job in the url)

But jobs are still 'hanging' when we throw (they do not fail)
<img width="838" alt="image" src="https://github.com/craftcms/cms/assets/771169/ab9adb3b-22a3-4d59-b736-7b15441c0c1a">

**Closed** 2023-10-16 20:10 UTC
Labels: bug, craft4

**Comment by brandonkelly** [comment] 2023-10-17 18:08
Hm, Craft should only be waiting for the TTR to expire if it isn’t aware that the job failed in the first place.

Any chance we can get access to your server so we can look into this further from there? If so you can send credentials over to support@craftcms.com

**Comment by nitriques** [comment] 2023-10-19 13:00
> Hm, Craft should only be waiting for the TTR to expire if it isn’t aware that the job failed in the first place.

Yeah that's the thing. We have nothing in the UI telling us that the job failed and will be retried. The status is still "reserved" when I think it should be "failed + reserved" (meaning it failed but will be retried after the ttr as expired).

also, TTR means Time To Reserve, not Time To Retry. Maybe they should be split ? I mean, I want to reserve a lot of time for a long running job, but might want to retry it faster then it takes to run it ?

**Comment by brandonkelly** [comment] 2023-10-19 13:07
We’re in agreement. I just can’t reproduce – failed jobs are immediately marked as failed on my end, and given the option to retry. If it’s possible to give us access to your box, we can look into why it’s not working as expected from there.

**Comment by nitriques** [comment] 2023-10-19 16:02
Hi @brandonkelly 

Sadly no our boxes are not easily reachable ;)

> failed jobs are immediately marked as failed on my end, and given the option to retry.

Sure, but only _after_ `canRetry()` return true. 

Take this job: https://github.com/DeuxHuitHuit/craft-cloudflare-stream/blob/dev/src/jobs/UploadVideoJob.php

It can retry 5 times. It has a ttr of 2 minutes.

The UI will show "Reserved" during 10 minutes (5 times 2).
After the 5 tries, it will give up, and show the "Failed" status, offer me to retry them.

There is no way to see that "Reserved" in this case means: "The job failed, but we will retry it in x minutes".

Let me know if this is what you are also seeing. You need to mix custom ttr with `canRetry()` to see it.

**Comment by nitriques** [comment] 2023-10-19 19:09
>  I just can’t reproduce – failed jobs are immediately marked as failed on my end, and given the option to retry.

Are they retried later on ? Automatically ?

**Comment by brandonkelly** [comment] 2023-10-19 21:15
> > failed jobs are immediately marked as failed on my end, and given the option to retry.
> 
> Sure, but only _after_ `canRetry()` returns `false`.

I’m describing what I’m seeing on my end, where jobs are _immediately_ retryable.

> Let me know if this is what you are also seeing. You need to mix custom ttr with canRetry() to see it.

No, I’m not seeing the same behavior as you.

> > I just can’t reproduce – failed jobs are immediately marked as failed on my end, and given the option to retry.
> 
> Are they retried later on ? Automatically ?

They are not being retried automatically, but I can immediately press **Retry** after they fail, and they are retried.

**Comment by brandonkelly** [comment] 2023-10-20 19:08
Once I’ve installed your plugin, what should I do to queue up the (invalid) job?

**Comment by nitriques** [comment] 2023-10-20 19:14
Our readme is not clear enough ? (we know!)

Add a stream field to an asset. Upload a video, then send it yo CF. it will queue the job.

**Comment by brandonkelly** [comment] 2023-10-23 21:47
Hey @nitriques, I just tried that but am unable to get the job to execute. Anything else I need to have in place?

**Comment by brandonkelly** [comment] 2023-10-23 22:45
Alternatively, have you tested with any of Craft’s built-in queue jobs, to rule out your job as the culprit?

You can easily queue up a “Resaving entries” job by running the following CLI command:

```sh
php craft resave/entries --queue
```

**Comment by nitriques** [comment] 2023-11-05 17:53
I will try to record what I see, just to make sure we are on the same page. It's a complex issue to describe.

We do run the queue usign the 3 ways available: via the cp (craft's default), via queue/run and via queue/listen, which runs as a systemd unit.

Typically, dev runs in the cp or run, prod gets its systemd unit.

All other jobs are working fine in all environnement/configuration! Custom ones (either via a module or plugin) are a nightmare for us, and has been since many years. I really hope to find my misunderstanding of what is going on.

**Comment by nitriques** [comment] 2023-11-15 15:52
Hi @brandonkelly 

Here's my screengrab: https://www.loom.com/share/42915c0dabc248b89fe1dc2a99a52ad6?sid=d3fb6233-9c64-4430-9d5d-c9a0f29f85d7

As you can see, the job gets stuck until its ttr expires, at which point it gets retried 5 times, then (and only then) do we see the error message and the Failed status.

The confusing part is the 2 minutes (ttr) between the error and the time it gets re-executed.

Thanks again.

**Comment by brandonkelly** [comment] 2023-11-15 19:53
Can you share your database backup and Compsoer files with us, and provide specific steps to reproduce? As I said I wasn’t able to get the job to execute in the first place, but I might have better luck with a preconfigured project. support@craftcms.com

**Comment by nitriques** [comment] 2023-11-24 16:08
@brandonkelly I'll create a project for you, in order to make sure I do not send client info. I am able to reproduce it at will.

Let just add this piece of data. Since this is time based, maybe this will help.

I have a job, with a 2min ttr, retryable 3 times. Time starts a 1:00:00 (h:mm:ss).


|time|attempt|job status|job status I would expect|problem|comment|
|----|-------|----------|-------------------------|------|-------|
|1:00:00|1|reserved     |reserved              |      |queue not running|
|1:00:01|1|running 1%   |running 1%            |      |job started|
|1:00:10|1|running 20%  |DELAYED/FAILED        |   !  |the job throws, but nothing is telling me about it...|
|1:02:00|2|reserved     |reserved              |      |queue still running|
|1:02:01|2|running 1%   |running 1%            |      |job started|
|1:02:10|2|running 20%  |DELAYED/FAILED        |   !  |the job throws, no feedback|
|1:04:00|3|reserved     |reserved              |      |queue still running|
|1:04:01|3|running 1%   |running 1%            |      |job started|
|1:04:10|3|FAILED       |FAILED                |      |this is the 1st time we get feedback about an error|

What _feels_ like a bug, is the fact that for most of the time, the system is telling me the job is _running_, while in fact, it is not: it failed and is waiting for a retry.... There are no way to know what the error is until ALL attempts have failed. In some of our use cases, this can takes hours. (ex: ttr of 30 min, 5 retries = 2 and a half hour!)

Is this clearer ?

**Comment by brandonkelly** [comment] 2023-12-10 16:43
> What _feels_ like a bug, is the fact that for most of the time, the system is telling me the job is _running_, while in fact, it is not: it failed and is waiting for a retry.... There are no way to know what the error is until ALL attempts have failed.

What I’m saying is that this is not how it’s supposed to work.

In my testing, jobs that fail are immediately marked as failed, and the queue will either retry them or move on to the next job.

The TTR should only ever come into play for jobs that are taking longer than expected — or perhaps if a fatal error occurs which would prevent Craft from marking the job as failed.

**Comment by nitriques** [comment] 2024-01-08 14:44
Hi @brandonkelly 

Happy new year. 

> What I’m saying is that this is not how it’s supposed to work.

Well, that's a bummer. I have _at least_ 5 craft installs with this exact behaviour.

> or perhaps if a fatal error occurs which would prevent Craft from marking the job as failed.

I've seen cases where calling setProgress would fail (because the comment was too long). I would get a log in that case. I my example, there is no such thing: the only thing that happens is a throw new Exception/Error.

I'll create an empty project which recreates this situation and resends it to you.

I am at least glad that the behaviour I've described is not the expected one.

Thanks!
