### ISSUE TITLE
Feature request: Save Entries / Categories order and grouping into project config

### ISSUE THREAD

**Issue by duskosobic** [craftcms/cms#6797] opened 2020-09-07 07:29 UTC
### Description

When you use more environments (development, staging, production), project config is magic wand.
It would be useful Craft stores Entries / Categories order and grouping into project config.

For example:

I have category groups: 
- Brands
- Colors
- Global
- Local 
- Types  
and I want to  make one group site related and another shop related. And I want to order them in more logical order:

SITE (this is heading)
- Local
- Global
SHOP (this is heading)
- Types
- Brands
- Colors

I can do this and have super organised category groups at my instance, but all other environments will have alphabetically ordered category groups without custom headings. Because those details are part of project setup, the art of content organization of Craft CMS will be more complete with this ;)

**Comment by brandonkelly** [comment] 2020-09-08 15:00
Thanks for the feedback! This sounds like a duplicate of #3658.

**Closed by brandonkelly** 2020-09-08 15:00 UTC
Labels: enhancement
